### ISSUE TITLE
Special Inventories

### ISSUE THREAD

**Issue by Corail31** [Corail31/tombstone_lite#1]
Only request here for any special inventories that aren't yet handle by Tombstone for the auto-equip when recovering your lost items from a grave.
Tombstone already integrates theses special inventories :
- Baubles (v1.3.3)
- GalactiCraft (v2.5.2)
- Techguns (v2.7.0)
- Aether Legacy (v2.8.5)
- RPG Inventory (v2.8.5)
- The BetweenLands (v2.9.1)
- Smart BackPacks (v3.1.2)
- Curios (v3.7.4)

**Comment by justinrusso** [comment]
The Betweenlands https://github.com/Angry-Pixel/The-Betweenlands/

**Comment by Trinsdar** [comment]
Smart Backpacks: https://github.com/V0idWa1k3r/SmartBackpacks

**Comment by Corail31** [comment]
you should first test... why it shouldn't work ?

**Comment by Trinsdar** [comment]
So I just tested it and it does get the backpack; it just doesn't put it back on your back.

**Comment by Corail31** [comment]
yes it's normal, autoequip requires me special compat individually :)
(and actually my mod checks first the priority between Elytra and Chest armors to reequip)

**Comment by Corail31** [comment]
You can test if all is ok in this version : [here](https://cdn.discordapp.com/attachments/429050628044488705/490808870105645057/tombstone-3.1.2-1.12.jar)

**Comment by WenXin20** [comment]
[Bring Me the Rings](https://www.curseforge.com/minecraft/mc-mods/bring-me-the-rings) mod doesn't auto equip baubles into it's slots.

**Comment by SirAron111** [comment]
Support for improvedbackpacks https://www.curseforge.com/minecraft/mc-mods/improvedbackpacks

The baubles are ok they equip to the back slot if they where there but if you have 2 of them one of them auto equips onto the chest plate slot having the chest plate drop into the next pond of lava or something like that. They should never auto equip into chest plate slot. Other than that it’s like the best backpack mod I came across I tested like 8 different one from the iron backpacks to voids backpacks and travelers etc. But these ones are plain simple well designed and have no duping or item loss problems. So I think they deserve a spot here. 

Also maybe Wings Mod pretty fluid animated flight and Wings https://www.curseforge.com/minecraft/mc-mods/wings

**Comment by Corail31** [comment]
@SirAron111 Yes but there's no code source, so no compat as i need to keep track of changes ;)
About paul's mod, it'll think to add it.
@WenXin20 I'm not sure this mod is really active.

**Comment by VeloxAzo** [comment]
Cosmetic armor reworked gets equipped in the primary armor slots even if there was something else in the slot when you died. 

https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked

**Comment by Animaly0** [comment]
Baubley Heart Canister's mod : the autoequip in Bauble is not working, have to re-equip the canister manually.
PS : Love your mod <3

**Comment by Invalids** [comment]
Curios added two backpack slots that are aren't handled upon death

https://www.curseforge.com/minecraft/mc-mods/curios

The rest of the support still works though, thank you!

**Comment by Corail31** [comment]
@Invalids you mean the slots of Travel Bag mod ? (tombstone tends to skip items stackable for equipping special slots too ;))

**Comment by Invalids** [comment]
Yes, that's what I meant. And now I feel a bit dumb for not realizing it was your mod lol, I was under the mistaken assumption that Curios was like Bauble with a fixed number of slots, I didn't realize it was a whole API for adding other slots.

**Comment by Corail31** [comment]
@Invalids i see what you mean and why they don't equip, they were before a recent change for curios items not implementing ICurio, and so relying more on the capability. I'll make the Travel Bags handle again in next release of Tombstone ;)
