### ISSUE TITLE
Request: Bigger Tombstones

### ISSUE THREAD

**Issue by sdaddy** [Corail31/tombstone_lite#1]
First off, nice work! My only gripe is that the craftable tombstones are rather small. They look more like graves for pets. Could you add some that are twice the size? Maybe keep the ones you already have for an awesome pet cemetery. :) Thanks!

**Comment by Corail31** [comment]
It was to avoid teleporting trouble over the grave :) but for decoration graves, why not bigger model :)

**Comment by Corail31** [comment]
I don't forget your request, i'm working on the models to include them in the next release :)
