### ISSUE TITLE
Tinkers tools get dropt in 1.16

### ISSUE THREAD

**Issue by zaze06** [Corail31/tombstone_lite#1]
In minecraft 1.16 tools from tinkersget dropt

minecraft: 1.16
forge: 36.1.0

**Comment by Corail31** [comment]
@zaze06 if you have no time to provide a correct explanation, i'll have no time to consider it and the issue will be closed.

**Comment by zaze06** [comment]
I can provide a picture but i don't know how to explain it better sorry

**Comment by Corail31** [comment]
If you're not able to write sentences, you're not welcome on this issue section.
Edit: you can still ask someone to formulate it for you, but your explanation has no mean and no context.
