### ISSUE TITLE
Lost Tombstone

### ISSUE THREAD

**Issue by NotSoNiceCanadian** [Corail31/tombstone_lite#10]
I had a tombstone from where I died in lava in the nether (playing skyfactory 4). I was swimming out and died. I accidently deleted my waypoint through journey maps and then went into creative to try and remove the lava and get to my grave. I also managed to delete the grave key so I can't tp to it but I remember the coordinates (0, 170, 89). I found my grave at those coordinates way up high in the nether when I drowned at y = 8 or so. Is there a file which would contain coordinates if I or another player lose their tombstone in such a way previously. Also what are the conditions for a tombstones location jumping up like that.

**Comment by Corail31** [comment]
If you remove the waypoint, and delete the key... you just search trouble :p
So, keys are not needed to interact the grave, and if you die near a grave, it will fill the same grave and give you a new key for the grave.
There're commands like it's explained on the CurseForge page :
The 2 first will only work as long as you have a key or the server didn't restart
/tbshowlastgrave to display the location of the grave
/tbrestoreinventory to click the grave a distance
There's a command /tbrecovery for inventory restoration.
The only reason for this position is there was no ideal place anywhere with a ground in that chunk, graves are never placed in lava.
