### ISSUE TITLE
crash server with tombstone 1.4.0

### ISSUE THREAD

**Issue by demon57730** [Corail31/tombstone_lite#10]
crash server 

forge-1.11.2-13.20.1.2530

UE	tombstone{1.4.0} [Corail Tombstone] (tombstone-1.4.0-1.11.2.jar)
report:
http://rock-rp.fr/dl/crash-2017-11-09_06.50.53-server.txt

**Comment by Corail31** [comment]
thanks for the report i'm going to make tests, but your log can't be read
