### ISSUE TITLE
endless flight/hover after eating lollipop.

### ISSUE THREAD

**Issue by xal3xhx** [Corail31/tombstone_lite#100]
after eating a Halloween lollipop i received a effect that made me hover. after the effect ended i still was hovering, some times restarting will fix it other times it wont.

**Comment by Corail31** [comment]
First of all, this is not the ideal way to present your issue.
Then, what happen with lollipop is what others mods add as benefical effects (and any effect is useable from command so, should be coded "safe")
It's up to you to localize the name of the effect and report it to the mod adding it.
