### ISSUE TITLE
Tombstone replaces waterlogged blocks.

### ISSUE THREAD

**Issue by SpokenWig620933** [Corail31/tombstone_lite#100]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Corail Tombstone Version

7.5.5

### What happened?

When I died on top of a waterlogged stone brick stair, used for decoration, the tombstone replaced the block and waterlogged itself
![2022-10-24_19 09 04](https://user-images.githubusercontent.com/49125888/197646850-51585515-9e9f-4976-92c2-e7408ab0b271.png)

I did not test this in an isolated environment, only in my modpack.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, thanks for reporting the issue here (it's a good catch, it was a missing a check for no collision when in water).

**Comment by SpokenWig620933** [comment]
Is this fix going to be released for 1.18 as like a hotfix or something? Im asking because that's the version I am and was using.

**Comment by Corail31** [comment]
Yes, when a new update on that version will be released (but if you need a fast solution, you can disable in client config "allow_grave_in_water").

**Comment by Corail31** [comment]
@RedstoneGamer123 It's done ;)

**Comment by SpokenWig620933** [comment]
Thanks!
