### ISSUE TITLE
Tombstone and Everlasting Abilities Loot Table error

### ISSUE THREAD

**Issue by Anuuviem** [Corail31/tombstone_lite#101]
Minecraft Version: 1.14.4
Forge 28.1.90
Everlasting abilities version: Cyclops and Everlasting Latest for 1.14
Tombstone version: Latest for 1.14

Error:
https://pastebin.com/E558ejYk

I have posted a bug for everlasting abilities as well. I hope the issue can be resolved! Thank you and keep up the awesome modding!

EDIT: Also occurs with Enigmatic Legacy, nearly exact same errors just with enigmatic legacy code
https://pastebin.com/JXSQHQF3

**Comment by Corail31** [comment]
Ah, you should report to cyclops, i'm not even sure their port was correct and finished.
No idea, what they are doing to loot tables but there's a concurrent.

**Comment by Corail31** [comment]
@Arstan13 Any evolution about this?

**Comment by Corail31** [comment]
It's on their side to fix if they use unnamed pools.
