### ISSUE TITLE
Initializing game [requires forge 40.1.84]

### ISSUE THREAD

**Issue by WickedS1ck** [Corail31/tombstone_lite#101]
### Minecraft Version

1.18.2

### Forge Version

40.1.76

### Corail Tombstone Version

tombstone-7.5.6-1.18.2

### What happened?

Initializing game with the last tombstone update
[crash-2022-10-24_19.25.49-client.txt](https://github.com/Corail31/tombstone_lite/files/9856444/crash-2022-10-24_19.25.49-client.txt)   Yes that was the last mod or the last update that i downloaded

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

none that i know

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Please provide the debug log, i don't even see Corail Tombstone in your log. Also, updates Forge to latest.
If you use create with oculus, don't be surprised to get a crash.
The error seems to be related to a mixin "MixinWorldRenderer" that failed in sodium-extra (redirectGetStarBrightness) and i'm sure Corail Tombstone has no related code.

**Comment by WickedS1ck** [comment]
[latest.log](https://github.com/Corail31/tombstone_lite/files/9857387/latest.log)
[2022-10-24-7.log.gz](https://github.com/Corail31/tombstone_lite/files/9857388/2022-10-24-7.log.gz)
like i said this happen when i use the last version of tombstone 7.5.6 with the 7.5.5 nothing happens

**Comment by Corail31** [comment]
So, you can read the log:
"net.minecraftforge.fml.ModLoadingException: Mod §etombstone§r requires §6forge§r §o40.1.84 or above§r"
It's not my fault if Forge takes "years" to handle correctly mismatch mods and missing dependency.
