### ISSUE TITLE
[1.19.2] Instant disconnect upon joining server

### ISSUE THREAD

**Issue by Gbergz** [Corail31/tombstone_lite#102]
### Minecraft Version

1.19.2

### Forge Version

43.1.47

### Corail Tombstone Version

8.1.9

### What happened?

When a user attempts to join a server they get disconnected instantly. "failed to handle packet for." then "Internal server error".

So not entirely sure what the steps are required to actually reproduce it.

Something related to ItemMagicScroll & MobEffect by looking at the logs.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Log Link

https://gist.github.com/Gbergz/757f750d6ee346239754f65f141461d9

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Gbergz Hi, it was happening in previous version ? euh **remove this mod if you want support: Corail-Adventurer** (i have no time for people supporting this modder using my pseudo)

**Comment by Gbergz** [comment]
I don't think it happened before adding the Adventurer mod.

Though I could be wrong.

Should I remove it?

**Comment by Corail31** [comment]
```
[25.10 16:38:38] [Server] 	at org.cursegame.minecraft.adventurer.registry.ModEffects$1.m_19481_(ModEffects.java:29) ~[Corail-Adventurer-1.19.2-055.jar%23187!/{re:classloading}
[25.10 16:38:38] [Server] 	at net.minecraft.world.effect.MobEffect.m_19482_(MobEffect.java:144) ~[server-1.19.2-20220805.130853-srg.jar%23559!/:?] {re:mixin,re:classloading}
[25.10 16:38:38] [Server] 	at ovh.corail.tombstone.item.ItemMagicScroll.getMagicEffectName(ItemMagicScroll.java:144) ~[tombstone-8.1.9-1.19.2.jar%23509!/:8.1.{re:classloading}
```
Edit : in general, i prefer a short modlist to discard a maximum of scenarios but i know your name since ages too...
I will make the server test later to confirm.

**Comment by Gbergz** [comment]
Hm. Gonna be honest. I didn't know you didn't make that mod. I usually look at "Corail" and think of Corail Tombstone and thought they were related. Didn't look at the author name. Whoops.

I will try without it, see what happens.

**Comment by Corail31** [comment]
By the look of it, it's a client classload by the other mod in their utils class, just remove the other mod (or to add the modid in the config 'unhandled_beneficial_effects') and it should be ok (packets don't like references to clientLevel & clientPlayer, even more when the runnable is wrote as a lambda).
NB: this also means that i can change my runnable to anonymous class (instead of lambda) to prevent their classload.

**Comment by Gbergz** [comment]
Confirmed fixed by removing Corail Adventurer.

**Comment by Corail31** [comment]
You can use 8.1.10 as i did the thing with anonymous class, i'm nearly sure it would no more happen.

**Comment by Gbergz** [comment]
Ah, oh well, I've already removed the mod from the modpack now. But thanks. :)
