### ISSUE TITLE
Lost Tablets no longer "Open" after recent update (1.12.2) (Dungeons, Dragons, and Space Shuttles)

### ISSUE THREAD

**Issue by Sartugha** [Corail31/tombstone_lite#103]
After updating to the newest version of DD&SS that has version 3.6.2 of Corail Tombstone, the Lost tablets are not damaging the player or unlocking their location.  An interesting observation I had, though, was that when I fished up a Lost Tablet I received the Advancement "Where is the Stone Pen."  As I am sure you know, this advancement is supposed to be rewarded when you enchant a strange tablet.

![Strange](https://user-images.githubusercontent.com/57288542/68913764-0c9b2c80-0722-11ea-88a9-b0b23c387a8a.JPG)

As a side note, thank you for the amazing Mod, I love how robust the aspects of the mod are.

**Comment by Corail31** [comment]
It's confirmed, and fixed in dev (3.6.0 is still the recommanded one and doesn't have this trouble).
Same for 1.14.4 with the recommanded version.

**Comment by Corail31** [comment]
@Sartugha it's published for 1.12 (1.14 will be fixed later as there're others changes ;) )
