### ISSUE TITLE
ServerHangWatchdog

### ISSUE THREAD

**Issue by Guest95300** [Corail31/tombstone_lite#103]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Corail Tombstone Version

tombstone-6.8.1-1.16.5

### What happened?

Server randomly crashes, I saw something related to "Tombstone Backup Thread" so I assume this mod is causing the crash.
[crash-2022-10-26_07.02.02-server.txt](https://github.com/Corail31/tombstone_lite/files/9867070/crash-2022-10-26_07.02.02-server.txt)

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Please, don't report server watchdog... it's just mean that your server tooks too long for a tick:
```java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)```
and is related to all your mods.
Edit: Perhaps, you can try "Spark" to diagnose performance issues (it would be more helful to locate the excessive ticking things than a log saying it's too late).
