### ISSUE TITLE
[Suggestion] Custom enchanted grave key

### ISSUE THREAD

**Issue by CritFlaw** [Corail31/tombstone_lite#104]
The ability to configure a custom item to be used to create the grave key that takes you back to your death-point, ideally with game-stage support. 

In general I would love if the mod had more game-stage support like vanilladeathchest so that the price of restoring your items on death scales with the player's progress.

**Comment by Corail31** [comment]
The grave's key recipe use an item tag for the recipe, so it can be replaced.
Game-stage support is not specially planned. Tombstone already uses a custom skill tree over time that is really slow, and the config options are numerous to set the game how you want it to be.
NB : i don't think it's good for players to lose any item not protected by the grave just to "scale" the game.
