### ISSUE TITLE
Potion Descriptions

### ISSUE THREAD

**Issue by AK-Chester** [Corail31/tombstone_lite#104]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Corail Tombstone Version

6.8.5

### What happened?

Thanks for making this, it's by far the best death / grave mod out there.

Could you please add [potion descriptions](https://www.curseforge.com/minecraft/mc-mods/potion-descriptions)?

![pd](https://user-images.githubusercontent.com/112804655/198251621-16db1300-1714-4be0-83e9-5e5338dc3ce8.jpg)

Keep up the great work!

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Potion descriptions

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Indeed, it will be added in the next release ;)

**Comment by AK-Chester** [comment]
Awesome, thanks! :)
