### ISSUE TITLE
druidcraft compatibility 

### ISSUE THREAD

**Issue by lag42** [Corail31/tombstone_lite#105]
the soul receptacle isn't picking up tamed mobs from [druidcraft](https://www.curseforge.com/minecraft/mc-mods/druidcraft), i'd like to be able to revive my beetles and dreadfish

quark's foxhound works so i think this is druidcraft not using the right flags that you pick up on

**Comment by lag42** [comment]
corresponding issue on [druidcraft's git](https://github.com/MysticMods/Druidcraft/issues/12)

**Comment by Corail31** [comment]
Hi lag42,
Actually, i check for TameableEntity (AnimalEntity->AgeableEntity->CreatureEntity) & AbstractHorseEntity.
The bettles of druidCraft extend TameableMonsterEntity->CreatureEntity.
So, it's how they want, they can extend the TameableEntity class, or i can make a compat to make it work without it.

**Comment by Corail31** [comment]
@lag42 Finally, i won't do it if the TameableMonsterEntity is not in the api, because i need to use their custom method setTamedBy...

**Comment by Corail31** [comment]
Not a lot of evolution on the other mod, so i pass this in Delested until they brought their opinion about it. (for me, their implementation is not ideal and should extend the tameable vanilla class)
