### ISSUE TITLE
forge crashes at opening a world 

### ISSUE THREAD

**Issue by elerex** [Corail31/tombstone_lite#106]
hi guys, could you help with this please?, I use tlauncher to play minecraft and I recently  installed forge 28.1.96 for the version 1.14.4 and while im trying to open one of my worlds or also create a new one it crashes and closes tha game, here  is the crash log: https://drive.google.com/file/d/1DGujpMESK2NqSvCmvBstH8QzuoT9GwcL/view?usp=sharing 
(its very long because i actually use like 16 mods taking advantage of my new laptop)

**Comment by Corail31** [comment]
Sorry, but this is not related to tombstone as it's not even present in your log, so i don't understand why you expect me to help you on this...
