### ISSUE TITLE
Tablet of Assistance teleports wrong player to each other

### ISSUE THREAD

**Issue by AechtRob** [Corail31/tombstone_lite#106]
### Minecraft Version

1.12.2

### Forge Version

2860

### Corail Tombstone Version

4.5.11-1.12.2

### What happened?

On a multiplayer server, when player A uses the Tablet of Assistance to teleport, entering the player B's name for where they want to teleport to...... it makes player B teleport to player A, rather than the other way around.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@AechtRob Can you ensure that the tablet is not an ancient tablet of assistance ?

**Comment by AechtRob** [comment]
Hi - yes we checked. When I use this tablet it tp's the named player to ME, and not vice versa.

![image](https://user-images.githubusercontent.com/59179133/200439864-d70e3405-dfea-4e2d-86a7-828163ab2210.png)

**Comment by Corail31** [comment]
Thanks for the info :)
Can you confirm if /tbrequestteleport is also inverted as this command is slightly linked to this tablet and it's not the first time that i mess this code (because testing this tablet is generally painful on my side) ?

**Comment by AechtRob** [comment]
If player A uses the command /tblrequestteleport and requests teleport with player B, then player A teleports to player B (once player B agrees to it). I don't know if this is inverted as I don't really know what the command is supposed to do.

**Comment by Corail31** [comment]
The bug seems to only exist in 1.12.2 and for non 'ancient' version.
Thanks for reporting this issue ;)
