### ISSUE TITLE
Hywla displays no info for Graves

### ISSUE THREAD

**Issue by WenXin20** [Corail31/tombstone_lite#107]
`Minecraft v1.14.4`
`Forge v28.1.96`
`Hwyla vB67`
`Tombstone v4.1.7`

If the player is looking at a tombstone that is formed after the player dies, Hwyla will not display any info at all.

**Comment by Corail31** [comment]
Was it different before?

**Comment by WenXin20** [comment]
I'm not sure if it is different from before, but I do know that if I look at a placed grave, it will display the name of the block, the id, and the states of the block (if enabled). But if looking at a grave placed after death, none of that will display. The info box won't display at all.

**Comment by Corail31** [comment]
@WenXin20 Sorry, i'm less productive in winter because it's a feast period.
You're right, it's reproductible in 1.12/1.14. It would be better to open an issue on Hwyla repo to ask to Tehnut, to avoid me to check its code. I would suppose it looks for an itemstack (and graves have no item version).

**Comment by WenXin20** [comment]
It's no problem!
I'm thinking the check for itemstack might be the case, the Ceiling Torch mod author also said that info won't display for the Ceiling Torch because it didn't have an item.

**Comment by WenXin20** [comment]
Found an issue for Hwyla with the same problem, but for 1.11.2
Looks like it go broken in the newer versions.

**Comment by WenXin20** [comment]
TehNut stated in the issue that mods can register a plugin. You can check the link above for the provided code example!

**Comment by Corail31** [comment]
![hwyla_compat](https://user-images.githubusercontent.com/17954109/71351700-a7362900-2574-11ea-80a3-bdce7fae19aa.png)
It looks to be good, thanks to TehNut for the informations ;)
But, it will only be added to next version for 1.12.2...

**Comment by WenXin20** [comment]
Nice!
