### ISSUE TITLE
Enchantment "Blessing" may grant OP effects when other mods are installed such as `cofh_core:supercharge`

### ISSUE THREAD

**Issue by James103** [Corail31/tombstone_lite#107]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Corail Tombstone Version

7.5.4

### What happened?

There are a few effects added by other mods that are either harmful, too OP for most players, and/or only intended to be used in debug/creative mode, but that are marked as beneficial. These effects include but are not limited to:
`cofh_core:supercharge` (charges all items in player's inventory with 2.147 GFE/t each)

A blacklist should be added to the server config to allow modpack creators to disable some potion effects from being randomly given when attacked while wearing armor with the Blessing enchantment, without having to disable the enchantment itself.

To reproduce,
1. Create a new instance with Minecraft 1.18.2 and Forge 40.1.84.
2. Install Cofh Core 9.0.0.24 and Corail Tombstone 7.5.4.
3. Create a new world with cheats enabled.
4. Give yourself unbreakable armor and enchant it with Blessing on all four pieces. Also enchant the armor with Protection IV on all four pieces and give yourself Resistance IV and Regeneration X.
5. Give yourself any battery (that holds RF/FE) and place it in your hotbar.
6. Get attacked by zombies, spiders, or other hostile mobs repeatedly while wearing said armor.
7. Wait.
8. Eventually, the battery will have been charged (partially or fully) due to the supercharging effect.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Other relevant mods

Cofh Core 9.0.0.24

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Config 'unhandled_beneficial_effects' (you can add the effect name or the modid for all effects of a mod).
