### ISSUE TITLE
tickloop(?)

### ISSUE THREAD

**Issue by Petrisis** [Corail31/tombstone_lite#108]
### Minecraft Version

1.19.2

### Forge Version

43.1.47

### Corail Tombstone Version

tombstone-8.2.0

### What happened?

playing ATM8 on a brand new server. reported this issue to the ATM help forum on discord too.
server went on 2nd day into tickloop-crashloop with many lines in the crash report indicating that corail does something. i dont understand these technical things so i thought i give it a try here.

crash report: https://gist.github.com/Petrisis/06ab8f4cd8c64873cc34fb97e1941288

the problem is gone when corail is removed from the server and client.

regarding occurence: it is occuring permanently now but i would not say its easy to replicate because i don't know what causes it...

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Log Link

https://gist.github.com/Petrisis/30348936bbe8f39e2b6c2ddf5e3d84bb

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Duplicate #103, serverHangWatchDog just mean your server took too long for a tick.
Uses Spark to locate your problem.
NB: 60sec for a tick that should last 1/20 sec means that you have probably highly ticking mods...

**Comment by Corail31** [comment]
@Petrisis I checked my code in the doubt but i didn't notice something like an infinite loop. May you confirm that you have server hang watchdog with a message not always targetting theses code lines. If not, it would mean that you would be able to make this happening with only Tombstone (like the template asks).

**Comment by Petrisis** [comment]
thanks for going in a deep investigation! i tried many things the last days with our server. we produced many more crashes but no more that pointed at corail. i am still in a conversation with our host about that bad performance of their services...

can be closed :)
