### ISSUE TITLE
Ghost rendering in multi

### ISSUE THREAD

**Issue by Ermen07** [Corail31/tombstone_lite#11]
When ghost disappear other client in the server continue to show you ghosted...

**Comment by Corail31** [comment]
Hi Ermen, i'll use look at this in the next release (but i'll take a week to finish it)

**Comment by Corail31** [comment]
@Ermen07  : let me know if the patch 1.6.1 corrects this.

**Comment by Ermen07** [comment]
Now works only when the effect finish. If i punch any entity to remove the effect doens't work but only when a little bit of time passes (i think the duration of the effect). Another is when you disable the effect (punching any entity) the particles remains but disappear after a bit of time (duration of the effect).
Another is when you die and respawn close to a player it seems that the player doesn't see you ghosted (with the effect) but yes for the client. To fix all this bugs i need to rejoin the server all times. (Tried with 1.6.1 (1.12) Version) PS: Sorry for my bad english.
![screenshot_1](https://user-images.githubusercontent.com/18754622/33176843-c8ea2e9a-d060-11e7-8661-8c919f04be42.png)
![screenshot_2](https://user-images.githubusercontent.com/18754622/33176844-cc8fa5de-d060-11e7-8ab5-799cc6603038.png)

**Comment by Corail31** [comment]
Thanks for the provided infos :)

**Comment by Corail31** [comment]
I don't forget you, i added some more checks about potion duration & blend profile in version 2.0.0 to correct this (not yet released) but i have no time for server test involving several players for now :)

**Comment by Corail31** [comment]
@Ermen07 : any news about this with the current versions?

**Comment by Ermen07** [comment]
I have not played anymore and unfortunately I can not try in this moment. Sorry @Corail31

**Comment by Corail31** [comment]
will be fixed in 2.1.1
