### ISSUE TITLE
Start up crash on forge 2702

### ISSUE THREAD

**Issue by DWX12** [Corail31/tombstone_lite#11]
Creating a modpack and after updating mods and using a working forge version (Forge 14.23.3.2702) I can successfully get a crash every time I add this mod. It took me awhile to go through everything to see what mod(s) were causing issues. Strange thing is that I got this or similar reports here and there, but Minecraft would load fine with more testing. So I'm not exactly sure what's going on. I only know that the few times I got reports like that, it was because I was missing core mods or libraries.

https://hastebin.com/ateqazejuj.rb
[crash-2018-06-18_23.54.06-client.txt](https://github.com/Corail31/tombstone_lite/files/2114177/crash-2018-06-18_23.54.06-client.txt)

Hopefully you can make sense of this. Thank you for the awesome mod and for being a great addition to the community.

**Comment by Corail31** [comment]
There's nothing related to my mod in your log, and 2.9.7 is working with no trouble on 2705 (2702 is not a recommanded version)

**Comment by Corail31** [comment]
NB : if you want me to investigate this a little more, you should show me a complete log.

**Comment by DWX12** [comment]
Alright, thanks alot. Atleast I have some direction to go by. I downgraded to that forge version simply because it was working for me rather than higher versions.

**Comment by DWX12** [comment]
Alright, updated to forge 2705, started my modpack without tombstone and got to the title screen without a problem. Added tombstone and got the same crash:

https://paste.dimdev.org/goyavohahe.mccrash

This is also from my latest log:
(ignore the lack of proper username in file locations, I edited them out)

https://hastebin.com/oqasonaqus.md

**Comment by DWX12** [comment]
I was running into this problem after updating mods. I hadn't touched that mod pack in awhile and received that crash when I tried booting it up. I took out all the mods and added them alphabetically (along with adding core mods along the way). So it seems I'll have to include your mod and do the same thing again until I get a crash.

If you don't have one already, consider making a discord channel since you have a fair amount of mods and that would help others to contact you easier, in addition to it being easier to contact other mod authors and developers (and teams).

Again, thanks for the help and awesome mods.

**Comment by Corail31** [comment]
Keep me update on this DWX12 :)

**Comment by DWX12** [comment]
I updated to your latest version of Tombstone, but haven't had a chance to sit down and work on my specific modpack that I'm using your mod in. I'll keep an eye out for you on discord and will keep you up to date with any more or current issues when I'm able to devote some time to Minecraft.
