### ISSUE TITLE
hardcore revival compat

### ISSUE THREAD

**Issue by cpm9** [Corail31/tombstone_lite#110]
When used witth hardcore revival the death message is bugged. This may be on the hardcore revival mods side not this mods side but I don't know so I will post it on both trackers.

Forge 28.1.96
Corail Tombstone 4.1.7
Hardcore Revival 3.0.10

> [Server thread/WARN] [tombstone/]: The death event of the player TextComponent{text='cpm9', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}} was cancelled by another mod
> 
> [Server thread/INFO] [minecraft/DedicatedServer]: death.attack.not_rescued_in_time

**Comment by Corail31** [comment]
This message of Tombstone is just to inform you that another mod has chosen to handle the death itself, and is server side as a log. It helps to debug sometimes ;)
