### ISSUE TITLE
It doesn't give me the Grave's Key in my server minecraft forge 1.16.5

### ISSUE THREAD

**Issue by Gabbonet** [Corail31/tombstone_lite#110]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Corail Tombstone Version

tombstone-6.8.6-1.16.5

### What happened?

In Single Player when I die it gives me the normal Grave's Key. But on a Forge server it creates doesn't give me the Grave's Key on death.

I have looked for the file to configure "tombstone-server.toml" and the option "allow_grave_key = true" is activated. Even so, on the server when I die it does not give me the Grave's Key

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

voicechat-forge-1.16.5-2.3.13 / Xaeros_Minimap_22.16.2_Forge_1.16.5 / jei-1.16.4-7.6.1.66

### Log Link

No crash happen

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Can you reduce your mod list to locate the mod making this incompatibility and provides the server log ?
Also, ensures to check the config "allow_grave_key" on the server (and not on your client).

**Comment by Gabbonet** [comment]
Even having the Tumbstone Mod completely alone the problem remains. But I have noticed that when I leave the server and re-enter I appear with the key in my hand.

Another thing that I discovered is that I tried with a server only "Forge" and it works perfectly alone and with the other mods without problems.

So I guess the problem is that I'm using MACMA Server, to have Mods + Plugins.

I leave you a screenshot of the version of Magma that I am using, I think that in Magma servers the key does not appear unless we exit and re-enter the server

Edit Corail31: don't post such screen.

**Comment by Gabbonet** [comment]
I closed accidentaly

**Comment by Corail31** [comment]
It seems you partially read the issue template (specially the part related to Magma: if something works differently with Magma, they have to fix their code)
NB: if you also don't have 'ghostly shape' on death, it probably means the respawn event is not fired.
