### ISSUE TITLE
Familiar Item Duplication

### ISSUE THREAD

**Issue by ArcaneSan** [Corail31/tombstone_lite#111]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Corail Tombstone Version

7.5.7-1.18.2

### What happened?

Obtain a familiar that can wear armor/weapons (Zombie, skeleton, ect)
Fully kit out familiar with equipment
Familiar is either killed by player or another mob
Items given to familiar will drop on death
Use Familiar Stone to resurrect mob
Familiar will come back fully equipped with items given to it

Repeatable

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I'll do the tests tomorrow but I guess your explanation is quite plausible.
Thanks for reporting this issue.

**Comment by Corail31** [comment]
@ArcaneSan You can test the new release: it guarantees the loots to drop except when a familiar receptacle is used.

**Comment by ArcaneSan** [comment]
After updating it appears to still be happening. Even with a completely fresh instance on mc and tombstone 7.5.8.

In fact, having a familiar that spawns with a weapon (Skeleton or Wither Skeleton) will in addition to the armor given, also drop their weapon at full durability 

Maybe something that prevents familiars from dropping any loot? I don't know if a mob can have "keep inventory" or not.

**Comment by Corail31** [comment]
@ArcaneSan I did the tests, so i'm sure it works in 1.18.2 (with a skeleton and familiar stone/receptacle).
If you have no familiar receptacle, all the equipped items will drop and vice versa, nothing will drop.
Ensures to make the tests with no other mod (and no hybrid server like Magma).
NB: if it's because the servants can drop the existing items instead of just the ones you gave, i don't think it could be a balance problem, the player needs to reach a certain "bad alignment" and the pray can only be done every 3 hours of playing time (min 1 hour with config).
Edit: the Familiar Stone is almostly a creative item allowing fast tests (but is also an advancement reward).

**Comment by ArcaneSan** [comment]
What I do is obtain a receptacle already filled. Pray to summon the familiar, give them items, and when they die they drop their items. Using a familiar stone, I can revive them.  When they return, they have the same gear before they died. 

I use curseforge to load up forge with just corail tombstone. So just regular forge

So I guess with someone having a lot of familiar stones and additional use for extra armor it can be an issue? (Salvaging or something)

maybe I'm just confused

**Comment by ArcaneSan** [comment]
Alright I made a short video showcasing exactly what I am referring to. I can't help but feel like I can't explain it well enough. A video demonstration is easier.

Edit Corail31: don't post such a link.

**Comment by Corail31** [comment]
@ArcaneSan Your issue title is about "dupe". There's no more dupe and servants drop their inventory.
NB: make sure you have read my previous answers. It's still possible to add a config if you prefer to never drop the servant inventory but i think it's more important to always retrieve any item that a minion might pick up.

**Comment by ArcaneSan** [comment]
Thanks for the time
Edit: yeah being able to retrieve what the servents pick up is ultimately more important. Them still having the inventory after returning with the familiar stone probably isn't too much of a deal for most cases since the stone itself is probably harder to get than most equipment.
