### ISSUE TITLE
[Question] Source code repo

### ISSUE THREAD

**Issue by LorenaGdL** [Corail31/tombstone_lite#111]
Hi,

Do you an official repository with the main source code? I'd like to propose some pull requests and others, but I don't seem to find anything apart from this and API repo.

**Comment by Corail31** [comment]
The code is on a private repo, but what do you need to be exposed from the api ?

**Comment by LorenaGdL** [comment]
It isn't a matter of having things exposed in the API. The API is extremely limited and in any case it is by no means the way to provide fixes/improvements/compatibilities to the mod by the community, which is exactly the purpose I talked about in my question.

It's your mod, so obviously your code and your choice, but now more than ever the mod would benefit from having an official open source code repo, since you're semi-abandoning/abandoning the mod.

Anyway, given your initial answer, and above all, given you've unilaterally closed this question just 7 days after I opened it (in the middle on some holidays, btw) without any warning, follow-up or whatever, well, it clearly shows your position regarding your mod and the community.

Not interested in collaborating anymore.

**Comment by Corail31** [comment]
So, i'll be clear on this, it's your choice to propose help in contribution (as far as i have seen you don't have a lot of repositories or anything else that can show me it worth to give an access, some people have access to it... if you don't know).
Then, my mod is up-to-date and all compats are always done on my side... so you probably don't know my mod at all.
Then, your opinion or trolling things, you can keep them for you, the source has been for a long visible without any commit, and it's now removed as the patreon contribution (also meaning i don't have to account for the way I manage the issues).

**Comment by LorenaGdL** [comment]
Honestly, you're again showing a clear lack of respect when I've been extremely polite in both my messages. I will answer you, although by now I don't think it's worth my time.

> it's your choice to propose help in contribution

It is, as it's your choice to accept or decline such help/contributions. However, you could've chosen to do it politely, and with some humility, which you haven't, and that's exactly the reason I stated I don't feel like wanting to contribute anymore to this mod.

> (as far as i have seen you don't have a lot of repositories or anything else that can show me it worth to give an access, some people have access to it... if you don't know).

1) You obviously don't know what I have or haven't done previsouly, as you don't know what other accounts may or may not I have. Yet if this would have been a reason to reject my question, and if you would have been interested, you would have explained and/or asked.
2) Granting access only to people you feel "worthy" is again your choice, though it proves two things to me: a) you feel superior to everyone else by default, until they prove something to you (something you don't ask for directly, instead it's something you try to discover/imply by spying their other repositories - you won't go far this way); b) you clearly lack knowledge of open source code & collaboration schemes (e.g. PRs). Someone wanting to help/contribute and giving them access to your repository doesn't mean they're automatically allowed to make direct changes.
2) I think my original question makes it clear I don't know the existence of accessible code, whether publicly or throught a whitelist. So yeah, I didn't know, and that's exactly what I asked. And you trying to point out there is accessible code like I should know it, well, it indicates you either have a lack of reading skills and/or you're failing to stick something to me.
3) I did not in any case requested access to your code in an exclusive manner, or depicting myself as the master of modding. I asked a pretty simple question with politeness. You in exchange have gone wild for no reason at all.

> Then, my mod is up-to-date and all compats are always done on my side... so you probably don't know my mod at all.

Once again, you're getting on the defensive for no reason at all. Have I said your mod is outdated? No. Have I said you haven't done compats in the past? No. Have I even implied you've done a bad job in the mod? I don't think so. I just said open source collaboration schemes help to do it more easily. And I did say your mod would benefit from it more than ever because you have stated you're semi-abandoning/abandoning mod development to focus on other stuff.

>  Then, your opinion or trolling things, you can keep them for you,

This kind of answer/behaviour is exactly why I said I don't want to even try to contribute anymore. I don't even feel like I need to explain this one. I did give my opinion, as I'm entitled to do, and I always did it politely and thinking about the better for the mod. If you don't want to hear opinions or questions, please close this repository already for everyone's sake. And well, trolling? It seems trolling means to you wanting to help, because otherwise I don't see anything I said remotely close to trolling.

> also meaning i don't have to account for the way I manage the issues

Man, do whatever you want, and manage things whatever way you feel. Just saying you showed quite disrespect and your clear position about not giving a damn about the mod and/or the community. Yet this again is your choice and/or problem.

If you feel attacked because I said I'm not interested in contributing anymore, read and think twice about the way you came across instead of going full rage with no reason,

If you really think people come here to troll or waste their time because they're bored at home, you honestly have a huge problem, and you understand nothing at all about Minecraft modding community.

I won't reply here anymore. I'd wish you luck, but I honestly don't feel like it.

**Comment by choekstr** [comment]
FYI, Corail31 is not native english speaker (he is french) so you will get some terse or not fluent responses, which I think you find offensive when they aren't meant to be. Also your wall of text probably lost him and the subtleties you bring up are probably lost as well.  His english is not very good yet.

Most people who have an issue tracker want to keep it clean.  responding, not hearing anything for a week, and closing the issue is common practice for someone actively working on issues and trying to close everything they can.  While it might have seemed offensive to close your question/issue after a week, it was also offensive to not respond after a week and once it was closed respond within 4 hours.  

Corail31 has been actively developing this mod in the 2 years I have known him and used his tombstone mod.  Your comment of:
> since you're semi-abandoning/abandoning the mod.
seems to indicate you didn't look at his curseforge page to see he has recent updated 1.12 PLUS 1.14 versions.  Plus I happen to have seen screenshots of his mod working on 1.15!  I would be there is less than a dozen mods working on 1.15 right now.  So you see, you started off kinda misguided and someone who has chosen not to open source his mod would probably have questions about someone who made a blatent error like that.  Then you came back and stated:
> Once again, you're getting on the defensive for no reason at all. Have I said your mod is outdated? No.
Yeah, ya kinda did.  

You can always decompile the mod very easily and add your input to corail31 directly, as feature requests, as pastebin links in suggestions.  Looking someone up to see what they have done on github is common practice and any developer needs to prove themselves and show they have solid code before it is accepted.  You don't have a track record (neither do I and would never expect to be trusted), nor has there been any code offered up.  

I think Corail31 is just being cautious, was asking for a bit more detail, and was met with some troll behavior.  Perhaps you might want to offer up some suggestions where you think you would make changes/updates, maybe some bug fixes if you found a bug and work with him.  it's far more productive.

**Comment by Corail31** [comment]
Hm, thanks @choekstr ,
I have no pretention about what i learned in java, being more an analyst programmer/php dev.
But i think the code is strong enough and only a few modder could bring improvments.
The Midnight needs help seriously... as i don't have time for it, why not committing on it ?

**Comment by LorenaGdL** [comment]
@choekstr 

> FYI, Corail31 is not native english speaker (he is french) so you will get some terse or not fluent responses, which I think you find offensive when they aren't meant to be. Also your wall of text probably lost him and the subtleties you bring up are probably lost as well. His english is not very good yet.

I'm sorry about that. Although I'm finding hard to believe that _"Then, your opinion or trolling things, you can keep them for you"_ wasn't meant to be offensive.

> While it might have seemed offensive to close your question/issue after a week, it was also offensive to not respond after a week and once it was closed respond within 4 hours.

Well the truth is I was making a list of issues/suggestions/others before properly answering here. And given we're in the middle of some pretty big holidays, I simply did not find the time to provide something in a week. So I did not answer exactly because I wanted to be productive, as you point out in your last paragraph. To me, there's absolutely no reason to close this simple question out of the blue, without any follow-up, in a repo with literally 0 issues open (and this wasn't even an issue at all, it was someone kinda offering help, you don't close issues of this kind just because after 7 days). I don't appreciate being treated this way, that's all.

> So you see, you started off kinda misguided and someone who has chosen not to open source his mod would probably have questions about someone who made a blatent error like that

Misguided, a blatant error? I'm not gonna argue, but I'll just post this from his Courseforge page:
_"Initially, i started developping my mods to improve my understanding of Java.
After 3 years of modding, i decided to reduce my modding time to the minimum in order to focus on others thing, not receiving suffient support from the community to be able to keep this activity.
I will continue to maintain my mods over time, but i won't make new mod, and new content is not specially planned.
Good Sabbath and thank you for making Tombstone so popular this last year ^^ [21/09/19]"_ 
All I understand from this very statement is that he is semi-abandoning/abandoning the mod and that he has not received enough help from the community in the past, and exactly the reason why I was willing to offer my help.

> Yeah, ya kinda did.

Please, indicate where exactly I said or even implied the mod is outdated. Wanting to improve or suggest stuff is a way different thing.

> You can always decompile the mod very easily and add your input to corail31 directly, as feature requests, as pastebin links in suggestions.

My initial question was about having an open source code repo, and that's the expected initial approach from my side imho.

> Looking someone up to see what they have done on github is common practice and any developer needs to prove themselves and show they have solid code before it is accepted. You don't have a track record (neither do I and would never expect to be trusted), nor has there been any code offered up.

Again, the problem is not about the fact, is about how he handled things. All I did was ask a simple question, I didn't offer anything because simply it wasn't the goal, not at this point. I can't make a PR if there's no open repo, and I don't see a reason to prove myself just because I want to know if there's a public repo. Does he need to review code before accepting it? Of course, obviously. But that's far from the simple question I asked. And again, as I already stated, if that would've been the reason to reject my contribution at any point (now or in the future), just explain it politely. This isn't about not being trusted whatsoever, it's about treating potential contributors with a minimum of respect.

> I think Corail31 is just being cautious, was asking for a bit more detail, and was met with some troll behavior.

Seriously, I still don't see any troll behaviour at all. You can agree or disagree with me or my opinions, but my answers have nothing, absolutely nothing related to trolling. And I don't appreciate being called a troll when all I did was employing my time to offer my help.

I'm leaving this here because this isn't going anywhere. At this point I just simply don't want to get involved with people who treat potential contributors this way, which I felt highly disrespectful, just that. As I said, if you identify this as trolling, you may want to read or think twice about this whole issue, because I'm betting many others will feel the same in the future.

**Comment by Corail31** [comment]
Seriously, you have a trouble, someone says you that i can read roman and you make roman... guy, go in hell i don't care of your troubles... the main conversation goes down because you say on your second answer i won't colloborate anymore...

**Comment by LorenaGdL** [comment]
@Corail31 my last reply wasn't directed to you, as I clearly pointed out in the first line. You again keep going full rage when I even didn't answered to you. Again, I'm truly sorry if you're not so proficient in English, but if you misunderstand and/or misinterpret my messages because of that, I'm sorry to say that's not my fault. Under other circumstances I'd ask what exactly within my text reflects "bad intention" as you say, but let's leave it here. I already said this is going nowhere, yet you continue to grow a dispute that makes no longer sense for anyone. I wanted to help, and you rejected my offer (in a questionable way imho), period. There was no need of your last message, as there was no need of labelling this issue as "Troll". I won't make any more comments, at least not to you. I have more respect than that whether you like or not.

@choekstr This last reply from the mod owner is what I've been referring to in my posts as clear signs of disrespect, which I think are clearly meant. You can disagree with me at certain level/stuff, no probs about that, but I don't really think this is the expected behaviour at all from the mod owner. Things can be discussed like adults, with politeness. I'm a person always open to listen to others' points of view. But labelling the issue as "Troll" only supports my message. I don't think anyone wanting to contribute should be treated this way at all. You seem a reasonable guy, and I'm sure you can see the problems here (whether you decide you publicly comment on it or not, which I understand). If you're somewhat close to Corail and somewhat appreciate him, please advise him a little bit. This is far from being the way to handle things with people trying to help.
