### ISSUE TITLE
crazy log spam on server [Earth Mobs]

### ISSUE THREAD

**Issue by Zelioth** [Corail31/tombstone_lite#112]
### Minecraft Version

1.19.2

### Forge Version

43.1.55

### Corail Tombstone Version

8.2.1

### What happened?

[22.11 18:47:39] [Server] [Server thread/INFO] [tombstone/]: A mod is doing something strange in LivingEntity.getModType()
[22.11 18:47:39] [Server] [Server thread/INFO] [tombstone/]: A mod is doing something strange in LivingEntity.getModType()
[22.11 18:47:39] [Server] [Server thread/INFO] [tombstone/]: A mod is doing something strange in LivingEntity.getModType()
[22.11 18:47:39] [Server] [Server thread/INFO] [tombstone/]: A mod is doing something strange in LivingEntity.getModType()
[22.11 18:47:39] [Server] [Server thread/INFO] [tombstone/]: A mod is doing something strange in LivingEntity.getModType()
[22.11 18:47:39] [Server] [Server thread/INFO] [tombstone/]: A mod is doing something strange in LivingEntity.getModType()
[22.11 18:47:39] [Server] [Server thread/INFO] [tombstone/]: A mod is doing something strange in LivingEntity.getModType()
[22.11 18:47:39] [Server] [Server thread/INFO] [tombstone/]: A mod is doing something strange in LivingEntity.getModType()
[22.11 18:47:39] [Server] [Server thread/INFO] [tombstone/]: A mod is doing something strange in LivingEntity.getModType()

Crazy log being spammed with this information

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You will need to locate the mod that makes this log to appear.

**Comment by Zelioth** [comment]
It doesn't seem to do this on older versions of the mod though

**Comment by Corail31** [comment]
I added this log (with a small mistake in the text as it's MobType) to locate a problem with a mod using mixin related to this issue:
https://github.com/Shadows-of-Fire/Apotheosis/issues/714

**Comment by Zelioth** [comment]
So you think that issue I was having with Apothosis is related to this error? I don't doubt it if that is what you are saying the mobs it spawns constantly causes issues with mob de-spawning, ticking entities hanging the server, etc

Apothosis is the only mod that greatly modifies mobs as well on my pack and server

**Comment by Corail31** [comment]
I don't think it's Apotheosis but one of the mixins mentioned in the log, i already check the mixins in Apotheosis and i didn't notice anything related to this method (and players can find the mod with the log if they want to help me).

**Comment by Zelioth** [comment]
What do you think would cause this issue? I have mods that control mob spawning, that stop ticking entities. tons of mods haha. too many to count 

wait I just reread the last part of our message. OF COARSE i'll help because it helps me to :D

**Comment by Zelioth** [comment]
https://bytebin.lucko.me/L3750pOViX

https://bytebin.lucko.me/idrtDBDBAg

Here are the latest two logs from my Friends United Pack and Public Server

**Comment by Corail31** [comment]
I recommand you to test first with only Corail Tombstone to see if the logs appear (to check if it's not just my mod, i'm not 'oversight proof'.
Then, if not, to test half of your mods each time to find the part having the log visible, in way to find the mod having an incompatibility or bug (i can take some times if your pack has lots of mods).

**Comment by Zelioth** [comment]
Taking this to a controlled local Environment. I'll update you on what mod once I find it in case anyone else comes to you with the question :D

**Comment by Zelioth** [comment]
with 450+ mods that is impossible. is there a way to just have it tell me what mod it's detecting that error from haha

**Comment by Zelioth** [comment]
Earth Mobs Version 3.5.2

When it is included in the pack it happens, when removing it the error goes away. tested in a server with just tombstone and earthmobs and the error occurred. removed earth mobs the error went away

**Comment by Corail31** [comment]
I really appreciate that you locate the mod.
You'll have to open an issue on their mod why their mod is breaking a simple call to getMobType() but i suppose the last commit on their github already fix the problem and **you just need to update your version of 'earth mobs'**.
https://github.com/baguchan/EarthMobs/blob/1.19/src/main/java/baguchan/earthmobsmod/mixin/LivingEntityMixin.java#L26
NB: the debug log will be removed in the next release now that i know which mod is doing this (note that the null is already caught by my code and the log was just to locate this mod instead of applying a blind fix).

**Comment by Corail31** [comment]
https://github.com/baguchan/EarthMobs/issues/30
