### ISSUE TITLE
tinker's battlesigns aren't re-equiped in offhand on regaining inventory

### ISSUE THREAD

**Issue by TDSSS** [Corail31/tombstone_lite#112]
When I die while using an offhand weapon (specifically a tinker's battlesign) and then regain my inventory by rightclicking the tombstone, the battlesign isn't equipped to my offhand, like my armor is. Since I was standing in flowing water and there wasn't any space in my inventory, it was carried away never to be seen again.

**Comment by Corail31** [comment]
If it isn't equipped, it probably means the item is stackable, or the item is not a shield, not sure what is your battlesign. If you have a full inventory, you expose yourself to this kind of minor trouble.

**Comment by TDSSS** [comment]
Tinker's Battlesigns definitely aren't stackable. It might be that they can be used as both a shield and as a weapon to hit people with.
