### ISSUE TITLE
Recent Crash But unsure if it's Tombstone at fault. 

### ISSUE THREAD

**Issue by Zelioth** [Corail31/tombstone_lite#114]
### Minecraft Version

1.19.2

### Forge Version

43.1.55

### Corail Tombstone Version

Latest

### What happened?

Server crashed with multiple players involved. Crash report from LOG does mention Tombstone to start but unsure if it was the issue. Reporting just in case it is and an unknown issue
[Recent Crash From Log.txt](https://github.com/Corail31/tombstone_lite/files/10097574/Recent.Crash.From.Log.txt)

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs rarely

### Other relevant mods

Friends United Mod Pack

### Log Link

https://pastebin.com/PMYrKxq4

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
The error is not from Corail Tombstone, what you're refering is about the suscribed mods to that event with the priority.
Updates or remove the mod "mo_enchants".
