### ISSUE TITLE
[1.14.4] Server Crash - "Exception in server tick loop" ?

### ISSUE THREAD

**Issue by Gbergz** [Corail31/tombstone_lite#115]
Now this doesn't happen every time it starts, it just happened now for some weird reason.

**Forge Version**: 28.1.107
**Mod-Version**: 4.1.8
**MC-Version**: 1.14.4

Crash-Report: [https://gist.github.com/Gbergz/d1cd3de7eb419ab4b85478a3c83f2b75](https://gist.github.com/Gbergz/d1cd3de7eb419ab4b85478a3c83f2b75)

**Comment by Corail31** [comment]
I don't think it's related to Tombstone, there're examples on the web about this issue :
https://www.minecraftforge.net/forum/topic/79123-cant-start-forge-server-file-with-mods/
https://board.aternos.org/thread/34864-server-crashes-when-installing-any-new-mod-1-14-4/
The error is not relevant and i suppose it's more related to the number of mods that you have that can make this happening, even rarely on startup.

**Comment by Corail31** [comment]
@Gbergz if you succeed to get it again in a reproductible way, i could look further. If it's only happened once and no more, it would be difficult to give you an answer (but i keep it in mind).
