### ISSUE TITLE
The tombstone does not recharge the soul

### ISSUE THREAD

**Issue by jbrandek** [Corail31/tombstone_lite#116]
### Minecraft Version

1.19.2

### Forge Version

43.1.47

### Corail Tombstone Version

8.2.2

### What happened?

Hi i upgraded to the last version 8.2.2 and now the tombstone are not recharging i played for a couple of hours and nothing...

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You can change configs 'chance_soul' & 'time_soul' to check it works properly.
The chance is on 1000 (100 by default so 10%).
The only change in 8.2.2 is what is noticed in the release notes.
NB: the issue template asks you to test with only Corail Tombstone to provide you an answer based on your informations (if you're using oculus and an incompatible shader for example).
