### ISSUE TITLE
Lost Tablet not working

### ISSUE THREAD

**Issue by Juanchoperezlol** [Corail31/tombstone_lite#116]
Hey, sorry if this is somewhere else but I couldnt find it, everything in the mod is awesome except the Lost tablet, the idea is great but for some reason its magic doesnt awaken. It just does no damage to me and therefore doesnt give me a location to go to. The familiar receptacle does work. Maybe some incompatibility problem? Thanks for your time! :)

**Comment by Corail31** [comment]
Hi, what is your forge version as only some versions got the lost tablets not working.

**Comment by Corail31** [comment]
@Juanchoperezlol I'm waiting your answer.

**Comment by Corail31** [comment]
probably a dupe of #103

**Comment by Juanchoperezlol** [comment]
Sorry for not answering, the serer in which I was playing was deleted and I forgot about this. I was playing in 1.12.2
