### ISSUE TITLE
Grave key use desyncs when used.

### ISSUE THREAD

**Issue by Darkere** [Corail31/tombstone_lite#117]
When holding the Key in hand I'm unable to interact with blocks, like chests and furnaces.

This creates some ugly desyncs when trying to open doors on servers. 
![image](https://user-images.githubusercontent.com/4283717/72544899-6f2ab900-3888-11ea-87d6-3273a64555f6.png)

The doors aren't actually open :(

tombstone-4.1.9-1.15.1
forge-30.0.39

**Comment by Corail31** [comment]
Hi Darkere, the key shouldn't interact with the blocks.
I just made tests about it and it's reproductible in 1.14.4 and 1.15.1, but not in 1.12.2 (even if the codes are exactly the same)
So, it could be a forge bug about onItemUseFirst.
Normally, the key returns a ActionResultType PASS when it interacts a grave, and SUCCESS when not.
If i would try to return PASS to the door, it would open it and it's not the objective. (and FAIL has the same trouble as your screen)

**Comment by Corail31** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/6448

**Comment by Corail31** [comment]
fixed in forge 1.15.2-31.0.11
