### ISSUE TITLE
Rubidium and Tombstone incompatibility..?

### ISSUE THREAD

**Issue by DetailedZetoprime** [Corail31/tombstone_lite#118]
### Minecraft Version

1.18.2

### Forge Version

1.18.2-40.1.86

### Corail Tombstone Version

tombstone-7.5.8-1.18.2

### What happened?

Adding Corail Tombstone to the modpack causes it to crash instantly, at first it works but once the config for corail tombstone is generated. Crashes occur( Crash logs seem to show Rubidium having responsibility for it)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Rubidium

### Log Link

https://pastebin.com/T9AkjTLg

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You didn't follow the issue template, your issue is now closed, feel free to better read next time and provides the adequates informations and the test with only the related mods.
