### ISSUE TITLE
Fishing Rod Of Misadventure Not Working

### ISSUE THREAD

**Issue by ddd800** [Corail31/tombstone_lite#118]
**Minecraft:** 1.12.2
**Forge:** 14.23.5.2847
**Corail:** Corail Tombstone 3.6.4 for 1.12.2
**Incompatible Mod:** 	Advanced-Fishing-1.3.3
**Problem:** Fishing rod will not cast whether enchanted or not. I have found that the mod Advanced Fishing(unsurprisingly) to be the conflict.

**Comment by Corail31** [comment]
Hi ddd800,
the mod Advanced Fishing uses an event to change the entityFishHook and this condition seems not correct :
https://github.com/NightKosh/Advanced-Fishing/blob/master/src/main/java/nightkosh/advanced_fishing/core/EventsHandler.java#L34
There seems to be an option in the mod to disable this : Config.overrideVanillaFishing

**Comment by Corail31** [comment]
@ddd800 can you try this small compat to solve this ? [LINK](https://tinyurl.com/w4cvv7p)

**Comment by ddd800** [comment]
Yeah, that config change fixed it I am so sorry for bothering you about this I should have looked at the config first which I will do first in the future.
