### ISSUE TITLE
[1.16.5] Mobs with inventories duplicate items when brought back with familiar stone

### ISSUE THREAD

**Issue by DoctorMage** [Corail31/tombstone_lite#119]
### Minecraft Version

1.16.5

### Forge Version

Forge 36.2.39 

### Corail Tombstone Version

tombstone-6.8.7-1.16.5.jar

### What happened?

As said in title

have mob that can store items example mule, donkey or human companion
have them die pickup items
bring them back with familiar stone and they will have the inventory they died with

tested with just corail and corail and human companions

[Edit Corail31: sorry, i don't accept such a link (and i won't watch them in any case)]

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

humancompanions-1.16.5-1.5.1.jar

### Log Link

https://gist.github.com/DoctorMage/06692065ee57fe874946cac89b60292b

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Can you check this [issue](https://github.com/Corail31/tombstone_lite/issues/111) and confirm that you have read it ?
Then, explain me how you obtain thoses 'familiar stone' ?
NB: 'Familiar Stone' is the 'creative item version' of the command 'tbReviveFamiliar' and is different from a 'Familiar Receptacle'.

**Comment by DoctorMage** [comment]
Ah apologies was reporting issue from a modpack see the error only reason I used familiar stone was due to the person reporting it having them.

Seems that a something is adding them to chest loot tables

**Comment by Corail31** [comment]
@DoctorMage It's an advancement reward. It's also present in Seeker Rod & Villager Gift with chance.
Should i remove it from the Seeker Rod ?

**Comment by DoctorMage** [comment]
I would say leave it as it is or possible config option to disable obtaining of the option for pack authors.

I do understand the utillities of it aka inventory mob dies in lava then you can use it like that since items would have been lost
