### ISSUE TITLE
Where does a players grave go when they die in the void?

### ISSUE THREAD

**Issue by Fleepy** [Corail31/tombstone_lite#119]
One of my friends died in the void in Project Ozone 3 and we had no idea where her grave was. Since we couldnt find it we had to use nbtexplorer to recover her inventory.

Does their grave still exist or was it never created?

**Comment by Corail31** [comment]
You get a message each time you die saying you if if creates a new grave, or fills an existing one, or no place was found. On the same time, you have in general a key showing the place at distance.
So, the game already provides you all theses answers.
NB : you have a command /tbrecovery to restore a player inventory.

**Comment by Corail31** [comment]
@Fleepy did you get the answer expected?
