### ISSUE TITLE
Permanent intangability with newest build. 

### ISSUE THREAD

**Issue by Akitori** [Corail31/tombstone_lite#12]
Forge 2555, corail tombstone 2.1.1

This is the issue.

https://youtu.be/5Doh9bmBNUY

In summary: I'm in permanent ghost form and only lose it when using the new scroll.

**Comment by Corail31** [comment]
Hi Akitori, sorry for this, it's mainly visual but ennoying.
I'll fix this, thanks for the report :)

**Comment by Corail31** [comment]
fixed in 2.1.2
