### ISSUE TITLE
Crash ItemLostTablet.wakeUpMagic

### ISSUE THREAD

**Issue by Drunkender** [Corail31/tombstone_lite#12]
Have two lost tablets in my inventory than random freeze, immediate crash log.
Modern Skyblock 3: Departed 3.4.1.3 ... Manually downgraded oreexcavator  ...

Forge 14.23.4.2705

https://paste.dimdev.org/vehapuroca.sql

Dropping the tablets into the void stops the freezing.

EDIT: Corail Tombstone Version 2.9.7 for 1.12.2

**Comment by Corail31** [comment]
Thanks for this report Drunkender, i'll release a version with the right import ;)
