### ISSUE TITLE
Magic items are casting but doing nothing when targetting a block

### ISSUE THREAD

**Issue by Ormathonz** [Corail31/tombstone_lite#120]
The second the channel is finished it tries to start a channel again since you are holding down right click.
So the first teleport check becomes invalid. So its a useless item since its impossible to let go of right click that fast after the channel finishes.

**Comment by Corail31** [comment]
Please consider this : [How to post an issue](https://github.com/Corail31/tombstone_lite/issues/96)
Any information really needs context to understand a little more your trouble.
When you hold an "enchanted magic grave item", it makes an action similar to a bow with a duration to end it and cast the spell. If your server is really laguy, the action can be finished on the client but not on the server, but you need to maintain the click any way until it teleports.

**Comment by Corail31** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/6448

**Comment by Corail31** [comment]
The bug is still present in forge as they didn't add it to the release even if they got all informations for the fix... so if you got this bug, report directly to forge...

**Comment by Corail31** [comment]
fixed in forge 1.15.2-31.1.8
