### ISSUE TITLE
Trying to copy paste grave contents / inventory list from previous death to new grave

### ISSUE THREAD

**Issue by Jackchessell1** [Corail31/tombstone_lite#120]
### Minecraft Version

1.19.2

### Forge Version

43.1.55

### Corail Tombstone Version

8.2.1

### What happened?

I recently encountered what is apparently a fairly common bug where I fell into the void in the end  and the game failed to generate a tombstone In order to solve this my friend and I were attempting to copy paste the contents / inventory list from a previous death in order to overide the contents of the grave so I could get my items back we are currently unsure what to do we have tried reloading previous player saves and are unsure what to do 

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
"I recently encountered what is apparently a fairly common bug"
-> i don't appreciate such formulation that would say it's possible to have no grave in void... without bringing anything that could help you so i will simply close and not answer.
I just hope you didn't create your github account to troll.

**Comment by Jackchessell1** [comment]
My apologies I had thought this was a simply a known issue an what I meant is that I had fallen in the void previously a few times and it generated a grave with my items and I had no issues for some reason this time however what happened was I respawned received the grave key went back to the end and the key suddenly disappeared for some reason
