### ISSUE TITLE
[suggestion] selective item collection

### ISSUE THREAD

**Issue by Biviho** [Corail31/tombstone_lite#121]
hi, i was wondering if it's possible to add the ability to select witch slots will be collected from the tomb as a config option.
For example i want to always keep armor, bubles and the hotbar, but i don't want the main inventory to be collected by the tomb and be dropped normally.
is this possible?

**Comment by Corail31** [comment]
Hi Biviho,
if you explain me the exact reason to want the main inventory to be outside the grave and so that can despawn ? as it's not really the objective of the mod, and can finished in report in my issues as they lost a part of their inventory because the modpacker just wants to make their life harder.

**Comment by Biviho** [comment]
the reason is to give meaningfull consequences to death:
while playing with tombstone in my pack i noticed that death was nothing more that an inconvenience as i can just walk there and recover my items, instead of something to fear of.
this way the player is able to keep items he worked hard on (eqquipment, bubles, hotbar items) while keeping the fear of a despawning dropped loot.
i know that there is an option to loose a percentage of items carried, but i think that this solution give more frustration than item dropped, as a sure percentage lost is not the same as the possibility to loose your items, but the ability to recover them all.
sorry for the bad english

**Comment by Corail31** [comment]
As you mention, there're config options, like disabling player grave, or the % to have lost that is not an exact % of lost but a chance of losing items, and the items lost are never something important as it needs to be at least stackable & no nbt.
