### ISSUE TITLE
1.15.2 server crash

### ISSUE THREAD

**Issue by Quu1337** [Corail31/tombstone_lite#122]
Using "recall tablet" apparently crashes server, user tested it 2 times.

Crash log: https://pastebin.com/Gr5JrrXh

tombstone-4.2.0-1.15.1.jar
forge-1.15.2-31.1.0

All The Mods 5, 1.0

**Comment by Corail31** [comment]
Your error is not related to Tombstone, and you can check it works properly without your others mods.
The line for the error is MathHelper.clamp()...
