### ISSUE TITLE
[1.15.2] Tablets get stuck on a 1 min cooldown after update.

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/tombstone_lite#123]
![2020-02-06_17 22 48](https://user-images.githubusercontent.com/4427684/73990793-741edd80-4907-11ea-9258-bbc3ad2a11e7.png)

tombstone-4.2.1-1.15.2
forge-1.15.2-31.1.0

**Comment by Corail31** [comment]
Impossible to reproduce, tested on server... except if your world time is stuck, i don't see any reason for this as it's a comparaison of time...
