### ISSUE TITLE
crash with latest version of Fluidlogged API

### ISSUE THREAD

**Issue by jbredwards** [Corail31/tombstone_lite#123]
### Minecraft Version

1.12.2

### Forge Version

latest

### Corail Tombstone Version

latest

### What happened?

It's discouraged for mods to call anything within the `fluidlogged_api.mod` package, since it can change at any time. The recommended ways of making blocks fluidloggable is to either have them extend the `IFluidloggable` interface ([example](https://github.com/jbredwards/Campfire-Mod/blob/1.12.2/src/main/java/git/jbredwards/campfire/common/block/AbstractCampfire.java)), or to add them to `assets/$your_modid$/fluidlogged_api/whitelist.json` ([example](https://github.com/jbredwards/Seared-Ladder-Backport-Mod/blob/1.12.2/src/main/resources/assets/searedladder/fluidlogged_api/whitelist.json)).

I didn't realize your mod had fluidlogged api compatibility, otherwise I wouldn't have renamed the config class, sorry 😅

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Fluidlogged API

### Log Link

https://mclo.gs/ntJgtcS

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@jbredwards Hi jbred, as long as i'm informed, it's fine.
As a provisory solution, it's possible to use a version before the compatibility (in 4.5.5) or your update.
Btw, i'm surprised that so few people use your mod in 1.12.2 because it allows to spawn graves in water without any visual trouble for 'not-water material' block.

**Comment by Corail31** [comment]
@jbredwards I didn't use your config this time ;p
