### ISSUE TITLE
Possible issue/incompatibility with Giacomo's fishing net.

### ISSUE THREAD

**Issue by SkullNo1se** [Corail31/tombstone_lite#124]
### Minecraft Version

1.19.2

### Forge Version

1.19.2-forge-43.2.1

### Corail Tombstone Version

8.2.2

### What happened?

After a starting time of few hours,i crash and get the following crash report that i've sent there,if i try to resume the play,the same error happens every few minutes.
From the look of it,seems Tombstone have issues with Giacomo's fishing net mod,probably because the nets use Loot pools.

Thank you for your time.

[crash-2023-01-03_12.58.56-server.txt](https://github.com/Corail31/tombstone_lite/files/10336336/crash-2023-01-03_12.58.56-server.txt)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Giacomo's Fishing Net

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by SkullNo1se** [comment]
Note: tried to remove the Fishing nets,got no crashes whatsoever,so i think my hunch can be right

**Comment by Corail31** [comment]
You didn't follow the issue template asking to locate your problem: so to provide a log with only thoses mods.
I'm not here to fix modpacks... It's about fishing conditions.
NB: feel free to edit your issue.

**Comment by SkullNo1se** [comment]
....ops...sorry,i'll make a fresh world with only Tombstone,Giacomo's net and Serene seasons,but since the net work in an rng manner and "produce" 1 item per 8 iro minutes may take a while to get the crash again,i'll let you know when i have the report.

**Comment by SkullNo1se** [comment]
ok,i got the new crash report(man i tought it would take more time,just 10 mins and 32 fishing nets),i'll edit the thread rn.

**Comment by SkullNo1se** [comment]
Done,hope i didn't messed up smth again.

**Comment by Corail31** [comment]
@SkullNo1se  is Serene Seasons really necessary for the test ? As it's done by the modders of BOP and i have doubt there could be a relationship.

**Comment by SkullNo1se** [comment]
Well i think not tbh,because,like i wrote in the  title,i said "maybe" because i saw it appeared in the logs....

Should i make another (brutally triggered with 100 fishing nets) crash report removing Serene Seasons?

(btw sorry for the response delay,i had another issue with Optifine/Domum Ornamentum so maybe i've skipped your comment by error...)

**Comment by Corail31** [comment]
I don't think you understand it's about the issue template: the problem has to be located (so not with "maybe", there's no reason to make the test with unrelated mods (and i don't want nested bugs).
The mod has no trouble with loots (since the version 1.19.2 exists so): if one mod is doing something strange about them, it's normal to have a crash and why it's necessary to be sure to know the culprit mod.
NB: I know I'm boring with the format of my issues sorry but it's also about time and i limit the mods that i add in my workspace (my computer has limitations too so testing a modpack is not possible ^^)

**Comment by SkullNo1se** [comment]
ok,re-editing again, and adding a new fresh crash report made today rn.
(wow i surely like to mess up things,don't i?)

**Comment by SkullNo1se** [comment]
Ok,edited,sorry for the trouble.

**Comment by Corail31** [comment]
I couldn't find the github repository for Giacomo Fishing Net (why i suppose you didn't report to this mod).
If i'm right (as i won't decompile), the mod uses an item NetItem using an entity (ThrowableItemProjectile) with a null world (and world is not nullable in entity).
Edit: i'm going to change how i get the world reference and the position. (release 8.2.3)

**Comment by SkullNo1se** [comment]
Thank you for your time invested in this issue,and sorry if i made some(many) errors in the issue template.
Have a great IRL time.

(btw imma grab rn the new relase and see if it works)

SkullNoise.

Edit: tested,mod works after 20 minutes of catching fish,i'll consider this a Case Closed.
(btw this testings made me discover some features of Giacomo's net i'd never noticed so far)

**Comment by Corail31** [comment]
@SkullNo1se Good news. It was long to make tests even by changing the config in the other mod (and to understand the fishing meal, also working like a bone meal on the ground... ^^) why i avoid to make tests before being certain of the issue ;p
Edit: i'll probably add a compatibility to consider how to check (~direction) if it's in 'open water' when it's a 'fishing net' (that are on the ground in the ocean). The 'open water' being a loot condition (unlike vanilla) for an 'additive' loot pool ('tombstone:lost_treasure') when fishing.
