### ISSUE TITLE
Crash Report TF + Hwyla

### ISSUE THREAD

**Issue by Darkfiend009** [Corail31/tombstone_lite#124]
Hey there!

I experienced a crash when dying in the Twilight Forest. I was testing a new modpack and wanted to test that graves would generate properly, among other things. I jumped off a tree and landed on some sort of tall grass and crashed.

Here is the crash log:
https://pastebin.com/b8iA6nkF

Corail Tombstone: 3.6.6
Minecraft: 1.12.2
Forge: 2847

**Comment by Corail31** [comment]
@Darkfiend009 is there any reason why the grave has been destroyed ?

**Comment by Darkfiend009** [comment]
Just to give some additional information, when i was testing, the final thing i tested was dying. As soon as i hit the ground, my screen turned red for a second and then i got the crash. So, i had no idea if the grave even generated. I had to leave so i couldn't follow up.

I just went back into the world for the first time after i died. I had the respawn screen. I respawned, went to my death marker, and the grave is there and i was able to use the key to get my contents. I use Corail Tombstone exclusively for my modpacks as it relates to dying and keeping inventory contents safe. This is the first time i've ever experienced this or any other crash.

I checked to see if gravesByPassGriefingRules was enabled, and it already was. So no issue there. I went back into the world, used the kill command a few times, and jumped off another tree and was not able to reproduce the crash.

I hope this information helps. If you need anything else, please don't hesitate to ask!

**Comment by Corail31** [comment]
Thanks darkfiend009 for your answer, it won't help me more as it's no more reproductible and also, as the grave was really present, and the block to not be grass as the crash mentions, i'll suppose it to be related to hwyla info and just fix the plugin to not crash.
