### ISSUE TITLE
[Feature Request] Gui for /tbrecovery

### ISSUE THREAD

**Issue by DoctorMage** [Corail31/tombstone_lite#126]
### Minecraft Version

1.16.5

### Forge Version

36.2.33

### Corail Tombstone Version

 tombstone-6.8.7-1.16.5.jar

### What happened?

A feature in corpse or your in grave mods is a gui that you can access that shows the players inventory
![image](https://user-images.githubusercontent.com/85318453/211190269-39c41589-a333-499a-a79a-531b7ead62bd.png)
![image](https://user-images.githubusercontent.com/85318453/211190361-4e39d971-60e6-414e-bd1f-c9d15789d2a4.png)

This is mainlly a request for servers

Current minor issue with tbrecovery on servers is if the player dies a few times after the grave they want back you would have to rollback through each grave if they don't recall when they died. By adding a gui it would allow admins and players to confirm what graves they want back or cheat in a specific item they had.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi DoctorMage,
I'm sorry but such synchronizations are not welcome. There's a date/time for the recovery.
It looks abnormal to use this command for 'graves', because it would mean that you didn't have a grave (and graves are not destructible by mods).
NB: It's the grave's key that show positions for graves, the command to recover a grave from a distance is /tbrestoreinventory (and restores all graves at once) and tbrecovery is a save over time (not specially related to player death and change the player position/world). I suppose that your wish is not just to see the the number of items on the grave's key.
Normally, if a player dies multiple times near the place of a grave, the grave will be used to store the items (to prevent 'griefing' on server).

**Comment by DoctorMage** [comment]
Alright understood for the first part regarding command only seen command frequently used in modpacks that have issues were certain events can cause no grave but thats out of your control.
 
 But regarding items on grave key possible for a way of it to print the contents of grave or show possible as a knowledge of death perk?

**Comment by Corail31** [comment]
If you get no grave, it's time to fix the problem by locating it. That's the only thing to do.
Most of the time, if a grave doesn't appear, it means that a mod asked to handle the death event (you even get a log "the death event has been canceled by a mod"), sometimes it's normal behaviour, sometimes not. Some mods like Player Revive succeed to bring trouble on disconnect but it's also about what they wrote in their code. The only thing to have a grave is to fire the "drop event", it's simple.
For the content of the graves, there won't be a gui for the reasons mentioned above: graves content can change to limit 'griefing' (there won't be tons of graves and the player has to get rid of 'Ghostly Shape' first to be able to die again) and i'm not going to sync inventories. In fact, grave inventories don't exist at all on client. The command restores all graves at once, i'm not sure why you want to see what was in. I have the feel that your 'use case' is only if you use another 'grave mod'.
In the early versions of Corail Tombstone, there was a gui for graves and it was removed for good reasons (Forge did changes about the packet limit in the between) and my mod kept this direction to have the datas only on the server (same for familiar receptacle for ex, you only know the name of the creature until it's revived, even by looking in nbt).
NB: don't hesitate to locate the mod involved in the grave spawn and to open an issue (i'm nearly sure that you already mentioned this trouble in a previous issue).
