### ISSUE TITLE
PlayerRevive compat

### ISSUE THREAD

**Issue by CreativeMD** [Corail31/tombstone_lite#127]
Not sure what event you use to determine whether a player has died. PlayerRevive uses `LivingDeathEvent` ([source](https://github.com/CreativeMD/PlayerRevive/blob/1.12/src/main/java/com/creativemd/playerrevive/server/ReviveEventServer.java#L142)).

If you use the same event I don't really know why the key still duplicates (because the event will be canceled).

**Comment by Corail31** [comment]
In fact, i don't try to handle the player in such high place event, tombstone use the LivingDropsEvent in lowest priority to create a grave as there're some drops to "protect". It's really something about the drops themselves, and the player body to be fullfilled instead of being in the drops list.
I didn't yet make tests about it, it's only based on the tale of @GuerreroCraft61.
There're some precisions on the issue linked.

**Comment by CreativeMD** [comment]
Now I'm confused. So what exactly does PlayerRevive cause?

**Comment by GuerreroCraft61** [comment]
The Player Revive, when you "die", does not kill you (the grave does not appear), only when you give it "continue", the grave appears but when you have the inventory full, the key drops and when you return, the key is doubled.

This for example when you die a lot, makes you die even more, since it is filled in inventory and you can not take your things

**Comment by Corail31** [comment]
I just made a test in my workspace (and server)
![full_invent](https://user-images.githubusercontent.com/17954109/74441767-b2b91880-4e70-11ea-8873-c4382dc8ffdb.jpg)
just before setting the player in survival mode & /kill him
![death_gui](https://user-images.githubusercontent.com/17954109/74441733-a339cf80-4e70-11ea-8681-7c68baa6bd29.jpg)
just after clicking the button "give up"
![respawn](https://user-images.githubusercontent.com/17954109/74441848-cb293300-4e70-11ea-9c59-c95ac9d9cf2b.jpg)
all seem to work perfectly to me, a screen of the respawn above

**Comment by GuerreroCraft61** [comment]
Now I test using only Corail and PlayerRevive and work fine 🤔 

This is all my mods:
`Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, 1.13 Water Mechanics Backport, AI Improvements, Advanced Machines, Advanced Solar Panels, Akashic Tome, Anvil Patch - Lawful, AppleCore, AppleSkin, Astral Sorcery, Attribute Fix, AutoRegLib, B.A.S.E, Backpacks!, Baubles, Blood Magic: Alchemical Wizardry, Bloodmoon, Bonsai Trees, Bookshelf, Bookworm API, CasinoCraft, Chest Transporter, Chisel, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Comforts, ContentTweaker, Corail Tombstone, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cucumber Library, CustomNPCs, Decocraft, DiscordIntegration, DupeFix Project, Enchanting Plus, EnderPay, Expanded Equivalence, Extended Crafting, Extra Alchemy, Extra Planets, Extra Utilities 2, FTB Backups, FTB Library, FTB Utilities, FastWorkbench, Fence Jumper, FoamFix, FoamFixCore, Foamflower, Future Versions, Galacticraft Core, Galacticraft Planets, GottschCore, Gravitation Suite, Guide-API, Hammer Core, Harvest, Ido - 1.12 movement enhancement, IndustrialCraft 2, Infernal Mobs, InstantUnify, JourneyMap, Just Enough Dimensions, Just Enough Items, Just Enough Pattern Banners, LLibrary, LibraryEx, Login Shield, MJRLegendsLib, MTLib, Mantle, Max Potion ID Extender, McLib, Mekanism, Mekanism: Generators, Micdoodle8 Core, Minerva Library, Moar Tinkers, Mod Tweaker, Morpheus, MrCrayfish's Furniture Mod, Mystical Agradditions, Mystical Agriculture, NetherPortalFix, NoMoreRecipeConflict, NotEnoughIDs, OnlinePictureFrame, OpenBlocks, OpenModsLib, OpenModsLib Core, Ordinary Coins, Pam's HarvestCraft, Phosphor Lighting Engine, Placebo, Player Revive, Player Skin Mobs, Potion Core, Progressive Bosses, ProjectE, Quark, Railcraft, RandomPatches, Redstone Flux, Roguelike Dungeons, Rpg Inventory, Rustic, SecurityCraft, Shadowfacts' Forgelin, SpawnerControl, Spice of Life: Carrot Edition, SpongeForge, Subaraki's Common Library, Thaumcraft, Thaumic Equivalence, The Twilight Forest, Thermal Cultivation, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker's JEI, Tinkering With Blood Magic, Tinkers Tool Leveling, Tinkers' Construct, Treasure2!, TreeCapitator, Uncrafting Table, UniDict, Unloader, VanillaFix, Vending, Waila, WanionLib, Waystones, Wither Skeleton Tweaks, WorldEdit, XP From Harvest, Zoo and Wild Animals Mod: Rebuilt, bspkrsCore, iChunUtil, kinetic anti-cheat`

**Comment by GuerreroCraft61** [comment]
Mmmm... and now I can't reproduce the bug 🤔

**Comment by Corail31** [comment]
Could be the config options being changed between your tests ?

**Comment by GuerreroCraft61** [comment]
![2020-02-14_19 30 00](https://user-images.githubusercontent.com/30746531/74557465-7f55b700-4f60-11ea-829b-5a2406464091.png)
![2020-02-14_19 30 16](https://user-images.githubusercontent.com/30746531/74557471-8086e400-4f60-11ea-9621-ab260f2f9e38.png)
![2020-02-14_19 30 21](https://user-images.githubusercontent.com/30746531/74557472-811f7a80-4f60-11ea-9a40-746dde993738.png)

**Comment by Corail31** [comment]
@GuerreroCraft61 now you have to find that mod... without this, i can't help you.
