### ISSUE TITLE
Using magic scroll item consumes whole stack

### ISSUE THREAD

**Issue by Proxwian** [Corail31/tombstone_lite#128]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Corail Tombstone Version

Corail Tombstone 7.6.0 for 1.18.2

### What happened?

When using enchanted scroll in stack, all scrolls in stack being consumed instead of one

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Proxwian Thanks for reporting this issue, i'll do the tests soon to check it.

**Comment by Corail31** [comment]
@Proxwian It's ready ;)
