### ISSUE TITLE
Bauble remove the grave

### ISSUE THREAD

**Issue by GuerreroCraft61** [Corail31/tombstone_lite#128]
When you have bauble, the grave is created, but when the player respawn, the grave disappear (and all items) and the bauble is dropped (last version)

**Comment by GuerreroCraft61** [comment]
Sometime the grave don't disappear

**Comment by Corail31** [comment]
@GuerreroCraft61 You made 3 issues in a few time, i'll be clear on this, you don't have fixed your pack about the last issue, don't open new ones as it means your pack is not correct...
Baubles work correct so stop this now, or you will just be tag as troll and won't have any more assistance.

**Comment by GuerreroCraft61** [comment]
Troll? Ok...
I only report errors of your mod... I change it to 3.6.6 and it work fine, but not when I use 3.6.7, that is  problem of other mods? And if it is an error of other mod, is imposible find it, because I have 181 mods... I only report it, but if you think it is troll...

**Comment by Corail31** [comment]
> I think the job of finding the bug is from the dev, not from the use... I'm only trying to help...

Ok you want others to do your job... try another github.
If you think that one line in one mod is not enough to break all, i can't help you anymore.
