### ISSUE TITLE
The tomb can't be unlocked if it is on Draconic Evolution‘s 'Guardian's Crystal'

### ISSUE THREAD

**Issue by papadave66** [Corail31/tombstone_lite#129]
* version tombstone-3.6.4-1.12.2

I was playing in the end world . And I can't unlock the tomb which is on that crystal . Here's the picture.
![tomb_on_crystal](https://user-images.githubusercontent.com/14260128/74584580-ffd2f100-500e-11ea-9674-1e4ab012d355.png)

**Comment by Corail31** [comment]
You can always activate a tomb by crounching/sneaking.

**Comment by papadave66** [comment]
Thanks. I found an angle which is looked up at the tomb below. That works
for me

Corail31 <notifications@github.com>于2020年2月15日 周六下午9:42写道：

**Comment by Corail31** [comment]
@papadave66 I see that you're chinese, if you see some parts i forgot to translate (or looks strange for your language), don't hesitate to report them :)

**Comment by papadave66** [comment]
> @papadave66 I see that you're chinese, if you see some parts i forgot to translate (or looks strange for your language), don't hesitate to report them :)

Haha I'll do my best.The translate is very good though
