### ISSUE TITLE
Rendering Bug

### ISSUE THREAD

**Issue by NomadicVoyager** [Corail31/tombstone_lite#13]
### Minecraft Version

1.16.5

### Forge Version

1.16.5

### Corail Tombstone Version

6.4.7

### What happened?

Entity Rendering Issue, when near a grave almost all entities in render will render through walls and floors.

** Example: **
Edit: Screenshots are not accepted

### Gametype

Singleplayer

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
If it was in 1.17.1, i could say it's possible but not in 1.16.5. (it would have been reported sooner, so the only reason is your others mods).
You checked it's reproducible with only Corail Tombstone and i have a doubt.
NB: Fake reports are not welcome.

**Comment by Corail31** [comment]
https://github.com/BloCamLimb/ModernUI/issues/75
