### ISSUE TITLE
Crash with EpicFight mod

### ISSUE THREAD

**Issue by sirben99** [Corail31/tombstone_lite#13]
Hey!

The mod crashes with EpicFight mod when player dies and presses the respawn button
(https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod)

Forge: Latest 1.16.5
Mod versions: Both latest

I have also created a issue on EpicFight mods issue page
(https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/issues/17)

Heres my crash report:
[crash-2021-02-08_14.42.41-client.txt](https://github.com/Corail31/tombstone_lite/files/5943773/crash-2021-02-08_14.42.41-client.txt)

**Comment by Corail31** [comment]
The log targets this mod : maninhouse.epicfight, you should open an issue in the mod concerned.
