### ISSUE TITLE
tombs trouble

### ISSUE THREAD

**Issue by Hide-Stampede** [Corail31/tombstone_lite#130]
I am playing through Dungeons dragons and space shuttles and as i die by the dragons i get the key and a highlighted hit box as expected but upon arrival i see that the clickable grave hasn't spawned and my item are on the floor like what happens with vanilla survival i believe it might have been when the dragon flies through the player and therefore not having room to spawn in the grave but I've had this issue a couple of times

**Comment by Corail31** [comment]
Please follow this topic to make an issue as what your current one is not correct :
https://github.com/Corail31/tombstone_lite/issues/96

**Comment by Hide-Stampede** [comment]
I am playing the latest release of Dungeon Dragons and space shuttles which is 7.21a and the forge version is 14.23.5.2847. I had an interacting with ice and fire: in a whole new light. it is loaded with tombstone-3.6.5-1.12.2.jar i had gone to retrieve my tombstone after fighting a dragon however i had no clickable grave to interact with i know that as i died the dragon flew through the block that i died in as that might be a factor as there wasn't any explosions. unfortunately after hours of trying to replicate this issue i haven't been unable to to get photo proof. Apologies if you need more information i'm not sure how much more to explain my issue i am having after about a year of using this mod i have only had it happen about 2 or 3 times

**Comment by Corail31** [comment]
Around 2016-2018, ice&fire had hard to respect the graves indestructibility.
But, i remember that Alex666 made changes since (but there could be still some attacks breaking them).
On my side, when a mod is asking to break a grave and even with no drop, i prefer actually to only drop the content than trying to restore the grave (that could bring others troubles).
