### ISSUE TITLE
Happiness Crashes People [carrotslib]

### ISSUE THREAD

**Issue by AngelicDeath** [Corail31/tombstone_lite#131]
### Minecraft Version

1.16.5

### Forge Version

36.2.33

### Corail Tombstone Version

tombstone-6.8.7

### What happened?

while more than 2 people have the happiness buff simultaneously, everyone on the server crashes repeatedly until the buff falls off of one person.
[crash-2023-01-24_15.55.24-client.txt](https://github.com/Corail31/tombstone_lite/files/10494475/crash-2023-01-24_15.55.24-client.txt)

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi AngelicDeath,
The error seems to come from the mod related to 'org.jwaresoftware.mcmods' (that i suppose to be carrotslib).
You can add theses effects to the 'unhandledBeneficialEffects' config to be sure they won't be used (but i recommand you to contact the modder of theses effects). You can also add directly the 'modid' in this config for all the effects of that mod.
Edit: i informed the other modder.

**Comment by Wabbit0101** [comment]
This is a carrots library issue and I will look into fixing it. In the meantime, please report this over at  [that library's tracker](https://github.com/Wabbit0101/mods_hoardercraft/issues). On your server disable the shared effects (which to be honest aren't a fully baked feature yet). See config in wabbity_carrots.toml set 'shared_effects_max_reach = 0' .
