### ISSUE TITLE
Auto backup of latest grave?

### ISSUE THREAD

**Issue by SirAron111** [Corail31/tombstone_lite#131]
Is there now way to make it possible to automatically backup the contents that get transported into a players grave so that in case the server or game crashes after death and gets rolled back the player can still get their inventory back via a command? tbrecovery and tbrestoreinventory don’t work so good for that situation where the grave disappears. ran intothis problem a few times in 1.12.2 now.

Like tbrestorelastgrave (playername) and you get that inventory even if the grave doesnt exist anymore. Would really help in such sad situations!

**Comment by Corail31** [comment]
euh SirAron111... tbrecovery is intended to recovery... and works for this situation **by not making lots of save if the player dies multiple times**...
Just configure it how you want it to be with enough saves.
tbrestoreinventory is only to click the grave at distance...
