### ISSUE TITLE
Magic scrolls can crash players and denying relogin untill removed from inventory

### ISSUE THREAD

**Issue by Zelioth** [Corail31/tombstone_lite#132]
### Minecraft Version

1.19.2

### Forge Version

43.2.3

### Corail Tombstone Version

8.2.4

### What happened?

Some Scroll when picked up by players are throwing MASS console spam and denying relogin from the players untill the players inventory is cleared of those items. 

I am not sure which one it is but it is one of these four 
Enchanted scroll of maturity II
Enchanted scroll of sunbird's blessing III
Enchanted scroll of Blast Resistance
Enchanted scroll of Blind Sight III

This has happened like 20 times now on our dedicated server for Friends United mod pack. We were not able to see what scrolls were present till a recent discovery of me being able to observe them without having to pick them up. 

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Log Link

https://gist.github.com/Zelioth/9fd4b752083560e170a61b1bb2b083cd

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi Zelioth,
Potion effects from other mods are to be solved by theses mods (based on your log, it would be org.cursegame.minecraft.adventurer).
They have no reason to crash as they could be called by the command /effect.
However, you can add theses effects to the 'unhandledBeneficialEffects' config to be sure they won't be used (but i recommand you to contact the modder of theses effects).

**Comment by Corail31** [comment]
https://github.com/Corail31/tombstone_lite/issues/102

**Comment by Zelioth** [comment]
My mod pack doesn't feature Corail Adventurer though. if that is the mod in reference
