### ISSUE TITLE
Server crashed and lost items

### ISSUE THREAD

**Issue by unbornchaos** [Corail31/tombstone_lite#133]
[crash-2020-02-18_15.51.42-server.txt](https://github.com/Corail31/tombstone_lite/files/4225998/crash-2020-02-18_15.51.42-server.txt)
[crash-2020-02-18_23.33.25-server.txt](https://github.com/Corail31/tombstone_lite/files/4225999/crash-2020-02-18_23.33.25-server.txt)

Hi, yesterday on our private server which has a few mods, two different users reported that they were together and one person died and received the tombstone. A few seconds after the other person died close to the tombstone and the server crashed. When the server came back up the second player(who died and server crashed) didn't receive a key nor a tombstone and the first player who died had a key but the tombstone was destroyed and the items were all on the floor. This happened twice on the same day but at different times. I have the crash log of both times the crash ocurred. I am using your latest version of the mod on Minecraft 1.12.2.b

Tombstone version: 3.6.7-1.12.2
Forge: 14.23.5.2847

**Comment by Corail31** [comment]
Hi unbornchaos,
May you lower your version to 3.6.6 and try it again, it could be related to the latest changes.

**Comment by unbornchaos** [comment]
> Hi unbornchaos,
> May you lower your version to 3.6.6 and try it again, it could be related to the latest changes.
> NB : is it karmaland modpack and are you able to make tests if i give you a try version (only required on the server) ? do you have mods breaking graves in your pack ? as this code shouldn't be reached in normal circonstances, even if the concurrent fix is on my side.

Hello we are not using any Modpack, we just manually installed some of them. None of the mods i know of should break the tombstone. Just to make it clear the tombstone was broken after the Server crashed and restarted, as soon as it was up again the items were floating around where the tombstone was seen. 
We can test a try version.

**Comment by Corail31** [comment]
@unbornchaos contact me on CurseForge, will be simplier ;)

**Comment by Corail31** [comment]
fixed in 3.6.8
