### ISSUE TITLE
Please blacklist Cyclic Potion effects

### ISSUE THREAD

**Issue by Nightcaste** [Corail31/tombstone_lite#136]
Cyclic contains a "potion" effect called Stunned, which causes your character to look straight up and spin around uncontrollably for two or three seconds.  Using my ankh of pray gave me this "buff" for twelve minutes.

First, it makes the game unplayable.  You have no control over where your character is facing, so you can't really move or interact with the world.  If you're not in a secure location, that could be a death sentence.

Second, it's nausea/vertigo inducing.  This could seriously cause problems for people with relevant health issues.

**Comment by Corail31** [comment]
Hello there,
First, Tombstone contains a blacklist of potion effects in config.
Then, if you get theses potions with Cyclic, it's because Cyclic doesn't correctly set its effects, so you should open an issue on this mod as it sets them to beneficial effects.

**Comment by Nightcaste** [comment]
The problem is not on Cyclic's side.  The only way to encounter the effect
normally is to be hit by a specific item by a player.

It's Corail that's adding it to the list of random buffs that praying can
give, therefore it's Corail that needs to intentionally not call that
effect.

**Comment by Corail31** [comment]
If you don't want my answer, don't ask a question.
As far as i know i'm modder, and if i say you that potion effects are categorized in beneficial/neutral/bad effects (at least in 1.14.4+).
If Cyclic makes its effects as beneficial even if they aren't, it's a bug in cyclic

**Comment by Nightcaste** [comment]
First, this is 1.12.2

Second, used as intended, the effect only lasts a second or two, so it's
not really a problem.  *Your mod* makes this effect last *TWELVE MINUTES*.
The duration is the problem, not the categorization of the effect.

**Comment by Corail31** [comment]
Time for a drink as you don't read my answers :
https://minecraft.gamepedia.com/Milk_Bucket

**Comment by Nightcaste** [comment]
That would require me to preemptively have a milk bucket in my inventory, since **as I said before you can't move during this effect.**

**Comment by Corail31** [comment]
honestly, you don't need to see the future, you just need to read my first answer, the second and the last line.

**Comment by Nightcaste** [comment]
Wow, you really are committed to being a dick.
