### ISSUE TITLE
Problem with 1.12.2 in my server

### ISSUE THREAD

**Issue by SirDante345** [Corail31/tombstone_lite#137]
Hello i have a problem with corail tombstone 1.12.2 when we die we get a form of a ghost but only we see the head of the character, we can see all the world by crossing any block from the world and we can´t get our tomb i tried everything i can´t to fix the problem from the configuration of the mod but i didn´t get to fix the issue i need help.
We also tried installing only the corail tombstone 1.12.2 and the problem still persist

This is the mods we have in the server and we use, i used this mods in aternos and we didn´t have any problem
![Screenshot_2](https://user-images.githubusercontent.com/37676069/75596036-6961ef00-5a54-11ea-93fd-307a1b9b90ac.png)

Also we have skin restorer but also use it in aternos without a problem 

I only set the chance of get a enchanted key to 100 ( I:chanceEnchantedGraveKey=100 ) and didn´t touch anything else from the config file

This is the ghost head i tell you before
![Screenshot_4](https://user-images.githubusercontent.com/37676069/75597219-d4fa8b00-5a59-11ea-882a-417ce08b6d43.png)

thanks for the help

**Comment by Corail31** [comment]
Hi SirDante345,
Even if your message seems to describe many things, it seems more the consequence of mods put together, and the first step would be to locate exactly the mod producing these inconsistencies (because I do not have time available to locate them myself)
By the look of it, there's an incompatibility with the player render, then why you can access a grave is unrelated to this and probably something else with another mod as you should always be able to click your grave, or by sneaking.

**Comment by SirDante345** [comment]
Hi, thanks for the help, i will have to check the mods and see if i can find the problem.
I don´t know why is this happening, in single player i don´t have any problem :c is pretty weird this happend.
I also need to disable this ghost thing i dont want to have it is there a option to disable it? 


I don't want to steal you a long time, it's just that I'm new to using mods in minecraft.

Thanks for everything

**Comment by Corail31** [comment]
If after using /effect <your_pseudo> clear (to be sure to remove the ghostly shape), you always see this ghostly render, it would mean it's not related to Tombstone.
But if you find the mod i could look the reason.
NB: always make sure to test Tombstone first to see if you can reproduce it alone.

**Comment by SirDante345** [comment]
I found this on the console of the server

28.02 21:31:39 [Server] Server thread/INFO [tombstone]: The death event of the player playername was cancelled by another mod

I also tried the command you gave me and didn´t work so i have to find the mod making the problem

thanks for the help Corail31

**Comment by Corail31** [comment]
This message can also be normal and is only because a mod is handling the death (player revive probably does it)

**Comment by Corail31** [comment]
Any new about this SirDante345 ? your pack seems lightweight so the load for tests should be short ?

**Comment by SirDante345** [comment]
I been very busy this days and i didnt have the oportunity to look the server and search the problem. I will tell you if i found something when i chekit
