### ISSUE TITLE
1.16.5 - Familiar Receptacle Crash

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Corail31/tombstone_lite#138]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Corail Tombstone Version

 tombstone-6.8.9-1.16.5

### What happened?

https://gist.github.com/P3rf3ctXZer0/e049d922acf5c079210755585ea54f2b

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Log Link

https://gist.github.com/P3rf3ctXZer0/e049d922acf5c079210755585ea54f2b

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Please next time follow the issue template (or maybe you just wanted me to check your log?).
Your issue is coming from com.pixelmonmod.pixelmon.
