### ISSUE TITLE
[bug] 3.6.7 is not a good version for 1.12.2

### ISSUE THREAD

**Issue by passage2016** [Corail31/tombstone_lite#138]
The server crashed when the player died, and the tombstone was not created after the restart, causing the backpack items to be lost.

edit by Corail : your log that you should normally put yourself on pastebin :
https://pastebin.com/09SAkEGY

**Comment by Corail31** [comment]
Hello, please try to follow the version patch notes, as it's really rare when i add a bug in my version, and it's the case for 3.6.7 due to a mistake by backporting some changes from 1.15.2.
It's indeed fixed in 3.6.8 and if you didn't see : the version is also archived on curseForge...

**Comment by Corail31** [comment]
dupe of #133

**Comment by passage2016** [comment]
Thank you for your help, I will try it.
