### ISSUE TITLE
Purple Creative Spike from Extra Utilities does not spawn grave.

### ISSUE THREAD

**Issue by Razernok** [Corail31/tombstone_lite#139]
When you die to an Extra Utilities creative spike no grave is spawned or generated.
Happens on both servers and single player.

**Comment by Corail31** [comment]
Hello Razernok, first fill the issue correctly : [How to post an issue](https://github.com/Corail31/tombstone_lite/issues/96).
I'm not here to guess the version and so on (i'm not even sure what is extra utilities repo as there's one with 1200 open issues and another one with 300 open issues named extra utilities 2.
Did you post this issue in extra utilities? because graves have a way to place them safely, and so, if they don't place, there's always a reason in the other mod.

**Comment by Corail31** [comment]
![test_spike](https://user-images.githubusercontent.com/17954109/76066097-2e4c4800-5f8d-11ea-9984-2851a6456099.jpg)
does it require a special setup to produce it? as i tried by making hole too, but without trouble (tested with extrautils2-1.12-1.9.9).

**Comment by Razernok** [comment]
Sorry, its from tombstone-3.6.8-1.12.2 and extrautils2-1.12-1.9.9

**Comment by Corail31** [comment]
What was the message in your log of death ? and did you test it with only theses 2 mods ?

**Comment by Razernok** [comment]
I tested it with only these 2 mods installed.
I got the following messages in console:

> 02:55:33.462
Razernok failed to become the guy
02:55:33.462
The drop event of the player Razernok was cancelled by another mod
02:55:33.473
[CHAT] Razernok failed to become the guy

**Comment by Razernok** [comment]
you also can use the commands to recover the last grave or teleport to it. It says the grave was not found.

**Comment by Corail31** [comment]
This log says you that another mod handled the death, so it's normal there's no grave, if the death happens differently.
Do you use player revive? as this block deals damage to the player.

**Comment by Razernok** [comment]
When you die to the spike it just gives you the normal minecraft death screen to 'Respawn' or 'Return to Title Screen' I used no commands or anything.

**Comment by Corail31** [comment]
Are you able to reproduce it consistently ? as for now, i haven't been able to produce it one time.

**Comment by Razernok** [comment]
yes
Video below shows how it happens.
[https://youtu.be/8aHREgRT0uc](url)

**Comment by Razernok** [comment]
Picture of the tooltip and icon for the block in question:
http://prntscr.com/rcfp0r

**Comment by Corail31** [comment]
you're in the dim -9999?

**Comment by Razernok** [comment]
its a superflat world. works in a normal world too

**Comment by Corail31** [comment]
Ah i got it, it's the purple one that does this behavior.
As it's called "creative spike", it's perhaps intended, but you should open an issue in extra utilities 2 if you think it shouldn't. (for sure, the event is canceled meaning the mod is doing it).

**Comment by Razernok** [comment]
Ah ok, this item is normally creative only, but the modpack MC.Eternal allows players to get it. It can 1-shot anything that touches it, but can't be broken by players not in creative mode.

**Comment by Corail31** [comment]
I made the test with only Extra Utilities 2 alone, if you die on this block, you loose all your stuff definitively. So there's no relation with Tombstone, it's what this block is doing in code.
You should at least ask to this mod to get additional informations about this in the tooltip of this spike.

**Comment by Razernok** [comment]
ok, thanks. it is a creative item. there happens to be a pack that allows players to obtain creative items like this spike.

**Comment by Corail31** [comment]
there's the command /tbrecovery load_player (tabulation to complete) to restore your player inventory if you have the permission level for it.

**Comment by Razernok** [comment]
Yea, that's what I did on his server to roll back a player.
