### ISSUE TITLE
[Suggestion] Reduce texture resolution when high-res texture pack is not being used

### ISSUE THREAD

**Issue by Reassembly** [Corail31/tombstone_lite#14]
The textures in use in this mod are generally fairly good-looking. However, they can be a little strange when using vanilla textures or a 16x16 texture pack - for example, the dirt in front of a decorative grave looks much smoother than the "regular" dirt next to it. It looks out-of-place, like it is not part of the world around it.

Is it possible to switch to lower-resolution textures for things like grave dirt, when there is no 32x32 texture pack loaded, to match the texture resolution in the rest of the world?

**Comment by Corail31** [comment]
Honestly, i'm not fan of the format in 16 pixel, because it prevents to draw rounded shape, and it would lead to a grave in part in 16 and 32.

**Comment by Corail31** [comment]
Done in 2.9.9 ;)
