### ISSUE TITLE
potion effects & exit conquered end

### ISSUE THREAD

**Issue by xuexiyue** [Corail31/tombstone_lite#14]
I lost the effects I got from magic siphon after going the through the portal when you kill the ender dragon the effects I had on me at the time had an indefinite duration is it a bug or an intended feature?

**Comment by Corail31** [comment]
Your issue is imprecise, it doesn't provide any info about your minecraft version, if you test only with Tombstone or it's related to the combinaison with others mods, is the portal a vanilla portal or a modded one ? is the potion come back if you delog and relog.
