### ISSUE TITLE
Snow layer causes misplacements for grave.

### ISSUE THREAD

**Issue by DevBefell** [Corail31/tombstone_lite#140]
### Minecraft Version

1.16.5

### Forge Version

Forge 1.16.5 36.2.39

### Corail Tombstone Version

6.8.8

### What happened?

When a player dies on snow layers, it will place the grave on the nearest full block that has air above it.
[Snow Test](https://streamable.com/zdq6y9)

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@PyICoder Thanks you for the time spent to solve theses issues ;) Feel free to contact me if something doesn't go as expected for the new changes.
