### ISSUE TITLE
Gravestone didn't spawn 'Grave drops event cancelled'

### ISSUE THREAD

**Issue by rk-exxec** [Corail31/tombstone_lite#140]
Logfile: https://pastebin.com/E1Yb1aFx
Error: `Grave drops event cancelled`

I died in the nether and somehow my grave did not spawn and I got no key. Worked fine for my buddy though.
Minecraft version 1.12.2

**Comment by Corail31** [comment]
I'm sorry in advance but : please, read [this](https://github.com/Corail31/tombstone_lite/issues/96) next time you want to post an issue.
NB : the minimum is at least to check the opened issues.
dupe of #138 being itself of dupe of #133

**Comment by rk-exxec** [comment]
yes, sorry about that
I thought this was something new
