### ISSUE TITLE
Issue with Gottschcore license causing crash on world load

### ISSUE THREAD

**Issue by EnderMelody** [Corail31/tombstone_lite#141]
crashlog:
https://gist.github.com/EnderMelody/341fbfd8f23785da5a5d26bd8eea7d20

problem mods:
Corail Tombstone 3.6.9 for 1.12.2
GottschCore-mc1.12.2-f14.23.5.2768-v1.12.1.jar
Treasure2-mc1.12.2-f14.23.5.2768-v1.10.0.jar
Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.1.jar

fixes:
backport to Corail Tombstone 3.6.8 for 1.12.2

if this is intentional, then can you please explain on the descriptions page for the mod.

**Comment by Corail31** [comment]
Je vais répondre en français car je n'ai pas envie de répondre dans une langue qui n'est pas ma langue habituelle sur ce sujet.
J'ai été très cordial avec ce moddeur en lui demandant gentiment d'enlever des codes de Tombstone qu'il avait décompilé alors qu'il savait très bien que la license était all right reserved et où des import du domaine étaient carrément sur son github.
Sa réponse a été qu'il n'avait fait çà que pour apprendre et qu'il en était désolé et avait fini par trouver une autre façon de le faire sur des tutoriaux (qui au passage n'ont rien à voir) et a fini par enlever les codes en question.
20 jours plus tard, il réintroduit les changements en ayant cette fois compris ce qu'il n'avait pas compris la première fois et en me disant en privé que çà fait 7 ans qu'il fait çà et n'a aucun soucis à faire ce code (complètement différent de sa première réponse qui était d'apprendre et de s'excuser).
Donc, oui ce monde est peut être pollué de gens malhonnêtes, çà ne veut pas dire que je dois les cautionner.

**Comment by lamoyrl90** [comment]
(Utilisation de Google Translate)

Je comprends les sentiments négatifs entourant ce sujet et la façon dont l'auteur a géré les choses. Cependant, je pense que rendre ces mods mutuellement exclusifs ne fait que nuire aux utilisateurs finaux. Je ne mets tout simplement pas à jour Tombstone pour l'instant, car je veux le contenu de ses mods dans mon modpack, ainsi que le vôtre. Malheureusement, je ne pense pas qu'il existe un substitut approprié au mod Dungeons qui s'adapte à mon modpack. Bien que Tombstone soit mon mod préféré pour son objectif, il a des substituts que je pourrais utiliser si j'en avais besoin. Je ne veux pas dire de sentiments durs par cela, j'essaie juste de montrer comment vous ne faites que nous blesser pour ses politiques malhonnêtes.

**Comment by EnderMelody** [comment]
the only real problem i have with this is that there was no explanation, it just suddenly stopped working. If you could explain that better in the crash I think it would help people understand that they have to choose between the mods.

**Comment by ParadoxOrigins** [comment]
Bien le bonjour,

Bien que je comprend votre colère si ce que vous dites est vrai (le vol de code alors même qu'il y a une licence est probablement une des choses que je déteste le plus), je me permet de noter que cela reste quand même assez immature...

J'entend bien que vous ayez droit de faire ce que vous voulez avec votre propre mod (et bien heureusement), mais votre approche fait plus de dommages collatéraux qu'autre chose: Les utilisateurs qui, eux n'ont rien demandé, se retrouvent maintenant impliqué, et plutôt que l'effet voulu, vont alors juste désinstaller votre mod parce qu'ils trouveront que votre approche est juste mauvaise (et je ne fait pas dans le théorique ici, je connais quelqu'un qui est déjà en train d'y songer).

Vous pouvez juste dire publiquement ce que vous pensez de lui, ou même contacter le support de Curse et voir si vous pouvez faire enlever son mod jusqu'à ce qu'il respecte la licence. Si lui aussi a un GitHub, tu peut aussi contacter le support de GitHub pour lancer une notice légale DMCA.

Je pense fermement que vous avez choisi la pire approche possible en décidant d'impliquer les utilisateurs la dedans et de les empêcher de continuer avec, au lieu de simplement expliquer la situation et de les laisser décider par eux-même.

De nouveau, je tiens à préciser que je comprend votre mépris envers la malhonnêteté de cette personne, mais faire mal aux utilisateurs qui eux sont honnête n'est simplement pas une bonne idée pour votre propre mod et surtout pas cool.

Bonne journée tout de même

**Comment by Corail31** [comment]
Les personnes qui ne comprennent pas que la licence n'est pas là juste pour faire joli et que si les codes de Tombstone ne sont pas publiques, c'est bien pour éviter ce genre de situation... donc si ça arrive c'est bien la faute de l'autre moddeur (un peu la faute de Forge à promouvoir la décompilation).
J'ai choisi la solution me coûtant le moins de temps, donc pas un DMCA (car si tu dis çà, tu n'en as jamais fait).
Cette situation n'est pas quelque chose que vous pouvez décider à ma place ou critiquer, ça ne vous concerne simplement pas (surtout si vous préférez soutenir cet autre moddeur incapable de coder lui même), c'est quelque chose qui concerne mes propres ideaux de l'être humain de demain et qui été déjà été amplement réfléchi sur ses répercutions.
Donc, ne demandez pas de changer ce statut c'est une histoire qui a déjà un mois de discussion et est déjà classé aux archives.
