### ISSUE TITLE
This mod is named for current crashing...

### ISSUE THREAD

**Issue by RepoDraghon** [Corail31/tombstone_lite#142]
[New Text Document.txt](https://github.com/Corail31/tombstone_lite/files/4315202/New.Text.Document.txt)
![Screenshot (32)](https://user-images.githubusercontent.com/8423696/76366588-b01ed700-62e7-11ea-8172-5cb25af43a8a.png)

**Comment by Corail31** [comment]
Please, read your log before posting them.
Dupe of #141

**Comment by RepoDraghon** [comment]
Sorry
