### ISSUE TITLE
Unknown message ID: origins

### ISSUE THREAD

**Issue by robtbs** [Corail31/tombstone_lite#142]
### Minecraft Version

1.16.5

### Forge Version

forge-1.16.5-36.2.39 

### Corail Tombstone Version

Corail Tombstone 6.8.10 for 1.16.5

### What happened?

[me.sh.ar.ne.fo.NetworkManagerImpl/]: Unknown message ID: origins:player_landed mine craft

when i jump in ghost mode, this message gets spammed alot

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi. Please, follows the template and locates your problem.
NB: did you notice the word 'origins' in your message ?

**Comment by robtbs** [comment]
yeah, but i dont use origins, this error happen when we use the jump key, while we are in the ghost shape 

is a bit weird
