### ISSUE TITLE
Tombstones is crashing my modpack (Crash Craft Survival)

### ISSUE THREAD

**Issue by slenered** [Corail31/tombstone_lite#143]
[crash-2020-03-12_12.32.49-server.txt](https://github.com/Corail31/tombstone_lite/files/4325434/crash-2020-03-12_12.32.49-server.txt)

**Comment by Corail31** [comment]
Please next time, read the rules [how to post an issue](https://github.com/Corail31/tombstone_lite/issues/96)
The minimum would have been to at least to consult the recent issues, and your log.
dupe of #141
