### ISSUE TITLE
/kill doesn't work on Ghostly Shaped players

### ISSUE THREAD

**Issue by Marshdex** [Corail31/tombstone_lite#143]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Corail Tombstone Version

4.6.0

### What happened?

Testing the effects in survival revealed that Ghostly shape cancels out /kill. Searched in the config for some workaround to no avail. 
It is possible to remove the damage immunity Ghostly shape provides?

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
/effect with clear ;)
There are also multiple ways to cancel Ghostly Shape depending on player actions (and some config options) explained in the Compendium if i'm right. If a player has this effect, it means he just died.
