### ISSUE TITLE
Melee bug?

### ISSUE THREAD

**Issue by Rexxy6** [Corail31/tombstone_lite#144]
Hello, I have a problem with running the mod on a server. I am currently using the M.C. Eternal Modpack, and once a player respawns from using the grave, he cannot punch or be punched, yet he can be shot by arrows and receive damage from other affects. Keep in mind, the player has been resurrected from the grave, and no longer has the ghostly form acting on him. The player cannot do any form of melee damage, whether he is performing or receiving melee damage. Is this a function of the mod? Or is this a bug? If it is a function of the mod, how do I disable this via config or legitimate methods of survival?

also, I posted a comment on the curse forge page, you can remove it if you like, it is just a copy and paste of this.

**Comment by Corail31** [comment]
Hello, so i'll answer you directly here : your first sentence looks to say that you really tested your server before adding Tombstone, and i have a doubt it's.
Something happening on respawn after a death doesn't mean it's related to Tombstone.
As you say you don't have Ghostly Shape (and even the initial ghostly shape doesn't do this), so why would like it to be related ?
Localize first the mod doing it, or test with Tombstone only to confirm you it works as expected.
```

**Comment by Corail31** [comment]
@Rexxy6 any news?
