### ISSUE TITLE
[1.19.2] - Question

### ISSUE THREAD

**Issue by ToxinZangoose** [Corail31/tombstone_lite#144]
### Minecraft Version

1.19.2

### Forge Version

43.2.6

### Corail Tombstone Version

Latest - 8.2.5

### What happened?

I have a question about Corail Tombstone. I am using Rings of Ascension and noticed that I got a message above my hotbar saying that I cannot use that effect yet while I was wearing a Ring of Mining which provides Haste.
Does Corail Tombstone gate certain potion effects behind the Knowledge of Death?

If this doesn't apply, let me know. 
If so, how do I configure Corail Tombstone to remove this?

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Rings of Ascension and Corail Tombstone

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I find your explanation not very clear, if you have a Tombstone magic item in hand, the interaction could be interrupted because it would be a right click, that would look normal if the item is in cooldown.

**Comment by ToxinZangoose** [comment]
I was wondering if Tombstone’s config file had a way to disable the message that I couldn’t use the effect yet. I couldn’t test with only Corail Tombstone installed since it seems to be a mod interaction.

**Comment by Corail31** [comment]
May you provide the exact message that you receive so i can know if there's a relationship with Corail Tombstone ? (again you don't try to explain the problem in a way that i can help you, you just want a solution)

**Comment by ToxinZangoose** [comment]
Sorry for the late response, I recently removed AttributeFix from my modpack and that seemed to have corrected the issue I was having. I no longer have a message pop up above my hotbar when using a miner's ring from Rings of Ascension.

My apologies for the confusion, thank you for your patience.

**Comment by Corail31** [comment]
@ToxinZangoose I'm happy for you that you found the trouble ;)
