### ISSUE TITLE
Graves can't be opened by players

### ISSUE THREAD

**Issue by Dany2114** [Corail31/tombstone_lite#147]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860 (1.12.2)

### Corail Tombstone Version

4.6.2

### What happened?

Everytime me and my "friends" want to opne our Graves it doesnt work.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You probably missed a part of the issue template. If you don't have time to locate the related mods to your issue, i won't guess an answer for you.
Try to "crouch" above the grave, to see if it's related to a 'permission' mod.

**Comment by Dany2114** [comment]
> You probably missed a part of the issue template. If you don't have time to locate the related mods to your issue, i won't guess an answer for you. Try to "crouch" above the grave, to see if it's related to a 'permission' mod.

I can't figure out what Mod is related to that issue because there are no Information in the Logs. And crouching on the grave doesnt do anything.

**Comment by Corail31** [comment]
I agree with you Dany, but if i start like this: i would need to test your exact modpack to figure out the problem and i would be costly in time if i did that for anyone having an issue with their modpack. It's just not possible actually with my limited modding time.
The issue template asks you to test with only my mod to discard the direct relationship with your issue.
You'll need to divide your modpack in 2 parts, test one part to see if it happens, and continue the process with the part having the issue until you find the mod bringing this 'incompatibility'.

**Comment by Dany2114** [comment]
I will do that as soon as im home. Thanks for the reply.
