### ISSUE TITLE
Tamable hostile mobs still count as hostile to grave guardians once tamed

### ISSUE THREAD

**Issue by Charmanth** [Corail31/tombstone_lite#149]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Corail Tombstone Version

7.6.3

### What happened?

Tamed "Hostile" mobs are targeted and killed by grave guardians without having attacked the grave guardians first***

I have Quark installed, which adds a tamable hostile mob called a foxhound.  I tamed one, brought it to my home, and have it sitting and chilling.  I also have grave guardians (two of them, I feel lucky) in my walled in territory.  If one wanders close to the foxhound, it just targets and attacks the foxhound even though the foxhound is tamed.  I also have Domestication Innovation so that the foxhound could respawn, and it just happens again when it respawns.

Expected Behavior: smarter targeting so it doesn't pick on tamed mobs that were formerly hostile.  Such as, leaving my poor foxhound alone >:C  Quark is not by any means the only mod to add mobs that start hostile, but can be tamed, so this behavior should improve qol/compat with more mods.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Quark, (suspecting any mod that has tamable mobs that start hostile)

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hello, normally, Grave Guardians and tamed animals/controlled undeads don't fight themselves but there may be something to check about this mentioned mob. I'll do a test in a few days.
Edit: To my opinion to answer to your explanation, agressive behaviors can be done without implementing Enemy (that would also affect how they spawn and how other entities will react against them~if i'm right). I didn't test yet, but my code actually checks isEnemy and not a controlled undead, why probably the guardian attacks them. I probably just need to check the "not tamed".

**Comment by Corail31** [comment]
@Charmanth I confirm the issue with the Foxhound, it's now solved in dev (so, for the next release and the changes are added to upper versions)
![foxhound](https://user-images.githubusercontent.com/68999590/230907905-76218cbb-4117-4ea7-ac92-358ca0d8bb10.jpg)

**Comment by Charmanth** [comment]
Thank you!  Now I don't have to worry about my foxhound.
