### ISSUE TITLE
The key doesn't enchant with a pearl.

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/tombstone_lite#15]
### Forge Version

1.17.1 - 37.0.59

### Corail Tombstone Version

tombstone-1.17.1-7.1.1

### What happened?

![image](https://user-images.githubusercontent.com/4427684/132995023-0126a166-7ff5-491d-a630-536d42f7581f.png)

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hello Goshen :)
There's no more crafting recipe for it in 1.17.1 but you can apply directly the ender pearl on the key in the inventory with right click.
Check JEI for what can be done with ender pearl, there's a custom category for it ;)

**Comment by ProsperCraft** [comment]
We can't figure out how this is supposed to work.

we drag the pearl over the key and right click, right click on the pearl, tried every combination.

Why change the mechanic?

**Comment by ProsperCraft** [comment]
Mouse tweaks breaks this mechanic, works fine without mousetweaks, can you go back to crafting the two together perhaps?

**Comment by Corail31** [comment]
If i changed this, it's for multiple reasons, if mouse tweaks breaks this mechanic, it probably also breaks the bundle item.

**Comment by Corail31** [comment]
https://github.com/YaLTeR/MouseTweaks/issues/58

**Comment by p1ut0nium-git** [comment]
Same problem in the 1.16.5 version of Tombstone.

Key can't be crafted with Ender Pearl to enchant.
Also, right clicking on key with Ender Pearl does not work.

Only Tombstone mod installed (no other mods).

**Comment by p1ut0nium-git** [comment]
Same problem in the 1.16.5 version of Tombstone. I'd really like my players to be able to use ender pearls to teleport to their graves (not the grave soul mechanic). Maybe an added config option to enable/disable this?

Tombstone Version: 6.5.5
Forge: 36.2.4

Key can't be crafted with Ender Pearl to enchant.
Also, right clicking on key with Ender Pearl does not work.

Only Tombstone mod installed (no other mods).

**Comment by Corail31** [comment]
@p1ut0nium-git 1.17.1 doesn't use the same game mechanic for this, so it can't be related... and the 1.16.5 works properly, so your test is not with only Tombstone (perhaps you use Mohist or another modified version of forge). Use JEI if you don't see the recipe.
Edit: also, we're in the halloween period, so players' keys are always enchanted, so probably why you can't enchant it, make sure to read the tooltip as it describes if you need to enchant it to teleport or if it's ready for this teleportation.

**Comment by Corail31** [comment]
fixed in 7.2.4
