### ISSUE TITLE
cant get to Tombstone in end 

### ISSUE THREAD

**Issue by firestorm2039** [Corail31/tombstone_lite#15]
just fell down in the black in the end, the tombstone is there, but its right down on the bottom, so when i teleport to it (key and ender pearl) i land on top of it and collect, i then fall, i then try pacing a rock on it so i can stand on something, but that also fail as it collects the tombstone. can anything be done here? it usually teleports to nearest land, but this time it didnt.

i can maybe build steps going down to it ( i have a build mod, that will make steps going down), but that will take a while to get to where the tombstone it.

**Comment by Corail31** [comment]
The recent versions always teleport you to the dragon spawn when you die in an empty chunk, so you just need to update your version. You can also use the command /tbrestoreinventory to click the grave at distance.
