### ISSUE TITLE
Travellers Backpack Duplication

### ISSUE THREAD

**Issue by Kakiharu** [Corail31/tombstone_lite#150]
I wasnt sure to post here or Travellers. If you put tombstone soulbound on your backpack and wear it then die, it will dupe the backpack.

**Comment by Corail31** [comment]
Travellers backpack is not my mod, open an issue on their repo, there seems to be some [messages](https://www.curseforge.com/minecraft/mc-mods/travellers-backpack?comment=296) about it on their page about soulbound in general.
