### ISSUE TITLE
Incompatibility with Twilight Forest Charms of Keeping

### ISSUE THREAD

**Issue by Toastr125** [Corail31/tombstone_lite#150]
### Minecraft Version

1.19.2

### Forge Version

43.2.7

### Corail Tombstone Version

8.2.5

### What happened?

Charms of Keeping 1-3 are items from Twilight Forest that cause you to keep parts of your inventory if you die with them in your inventory (1 keeps hands, armor, and curios; 2 keeps that plus the rest of the hotbar; 3 keeps the whole inventory) and are consumed on use.
They do not function when Corail Tombstone is present. They remain in the grave (and pop back into your inventory when unlocking it) and do not cause the player to keep anything.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Twilight Forest

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Toastr125 Did you ask on the subject with TF modders as they are really active to answer in general and know how to be before a grave mod... the grave only generates when the loots are already there.
NB: i use the 'low' priority of the livingDrop event to not have to check if "before/after mod" is still working in Forge for event order with same priority. Normally, TF handles its charm code in death/respawn event, so there may be no relationship; if you use more mods, you should locate better your problem.

**Comment by Toastr125** [comment]
I tested it with just the two mods in isolation and the charm of keeping still fails to work, it's not being affected by any other mods.

**Comment by Corail31** [comment]
Same answer as above.
