### ISSUE TITLE
Don't have permission of post this mod?

### ISSUE THREAD

**Issue by Mototopototo** [Corail31/tombstone_lite#151]
It's not compatible with some mods for making big modpacks and Minecraft don't allows me to play it, it says you don't respect the privacy policy and terms of use, is that true?
Please, I don't know why, but please give me a version of this file where I can play please, thx

**Comment by Corail31** [comment]
The message you probably got is from tombstone informing you when you combine it with incompatible mods and you probably got the exact incompatibility.
So please, read your message, before posting issue.

**Comment by Mototopototo** [comment]
Yeah, it says hat with gottsch core, but can he fix that?
