### ISSUE TITLE
Error when joining lan game

### ISSUE THREAD

**Issue by vasmark1** [Corail31/tombstone_lite#152]
### Minecraft Version

1.19.4

### Forge Version

45.0.43

### Corail Tombstone Version

Corail Tombstone 8.4.1 for 1.19.4

### What happened?

Tested with other and without other mods. It works fine in single, but mp is somehow broken. Also tested on forge v45.0.42

![image](https://user-images.githubusercontent.com/65904048/232324657-8dad477c-04a8-4018-a30d-ed504ea38094.png)
Client latest.log
[latest.log](https://github.com/Corail31/tombstone_lite/files/11242730/latest.log)
PC with world latest.log
[latest.log](https://github.com/Corail31/tombstone_lite/files/11242732/latest.log)

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

No

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by vasmark1** [comment]
Upd: it always says same error. but text after "of location:" is always different.

**Comment by Corail31** [comment]
@vasmark1 May you check the latest version in a valid launcher ?

**Comment by vasmark1** [comment]
Yup, problem solved in latest ver. Thx for your work, @Corail31!
