### ISSUE TITLE
Compatibility issue with Ars Magica: Legacy

### ISSUE THREAD

**Issue by IchHabeHunger54** [Corail31/tombstone_lite#153]
### Minecraft Version

1.19.2

### Forge Version

43.2.7

### Corail Tombstone Version

8.2.7

### What happened?

I received a bug report about the Ars Magica: Legacy mod (which I am developing) crashing when the player dies with Corail Tombstone installed. I wanted to have a look at what your mod is doing internally, but unfortunately the code doesn't appear to be public.
As a result, I want to kindly ask for advice on how to best solve this problem - what do you do internally, and how can I work around this problem?

The issue on our repo: https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/issues/381
The relevant event handler: https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/blob/fb5c5e32525bb57b6683a58c0daf86ff8eabfe21/src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/handler/AbilityHandler.java#L106

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Ars Magica: Legacy

### Log Link

https://gist.github.com/IchHabeHunger54/c97b66f7f74e447e260b1f0393f6672c

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hello, i think the player wanted to tell you that it happened on death (and mentioned that it happens only in certain dimensions).
There's probably no relation between my mod and your capabilities not working on death.
The log shows only your code and tons of mods with mixin: my template asks to locate the problem first.
Edit: as additional infos, the key allows to teleport to the grave (and may be in another dimension). Don't hesitate if you need more infos.

**Comment by Darkmega18** [comment]
it happens AFTER death, corail, not specifically on the death.

when I spawn in, I'm capable of holding the key and moving for a few moments and seeing the particles pointing me to the grave before the game goes down.

However occasionally the bug with escalate and it will instead hardlock the game and stop any of my inputs and remove the gui except for the floating icons of my inventory etc but I'm incapable of doing anything until end tasking.

Another observation I had is that if I have to be reloaded through another dimension, like dieing in the nether and spawning in the overworld again the bug does not occur and I'm fine. it's like it doesn't reinitialize me properly or quickly enough. But when it has to load through a load gate it has a moment to properly come back online before ars magica's ticking chucks a wobbly.

does that give you any better idea? I will however get my testing pack and throw both of these together and see if it still occurs, incase it is indeed just a really nasty lag issue and there needs to be a delay to have everything catch up.

**Comment by Darkmega18** [comment]
hm. it actually doesn't crash just with ars magica + corails alone. so we've definitely got some kind of tangential problem.

**Comment by Corail31** [comment]
Hi @Darkmega18, my main language is french, i used 'on death' to say the capabilities of Ars Magica are no more sync on the client after the clone/respawn events and the crash is because the other mod wants to crash when their capability is not sync.
I can't consider the issue if you don't isolate the mods needed to make this happen, any mod can break the respawn, i know it's boring but hey!

**Comment by Darkmega18** [comment]
In the process of it. I just saw something interesting in the crash that's unrelated to both these mods, so I'm investigating the mod it's likely from so to narrow the issue down.

**Comment by Darkmega18** [comment]
came up with nothing so far with just the mods in question even after getting some magic levels and stuff. so why it references ars so strongly when it happens in the larger pack is confusing.

**Comment by Corail31** [comment]
@Darkmega18 The way to go is by splitting the pack in 2 each time (all tested with Ars Magica), you know it (why you opened the issue on Ars Magica, right ? :p)

**Comment by Darkmega18** [comment]
strange. removed 100 out of 300ish mods. tested. didn't seem to do it. but I kept playing for a moment and did some fighting and picked up some various stuff then it occurred. but just off a kill command early on, it wasn't really being caused.

so it seems to require some amount of extra data needing to go into the player upon death, and not just any old death straight on. nor is it always gauranteed. as even in testing rarely I'd survive without a crash for whatever reason or another. so it's a bit of a heisenbug cause of how it just happens to react differently. either locking, not happening, or crashing.

200 now. couple of deaths. no occurence. then another. it happened. it happens less and less as the mod load decreases. but still occurs sometimes.

**Comment by Darkmega18** [comment]
Well, update for you corail. I'm not even sure if the bug was related to this or not, just the observation that it would usually happen while I was holding the key and stuff cause thats just what you do for the player after death.

However the bug surfaced less and less as the mods got divided until I seem to have come to settle on the effect that it was hammerlib and a related mod when I only had about 50 left (JEI and some quality of life + tombstone and ars), but the issue would only become more present under high load, such as my full pack.

So now I was back in my 300+ sized pack without hammerlib etc and respawned several times and no crash or lockup has reoccurred yet. So I'm not sure what zeitheron is doing, but sorry for the bother, corail.

**Comment by Corail31** [comment]
@Darkmega18 I'm happy to answer you (even if i was certain that my mod couldn't interfere with capabilities on death).
I suppose you're right it's about the amount of mods (300 looks a lot), and some mods may be more costly than others.
In general, i silent errors in my mod, where others modders want to display them (and their way is good too to track issues).
Edit: if you think it happens with hammerlib and the improvable skills mods, it would worth to test with only the 2 mods and Ars Magica to make the bug happening (or the modpack size is a factor).
