### ISSUE TITLE
Restore Inventory from File - Baubles Not Restored - 1.12.2

### ISSUE THREAD

**Issue by MadMex1** [Corail31/tombstone_lite#153]
Hi, 

Sorry if this is not an issue with Corail Tombstones but hopefully you might be able to help.

An item has killed a couple of players how this item has prevented the grave from spawning, having restored inventory from the file generated on death, it does not seem to restore anything in baubles slots.

Is there a different file I should be using that contains bauble information, as I understand the graves themselves do give back baubles?

Again I appreciate this might not be because of this mod, but though I would check anyway :)

Thanks!
MadMex_

**Comment by Corail31** [comment]
Hello, so i guess you're on 1.12.2, your story is interesting even if you didn't choose the right day to post an issue, and really be trust too ;)
You specially avoid to bring details as asked in [how to post an issue](https://github.com/Corail31/tombstone_lite/issues/96), even if i can guess you're on 1.12.2, but you don't explain what is this item (from which mod).
Saves are done every x time and are not specially related to when the player dies, you can configure them in "config->recovery" or enable the new config option to save before the death.
If you think it's not related, you should do tests to understand better what happen as there's no reason for the baubles to not be there ;)

**Comment by MadMex1** [comment]
Hi, 

My apologies I can confirm it is 1.12.2 and this is a genuine query haha. I somehow completely missed that pinned post! Here are the specifics:

The forge version is 14.23.5.2847 and the mod version is 3.6.8. The modpack being used is MC Eternal.

The item in question is "Creative Spikes" from Extra Utilities 2, these were obtained from a Black Market Container - purchasable in the FTB Quest Shop within the modpack. Upon instantly dying from these spikes it resulted in no grave and the logs stated that another mod prevented the grave from spawning.

tbrecovery was used to recover the inventories.

As I know that clicking the grave with a key gives you back everything, I assume that restoring would also do the same, which it sounds like it should from what you are saying? But no baubles unfortunately :(

**Comment by MadMex1** [comment]
I think I have answered my own question, after testing in singleplayer resoring with the .save does indeed restore everything. 

Apologies for possibly wasting your time!

Thanks,
Robert

**Comment by Corail31** [comment]
In fact, you can find some informations about this creative spike [HERE](https://github.com/Corail31/tombstone_lite/issues/139).
This item in Extra Utilities shouldn't be used by mod as it's intended to destroy the inventory of the player that is killed by.
You're right, the config to save before the death "backup_on_death" is added in 3.7.0.
About the command to restore the player, it should be a .save but you only need to use tabulation to auto-complete the command :
```
/tbrecovery <save_all_players|save_player <player>|load_player <player> <save>|load_offline <uuid> <save>>
```
