### ISSUE TITLE
Tombstone attacking players with snowballs causing slowness

### ISSUE THREAD

**Issue by Gunner76th** [Corail31/tombstone_lite#154]
I am playing on the modpack Project Ozone 3 which is found here https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward

The current version of the Tombstone mod in the modpack is tombstone-3.7.1-1.12.2

The issue I have is I crafted the tombstone and placed it at my base. Currently it has a purple orb floating about it. The problem is, whenever I am in direct line of sight of the tombstone, it attacks/throws a snowball at me applying slowness for 8 seconds, and it does this about every 8-12 secs that you are within LOS and in range. I have been unable to find any documentation on this, or explanation as to why this is happening.

**Comment by Corail31** [comment]
Hello Gunner76th, I guess you must have annoyed the graves, did you make a particular movement around them?

**Comment by Gunner76th** [comment]
I just walk past the one I crafted. I made the one in the screenshot, and now when I walk near it, it tosses snowballs at me. 
![image](https://user-images.githubusercontent.com/5566872/78140742-788fe000-73f8-11ea-81e8-44b0ce0594aa.png)
![image](https://user-images.githubusercontent.com/5566872/78140756-7ded2a80-73f8-11ea-836e-37c549597da5.png)
The second is of the tombstone itself. And while standing in front of it while on the Game Menu (player on a server) it shot a snowball at me. 

It is getting rather annoying I must say.

**Comment by Corail31** [comment]
As you say that they don't throw anything if they don't see you, perhaps you can make a wall to protect you ? or perhaps a pray to appease them.

**Comment by Gunner76th** [comment]
>  or perhaps a pray to appease them.

So I take it this is an intended feature, triggered by some event?

**Comment by Corail31** [comment]
You can find info [here](https://github.com/Corail31/tombstone_lite/blob/master/src/main_1.14/resources/assets/tombstone/lang/en_us.json#L382).

**Comment by Corail31** [comment]
@Gunner76th sorry again ;) there was some nested codes like this one for april fools, and if you got ennoyed by them, you will receive a reward through advancement.
