### ISSUE TITLE
Souls not spawning

### ISSUE THREAD

**Issue by Sbeego99** [Corail31/tombstone_lite#155]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Corail Tombstone Version

7.6.4

### What happened?

Hi, i'm playing a modded server with my friends and i already have like three tombstones, i'm already playing like a week ago and not a single soul appeared.
I tried to modify the chance in the config files, howeverten days has passed (ingame) and still nothing happens.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

Thermal series, Mekanism, Botania, Alexs mobs

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Even if you don't see the soul floating over the decorative grave, it may be present (ex if you use Oculus with an incompatible shader like 'Complementary Shaders'.
The config allows to change the soul on **1000**(not on 100) and to reduce the time for a soul check.
If you interact a decorative grave with an enchantable item, you will get a message if a soul is present or not.
I don't think you can make this happening with only Corail Tombstone.

**Comment by Sbeego99** [comment]
It's weird because, i tried that, youre right, but still no souls, un a long period of time... It's that normal? Can it be a bug, because i'm constantly checking if any soul spawned and nothing...

**Comment by Corail31** [comment]
You got the informations, now it's time to make your own tests.
