### ISSUE TITLE
Unknown Console Error when player dies.

### ISSUE THREAD

**Issue by X-Niter** [Corail31/tombstone_lite#155]
The following error occurs when someone dies. I do have openmod wich has a grave but it is disabled.
SpongeForge version 7.1.10
And Tombstone mod version is Version 3.7.1. 

Any ideas on why this error is constantly happening? 
It does not seem to cause any issues with them getting there grave. 
-
-
-
Server thread/FATAL Error executing task
03.04 23:56:46 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: ovh.corail.tombstone.helper.LangKey.getClientTranslation([Ljava/lang/Object;)Ljava/lang/String;
03.04 23:56:46 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212-1-ojdkbuild]
03.04 23:56:46 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212-1-ojdkbuild]
03.04 23:56:46 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
03.04 23:56:46 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.10]
03.04 23:56:46 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$zjh000$onRun(MinecraftServer.java:4713) [MinecraftServer.class:?]
03.04 23:56:46 [Server] INFO at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
03.04 23:56:46 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
03.04 23:56:46 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
03.04 23:56:46 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
03.04 23:56:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212-1-ojdkbuild]
03.04 23:56:46 [Server] INFO Caused by: java.lang.NoSuchMethodError: ovh.corail.tombstone.helper.LangKey.getClientTranslation([Ljava/lang/Object;)Ljava/lang/String;
03.04 23:56:46 [Server] INFO at ovh.corail.tombstone.event.EventHandler.lambda$onPreventDeath$3(EventHandler.java:233) ~[EventHandler.class:?]
03.04 23:56:46 [Server] INFO at ovh.corail.tombstone.command.CommandTBRecovery.lambda$null$4(CommandTBRecovery.java:161) ~[CommandTBRecovery.class:?]
03.04 23:56:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212-1-ojdkbuild]
03.04 23:56:46 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212-1-ojdkbuild]
03.04 23:56:46 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
03.04 23:56:46 [Server] INFO ... 7 more

**Comment by Corail31** [comment]
please edit your issue if you want it to be considered....
