### ISSUE TITLE
Is this normal? Is this your end or JEI Integration?

### ISSUE THREAD

**Issue by Minebrah** [Corail31/tombstone_lite#156]
### Minecraft Version

1.19.2

### Forge Version

43.2.6

### Corail Tombstone Version

8.2.8

### What happened?

[02May2023 13:52:21.264] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Registering recipes: tombstone:jei_integration took 898.7 ?s

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Jei Integration

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I don't think your log is relevant and is not in seconds.
