### ISSUE TITLE
[Incompatibility] Tool belt mod 1.14

### ISSUE THREAD

**Issue by D-Bigboy-302** [Corail31/tombstone_lite#157]
I am using the latest 1.14 version and when played along with the tool belt mod by gigaherz, it isn't auto equipped in the curio slot when unlocking tomb. (Tool belt has it's own slot in the curio's api) Sometimes the belt completely dissapears as well.

**Comment by Corail31** [comment]
I'm not sure what you mean, my mod Travel Bag has its own slot in curios and has no trouble.
Are you sure that it's reproductible with only theses 2 mods? 
As even if it has its own slot, it wouldn't change how it's handled.

**Comment by D-Bigboy-302** [comment]
Did some testing. I play along with other curio mods like enigmatic legacy, backpacked, and bountiful baubles. For some reason the toolbelt is the only one that doesn't auto equip. It always comes back into the regular Inventory. And if the inventory is full, the belt along with its items, dissapear.

**Comment by Corail31** [comment]
I made the tests : the belt is not equipped, so i'll look the reason.
The inventory full leads to the item being dropped on the ground only.

**Comment by D-Bigboy-302** [comment]
Awesome! Thank you for your time! I love your mods!
