### ISSUE TITLE
[1.16.5] Familiar stone works while disabled

### ISSUE THREAD

**Issue by DoctorMage** [Corail31/tombstone_lite#158]
### Minecraft Version

1.16.5

### Forge Version

Forge 36.2.39

### Corail Tombstone Version

tombstone-6.8.12-1.16.5.jar

### What happened?

Disable familiar stone in config
![image](https://github.com/Corail31/tombstone_lite/assets/85318453/5aff0588-80ee-4166-91d1-8fafa39b47d6)

Obtain familiar stone

Kill tamed mob
![image](https://github.com/Corail31/tombstone_lite/assets/85318453/62be6e41-30de-467b-9b0a-784ca7748fc0)

Use familiar stone
![image](https://github.com/Corail31/tombstone_lite/assets/85318453/ef21d24e-b2ef-4d36-a9b7-0221fe6d740f)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Log Link

https://gist.github.com/DoctorMage/05777d1a0c05e9ceba531c0ab8592695

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's working as expected and there's no more support for 1.16.5 if you missed that information on the mod's page.
If you disable the familiar stone, it means you can't get it as a loot but it doesn't remove existing items or prevent to use them. Disabling to use an item could be consider as a bug for players (as the config is on the server and depends on the modpack).
I tend to think that players never read item tooltips.
