### ISSUE TITLE
Config to disable magic system

### ISSUE THREAD

**Issue by Pengu-Hunter** [Corail31/tombstone_lite#158]
This is a suggestion that I couldn't find in existing issues though I might have missed it, this also may seem redundant with the obvious answer being just don't use the knowledge of death and related items and that is true but I'd still rather not have the mods magic system at all.
I love the grave and key system and it is IMO the best grave mod, but I don't want the associated magic system.

**Comment by Corail31** [comment]
Hello Pengu-Hunter,
I completely understand your opinion, i often thought the mod could be splitted into 2 parts, but i often get to the initial steps of Tombstone that were : i need a key to open the grave and a rare way to enchant it.
On the other side, the magic content is not something that "tick a lot" or can have a performance reduction, it's really something silent.
If you removed the magic part, it would be less "best grave" as you think, as most of things that are you're used like ghostly shape are parts of it.
As you imagine, disabling that part is less worthing than splitting the content, and splitting content requires a new mc version to stay compatible with previous versions.
Also, in 1.16, decorative graves are planned to be normal grave except when someone prays over them (and no soul until that).
Not sure if it answers to your suggestion :)

**Comment by Pengu-Hunter** [comment]
Thank you for a comprehensive and answer and yes I understand and it does does answer my question and I have used the config to do just that however the config doesn't affect loot tables for blank scrolls and the dust.

**Comment by Corail31** [comment]
I suppose it's the loottables called by the advancements, as the other ones don't contain the disabled items. The dust being also dropped by undead but required to build decorative graves.
You can also disable the perks based on some configs (example : memento mori with config related to xp, jailer with the config chanceEnchantedGraveKey)

**Comment by Corail31** [comment]
@Pengu-Hunter if you want, you can contact me on CurseForge to discuss about the exact parts that would need to be disableable (as you seem to be nearly to the result that you wanted)
