### ISSUE TITLE
Decorative tombstone not breaking

### ISSUE THREAD

**Issue by Proxwian** [Corail31/tombstone_lite#159]
### Minecraft Version

1.2

### Forge Version

40.2.4

### Corail Tombstone Version

tombstone-7.6.5-1.18.2

### What happened?

Players can't break decorative graves on server: breaking animation persist, but when player "breaks" grave, it restores back.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Since the time 1.18.2 exists, i won't consider your issue.
Support for 1.18.2 (and old versions) are now limited to patreon supporters.
I recommand you to update to a recent version.
