### ISSUE TITLE
[Compatibility] No Loot generation with Enigmatic Legacy 1.14

### ISSUE THREAD

**Issue by D-Bigboy-302** [Corail31/tombstone_lite#159]
When combined with Enigmatic Legacy no loot generates in certain structure chests such as Shipwrecks, dungeons, buried treasure and end city chests.

I am using the latest 1.14 version for both mods. An issue was opened for Enigmatic Legacy as well.

**Comment by Corail31** [comment]
Hello,
You'll need to localize better what mod is preventing to inject the loottables as they work fine without theses mods.

**Comment by Corail31** [comment]
https://github.com/Extegral/Enigmatic-Legacy/issues/12

**Comment by D-Bigboy-302** [comment]
The issue is on enigmatic's side completely, which you figured out obviously. I apologize.

**Comment by Corail31** [comment]
@D-Bigboy-302 By reading better your initial message, all the lootables are not added by default, it's a config and some of the ones you mention are not in by default like the buried treasure or shipwreck.

**Comment by D-Bigboy-302** [comment]
After removing and adding EVERY single mod, 80, I found out that it was 2 separate mods messing with the injectables. It ended up being completely unrelated to your mod and Enigmatic Legacy.

Once again I apologize for wasting your time, but thank you for looking into it even slightly.
