### ISSUE TITLE
Graves sometimes rotate randomly when they acquire a soul

### ISSUE THREAD

**Issue by Reassembly** [Corail31/tombstone_lite#16]
I have noticed that when graves (only Simple variety tested so far, may affect others) are struck by lightning and acquire a soul, they are sometimes rotated to a new and seemingly random direction.

I can't confirm this yet, and I can't decompile the .jar fully enough to check this myself, but I suspect that when a grave acquires a soul, it is being replaced with a mostly-identical grave block (with the soul activated), but that the direction it is facing is not being transferred to the new grave block - it might be turned in the direction of the nearest player, as though it had been "placed" by them remotely. I could be completely wrong about that, though.

**Comment by Corail31** [comment]
Hi Reassembly, i think you're right on it, and i know why so i'll publish a release today to fix it. (and #15)
Thanks for the interest on my mod :)

**Comment by Corail31** [comment]
Fix in 2.9.9

**Comment by Reassembly** [comment]
I'm afraid that the issue is still occurring with 2.9.9. At least I can be a little more specific with the symptoms now: graves which are placed facing _south_ are turning to face _east_ when they acquire a soul.

I also see that, while a grave's PropertyDirection FACING is declared using EnumFacing.Plane.HORIZONTAL, most of the other type references are to just EnumFacing.

EnumFacing[] has six elements, while EnumFacing.Plane.HORIZONTAL[] has four - and they're not in the same order. In fact. the fourth element of each enum is EnumFacing.SOUTH = EnumFacing.Plane.HORIZONTAL.EAST. I think this is...not quite a typecasting error, but an index-translation error? Is that a thing?

Please forgive the all-caps - I'm not _trying_ to shout, it's just that the property names and enums are in all-caps, and Java is case-sensitive. That being said, I'm sure that enum typecasting issues like this might make a person _want_ to start shouting.

**Comment by Corail31** [comment]
Hi Reassembly,
I haven't done the tests on it last time(as i'm on others projects for now and i'm alone on all my projects), but i'll make them and fix it if needed ;)

**Comment by Reassembly** [comment]
Upgrading to 2.9.10 caused a west-facing grave to turn north, and a north-facing grave to disappear - not from acquiring a soul, but just from upgrading the .jar. However, _after_ replacing those graves, they acquired souls without rotating. So it looks like the issue is actually solved now. 👍

**Comment by Corail31** [comment]
Are you sure that a grave "disappear"... as there's no reason for it ;)
NB : I'll do the test when i have time, with a grave in each direction & update the version to see if it can happen. (before releasing the version)

**Comment by Reassembly** [comment]
No, I'm fairly sure it was the north-facing grave which vanished. It's strange, because NORTH is element 2 in both enum lists, so it shouldn't have ended up with an invalid index - and WEST and NORTH don't share an index between the lists, so WEST should not have become NORTH. Unless you made some other change with how you encode/decode the direction to/from the blockstate, this _should not_ have happened - but it did, and I can't figure out why.

In any case, these issues only occurred with _previous_ graves when upgrading a world from 2.9.9 to 2.9.10. The graves I've placed _after_ upgrading to 2.9.10 have been perfectly fine.

**Comment by Corail31** [comment]
So, i've done the tests, and i'll just remove the predicate on the PropertyDirection (as i want to keep compatibility with previous saves, and i don't want to "invalidate" some states in the blockstate)
Fixed in coming 2.9.10
