### ISSUE TITLE
I think the new update hates RPGz (6.3.3)

### ISSUE THREAD

**Issue by Niconoko** [Corail31/tombstone_lite#16]
https://pastebin.com/bjfBrkp7
Just crashed right when about to enter the world.

**Comment by Corail31** [comment]
https://www.curseforge.com/minecraft/mc-mods/rpgz
Read the description of this mod, meaning it's incompatible with a grave mod.
You also got a log on your server with this message :
"You loaded another grave mod. If you want this other mod to handle the player's death, you need first to disable the config option 'handle_player_death' in Tombstone.""
