### ISSUE TITLE
Ready to die advancement not unlocking

### ISSUE THREAD

**Issue by suprra** [Corail31/tombstone_lite#160]
I have changed my grave via the configs outside of game, and via knowledge of death config in game
I changed the in game config of client.toml to subaraki_grave but when in game and I navigate via knowledge of death it shows it the first time but once I click the arrow it doesn't show subaraki as an option anymore only the other 5 until I reopen knowledge of death.

Is there something else I can do?

Personal private server running curse All the mods 5-1.15 /w added building gadgets and updated forbidden arcana
forge 31.1.30
video/gif showing knowledge of death
https://i.gyazo.com/aa504275290de78fc511dd012c908230.mp4
![2020-04-20_12 17 40](https://user-images.githubusercontent.com/31143536/79703849-7687b580-8302-11ea-9267-120b224bfc69.png)

Hope I haven't missed something obvious 
Thank you for your time <3 your mod

**Comment by Corail31** [comment]
This grave is limited to contributors for player death, but can be used as decorative grave.

**Comment by Corail31** [comment]
![favorite_grave](https://user-images.githubusercontent.com/17954109/79744259-535f0500-8306-11ea-95d7-4e5d3962c01f.jpg)
Make sure you click the save button ;)

**Comment by suprra** [comment]
I was doing that anyway but thought I'd post a vid showing it
https://gyazo.com/e655ca3c0acdebd7839b598b9e9c21f5

Strangely, in a creative world when doing this exact same thing it worked perfectly fine :/

**Comment by Corail31** [comment]
@suprra thanks for all your details, i succeed to reproduce it, so i'll look to fix it.
