### ISSUE TITLE
class ovh.corail.tombstone.entity.GraveGuardian tried to access private field net.minecraft.world.entity.Entity.f_19793_

### ISSUE THREAD

**Issue by sandalle** [Corail31/tombstone_lite#160]
### Minecraft Version

1.20

### Forge Version

1.20.1-47.0.35

### Corail Tombstone Version

8.5.0-1.20

### What happened?

A mob from MineColonies tries to spawn/load/or die and causes a crash:
```
java.lang.IllegalAccessError: class ovh.corail.tombstone.entity.GraveGuardian tried to access private field net.minecraft.world.entity.Entity.f_19793_ (ovh.corail.tombstone.entity.GraveGuardian is in module tombstone@8.5.0 of loader 'TRANSFORMER' @671da0f9; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @671da0f9)
```
Removing MineColonies removes this crash (haven't had any other mods/mobs cause this issue yet).
I've also filed a ticket with MineColonies at https://github.com/ldtteam/minecolonies/issues/9229 if the issue is on their side.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Minecolonies

### Log Link

https://pastebin.com/m44ZE2d8

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hello, I can't answer you for the moment because I don't have the mappings in front of me to check if Raycom is right.
For now, it only appears with a specific mod (and not vanilla), so I won't say it's on my end.
NB: you can probably try an older version 1.20 of Minecolonies as i doubt there was an incompatibility with the other mod before ('cause i know i won't have time to make changes for a month).

**Comment by sandalle** [comment]
The is the only version of MineColonies available for MC 1.20.1 for now. I'll try a newer MineColonies when it comes out as well to check. Thank you for looking into it when you have time.

**Comment by Corail31** [comment]
Edit: The current version was built for 1.20.0 and it looks related to a [forge change](https://github.com/MinecraftForge/MinecraftForge/commit/a43be391371911e231cd09703ec84e71c94ed8c8#diff-3c5e61e6b3303cd31e5882573871953441b3b1d9a4cc7b018b1ff5eda25ce27dL222). You probably can use a previous version (before 47.0.26) until i update the mod (soon).

**Comment by ModernGamingWorld** [comment]
Thank goodness this was reported as I am starting to crash now, I had to remove this mod to fix the crash

**Comment by Corail31** [comment]
Forge is in beta, that's the only problem when they make breaking changes. Nothing forces you to update to latest forge.
The problematic version by Forge was published 2 weeks ago, it's not like there is an emergency.

**Comment by Raycoms** [comment]
Any update on this? Minecolonies is blocked from pack inclusion because of this.

**Comment by Corail31** [comment]
After a discussion with Raycoms, an update is for tomorrow to solve the problem.

**Comment by Raycoms** [comment]
Perfect, thanks!
