### ISSUE TITLE
Bug with Dragon Survival in 1.19.2

### ISSUE THREAD

**Issue by SumaniPardia** [Corail31/tombstone_lite#161]
### Minecraft Version

1.19.2

### Forge Version

43.2.11

### Corail Tombstone Version

8.2.9

### What happened?

This is related to the Dragon Survival claw fix you implemented for me before (thanks again by the way).  In the new 1.19.2 version of Dragon Survival they renamed the getClawInventory() method to getClawToolData(), which causes Corail Tombstone to crash the server if a dragon player with an item in one of the claw slots tries to loot their grave.  Can you please update the ovh.corail.tombstone.compatibility.CompatibilityDragonSurvival.autoEquip(CompatibilityDragonSurvival.java:29) to use the new method when you get a chance?

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Dragon Survival 1.19.2-1.5.52

### Log Link

https://pastebin.com/ra8TBKNG

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@SumaniPardia the compatibility has been updated (8.2.10), thanks for your report ;)
