### ISSUE TITLE
Feature for the loss of items in graves after X time

### ISSUE THREAD

**Issue by FacundoGimenez** [Corail31/tombstone_lite#161]
Is there a way into configurations to say in X time if you don't take ur grave when you die it disappear?

Or could you tell me how can I do it?

Thank you.

**Comment by Corail31** [comment]
Hello :)
To answer you, i should first understand what will be the real use of this.
In general, players don't like to lose their stuff and except if it's a behavior with an explicit message to the player, it would be more seen as a bug to them.
There's a config option named decayTime allowing graves to be openable by anyone after x times.
There's a config option giving a chance to lose some items when you recover the grave (with an explicit message to player) that could be adapted to be applied only after x times elapsed.

**Comment by FacundoGimenez** [comment]
The use of this is to make the difficult harder in some cases, eg: if you dont reach your grave in 5 minutes things will be lost.

**Comment by Corail31** [comment]
So i suppose the grave could be still present but empty, in this case, i can adjust really fast my next update about it :)
This will also allow them to know the path to return to their death point, as key disappears when graves are no more there.

**Comment by Corail31** [comment]
for the time, i thought to use the decayTime option that corresponds when the grave is considered as "abandoned" but also means any player could open it too. I could adapt this if it's a trouble.

**Comment by Corail31** [comment]
@FacundoGimenez don't hesitate to bring me feedbacks about this as i'll probably improve it later (on curseForge or here).
