### ISSUE TITLE
Crash on world load at 100%

### ISSUE THREAD

**Issue by realBritakee** [Corail31/tombstone_lite#162]
### Minecraft Version

1.20

### Forge Version

47.0.43

### Corail Tombstone Version

Latest 1.20.1

### What happened?

the game crash when loading a world at 100% 

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Log Link

https://pastebin.com/0r77cA6q

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Please, don't create duplicate issues. Forge 47.025 and below may be a provisory solution.
https://github.com/Corail31/tombstone_lite/issues/160
