### ISSUE TITLE
How to avoid crashes after editing manually the config files

### ISSUE THREAD

**Issue by victorgh1991** [Corail31/tombstone_lite#163]
Hi,

First of all thanks for the mod we love it, but seems like we have some issues on the server when we change the "chance_enchanted_graveKey" parameter from 0 to any other number at the 1.15.2 version of Minecraft, we tested several versions of the mod in the server and after every test we made the server crashes when it is starting up after changing this parameter to let the users always have the enchanted key after die. Maybe we need something that complements the mod?

We really hope that you can help us with with your knowledge.

Thanks in advance.

**Comment by Corail31** [comment]
Hello victorgh1991, what is your tombstone version and what is the log ?
The most common mistake about this is a wrong edit of the toml file, there's no special other reason for it to crash.

**Comment by victorgh1991** [comment]
Hi,

The Tombstone version is: tombstone-4.3.4-1.15.2.

And here you have the log: https://pastebin.com/FZVcY8NX - this is from the last try of changing the chance parameter.

I just edited the file with server stopped, just changed the chance parameter from 0 to 100, saved the file and started again the server, no more changes.

**Comment by Corail31** [comment]
@victorgh1991 can you confirm me that changing others server configs work correctly ?

**Comment by victorgh1991** [comment]
Hi,

Sorry for the late reply, i have changed the "xp_loss" parameter from 0 to 25 and again it crashed.

tombstone-server.toml: https://pastebin.com/RmrzYFSv
Crash report: https://pastebin.com/NsDuNxRc

**Comment by Corail31** [comment]
@victorgh1991 i want the real file to check the encoding, not a copy/paste.

**Comment by victorgh1991** [comment]
Sorry here you have it
[tombstone-server.zip](https://github.com/Corail31/tombstone_lite/files/4523077/tombstone-server.zip)

**Comment by Corail31** [comment]
So, i know what is your trouble, you have BOM in your file encoding, i'll recommand you to use an editor of text like notepad++.

**Comment by victorgh1991** [comment]
Great let me try it

**Comment by victorgh1991** [comment]
It's working!!!

Hahahaha i cant believe that was the problem thank you so much for your help

**Comment by Corail31** [comment]
Neat, no problem, this topic should help others people :)

**Comment by victorgh1991** [comment]
Thanks a lot

**Comment by Corail31** [comment]
I'll leave this issue open for now as it can be informative for others experiencing the same trouble.
