### ISSUE TITLE
Bug with "Bottle your Xp" mod

### ISSUE THREAD

**Issue by Pengu-Hunter** [Corail31/tombstone_lite#164]
Muahaha yes tis I who have come to darken your Github door step again.
Ok sorry about that but now that ive gotten that silliness out of my system.
When using the mod "Bottle your Xp" which lets you use empty bottles to remove xp from yourself and create bottles o enchanting at the cost of half a heart and go to far and die no grave is generated.
This is happening in 1.12.2 on the as of this post most recent version of both mods "tombstone 3.7.3" and "Bottle your Xp 1.0"

Regards Pengu

**Comment by Corail31** [comment]
What you explain me look more to a bug in this mod how they kill the player (behavior like how sacrificial dagger was before in blood magic but fixed since) making the player losing its drops forever, and no drop = no grave.
Fortunetely, you have a command /tbrecover to restore your player :)

**Comment by Pengu-Hunter** [comment]
good to know I'll add this issue to the other mod

**Comment by Corail31** [comment]
@Pengu-Hunter did you just test it alone without tombstone to check what happen on death and if your drops were there ?

**Comment by Pengu-Hunter** [comment]
no but i will do that

**Comment by Corail31** [comment]
@Pengu-Hunter don't forget to check the existing issues when you open a new one (thinking to your new one)
