### ISSUE TITLE
[Suggestion] Binding Familiar Receptacles to a specific familiar

### ISSUE THREAD

**Issue by Uub112** [Corail31/tombstone_lite#165]
So I've been playing around with these familiar receptacles for a little bit now, and one of the things that's happened is that sometimes I'll try to cull some mob with my name to it that I maybe tamed but didn't want to keep, or sometimes there'll be a mod that will have mobs which keep track of the player who spawned or interacted with it but otherwise have little player control/interactions getting themselves killed; in both cases you would end up with a receptacle that's essentially wasted because the intent was to keep a receptacle in the inventory to potentially save a different mob, so _if you could bind a receptacle to a specific entity, it would be possible to prioritize which mob(s) you'd want to save._

**Comment by Corail31** [comment]
Hi Uub112,
That's a good idea to pass here to make a suggestion.
It would be even better if you could explain the details how you would see it in game.

**Comment by Corail31** [comment]
@Uub112 imagine that the feature is done and you're trying it, can you describe/imagine the steps that will allow to change the familiar receptacle into a linked one catching only one specific creature.
But i have still the doubt your trouble is some specific creatures that are catch when you don't want : in this case, i would need the names of theses mobs to better understand as only tameable creatures are captured (and tamed by you).

**Comment by Uub112** [comment]
Sorry for the late response, @Corail31 ,
How about just a sneak+right click or something similar with the receptacle in hand to register a specific mob to preserve in it? The regular behavior for the receptacle is actually quite excellent and useful as-is, so this way you can have the option to have just one or two familiar receptacles bound to specific mobs, or to have them in the inventory to catch whatever dies as a default if you didn't bind anything to them.

**Comment by Corail31** [comment]
@Uub112 the sneak is not required to interact but this action could be the way to link the empty receptacle to this tamed creature, so you mean at the same crafting cost as a normal one catching everything.
The 2 possible creatures capturable in the same receptacle looks perhaps you want to capture a specific type (all tameable beetles from druidcraft for example) and not a specific one from that type.

**Comment by Uub112** [comment]
@Corail31, indeed the idea initially was to have a simple interaction to select a specific mob to preserve with a given receptacle at normal cost, although I like your idea where you kill the mob type that you want to make a receptacle capture as well.
How about a somewhat weak weapon as a linking item? Maybe it could be enchanted, then it would be able to get the creature's type and bind familiar receptacles, or even maybe make soul receptacles, at a cost to alignment...

**Comment by Corail31** [comment]
@Uub112 you can contact me on curseForge if you want a version of test ;)
