### ISSUE TITLE
crash from familar death damge type

### ISSUE THREAD

**Issue by Pultex** [Corail31/tombstone_lite#166]
### Minecraft Version

1.20

### Forge Version

forge-47.1.3

### Corail Tombstone Version

tombstone-8.5.1-1.20.1

### What happened?

runs fine till familar death from null damage from other mod interact

this is not a corail tombstone crash on it's own just wanted to know
if there is a ID for familars or are all them the same to default mob IDs

Think I can blacklist it if there is a separate ID for them also might be able to make them immune to some damage that seems to not be recognized

log shows this is modpack ATM9 Alpha

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Other relevant mods

EvilCraft-1.20.1-1.2.25

### Log Link

https://gist.github.com/Pultex/49436ce2abf5ee902039e2161cca1472

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Pultex** [comment]
okay seem wrong it is causing me the player null damage from the familar lantern

thought I was causing the null damage to the familar

**Comment by Corail31** [comment]
I will look for your issue this weekend (but not before).

**Comment by Corail31** [comment]
@Pultex Thanks for your report, you can disable the config 'allowBeyondTheGraveDamage' (in category general) as a provisory solution.
