### ISSUE TITLE
Scroll drops from modded chest blocks

### ISSUE THREAD

**Issue by SoullessCookie** [Corail31/tombstone_lite#167]
### Minecraft Version

1.20

### Forge Version

47.1.3

### Corail Tombstone Version

8.5.1

### What happened?

Blocks such as the Reinforced Chest from PneumaticCraft and according to another user, the Controller block from Refined Storage/AE2 have a high probability of dropping a spell scroll when broken. You left a comment on my bug report for ATM9 saying that it would need "to reduce the affected loot tables". 
It's definitely not a bad thing, I just found it kind of odd that you can place like a hundred Reinforced Chests and use any vein mining mod to break them, yielding 30+ scrolls very quickly.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

PneumaticCraft: Repressurized

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, sorry if I was not precise enough: it's resolved in the new release:
- fixes magic items being found on modded chest drop
It was not expected to be found in modded chests.

**Comment by Corail31** [comment]
https://github.com/AllTheMods/ATM-9/issues/79
https://github.com/AllTheMods/ATM-9/issues/168

**Comment by SoullessCookie** [comment]
> Hi, sorry if I was not precise enough: it's resolved in the new release:
> 
>     * fixes magic items being found on modded chest drop
>       It was not expected to be found in modded chests.

Oh, my bad. Thanks for the update!
