### ISSUE TITLE
Server Crash at ovh.corail.tombstone.effect.EarthlyGardenEffect

### ISSUE THREAD

**Issue by IchigoGames** [Corail31/tombstone_lite#168]
i think this crash that happened on my server is from this mod

Minecraft 1.15
Forge 31.1.50
tombstone-4.3.5-1.15.2
https://pastebin.com/Lxbd9MSF

**Comment by Corail31** [comment]
I'm sorry for this IchigoGames, it should be really rare to obtain it in 4.3.5, and it's still experimental, you got it through a pray, i suppose.
I'm going to provide you a simple solution by disabling the effect with config "unhandledBeneficialEffects" -> "tombstone:earthly_garden".
I'll prevent this to happen in the next release but not for now, as i wait any report about theses last versions that are not the recommanded actually :)

**Comment by IchigoGames** [comment]
obtain what tho is it a enchant it was not me who crash it so i was unsure what it is

**Comment by IchigoGames** [comment]
also i looked at all 3 configs dont see anything like that

**Comment by IchigoGames** [comment]
nvm found it
