### ISSUE TITLE
Multicraft Persistant Player Count

### ISSUE THREAD

**Issue by EDFDarkAngel1** [Corail31/tombstone_lite#169]
MC Ver: 1.15.2
Forge Ver: 31.1.77

I am currently running tombstone-1.3.5-1.15.2 in both client and server.  The server is being managed through Multicraft, and there is an issue when I am looking at my player list. Although there are only 5-6 active players on the server, the player count shows over 110 entries. 

When troubleshooting it, I noticed that there are timestamps in the player name that coincide with the occasional output on the server that states something like this: "09.05 19:00:00 [Server] INFO [m[32m[15:00:00] [Server thread/INFO] [tombstone/]: The player  has successfully been saved"

If you need any additional information, please let me know.

**Comment by Corail31** [comment]
Hello, i don't see the relationship between the automatic saves done by Tombstone and what you're describing, it's a normal log when theses backup are done.
You should first desactivate theses backup in config to confirm you there're not related.
Then, you should try to localize your trouble.

**Comment by Corail31** [comment]
@EDFDarkAngel1 did you find the cause ?

**Comment by EDFDarkAngel1** [comment]
Good evening.  Sorry I haven't responded, life has been very busy.

No. I host through Shockbyte, and I had talked to them first.  They
identified it was a mod, but couldn't tell me which one.  Since you stated
that you didn't see a relationship between Tombstone and the server, I
haven't been able to find out what is causing it.

**Comment by Corail31** [comment]
Hi darkAngel, i also said you to disable the backup to compare so you could see it's not related.
The message displays late because it's coming from another thread, but it doesn't load any player... it only serializes the online players' datas and stores them, it's why i said you it's unrelated.
