### ISSUE TITLE
[1.16.5] brewing issues

### ISSUE THREAD

**Issue by DoctorMage** [Corail31/tombstone_lite#169]
### Minecraft Version

1.16.5

### Forge Version

Forge 36.2.39

### Corail Tombstone Version

 tombstone-6.8.13-1.16.5.jar

### What happened?

instant health 2 potions get turned in spectral potions instead of restoration potions
![2023-09-02_00 12 29](https://github.com/Corail31/tombstone_lite/assets/85318453/2b0a7838-6915-476c-8ec0-c82bce5cad2e)
![2023-09-02_00 13 44](https://github.com/Corail31/tombstone_lite/assets/85318453/636b6016-50f6-4c19-b9b4-07c660fb95b4)

as well as spectral potions will be constantly brewed as long as its fueled by grave dust
![2023-09-02_00 15 17](https://github.com/Corail31/tombstone_lite/assets/85318453/9beb0262-7d3c-48d0-a934-11d8e9da14e1)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi DoctorMage and thank you for reporting this issue.
This is due to backported code and the use of NBTIngredient.of(). This is fixed in dev and only affects version 1.16.5.
