### ISSUE TITLE
Please remove your DMCA attack on me so I can delete the repository

### ISSUE THREAD

**Issue by Lothrazar** [Corail31/tombstone_lite#17]
HI.

Github will not let me delete this https://github.com/Lothrazar/Tombstone
Because you have it under dispute

I assumed it was fine to have since you said it was LGPL v2.1

But i totally am willing to delete it.  Please Take back your DMCA attack so i can delete it. Thank you.

Context: https://github.com/github/dmca/blob/master/2021/03/2021-03-04-tombstone.md

**Comment by Corail31** [comment]
You already got an answer on curseForge that you could answer instead of false allegations.

**Comment by Lothrazar** [comment]
Why didnt you just ask me to delete the repo? Why attack me with DMCA

**Comment by Lothrazar** [comment]
If you remove the DMCA, i will delete it.

**Comment by Corail31** [comment]
As i said you it's not really possible to discuss with someone not understanding that restoring a mod without the consentment of the author to decompile it and make the source available is not acceptable and even if i mentioned that all the code as lGPL were available of Jared Maven with lots of comments.

**Comment by Lothrazar** [comment]
I never wanted to cause drama or hurt anyone. and for the simple-tomb i really am trying to make it totally different

**Comment by Lothrazar** [comment]
" the dmca should be removed"

Oh good, thanks for doing that.  Once github notifices me the DMCA attack is lifted i will delete it right away.  Thanks again.
