### ISSUE TITLE
[bug] Unlimited xp after death.

### ISSUE THREAD

**Issue by alxcool** [Corail31/tombstone_lite#17]
Hi! Once updating your mod, lately I've encountered a weird bug.
From : V .9.8 to v.9.9 (current I use is 9.11)

I though that by updating this mod, once again this would be solved but it din't happen. When I die, the usual penalty system from minecraft is ignored.  My "score points" print, then I re spawn at my "set spawn point" with my (max xp), like if my xp level or xp value was based on my current game's score, more than on my current or last xp pool. Then from one death to an another one, since I no longer die following the base penalty system, my score keep increasing (like if I din't die at all). My xp pool is reset based on my score (who is always increasing.), also I earn max health and max stamina.

The main problem I see with this, as example, is when I spend my xp, using an enchantment table or an anvil.

### Common info
single player minecraft 1.12.2 forge 2705
tombstone-2.9.11-1.12

### How to reproduce

A) Start a new world in creative, as you will need an enchantment table to test that bug. Then place a table with a few bookshelf, and don't forget to equip 1 weapon, a shield and a few lapis.
B) Switch gamemode to survival then start fighting mobs.
C) Earn a level 5
D) Pay away a few xp / xp level in the enchantment table on your weapon or shield. As example using an enchant who cost 4 level may set your xp pool back to level 1.
E) Find a way to die; any.
F) Respawn at level 5

Note, thk for this mod its really fun to play with! And let me know If you need more info ;)

**Comment by Corail31** [comment]
i'm gonna try to reproduce this, Alxcool :+1:

**Comment by gegy1000** [comment]
Do you have keepInventory enabled?

**Comment by Corail31** [comment]
I localized the reason, more likely how the enchant table removes levels without changing the total of xp, but i'm able to recalculate the total of xp based on the level & the bar to adapt my code to this.
So a fix soon :)

**Comment by alxcool** [comment]
Thk! wow that was fast and you'r really kind too ^^ good luck and it was a pleasure!

**Comment by Corail31** [comment]
Can you test this [version ](https://cdn.discordapp.com/attachments/346362472195686401/469322174948442113/tombstone-2.10.0-1.12.jar) to tell me if all is ok ? :)
NB : the fix is also applied to the Scroll of Knowledge

**Comment by Corail31** [comment]
Fix in 2.10.0
