### ISSUE TITLE
onCheckDiscretion uses ~10% of server time w/ astralsorcery

### ISSUE THREAD

**Issue by JoshuaRowePhantom** [Corail31/tombstone_lite#17]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Corail Tombstone Version

6.5.0

### What happened?

onCheckDiscretion uses ~10% of server time for a single player.  I suggest caching whatever information it is looking for and only rechecking periodically.  This may only be happening in concert with astralsorcery; I'm using AllTheMods.  

```
tombstone (720ms)
Server thread9.23%
ovh.corail.tombstone.event.EventHandler.onCheckDiscretion()9.23%
ovh.corail.tombstone.helper.EntityHelper.getShadowStepLevel()8.87%
net.minecraft.enchantment.EnchantmentHelper.getEnchantmentLevel()8.72%
hellfirepvp.astralsorcery.common.util.ASMHookEndpoint.getNewEnchantmentLevel()7.08%
hellfirepvp.astralsorcery.common.enchantment.dynamic.DynamicEnchantmentHelper.getNewEnchantmentLevel()7.03%
hellfirepvp.astralsorcery.common.enchantment.dynamic.DynamicEnchantmentHelper.fireEnchantmentGatheringEvent()6.51%
hellfirepvp.astralsorcery.common.enchantment.dynamic.DynamicEnchantmentHelper.canHaveDynamicEnchantment()0.36%
net.minecraft.util.ResourceLocation.tryCreate()0.87%
net.minecraft.enchantment.EnchantmentHelper.handler$zha000$getEnchantmentLevelReturn()0.51%
net.minecraft.nbt.CompoundNBT.getString()0.21%
ovh.corail.tombstone.helper.EntityHelper.getPerkLevelWithBonus()0.36%
```

See spark link.

### Log Link

https://spark.lucko.me/gx0oUElePI

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

No

### Other relevant mods

astralsorcery; allthemods

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, as you said, it's probably only related to Astral Sorcery, so in this case, why didn't you open an issue in that mod ?
My code in onCheckDiscretion is only to provide the distance an entity can be seen and is a fast code, but what happen in the forge event LivingVisibilityEvent is more related to your others mods or the code in Astral Sorcery.
So, the answer depends more if you really check this with only the 2 mods, or with a full modpack like ATM.
NB: as far as i know, Astral Sorcery uses asm on a vanilla method to provide temporary bonus of enchantments and your "server time constatations" start from this. I also have doubt about the performance of your server or the consistency of your log.

**Comment by JoshuaRowePhantom** [comment]
While astral sorcery may be the cause of onCheckDiscretion taking a long time, I do see onCheckDiscretion in the call stack of every entity AI tick.  I'll investigate the astral sorcery aspects as well, but please reconsider whether there is something to do here.  I'd look at tombstone myself... but the source code is unfortunately not available.

**Comment by JoshuaRowePhantom** [comment]
Also, simply setting "nerf_shadow_step = true" fixed my cpu issues.

**Comment by Corail31** [comment]
@JoshuaRowePhantom Listen, i don't see why i would take any consideration for a newly created github account being an expert on the same time... if you see the point, it's easy to think that you're only a troll. As i mentioned you didn't open an issue in Astral Sorcery.

**Comment by JoshuaRowePhantom** [comment]
Cool!  Thanks for your help and insults.

**Comment by Corail31** [comment]
You got the information: to open an issue in Astral Sorcery, you prefer to answer with a trolling thing, so assume !
Edit: as a precision, if i don't want to look further on my side, it's because the only thing being between the config that solves your trouble and the return from this event (due to mobs not having this enchantment) is the asm of Astral Sorcery (and only to look the enchantment level on the boots).
If theses mods adding temporary enchantment bonus would like to be really compatible, they would make theses changes directly in Forge and not with asm. The fact they use asm at this place (like Apotheosis) forces others modders to use theses methods and prevents any micro improvments about the way to read the nbt.
The config restrict_shadow_step_to_player is probably better any way to reduce theses calls.
