### ISSUE TITLE
Inventory cleared upon opening tombstone with full inventory and extra items on ground around the tombstone.

### ISSUE THREAD

**Issue by Tangosucka** [Corail31/tombstone_lite#170]
This took a while for my server to figure  out.  If you die with a full inventory and there are items on the ground around your grave when you go to retrieve your grave it gives you nothing back.    This is the mod in causing the issue we found triggering the issue.    [Culprit](https://ore.spongepowered.org/TimeTheCat/CatClearLag)
 Its some kind of compatibility I'm assuming.    Once we removed the clearlag tombstones would retrieve items correctly regardless of how much was on the ground around it.

**Comment by Corail31** [comment]
I'll first confirm you that you completely missed [how to post an issue](https://github.com/Corail31/tombstone_lite/issues/96).
what mean 'clearlag' ?
I think you're misunderstanding your trouble, and it's normal that you have no grave, you can't reproduce this incompatibility.
If you read correctly how to post an issue, you will also read that you have first to localize your troule in your combined mods.

**Comment by Tangosucka** [comment]
OK with just corail tombstone catclearlag and sponge.   If you die with a full inventory,  and their are more items on the ground around you at time of death in excess of your inventory. the grave will suck up all the extra items on the ground around the grave in addition to your inventory.   When you open your grave it will be empty, nothing extra will be dropped on ground.  there is no error or anything in the console.

**Comment by Corail31** [comment]
Are you able to reproduce this with only Tombstone ?

**Comment by Corail31** [comment]
https://github.com/Time6628/CatClearLag/issues/64

**Comment by Tangosucka** [comment]
OK with just corail tombstone catclearlag and sponge.

If you die with a full inventory, and their are more items on the ground around you at time of death in excess of your inventory the grave will suck up all the extra items on the ground around the grave in addition to your inventory.

Normally when you open your grave it would equip your gear and drop the excess on the ground around you but with catclearlag something is interfering with this process. Your grave will instead be empty, nothing extra will be dropped on ground. there is no error or anything in the console.

The catclearlag dev refuses to even acknowledge his plugin could cause an issue.

im using the most recent of all 3 mods

**Comment by Corail31** [comment]
@Tangosucka It's one of the behavior of the mod CatClearLag to [delete your items on ground](https://github.com/Time6628/CatClearLag/blob/master/src/main/java/me/time6628/clag/sponge/runnables/ItemClearer.java#L20).
If you don't like this, just ask how to configure/disable it to the modder of CatClearLag, or remove the mod if you don't achieve to disable it.
It's not something that can be changed on my side.
