### ISSUE TITLE
smithing template duplication

### ISSUE THREAD

**Issue by ambrosius42** [Corail31/tombstone_lite#170]
### Minecraft Version

1.20

### Forge Version

47.1.3

### Corail Tombstone Version

tombstone-8.5.2-1.20.1.jar

### What happened?

i expected when using a book of recycling on a smithing template for it to require 2 templates then give 1 back along with the required block and the 7 diamonds but it requires 2 templates only consumes 1 and gives 2 back along with the required block and 7 diamonds
so in the end i have now 3 smithing templates and the required block plus 7 diamonds

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Thank you for your report. This is fixed in dev (by shrinking the itemStack sooner).
