### ISSUE TITLE
Crash on world Load Version 8.5.3 [PhantomSpawnEvent]

### ISSUE THREAD

**Issue by Zelioth** [Corail31/tombstone_lite#171]
### Minecraft Version

1.20

### Forge Version

43.1.7

### Corail Tombstone Version

8.5.3-1.20.1

### What happened?

Including the mod in my pack crashed on world load with the latest version. 

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Log Link

https://gist.github.com/Zelioth/ddb00e59382d7e4d576a25fe0caf62ec

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Zelioth** [comment]
Crash doesn't happen on version 8.5.2

**Comment by Corail31** [comment]
"java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/PlayerSpawnPhantomsEvent"
This is a forge event and exists. Use a recent version of Forge.
Don't use hybrid server.
Edit: i checked Forge versions, you need 47.1.12 (Add PlayerSpawnPhantomsEvent), your version is probably incorrect as you wrote 43.0.7 (1.19.2)

**Comment by Zelioth** [comment]
I’m using Forge version 47.1.3 because of the recent forge drama tons of mods aren’t pushing support past that version. 

Forge version 47.1.3 for Minecraft version 1.20.1. 

Also this was on single player generating a world in creative mode after adding corails tombstone.

**Comment by Zelioth** [comment]
A yes I did write the wrong forge version. I apologize. I meant 47.1.3 for Minecraft version 1.20.1

**Comment by Corail31** [comment]
Hi, i can understand you on that point but, you need to update to 47.1.12 and i don't think it would cause problems with other mods.
Obviously, you can stay on your previous version too ;)
Edit: Future releases will require the forge version to avoid reports.

**Comment by Corail31** [comment]
@Zelioth @wycats0 The next version for 1.20.1 won't require 47.1.12 ;)

**Comment by wycats0** [comment]
> @Zelioth @wycats0 The next version for 1.20.1 won't require 47.1.12 ;)

Now I use Minecraft 1.20.2
