### ISSUE TITLE
Lost Tablet activating causing server to crash

### ISSUE THREAD

**Issue by 007wins** [Corail31/tombstone_lite#172]
### Minecraft Version

1.19.2

### Forge Version

42.2.14

### Corail Tombstone Version

2.5.2

### What happened?

Tombstone tablet is trying and failing to look for a structure when activating causing the server to crash.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

All the mods 8 Latest version

### Log Link

https://mclo.gs/obtGll1 

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Server Hang Watchdog means your tick has last too long and the server has stopped.
It would be hard to help you on this as it depends on all your mods. 'Spark' mod may be a way to further investigate your modpack. If you have mods disabling vanilla structures, i would recommand you to remove them/disable theses features or to disable the lost tablet (MC-250276), or to locate the exact mods allowing me to make tests.
Feel free to edit your issue to provide more precise infos.
