### ISSUE TITLE
1.15.2 Dedicated Server Shutdown Hang Up 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Corail31/tombstone_lite#172]
Hang Description
https://gist.github.com/P3rf3ctXZer0/f482c10275c746f48d6a443103f1c964

Mod Version
tombstone-4.3.7-1.15.2.jar

Forge Version
forgeVersion, 31.2.0

**Comment by Corail31** [comment]
As far as i know theses codes have been tested to work to sync properly the config on dedicated server when some players are log in.
I'll do a test with the new version of forge but you need to provide a full log and to reproduce it with only tombstone.

**Comment by P3rf3ctXZer0** [comment]
I cannot do any more deep testing until my other pc gets back which is in 2 days. I am sorry.

**Comment by Corail31** [comment]
@P3rf3ctXZer0 can you just confirm me that you weren't editing the server config file while disconnecting. If it's something that you got only once or is reproductible. And anything you have done before this happening.
As you imagine it's not exactly how to post an issue, i need to detail to have a better comprehension of the whole thing ;)

**Comment by P3rf3ctXZer0** [comment]
Okay so the only thing I changed on the server world is this /config/ 
tombstone-server.toml
https://gist.github.com/P3rf3ctXZer0/dd17b48f436a25a966a5ed0b93fe7fb1

**Comment by Corail31** [comment]
And then what happen?

**Comment by P3rf3ctXZer0** [comment]
That is all. I mean your mod has had next to no changes. I am using whatever is available. It has been happening since 1.15.2-31.1.73 - Sun May 03 20:48:25 GMT 2020

**Comment by Corail31** [comment]
If the fact to edit the config file is the reason that make your trouble, you should make sure you edit it with a [correct editor](https://github.com/Corail31/tombstone_lite/issues/163) not adding bom to the encoding (example notepad++)

**Comment by P3rf3ctXZer0** [comment]
I only changed how many seconds till a grave becomes public.

**Comment by Corail31** [comment]
@P3rf3ctXZer0 the log that you provided is not the full log, the error happened before this log.
If you don't provide the full log, i will just consider this issue as resolved.
NB : i'm also curious to know why you only paste this part if you saw an error before this, and why you mentioned the date of when it happens with forge version if your modpack is only created since 3 days with 27 downloads.

**Comment by P3rf3ctXZer0** [comment]
I will test for you more in 2 days. I told you I consider this closed for now.

**Comment by P3rf3ctXZer0** [comment]
Finally happened again. https://gist.github.com/P3rf3ctXZer0/59ff08822f82d8e659b6527a636007ef

**Comment by P3rf3ctXZer0** [comment]
This time I have provided the full log.

**Comment by Corail31** [comment]
Hi P3rf3ctXZer0,
the server stopped before the event is fired for "reloading this server config".
the best i can do is what is already applied to 1.14.4, so a check when getting the server from the logical side provide. then, the logic behind config is really forge... even if they probably don't expect someone to get the server there.

**Comment by P3rf3ctXZer0** [comment]
Okay sounds good.
