### ISSUE TITLE
LootableLoad Crash

### ISSUE THREAD

**Issue by Darkere** [Corail31/tombstone_lite#173]
latest.log https://gist.github.com/Darkere/6f2ecb21601a3bb641972f2a4fdad7bf

Error around line 1839

tombstone-4.3.3-1.14.4.jar (not the latest version but I don't see any changes to this part of the code)

**Comment by Corail31** [comment]
I don't expect this event to be called from the client side.

**Comment by Darkere** [comment]
JER needs to call this code clientside though if it wants to show lootables on the client. 

Although I find it weird that this crash only happened now. The player from whom the crash is has played on the server just fine before.

**Comment by Corail31** [comment]
Doesn't it mean its implementation is really wrong to do what he does ? it duplicate all client side ?
It won't crash in my next release but i wont support this (i'll skip it)
