### ISSUE TITLE
[1.16.5] Loot section partially deleted

### ISSUE THREAD

**Issue by DoctorMage** [Corail31/tombstone_lite#173]
### Minecraft Version

1.16.5

### Forge Version

Forge 36.2.39

### Corail Tombstone Version

 tombstone-6.8.14-1.16.5.jar

### What happened?

tombstone-6.8.14-1.16.5.jar

causes loot section of the config to be partially wiped 

before updating on version (
tombstone-6.8.12-1.16.5.jar)
![image](https://github.com/Corail31/tombstone_lite/assets/85318453/832f924c-e6cb-46d1-b0bd-1e041059aa80)

after updating 
![image](https://github.com/Corail31/tombstone_lite/assets/85318453/9449338c-515e-4c04-8f37-6ed41b246f14)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Log Link

https://gist.github.com/DoctorMage/f1d02d84976b3ff151bb526582dc35d1

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Based on changes in 6.8.13, It looks normal:
- allows to tame fox with the ankh
- _**Lootpools (related to Corail Tombstone) can be edited in your save folder in "tombstone/loottables".
They only regenerate if the file is not present, can't be read or if a new version requires an overwrite (creating a bak file of your previous lootpool)**_
- new item Potion of Restoration
- enchantment Shadowstep is removed (perk Shadow Walker & potion of Discretion are enough)
- new feet enchantment 'Spectral Bite'
- Ghostly Shape keeps hunger bar to maximum
- prevents to find Familiar Receptacle with 'mounted undead'
- prevents to use exorcism with bad alignment
- displays magic circle over snow layer
- remove fishing marker (and client config) as it uses the same vanilla condition for open water
- **_removes multiple configs related to loot chance_**

**Comment by DoctorMage** [comment]
hmm regarding the loot table ones if none are created

after updating to tombstone-6.8.14-1.16.5.jar
![image](https://github.com/Corail31/tombstone_lite/assets/85318453/e280d640-ddbb-49e0-91f3-06581fc53c96)

would placing them in a paxi folder work just same format paxi/tombstone/loottables
?

this is for a mod pack by itself it seems fine
realised it was tombstone-6.8.13-1.16.5.jar but even after updating to tombstone-6.8.14-1.16.5.jar

![image](https://github.com/Corail31/tombstone_lite/assets/85318453/c945c5ff-d0b2-43aa-97e6-68c32d1d04f8)

**Comment by Corail31** [comment]
Hi DoctorMage,
The files are created when the world is loaded (i checked them to be created with latest version).
The change is mainly to let players change the loots easily.
For modpacks, the files need to be in the save (but you can generate them in singleplayer). I don't make modpacks, so I don't know what your options are for doing so.
Edit: what are normally the changes that you want for your modpack (with the old configs) ?

**Comment by Corail31** [comment]
@DoctorMage What are normally the changes that you want for your modpack (with the old configs) ?
If you can explain what you can do as a modpacker to have some files on the server, i could look to adapt my code to look if the loottable files are not elsewhere.

**Comment by DoctorMage** [comment]
Datapacks intergration would be helpful especially if it works with a mod like paxi

makes it easier to edit and configure

**Comment by Corail31** [comment]
Yes, but it's not how i inject them as the objective is to let players edit them too (as i'm not sure players really use datapack...).
It could be in the config or anywhere else.
