### ISSUE TITLE
Crash when used with Immersive Portals [Fabric] on a forge/sinytra-connector pack

### ISSUE THREAD

**Issue by Xplodin** [Corail31/tombstone_lite#174]
### Minecraft Version

1.20

### Forge Version

47.1.3

### Corail Tombstone Version

8.5.2

### What happened?

https://github.com/Sinytra/Connector/issues/186#issuecomment-1722564904

this mod conflicts with immersive portals due to same redirector mixin target

The mods work fine if one is removed, but having both causes a pretty harsh crash

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Sinytra Connector, Forgified Fabric API, Corials tombstone, and Immersive Portals [Fabric]

### Log Link

https://github.com/Sinytra/Connector/issues/186#issuecomment-1722564904

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, the mixin exists for compatibility with Oculus (Iris) and custom shaders (that was already a long story).
When the Tombstone shader for smoke particles will work when Oculus is present (with an optifine shader active), i could remove this mixin.

**Comment by Xplodin** [comment]
Gotcha, I think. Its either support oculus and shaders (personally the better option) or support immersive portals
Unless oculus works with tombstone out of the box without extra compat. 
I like all three mods and having all three work without removing compat for one would be killer.

**Comment by Corail31** [comment]
@Xplodin I'll keep this issue in mind, but i know i won't look for a solution for now. You can still contact the other mod.

**Comment by Corail31** [comment]
@Xplodin may you test with the new version ?

**Comment by Xplodin** [comment]
> @Xplodin may you test with the new version ?

Doesnt crash on boot so I think its good!
Will load in sp and test further

**Comment by Corail31** [comment]
Neat, if you use iris/oculus(with an optifine shader active)+sinytra connector+immersive portals, you might not be able to see some particles like smoke, but i guess it's a minor trouble as my mixin will disable if another mod is using the same (like 'immersive portals' does) ;)

**Comment by Xplodin** [comment]
Hi Corial, I started getting a mixin crash relating to this issue again

with tombstone 8.8.4 and immersive portals + miniscaled

Critical injection failure: Redirector methodCompileShaderInternal(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String; in tombstone.mixins.json:ProgramMixin from mod tombstone failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.tombstone.refmap.json
[debug.log](https://github.com/user-attachments/files/17892843/debug.log)
Here is the full debug just incase
