### ISSUE TITLE
Enchanted Tablet of Cupidity causing corrupted player data

### ISSUE THREAD

**Issue by Whyett78** [Corail31/tombstone_lite#174]
While playing on a server on the 1.15.2 Plunger modpack he found that when he used an enchanted Tablet of Cupidity it caused a ticking issue, on the server it caused his player data to get corrupted. we then tested it on a single player world and it causes the same issue.

**Comment by Corail31** [comment]
If you want to post an issue, you need to follow the topic [how to post an issue](https://github.com/Corail31/tombstone_lite/issues/96).
This means to be able to reproduce it with only tombstone, or to localize the incompatibility, but what i can say you : this tablet only teleports you and give you a bad effect. There's nothing ticking.
You should also bring a log if you really got something corrupted, right ? or i should just trust your deductions from your newly created github account ?

**Comment by Corail31** [comment]
Feel free to edit your topic to provide the required informations if you want additional support.
