### ISSUE TITLE
Rough Mobs Revamped - Tombstone Comp. Issue. Certain types of deaths don't create Tombstones.

### ISSUE THREAD

**Issue by Tippy2** [Corail31/tombstone_lite#175]
Rough Mobs Revamped Creates "Boss Mobs" Which Emit a fog, when players die by the fog, there is no Tombstone created. Tested by dying a few times to the fog.

Running server 1.12.2 - 

Forge - 14.23.5.2854
Corail Tombstone | Corail_31 | tombstone-3.7.4-1.12.2
Rough Mobs Revamped | p1ut0nium_94 | roughmobsrevamped-1.12.2-2.3.16

I was losing items all the time when I died, and couldn't figure out why, then I just started dying by everything until I died by the fog and didn't get a Tombstone. I'm not sure if only certain types of deaths trigger a Tombstone or what issue would cause this.

**Comment by Corail31** [comment]
Can you just test with only "Rough Mobs Revamped" (so not with tombstone) :
- /summon roughmobsrevamped:bossskeleton
- die with some items on you
Looks if the drops are there : if not you can open an issue in this mod.

**Comment by Tippy2** [comment]
I didn't drop any items, thank you for the idea. I'll continue my search.
