### ISSUE TITLE
Loot Chance Error 1.19.2

### ISSUE THREAD

**Issue by Peasmith** [Corail31/tombstone_lite#175]
### Minecraft Version

1.19.2

### Forge Version

43.2.0+

### Corail Tombstone Version

8.2.11

### What happened?

Hi I want to remove the items on my inventory when Im dead, on my server. I modified the 2 variants on the corail tombstone mod, 
    chance_loss_on_death = 100
    percent_loss_on_death = 100
But my items They are still in my inventory. 
I restart the server but it still doesn't work, I have set it to 100% probability and I recover the inventory. I have restarted the server and nothing. Is there any other way?
I think its bugged, But I read on the changelog of the Mod, That configuration has been removed, is there any other option to configure the option to lose items? Or there are no more options. Because my configuration files keep showing me the old options.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Moderation is set for one month. Questions are on CurseForge. Only some items are losable by this way (stackable).
