### ISSUE TITLE
Fix Corail Tombstone xp

### ISSUE THREAD

**Issue by Danny210601** [Corail31/tombstone_lite#176]
Well, the situation is that on my server we have the mod, as you know, it brings a function that, when dying, leaves a grave, and on top of that it leaves a certain amount of experience, fully configurable, if I want to die lose 70% experience , 50%, etc. What happens is that it doesn't work, the whole mod is fine but only this function doesn't work for me, I put the experience loss at 0% and they still lose all levels. Would there be a way to indicate a mod support or any errors that may be in the settings? Minecraft 1.12.2

**Comment by Corail31** [comment]
Hi, on server, you don't define your xp lost yourself, it's the server that defines theses options and you can only modify them on the server folder config.
Then, if it doesn't work, this doesn't change that you need to follow the steps ask in the topic how to post issues : be able to reproduce it with only Tombstone, or to localize the mods doing something wrong.

**Comment by Danny210601** [comment]
I clearly don't change it in my files. I think it is logical that I change the .cfg file on the server, where the mod is. You have already modified the server's cfg thousands of times and it doesn't work.

**Comment by Corail31** [comment]
Hi Danny,
if you are not able to reproduce it with only Tombstone, it means it's an incompatibility or a bug in another mod.
It's why i said you to first test this, as explained in the topic related to [how to post an issue](https://github.com/Corail31/tombstone_lite/issues/96), if it's not reproductible with only my mod, you will need to localize the incompatible mod.
Then, i also mentioned : "3.7.4 also has a code helping in compatibility with others mods about the clone event".
NB : for me, you read partially my previous answer.
