### ISSUE TITLE
Crash report [Forge version]

### ISSUE THREAD

**Issue by wycats0** [Corail31/tombstone_lite#176]
### Minecraft Version

1.20

### Forge Version

47.1.3

### Corail Tombstone Version

tombstone-8.5.3-1.20.1

### What happened?

The game will crash when I open or create a world, the crash will occur when you use Corail Tombstone with this list of mods:
Sinytra Connector
Alex' Mobs
Architectury
Better Villages
Biome's O Plenty
Citadel
Cloth Config
Crash Utilities
Forgified Fabric API
Falling Tree
FPS Reducer
Game Menu Mod Option
Identity
Inventory Porifle Next
Just Enough Items
Kotlin for Forge
libIPN
Library Ferret
Log Begone
Lost Cities
Comes Alive
MineMenu
Mo Villagers
Not Enough Crashes
Rubidium
TerraBlender
The One Probe
[crash-2023-09-22_21.32.06-client.txt](https://github.com/Corail31/tombstone_lite/files/12705229/crash-2023-09-22_21.32.06-client.txt)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, it's about your forge version, you need to be on Forge 47.1.12 (and don't say me that Sinytra Connector requires 47.1.3, it's not my problem; 1.20.2 is out so, they will need to update in any case).
Note that you can stay on the previous version of Corail Tombstone for now.
https://github.com/Corail31/tombstone_lite/issues/171
