### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by HeberonYT** [Corail31/tombstone_lite#177]
When a player dies I get this error on the console.
Only occurs when a player spawns a Tombstone mod grave. If the player is only injured and is revived by another player, then his grave is not spawned and the error does not occur.

CreativeCore_v1.10.16_mc1.12.2.jar
tombstone-3.7.4-1.12.2.jar

https://pastebin.com/raw/cMCzwjEY
https://pastebin.com/raw/AKmj39gG

**Comment by Corail31** [comment]
Probably, something to fix on their side, but it will let the issue visible ;)

**Comment by Corail31** [comment]
@HeberonYT I made additional tests about this, and it works correctly if you're in an enough version of forge (keeps in mind that players should always be in the latest or around latest)
For me, all is working and this is not reproductible.
If you have still this trouble, you'll need to localize exactly the mod doing an incorrect interaction.

**Comment by Corail31** [comment]
https://github.com/CreativeMD/CreativeCore/issues/79
