### ISSUE TITLE
Curse of Bones causes server crash via CME in GoalSelector

### ISSUE THREAD

**Issue by Geolykt** [Corail31/tombstone_lite#179]
### Minecraft Version

1.19.2

### Forge Version

43.2.23

### Corail Tombstone Version

8.2.11-1.19.2

### What happened?

Fighting against (read: Standing idly while being attacked by) a horde of wither skeletons will inevitably cause a CME (ConcurrentModificationException). The issue could only be reproduced once the Curse of Bones enchantment was applied to the chestplate.

The attached crash report was made possible using a custom mod that would transform GoalSelector#tickRunningGoals - hence in the attached report there is no CME, but rather an UnsupportedOperationException as I wrapped the availableGoals field in an unmodifiableSet while the method was called, which revealed Corail Tombstones to be the only possible cause (even though the Curse of Bones thing was already a pretty good indicator).

The crash occurs while ticking `net/minecraft/world/entity/monster/AbstractSkeleton$1`

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Quark

### Log Link

https://gist.github.com/Geolykt/fbf0a0b7504b6ef0adb57bdc81d1ea58

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You didn't follow the 'issue form' that asks to not add tons of mods using tons of mixin to make your tests.
Closed until you bring a real log showing what your think without other mod.
Note that my code only call entity.hurt() after checking it to not be null.
```
at net.minecraft.world.entity.ai.goal.GoalSelector.m_25363_(GoalSelector.java:57) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:GoalSelectorAccessor,pl:mixin:APP:**mixins.geolyfix.json:GoalSelectorMixins,pl:mixin:A**}
```

**Comment by Geolykt** [comment]
Completely useless crash report that you somehow need anyways: <https://gist.github.com/Geolykt/941ece59005eb677fc9202890540e16f>

not reproducible without other mods because you are modifing the last value in the iterator hence with JUST this mod it is not reproducible - however that still does not mean that quark is at fault even though it only happens with quark installed [I wasn't able to find any other mod that adds another goal to the goal selector hence Quark]

**Comment by Corail31** [comment]
So, you have made a mod to find the origin of a CME in a world of mixins ?
Try spark mod that is probably more intended for this purpose. There's a good reason why i ask to locate the problem in your mods first. I'm not here to debug others mods.

**Comment by Geolykt** [comment]
Spark is not a debugger - certainly not a debugger capable of detecting concurrent modifcations at that. It's a profiler.
Without a custom mod I'd be here without the UnsupportedOperationException and you'd able to plausibly be able to deny any involvement in the crash.

**Comment by Corail31** [comment]
I'm not sure if you're looking for a solution for something and this place is for this purpose.
The only particularity of the Curse of Bones is when BoneShield is active, the damages are 'thorns' (and it doesn't reflect thorns damages).
My mod doesn't specially edit goals... so i therefore prefer to lock this issue and leave you to your convictions.
Edit: Thanks to have opened an issue in Quark, i unlock the issue as you are really looking for a solution.
