### ISSUE TITLE
[1.17.1] Advancement triggering saying I didn't use a key, when I actually did.

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/tombstone_lite#18]
### Minecraft Version

1.17.1

### Forge Version

forge-1.17.1-37.0.78

### Corail Tombstone Version

tombstone-1.17-7.1.2

### What happened?

![image](https://user-images.githubusercontent.com/4427684/135774579-0004b06f-2e2c-44a0-b01b-dedae40c2f9a.png)

I got this when I used a key on my grave.

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@ProsperCraft may you edit your title and tombstone versions to fit the description ?
I don't think it's possible to make this happening, except if you got that key in an old tombstone version (7.0.2-).

**Comment by ProsperCraft** [comment]
Brand new world with the latest version of tombstone.

I may have been in creative if that makes a difference.

**Comment by Corail31** [comment]
@ProsperCraft The only possibility for this is if your uuid changed (and you mentioned you loaded in a valid launcher).
Except if you succeed to produce this again, i don't think this advancement can trigger incorrectly.
