### ISSUE TITLE
Auto-equip Wearablebackpacks on Grave click

### ISSUE THREAD

**Issue by Boymann** [Corail31/tombstone_lite#18]
Would it be possible for wearablebackpacks to keep their contents and get picked up when we interact with tombstones from CorailTombstone?
https://github.com/copygirl/WearableBackpacks/issues/68

**Comment by Corail31** [comment]
Last time , i talk with copygirl, we agree that it was better to not fill the grave with the backpack (because the backpacks store lots of things too)
But equiping the backpack when clicking the grave could be possible indeed.

**Comment by Corail31** [comment]
I got the infos from CopyGirl to make the "grave click" reequips the backpack.
I'll add this feature in a coming release.

**Comment by Boymann** [comment]
So, this will equip the backpack dropped next to the grave with opening the grave?

**Comment by Corail31** [comment]
yes, it's what is expected ;)

**Comment by Boymann** [comment]
woah, you just do code magic everywhere

**Comment by Corail31** [comment]
it's not magic :) wearable backpacks don't remember their owner, but always appears near the player death and have a data about their time since they are put on the ground :+1:

**Comment by Corail31** [comment]
@Boymann is it enough to put the backpacks near the grave, if they're too far away ?
(because i don't want to save datas about the backpacks)
NB : i'll handle the auto-equip backpack when the backpack could provide an owner.
