### ISSUE TITLE
[2.10.0] Compat issue with AetherLegacy 3.1

### ISSUE THREAD

**Issue by Rikshy** [Corail31/tombstone_lite#18]
https://paste.dimdev.org/azuyuficol.mccrash

i keep on dieing, cant go to creative -> get stuck (until relog) and can't open my grave.

`B:allow_aether_legacy_autoEquip=false`

fixed the issue

**Comment by Corail31** [comment]
they probably changed their api, i'll look their code, and yes, you can desactivate it in config.

**Comment by Corail31** [comment]
I got some infos from Kino, they'll release a new version that won't crash anymore.
