### ISSUE TITLE
Crash with phantomspawnevent

### ISSUE THREAD

**Issue by Xplodin** [Corail31/tombstone_lite#180]
### Minecraft Version

1.20

### Forge Version

47.1.3

### Corail Tombstone Version

8.5.4

### What happened?

once it hit night in-game I crashed

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Sinytra Connector, Forgified Fabric API, Corials tombstone, and Immersive Portals [Fabric], more

### Log Link

https://gist.github.com/Xplodin/3a7f0ab034873ac6d891fb92ddcff2a7

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
If you can try with forge 47.1.12, it should be ok (as it's related to a forge event not be present in all versions of forge). It seems i didn't do my compat with forge correctly, i will check tomorrow.

**Comment by Xplodin** [comment]
I would try but id just crash countless times due to mods requiring 47.1.3. Ill give it a shot in a empty instance rq
47.1.12 works with only corails

**Comment by Corail31** [comment]
@Xplodin It was probably a 'class load' due to import, a new version is awaiting you for new test ;)
