### ISSUE TITLE
ClassCastException after zombifying a villager

### ISSUE THREAD

**Issue by leagris** [Corail31/tombstone_lite#181]
### Forge Version

47.1.3

### Corail Tombstone Version

8.5.2

### What happened?

Withe alignment < -1, zombifying a villager causes `ClassCastException` crash as it attempts an invalid cast of a `net.minecraft.client.multiplayer.ClientChunkCache` into a `net.minecraft.server.level.ServerChunkCache`

Can be reproduced in single player. Not tested in multiplayer.

```none
java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientChunkCache cannot be cast to class net.minecraft.server.level.ServerChunkCache
```

- [crash-2023-10-09_19.08.56-server.txt](https://gist.github.com/leagris/a58f240d4cd6cc2c8e375039d3d5e4e1)
- [crash-2023-10-10_19.46.50-server.txt ](https://gist.github.com/leagris/acdc47e3000b751a1aa68420adc5305c)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Log Link

https://gist.github.com/leagris/acdc47e3000b751a1aa68420adc5305c

**Comment by Corail31** [comment]
Hi Leagris, i'll check on Friday.

**Comment by Corail31** [comment]
@leagris You used the form for 1.20.2 beta (and i didn't notice so i tested that version to have no trouble like your issue on server with Forge). So, there's no reason for it to happen in 1.20.1. If you're not using Forge, first test with Forge, or try to reduce your mod list (or make yourself the test with only Corail Tombstone on server).
Note that latest version is 8.5.5 on 1.20.1.
