### ISSUE TITLE
Not auto equiping gear after death

### ISSUE THREAD

**Issue by Guineapigboyx** [Corail31/tombstone_lite#182]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Corail Tombstone Version

6.8.14

### What happened?

When I collect the tombstone that spawns after death, it will not auto-equip my gear or any curio slots I previously had.

Also, I have the setting for it in the config set to always. I also tried other configs like grave recovery, but it still seemed broken.

It did work in older versions not too sure which version broke it but I just know it is one of the newer ones that it started being broken in.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [x] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
The form asks you to locate your problem. As you're not able to make it happening with only Corail Tombstone, i can't help you due to lack of informations. Commands are also working and have no reason to not work... as they're a different thing from graves.
