### ISSUE TITLE
Crash 1.20.1 [Eidolon]

### ISSUE THREAD

**Issue by castilio20** [Corail31/tombstone_lite#183]
### Minecraft Version

1.20.1

### Forge Version

neo 47.1.79

### Corail Tombstone Version

8.5.5

### What happened?

The games crash and i am not sure if it bc of corail 100% but it mentions in the log
[latest.log](https://github.com/Corail31/tombstone_lite/files/13043030/latest.log)
didnt find a site that can handle a log of 6mb

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Corail Tombstone is a Forge mod. This means that you have to do your tests on Forge (and if there's a difference with "NeoForge", to report to them ~like for Mohist & Magma). You didn't follow the issue template to locate your problem (instead of bringing a report with multiple mods), so closed.

**Comment by castilio20** [comment]
1 sorry i though that was for sever plugins my bad
2 i did test it with forge and it stil crash the game
3 without you mod it doesnt crash so it a conflict
and i did find the issue eventualy with the help from a smart person https://github.com/Alexthw46/Eidolon-Repraised/blob/1.19.2/src/main/java/elucent/eidolon/mixin/LivingEntityMixin.java

**Comment by Corail31** [comment]
@castilio20 Hi! Thanks for locating your issue, i'll do some tests with the other mod. It remembers me an older issue. Can you open an issue in the other mod ?
https://github.com/Corail31/tombstone_lite/issues/112
https://github.com/Corail31/tombstone_lite/issues/129

**Comment by Corail31** [comment]
I guess it's solved in their new version, no ? https://github.com/Alexthw46/Eidolon-Repraised/issues/9

**Comment by castilio20** [comment]
yep that is the new ver (and that is the  issue) and the fix is already out and it working
