### ISSUE TITLE
"Mysterious Package" dissapeared. 

### ISSUE THREAD

**Issue by MattRidge** [Corail31/tombstone_lite#186]
### Minecraft Version

1.20.1

### Forge Version

42.2.8

### Corail Tombstone Version

8.5.5

### What happened?

I quit the game last night, and I logged back in and my "Mysterious package" is gone.  It was in my backpack.  Is there a way to recover it? 

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I'll probably extend Christmas event period, and make some adequate changes. Thanks for the report.
Edit: there's no "mysterious package" in Tombstone, maybe it's about Villager Gift or Christmas Gift. An update will bring Easter event to get similar rewars in the future.
If it's about Christmas Gift, the gift disappeared after Christmas if you didn't enchant it to get the reward. You can manually get the rewards with command /give for an Essence of Undeath and a Merchant Stone, the command /tbknowledge for 10 points and the command /xp to get 1000 xp.
