### ISSUE TITLE
1.20.1 Grave not spawning on death

### ISSUE THREAD

**Issue by RiscmonIngk** [Corail31/tombstone_lite#187]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Corail Tombstone Version

8.5.5

### What happened?

On death, A grave does not spawn. Tbrecovery works perfectly fine.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Hardcore Revival

### Log Link

https://pastebin.com/g3CyyJiV

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Are you in hardcore mode ? :p
