### ISSUE TITLE
Scroll drops from some modded blocks

### ISSUE THREAD

**Issue by loving2** [Corail31/tombstone_lite#188]
### Minecraft Version

1.20.1

### Forge Version

47.2.16

### Corail Tombstone Version

tombstone-8.5.5-1.20.1

### What happened?

Breaking Demon Stone (bloodmagic:dungeon_stone) and Demonite (bloodmagic:dungeon_ore) is resulting in scrolls and tablets and familiar stones to drop. This seems to be infinitely farmable with the Demon Stone because it always drops itself. Not sure what other blocks this may be happening with, if any.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

bloodmagic

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, some loots are added to loottables based on name, I will have to prevent loots from this loottable ;)
Bloodmagic loottables won't be accepted for additional chest loots in the future.
