### ISSUE TITLE
Dying in/under water causes the graves to spawn in a cave under the water

### ISSUE THREAD

**Issue by Boymann** [Corail31/tombstone_lite#19]
Happened twice to one of my friends.
Version 2.3.0
Forge: 2568

**Comment by Corail31** [comment]
That's indeed how the mod works :)
If there's a underground cave, it's normal

**Comment by Boymann** [comment]
Well, it caused a lot of frustration, because the water was so deep, they couldn't get to the grave without spending a lot of time on potions or some water-breathing gear

**Comment by Corail31** [comment]
But, you have a grave's key upgrade to teleport ?

**Comment by Corail31** [comment]
btw, there's also a command when you don't want to go to your grave,
/TBRestoreInventory <name>

**Comment by Boymann** [comment]
We didn't have ender pearls to craft it. So I immediately though it was a bug of some sorts, and thought I'd report it. We're trying to use as few cheaty things as possible.

**Comment by Corail31** [comment]
for teleporting :
- All commands are fully safe (no way to be stucked)
- the grave first choose a valid position for teleporting, with a ground under the grave, and returns a less safe position if not found in the current chunk (i don't go on others chunks)
- the grave's key and tablet of recall used the last know safe position and doesn't check if it has changed (but i know i can improve it)

**Comment by Boymann** [comment]
Alright, thank you. We'll stock up on ender pearls now I guess :D

**Comment by Corail31** [comment]
for me, the commands is not a cheat, it's a tool when you need them ;)
NB : are the graves so hard to produce on start with the quest line?

**Comment by Boymann** [comment]
Well, in my opinion when tools are too convenient you'll forget about the actual cool features :D 

Quest line?

**Comment by Corail31** [comment]
The advancements allow you to get nearly your first decorative grave. (you probably need to drop grave's dust from undead to complete the recipe)
And when decorative graves have grave's soul (appear randomly while thundering), you can use them to upgrade the grave's key and others magic items.

**Comment by Boymann** [comment]
Ah, we didn't get there yet. They are busy building, and I'm just tweaking and working on the server while studying for now.

**Comment by Corail31** [comment]
Any way, i'll add a short line in the spawner to not try to look for grave's placement, until the initialPos is no more in water, and not looking down in this case too.

**Comment by Corail31** [comment]
Fix in 2.3.1
