### ISSUE TITLE
Dedicated server locks up hard on load.

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/tombstone_lite#19]
### Minecraft Version

1.17.1

### Forge Version

1.17.1 - 37.0.90

### Corail Tombstone Version

tombstone-1.17.1-7.2.1

### What happened?

Server hard lock on load, 

Log has this in it.

[16:46:00] [Server thread/ERROR]: A BlockEntity type ovh.corail.tombstone.tileentity.BlockEntityDecorativeGrave has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.RuntimeException: class ovh.corail.tombstone.tileentity.BlockEntityDecorativeGrave is missing a mapping! This is a bug!

Killing the server, next load it loaded without a problem.

### Log Link

https://gist.github.com/ProsperCraft/1ee6e05bab45266947b9c29459a03b80

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

No

### Other relevant mods

TownCraft THREE for 1.17.1

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Your issue doesn't respect the template (by avoiding to list 5 mods at max).
As i didn't update the mod: if you have a trouble related to a modpack, and if it's not related to the fact of being on the latest forge versions, you'll need to localize how to make this happens.
