### ISSUE TITLE
Faster sneaking

### ISSUE THREAD

**Issue by ghost** [Corail31/tombstone_lite#190]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Corail Tombstone Version

8.5.5

### What happened?

When u crouch u go faster than u do in vanilla.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's related to your perks, it's a normal behavior.
Note that someone asked me to add a config to disable the related perk, so it would be disableable in the future ;)
