### ISSUE TITLE
Familiar Receptacle Summon crashes server

### ISSUE THREAD

**Issue by sourachath** [Corail31/tombstone_lite#191]
### Minecraft Version

1.20.1

### Forge Version

42.2.16

### Corail Tombstone Version

8.5.5

### What happened?

Used an Ankh with a Familiar Receptacle to summon a mob and it crashed the server.

Was in a loaded FTB Teams chunk, if that matters.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

ATM9

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
What is needed is explained in the form for issues. If you don't have time to locate your problem, i won't have too.
Please edit your issue with relevant informations, it's probably related to one of your mod, the log is also needed if you have a crash...
Feel free to edit your issue.
