### ISSUE TITLE
I cannot tp to my grave using the enchanted key

### ISSUE THREAD

**Issue by ESOJM3** [Corail31/tombstone_lite#192]
### Minecraft Version

1.20.1

### Forge Version

forge-47.2.0

### Corail Tombstone Version

1.20.1

### What happened?

When I die and I have the enchanted key that's supposed to tp to the grave, it doesn't.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Please bring enough informations to help you. The form is done in a way that you have to limit the number of your mods to find the one making your issue.
Make sure your key is really enchanted and not a created one with command /give without the coordinates.
Note that the actual supported version of Forge for 1.20.1 is not 47.2.0 and is intended (try with 8.5.4 for 47.2.0).
Feel free to edit your issue.
