### ISSUE TITLE
Permanent Slow Fall Bug

### ISSUE THREAD

**Issue by scribe-of-days** [Corail31/tombstone_lite#193]
### Minecraft Version

1.20.1

### Forge Version

47.2.17

### Corail Tombstone Version

8.5.5-1.20.1

### What happened?

If I log out of the game in creative mode, it seems that when I load back in I will not be able to fly any longer, and instead will drift slowly to the ground. A permanent 0:00 slow fall effect is visible beside my character portrait and cannot be removed by changing game modes back to survival, drinking milk, or removing the effect with commands (the game does not register that slow fall is actually being applied as an effect to the player). The only way I've been able to remove the effect is to change my game mode to survival and log out, then back in again, which clears it.

I don't know for sure that this is Corail Tombstone causing this but it's the only mod I have in my pack that purposefully adds a slow fall effect through gameplay (usually after death), so I thought I'd start trying to track it down here. Because there isn't a crash associated I don't have a log to provide.

I tested it by using only your mod in singleplayer and was unable to replicate the effect, so it might be caused by the mod being used on a server, or by several mods acting in conjunction to cause this to happen.

Thanks!

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, the first thing I would recommend is to test your bug without Tombstone on a server with your modpack.
What I can tell you at the moment is that the slow fall effect (FeatherFall) is not the same as Vanilla (as well as Ghostly Shape which uses the same logic as FeatherFall) : it doesn't use FallFlying logic and the related ShareFlag 7.
