### ISSUE TITLE
[1.18.2 Crash] Tombstone and Ice and Fire Cockatrice Constant Crash

### ISSUE THREAD

**Issue by itsdinkd** [Corail31/tombstone_lite#194]
### Minecraft Version

1.19.2

### Forge Version

40.2.8

### Corail Tombstone Version

7.6.6

### What happened?

A Cockatrice from ice and fire is causing constinously crashing upon a dedicated server start most likely due to this entity being in loaded chunk.

I reported this to Ice and Fire and they told me to report to you as this is most likely a Tombstone issue 
(https://github.com/AlexModGuy/Ice_and_Fire/issues/5078) 

**Player said this is what happened before it crashed:**
```
A fully grown cockatrice from ice and fire was glitched in the ground.
It was digged out and I started to kill it.
Then server crashed and there said something in the chat about "tickingentity".
The server kept crashing when started, most likely because the entity was constantly loaded with the chunkload.
```

**MC Version is actually 1.18.2**

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Log Link

https://mclo.gs/w4COii6

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
What is your real mc version... because you put 1.19.2 and then MC 1.18.2, and on alex issues you put 1.16.5?
You didn't reduce your mod list to locate your issue like it's asked on the issue form.
You have better chance to report to lucky perms.
```me.lucko.luckperms.forge.listeners.ForgeConnectionListener.onPlayerLoadFromFile(ForgeConnectionListener.java:138)```
Note that there's nothing in my mixin before this line that can conflict with the other mod ;)

**Comment by itsdinkd** [comment]
As I wrote in the post, mc version is 1.18.2, there is no option to select 1.18.2 in your drop down in your bug template. **I recommend you add that if you are going to criticize the way I had to mention the version.** 

![Screenshot_20240114_121325_Firefox](https://github.com/Corail31/tombstone_lite/assets/35115304/40711d46-f1c8-40ab-acc5-cec3e822f39a)

No I did not test alone as I have no way to reproduce this. Please explain how I can have a mob spawn naturally stuck in the ground. 

What you put from Luck perms is a wrapper that is only a listener. It is not luckperms.

I love run arounds.

**Comment by itsdinkd** [comment]
>You didn't reduce your mod list to locate your issue like it's asked on the issue form.

Your template mentions "testing with **only** corails (required)" to which I selected no, as this is not a singular issue with just corails. It does not mention reducing mod list, like you said to follow.

Highly suggest you update your template with your expectations rather than pretending they're there while being a patronizing asshole about it, calling people out on what you think exists on said template.

You can delete this now as I'll be deleting your mod from my pack.
