### ISSUE TITLE
Knowledge of Death: Slow Experience Gain

### ISSUE THREAD

**Issue by LegoNoah123** [Corail31/tombstone_lite#195]
### Minecraft Version

1.18.2

### Forge Version

40.2.17

### Corail Tombstone Version

7.6.6

### What happened?

I've been noticing an issue when playing on a server (1.18.2) that my Knowledge of Death experience bar seems to be increasing incredibly slowly, even when using the Ankh of Pray. I've been stuck at level 7 for the Knowledge of Death feature and using the Ankh of Pray only increases the experience bar by an incredibly minuscule amount. I couldn't find anything in the config to change how much experience is gained when using the Ankh of Prey so I am assuming that there is an issue. I'll include a list of the mods being used, could you please help me figure out why my experience is increasing so slowly or what kind of workarounds I can use? Thank you. 

Edit Corail31: mod list screenshots removed as it's not necessary for answering you.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

N/A

### Log Link

N/A

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, the perk tree is simply done to be slow. You can focus on advancements to get enough points to be around lvl 20.
The Ankh can rarely be used, you have better chance to enchant items with souls over tombs.
The first essence of undeath is found by only choosing your favorite grave in the config in game (to get your first decorative grave).
It's possible anyway to change the Ankh's cooldown/soul chance & time in config.
Note that i always answer to questions on my mod page, even for version no longer supported.
