### ISSUE TITLE
plague bringer issue

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [Corail31/tombstone_lite#196]
### Minecraft Version

1.20.1

### Forge Version

47.2.4

### Corail Tombstone Version

8.5.5

### What happened?

![2024-01-18_20 01 50](https://github.com/Corail31/tombstone_lite/assets/115895321/25740f06-3ea6-4be9-960a-89e88760c5e4) gives the user bad effects too

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's how Plague Bringer works for players not having a bad alignment. It's a cursed enchantment for them.
Out of curiosity, what is the mod adding a life bar ?

**Comment by SonicTheHedgehog58987276** [comment]
the healthbar mod: health indicator txf
