### ISSUE TITLE
1.20.1; 8.6.0; Xp loss after dying

### ISSUE THREAD

**Issue by Wizqok** [Corail31/tombstone_lite#198]
### Minecraft Version

1.20.1

### Forge Version

47.2.19

### Corail Tombstone Version

8.6.0

### What happened?

After dying, the experience ist completely gone. Also the tombstone experience skill ist set to 

0% on Level 0 instead of 50%.
10% on Level 1  instead of 60%
and so on

This happens in SMP and SSP.

Downgrading to 8.5.6 solving the problem. Xp are saved proportionally like always

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Before 8.6.0, the "memento mori" perk was at 50% due to another config (and its default) to set the minimum xp retained upon death. The perk's max level was also adjusted based on the left points to get 100%.
In 8.6.0, the config was removed and another config was added to always keep xp on death.
Feel free to give your opinion about the changes in 8.6.0 (there's a changelog).

**Comment by SoundChaos** [comment]
> Before 8.6.0, the "memento mori" perk was at 50% due to another config (and its default) to set the minimum xp retained upon death. The perk's max level was also adjusted based on the left points to get 100%. In 8.6.0, the config was removed and another config was added to always keep xp on death. Feel free to give your opinion about the changes in 8.6.0 (there's a changelog).

I tested this the same as original issue in single player and server. The perk still doesn't seem to work as it should.
Default config, with keep exp false, there is 100% loss of exp on death.
Raising the perk from lvl 1-9 does not change this behavior and still results in 100% loss, but upon leveling to 10, 100% of exp is returned when you activate the grave.

**Comment by Corail31** [comment]
Thanks you @SoundChaos for your feedback, i'll check.

**Comment by Wizqok** [comment]
Thanks for clarification @Corail31 
Exactly like @SoundChaos described, i was wondering why i lost all xp although i spent 3 points in the perk.

If its works like intended it would be ok, but i think 0% as starting point is bit hard, maybe 10-30% would be good or like vanilla.
Why we cant have still xp_loss for ppl who wants to set starting point themselves.

**Comment by Corail31** [comment]
@Wizqok because i would like to reduce the number of points max around 5 instead of 10 (like in the past), so i made a few changes already ;)

**Comment by Corail31** [comment]
@Wizqok @SoundChaos Fixed in 8.6.1
