### ISSUE TITLE
Can't use Prayer of Protection on villagers after reaching tier 3 good alignment

### ISSUE THREAD

**Issue by Falkenei** [Corail31/tombstone_lite#199]
### Minecraft Version

1.20.1

### Forge Version

47+

### Corail Tombstone Version

1.20.1-8.6.1.jar

### What happened?

If I try to Pray for Protection for a villager after unlocking Pray of Empathy  I can only use the prayer of Empathy/Harmonization, so denoted by the lack of little shields and the text message in the chat(" Your prayer has appeased the creature that seems determined to be your familiar"). 
Even after praying 3 times in short succession, through ank reset, nothing except the text message happens. I discovered it first in atm9 and then tested it with only forge and corails tomstone installed. 

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Falkenei** [comment]
actually it was Minecarft 1.20.1 I just wrote the wrong version of tombstone. I encountered the problem in 1.20.1-8.6.1.jar not in 1.20.4-8.6.1.jar as initially written. Sorry about that. P.s. I editet the issue to that effect

**Comment by Corail31** [comment]
It's fixed in 8.6.2 if you're in 1.20.1.
