### ISSUE TITLE
[Suggestion] Different modes of grave operation  receptacles restore and void protection.

### ISSUE THREAD

**Issue by Darkmega18** [Corail31/tombstone_lite#2]
Hey Corail, figured i'd come make a suggestion for you. This suggest is different modes of grave operation on death. For example:

tombstones:
1. A mode where gravestones works first/normally barring any mechanics which keep equipment already present, such as enigmatic legacy's amulet, another tombstone mod, a totem of keeping from quark, death chests or whatever.

2. A mode where gravestones will work LAST and will allow other death mechanics to go first, such as the things listed previously. For example if I want there to be no timer on grave robbing, players can instead utilize other death mechanics which require investment or equipping such as the enigmatic amulet's dimensional capsule which unless set can't be picked up by other people etc.

3. A mode where gravestones isn't an automatic mechanic and will instead trigger only if you're holding a gravestone in your inventory. The gravestone of which will be consumed to place a grave for the player on death using the standard mechanics of the mod doing all as normal. But when you get your stuff back the grave will rumble and break into pieces as a sort of particle effect and you won't get the item grave back. In this mode you could create a new slot for curios called a "grave" slot, and when a grave is equipped there that is the grave you will be placed inside on death.

From this idea an ability to set a decorative grave using a tablet or scroll as your "item recall location" could be an absolutely epic idea. 
Where basically, you set a decorative grave as YOUR grave. and when you die, your items will instead not spawn in a grave at your death location, but rather your items with instantly be transported into the grave which you marked, that grave now becoming your grave that shows up when holding list etc.

---

As for soul receptacles dropped by bosses and such a thought on how they revive the player on death.

Modes could be related to be like:
1. On "death" do what you do currently, distract and restore the player for a minute to prevent chain deaths.
2. Recall the player to their spawn and refresh them. But not for as long as they shouldn't be in trouble anymore.

Also, ability to set the duration of how long the buffs of one such receptacle would be good, because the healing and saturation is very long lived all things considered. I'd say 10-20 secs is rather fairer. As the receptacles can be very powerful when using them as a means to basically berserk through content if you happen to have a way to craft them or ways in which they can drop.

---

The void protection mechanic is similar to your receptacles in how it protects the player, but theres probably some other ways it can be handled.

1. Recall to last known location on land and act like receptacle (current).

1b Recall to last known location and die placing grave there (just so that when you die anything that happens to for some reason not get sucked into the grave will be left in the ground there, not floating over the void or made to not exist) I'm thinking stuff like backpacks which drop on the ground and other such things.

2. Recall to spawn and receptacle.

2b Recall to spawn and die. similar deal as 1b.

Just some configurational stuff to consider perhaps. :)

**Comment by Corail31** [comment]
I'm sorry but suggestions like this are not accepted, as it's not really a description of something, you seem just to not know what already exist, and want additional "unbalanced" features that will never be added.
Tombstone has already a complex system.
Edit: to resume, Soul Receptacle will never be craftable(even by diminishing duration), decorative graves are for the magic purpose, 'void protection' teleports in WorldBorder and not in your home.

**Comment by Darkmega18** [comment]
>  Soul Receptacle will never be craftable(even by diminishing duration)

I never asked for that, I asked for the duration of their effects to be able to be set for someones own personal balance. Because I happen to get them from mobs who spawn as apotheosis bosses and such because they have over 100 HP occasionally, and so they just drop them. 
And I've noticed they are very very powerful at saving your life, if sometimes too powerful, because I can drop myself in the void while one is going and be almost invincible to it's ravages while the regeneration is working..

> decorative graves are for the magic purpose,

Yes, yes they are, I also suggested a new magic effect for them with the grave conversion on death magic.

But what is so wrong for having an optional mode where instead of outright disabling grave creation as I have so that another mod's mechanics happen, you make the player require a grave or a trinket of some kind to utilize the mechanics behind the mod, 

so that other mods can still have their death mechanics utilized if they happen to have them?

> 'void protection' teleports in WorldBorder and not in your home.

once more, I didn't say that it did. I mentioned that it felt like it teleported me to the last position where i was on land. As happened at 1:40 of my video here:
https://www.youtube.com/watch?v=NBQmbv7LN8I

but I SUGGESTED other ways for it to trigger which can be selected in the configs: for modpack balance tweaking and such,
one of them was throwing you home or putting you on land but still killing you so you can die out of the world (and not get basically a free trigger of the soul receptacle) while still allowing the intention of your stuff not being voided out cause you were TP'd to land.

I never suggested anything to drastically unbalance the game, Corail.


I'm sorry if I combined too many suggestions in one go and it became a mess and you thought something else about them or if I missed that some of these mechanics already existed.

**Comment by Corail31** [comment]
The life for a mob to be considered as a boss is a config. (simply because nothing in code allows to know if it's a boss)
It's possible for a soul receptacle to not save you from a fall too if it's an empty chunk.
But the "void protection", i supposed you talked about a config allowing to prevent death outside world (that also exists)
NB: yes it's hard for me to read as dense ;)
Edit: feel free to provide others details, but for example, if you require an item to craft to get a grave, people going on your server will just think the grave is not working without searching if they need an item for it (as used with the grave mod). They will have to die to discover how is configured Tombstone and with the risk to lose their stuff in lava or any bad consequence.
Also, players have multiple options in the gui in game allowing them to define if they want a grave or not (and others options related to equipements) 
About Soul Receptacle, it has to be rare, the survival item being the Voodoo Poppet.
The chance of drop on undead boss is 5% by default too (and requires the player to be the killer).
You seem to play on a really unbalanced server and you discuss about the duration of an item being rare.
About the video, i'm not sure if this is intended but the fact that you have no item at the end also shows that you have a mod acting before the graves (read your server log, Tombstone always provides this information).
I'll anyway change the minimal default life for undead boss to 200.

**Comment by Darkmega18** [comment]
> The life for a mob to be considered as a boss is a config

Yep. I think I saw it but left it at 100ish.

> But the "void protection", i supposed you talked about a config allowing to prevent death outside world (that also exists)

I actually have that setting activated, as seen in my video. I just wanted to suggest other "config variations" which could be selected to change it's behavior. 

The same was true for the numbered variations on how death tombstone creation could be worked for different mods and pack needs, and the power levels and effects caused on triggering of receptacles.

> NB: yes it's hard for me to read as dense ;)

I apologize, again. I will split my suggestions up a bit better next time. I sometimes get carried away.
