### ISSUE TITLE
HELP! character experience

### ISSUE THREAD

**Issue by MrPacha23** [Corail31/tombstone_lite#2]
In my configuration it is that the experience is not lost when dying but in the same way it is lost and I do not know what to do so that it does not happen, it helps!

**Comment by Corail31** [comment]
Hi, you should test Tombstone alone to make sure it's not related to others mods, as the experience kept on death works in all versions.

**Comment by MrPacha23** [comment]
Yes, I actually tested in a single world with all server mods and if it worked for me.

**Comment by Corail31** [comment]
I'm not sure to understand your answer as i ask you to test it with Tombstone alone, and you answered you tested it with all server mods ...?

**Comment by MrPacha23** [comment]
Ok, let me explain I have a server with magma with around 85 mods and the xp is not saved there, it is lost at the moment of death but in a world I only tried the mod with the same 85 mods and the xp is not lost so I don't know that may be. Another thing that I did not understand is what you sent me, if one improves, does that keep more and more xp?

**Comment by Corail31** [comment]
> Another thing that I did not understand is what you sent me, if one improves, does that keep more and more xp?

It's how it works, yes.

> Ok, let me explain I have a server with magma with around 85 mods and the xp is not saved there, it is lost at the moment of death but in a world I only tried the mod with the same 85 mods and the xp is not lost so I don't know that may be

If you join a distant server, it's the server that sets the xp config option.
If i understand well, Magma is a modified forge, and if the bug only appears when using it, you should report to them.

**Comment by MrPacha23** [comment]
Ready, I'm going to be testing it to see if this is how it is working on the server. I am on version 1.12.2

**Comment by MrPacha23** [comment]
I checked what you sent me earlier but on the server I don't get the option that you mentioned "Memento Mori".

**Comment by Corail31** [comment]
What i can say you is the support is for Forge (and a little Sponge), 1.12.2 is old, very old, and the code of Tombstone didn't changed and is stable since a long in theses versions.
You should stay on forge :p or you will really need to post an issue on Magma github. (if you want to make tests it's better to test with Forge instead of Magma to compare the result)

**Comment by Corail31** [comment]
https://github.com/magmafoundation/Magma/issues/124
