### ISSUE TITLE
Crash after update [2.8.6]

### ISSUE THREAD

**Issue by raltus** [Corail31/tombstone_lite#2]
I updated my mod pack with the latest version. While walking around after a little bit it seems to have a lag spike and crashes. Since this mod was listed near the top of the log I tried switching to the last version and it is working fine. There is some stuff listed father down the log so I'm not sure if this is conflicting with something else or not.

https://gist.github.com/raltus/d6aa0c63953d59ece07136e2ef066a8e

**Comment by Corail31** [comment]
strange an itemstack return null to this method (what was the item in the enchant table ?)

**Comment by ZZaphodd** [comment]
modversion : 2.8.6-1.12

https://github.com/EmosewaPixel/Crimson-Skies/issues/32 may be same problem?

**Comment by raltus** [comment]
Looks like it. Update to 2.8.7 to fix it.

**Comment by Corail31** [comment]
yes, don't use 2.8.6, it's not in download (and pixel knows this)
