### ISSUE TITLE
[Suggestion] Config option for item loss

### ISSUE THREAD

**Issue by foxanthony1** [Corail31/tombstone_lite#20]
I'd like to have an option for there to be a configurable % chance that a configurable # of the players items will disappear/be destroyed when they die.

**Comment by Corail31** [comment]
Wow, that seems a strange feature to want a chance of completely destroy a % of your inventory.
Vanilla didn't it so... it looks strange, as inventory is something very precious.

**Comment by foxanthony1** [comment]
In Vanilla you can lose ALL your inventory though. This is an option for there to be a chance of losing some of it - bring back some of the fear of dying to modded.

See, that's the thing - in modded dying is mostly just a hassle, not something scary, because of grave mods. Unless, you play in hardcore - which is a bit much for most people.

**Comment by Corail31** [comment]
Ok, so there could be reasons to add this feature, so :
=> a config option, disabled by default, that allow this feature
=> a other config option, to set the chance to have some losses
=> a third config option, to set a % of items lost when this occurs
and what about to only affect items that are stackable ? (to avoid to loss important items)

**Comment by foxanthony1** [comment]
`=> a config option, to set the chance to have some losses (0% by default, so disabled)`
Yep.
`=> a second config option, to set a % of items lost when this occurs`
Yep.
`and what about to only affect items that are stackable ? (to avoid to loss important items)`
I don't know that players would really even notice - they'd probably just think they misremembered what they had. But... if you could replace those items with something else like dead bushes or sticks or bones... then they'd know something happened. I kind of like that, keep all your good stuff and everything else is turned into dead bushes. That'd be funny and kind of suck at the same time.

**Comment by Corail31** [comment]
I thought to add a message when the grave disappears, about some missing items (because i want to be sure that player knows it's a feature of tombstone), and your idea about junk loot in replacement is good too.

**Comment by foxanthony1** [comment]
Yeah, a message would be smart. Otherwise, people might think it's a bug not a feature.

**Comment by Corail31** [comment]
hi foxanthony1,
it will be included in 2.3.1 :+1:

**Comment by foxanthony1** [comment]
NIce! :+1:
