### ISSUE TITLE
Tombstone doesn't give back item from grave

### ISSUE THREAD

**Issue by Klouver-github** [Corail31/tombstone_lite#20]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Corail Tombstone Version

1.16.5-6.5.4

### What happened?

I am trying to get my stuff back but the tombstone not taking the key and I have reloaded the world and game menu but won't give back to me but other times it did give stuff back to me as I am playing the latest Tombstone released

### Gametype

Singleplayer

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi Klouver,
You are probably one of the 249 players who downloaded it this morning before i released the fix as someone warned me about it (just download again the same version).

**Comment by Good-BoiMcLovin** [comment]
> Hi Klouver, You are probably one of the 249 players who downloaded it this morning before i released the fix as someone warned me about it (just download again the same version).

Hahaha, amazing, so did I, I somehow managed to sneak in there before you fixed it. What are the chances, good I checked here right away, thank you for fixing it!
