### ISSUE TITLE
Easter egg searcher and Expert searcher triggered upon joining World

### ISSUE THREAD

**Issue by Falkenei** [Corail31/tombstone_lite#200]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Corail Tombstone Version

1.20.1-8.6.2.jar

### What happened?

Upon updating to 1.20.1-8.6.2.jar and joining the world I got both the achievements Easter egg searcher and Expert searcher without having done anything except join the world. I have no easter eggs in the inventory so that can't be the reason

Edit:
After further testing it appears as soon as I trigger 1 achievement in a new world (survival with cheats) I get both of the achievments

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's a minor issue due to json probably (strange that i didn't notice it). Easter starts on 21th march to 21th april. (with April Fools' Day in the middle).
Edit: after tests, it happens on inventory changed (and only the first one triggers in 1.19.2).

**Comment by Xplodin** [comment]
![image](https://github.com/Corail31/tombstone_lite/assets/13007677/d125017f-8029-4dd7-b41a-f0f050127f15)
seems both advancements are done on 1.20.1
