### ISSUE TITLE
Tablet of recall

### ISSUE THREAD

**Issue by TAN92LA88** [Corail31/tombstone_lite#202]
### Minecraft Version

1.20.1, 1.19.2

### Forge Version

1.20.1, 1.19.2

### Corail Tombstone Version

1.20.1, 1.19.2

### What happened?

Tried to create any kind of tablets but for some reason I can craft them, I try it with other mods and also without mods, but not working, also I tried to combine the key and an ender pearl to be able to teleport to my tomb but the key disappeared every time I tried.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Please read the compendium in game (command /tbgui compendium combination).
In 1.20.1, the grave key can also be crafted with a crafting table...

**Comment by TAN92LA88** [comment]
Where do I find the compendium?

Is the first time playing with mods.

**Comment by Corail31** [comment]
The command /tbgui in game, then the button compendium, and finally the subject about "Combination".
To Combine the ingredient with the strange tablet, just drag the ingredient on the strange tablet with right click.
Tablets also require to be "enchanted" with a "soul over a decorative grave".

**Comment by TAN92LA88** [comment]
Awesome thanks for the help.
