### ISSUE TITLE
easter egg in every creative tab

### ISSUE THREAD

**Issue by Orangejewce92** [Corail31/tombstone_lite#203]
### Minecraft Version

1.19.2

### Forge Version

1.19.2 - 43.3.8

### Corail Tombstone Version

8.2.14

### What happened?

There is easter eggs in every creative tab for every mod including the destroy item space in creative inventory !

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Orangejewce92** [comment]
![egg](https://github.com/Corail31/tombstone_lite/assets/110748022/ade5b2a7-f993-42f1-a916-84246f5c619d)
![egg1](https://github.com/Corail31/tombstone_lite/assets/110748022/18f49c2d-bb38-4b47-a242-8788f04c6e1a)
![egg2](https://github.com/Corail31/tombstone_lite/assets/110748022/278e5f05-342c-4841-9dad-7408c3eaeeec)
![egg3](https://github.com/Corail31/tombstone_lite/assets/110748022/0486726e-920d-4805-8089-09cc2be7e368)

**Comment by littlepianist** [comment]
Same issue

**Comment by Corail31** [comment]
Fixed in 8.2.15.
