### ISSUE TITLE
Corail loot table drop on chest break

### ISSUE THREAD

**Issue by TysonTheEmber** [Corail31/tombstone_lite#206]
### Minecraft Version

1.18.2

### Forge Version

1.18.2

### Corail Tombstone Version

7.6.7

### What happened?

Sometimes when you break a chest or chest-like block it drops the chest AND a corail scroll type item. 

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's already fixed in upper versions (and is about modded chests and the name of their lootTable). https://github.com/Corail31/tombstone_lite/issues/188

**Comment by Corail31** [comment]
@TysonTheEmber Fixed in 7.6.8.

**Comment by TysonTheEmber** [comment]
Thank you so much for the quick update!
