### ISSUE TITLE
Impregnated Diamond lost the NBT when crafting Familiar Receptacle

### ISSUE THREAD

**Issue by morgantic** [Corail31/tombstone_lite#207]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Corail Tombstone Version

8.6.1

### What happened?

First of all, sorry for posting here, CF doesn't let me create a comment. But I'm thinking this might be a bug, so maybe I'm even right here.
Issue: After bringing a skeleton back to life from a Familiar Receptacle, I wanted to get a pet enderman as well. So I crafted and used a bone needle on an enderman, combined it with an Impregnated Diamond, and crafted that into a Familiar Receptacle. But the moment I went from Combined Impregnated Diamond to Receptacle, it lost its NBT. I now have an NBT-less Familiar Receptacle... Did I do something wrong? Is that supposed to happen? Thanks in advance!

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by morgantic** [comment]
Tested, happens in single player as well. I feel like I might be misunderstanding how the Familiar Receptacle works?

**Comment by Corail31** [comment]
The Familiar Receptacle is only for your "existing" tamed entities (or undead servants). It's not used to tame.
The Impregnated Diamond is used to precise which tamed entity to capture if you have multiple.
It's explained in the compendium in game. (/tbgui compendium)
The Impregnated Diamond accepts others types of creatures but not the Familiar Receptacle and why it losts its nbt.
The Impregnated Diamond is used as trade by the Grave Guardian, why it allows more creatures.
