### ISSUE TITLE
Config to Remove (not reduce rarity) of Easter Eggs

### ISSUE THREAD

**Issue by ArcTrooper210** [Corail31/tombstone_lite#209]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Corail Tombstone Version

8.6.5

### What happened?

I looked and there is no config to completely disable easter eggs, I saw one to reduce the rarity but there should be an option to completely disable it like with the Halloween ghosts.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Like Lollipops, it's not disableable. Already answered here... https://github.com/Corail31/tombstone_lite/issues/208

**Comment by ArcTrooper210** [comment]
Can I ask why there can't be a config to disable? I mean there's a config to disable the ghosts.
