### ISSUE TITLE
Dedicated Server Crash on Startup with version 2.3.1

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Corail31/tombstone_lite#21]
https://gist.github.com/P3rf3ctXZer0/f6486795a151ef1539598009318998dc

**Comment by Corail31** [comment]
thanks for the report, i removed the dl link btw.

**Comment by Corail31** [comment]
I'm going to publish it again in 10 minutes
NB : was my fault, this class shoudn't appear there ;)
