### ISSUE TITLE
Prayer stone doesn't work on Server but works in Singleplayer

### ISSUE THREAD

**Issue by camp00000** [Corail31/tombstone_lite#211]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Corail Tombstone Version

8.6.5

### What happened?

Tested on ATM9 (0.2.58) which used the above specified Corail Tombstone and Forge Version.

Also tested with **only** Corail Tombstone and Forge of the same versions as above - the same stacktrace basically occurred with my locally running dedicated server.

See image for reference:
Edit Corail31: i don't need such image

Clients both times initialized from the CurseForge launcher.

Issue occurs in Multiplayer but **not** on Singleplayer (for both ATM9 and purely with Corail and Forge)

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Log Link

https://pastebin.com/tUV9NzEY & https://pastebin.com/TCgpqG6S

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Thanks for your report, i indeed used a client only method (and it also affects the command to reset the Ankh, since 8.6.0).
