### ISSUE TITLE
All soul receptacles are consumed upon right-clicking on a grave

### ISSUE THREAD

**Issue by camp00000** [Corail31/tombstone_lite#212]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Corail Tombstone Version

8.6.5

### What happened?

Tested with the same setup as #211, I believe this is a long-standing bug as I remember it also occurring on ATM8 and perhaps even earlier modpacks.

Tested also with the same purely tombstone & forge setup in singleplayer -> same result.
Tested on atm9 server & only-tombstone server -> same result.

Reproduce: Take >= 1 soul receptacles in Survival an right click on a grave that doesn't have a soul on it.
Expected behavior: Only one out of however many soul receptacles on-hand are consumed.
Current behavior: The full stack of however many (1-64) soul receptacles get deleted upon right-clicking a grave that doesn't have a soul on it yet.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Nice catch, even if it's not so common to have a stack of soul receptacle :)
