### ISSUE TITLE
Jade tooltip on a tameable entity displays errors

### ISSUE THREAD

**Issue by mberlin1** [Corail31/tombstone_lite#213]
### Minecraft Version

1.20.1

### Forge Version

47.2.23

### Corail Tombstone Version

8.6.5

### What happened?

See screenshot "Error occurred, plz report to Jade"
![2024-04-28_16 02 28](https://github.com/Corail31/tombstone_lite/assets/3492348/546ce951-3146-4c38-b8e9-2343d273df42)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Monumental modpack

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
"plz report to Jade".
Jade is a mod.
