### ISSUE TITLE
GRAVESTONE DOESN'T APPEAR IN MINECRAFT MOHIST SERVER 1.18.2

### ISSUE THREAD

**Issue by CarlosNsV** [Corail31/tombstone_lite#214]
### Minecraft Version

1.18.2

### Forge Version

40.2.4

### Corail Tombstone Version

7.6.6

### What happened?

When we die in the server the gravestone doesn't appear and the loot drops in the floor, also we have clearlagg and sometimes the loot disappears. However the mod is correctly instaled, as we can craft gravestones, get mod objects...

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's known and why there's a question about forge alternatives, Mohist has to behave like forge to have a grave (the drop event is probably not called the same way). It's something to be fixed on Mohist side.

**Comment by Corail31** [comment]
https://github.com/MohistMC/Mohist/issues/3117
