### ISSUE TITLE
After death I need to click respawn 2 times, after i spawn again im instalocked, can't move, can hit and have immunity to damage.

### ISSUE THREAD

**Issue by Ctakep** [Corail31/tombstone_lite#215]
### Minecraft Version

1.19.2

### Forge Version

4.3.13

### Corail Tombstone Version

tombstone-1.19.2-8.2.16.jar

### What happened?

The title explaings

Video

Edit Corail31: videos are not welcome.

Modlist

[modlist.txt](https://github.com/Corail31/tombstone_lite/files/15209678/modlist.txt)

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

there is 237 mods

### Log Link

.

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, you have to locate better which mod is doing this if you can't make this happening with only Corail Tombstone.
If you don't have time for this, your issue will be simply closed.
