### ISSUE TITLE
Error when starting a server for the first time

### ISSUE THREAD

**Issue by lupiiiin** [Corail31/tombstone_lite#217]
### Minecraft Version

1.20.1

### Forge Version

1.20.1

### Corail Tombstone Version

8.6.5

### What happened?

When I log in to a server for the first time, I receive this error:

"java.lang.NullPointerException: Cannot invoke "ovh.corail.tombstone.helper.PlayerPreference.hasChangedFromConfig()" because "this.lastPlayerPreference" is null"

When re-entering the world everything works normally, but the first time it always crashes.

It happens only with other mods.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Log Link

https://pastebin.com/P1VGCh4R

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's not something that can happen without others mods. You didn't locate the problem and i don't help if there's a ton of mods. The player preferences are init on login with a packet.
