### ISSUE TITLE
Unable to remove Tombstone items from Loot Tables

### ISSUE THREAD

**Issue by KnightCa** [Corail31/tombstone_lite#218]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Corail Tombstone Version

4.6.6

### What happened?

I tried removing these items from Loot Tables, as there is no way in the config to disable them:

- Voodoo Poppet
- Magic Scroll
- Fishing Rod of Misadventure

**Loot Table dumps** I based the script from:

1. [junk.json](https://github.com/Corail31/tombstone_lite/files/15271231/junk.json)
2. [abandoned_mineshaft.json](https://github.com/Corail31/tombstone_lite/files/15271263/abandoned_mineshaft.json)
3. [simple_dungeon.json](https://github.com/Corail31/tombstone_lite/files/15271281/simple_dungeon.json)
4. [village_blacksmith.json](https://github.com/Corail31/tombstone_lite/files/15271311/village_blacksmith.json)

**LootTweaker Script**:
```
recipes.remove(<tombstone:voodoo_poppet>);
JEI.hide(<tombstone:voodoo_poppet>);
LootTweaker.getTable("minecraft:chests/abandoned_mineshaft").getPool("tombstone:chest_treasure").removeEntry("tombstone:voodoo_poppet_loot");
LootTweaker.getTable("minecraft:chests/simple_dungeon").getPool("tombstone:chest_treasure").removeEntry("tombstone:voodoo_poppet_loot");
LootTweaker.getTable("minecraft:chests/village_blacksmith").getPool("tombstone:chest_treasure").removeEntry("tombstone:voodoo_poppet_loot");
LootTweaker.getTable("minecraft:gameplay/fishing/junk").getPool("tombstone:lost_treasure").removeEntry("tombstone:voodoo_poppet_loot");

recipes.remove(<tombstone:magic_scroll>);
JEI.hide(<tombstone:magic_scroll>);
LootTweaker.getTable("minecraft:chests/abandoned_mineshaft").getPool("tombstone:chest_treasure").removeEntry("tombstone:magic_scroll_loot");
LootTweaker.getTable("minecraft:chests/simple_dungeon").getPool("tombstone:chest_treasure").removeEntry("tombstone:magic_scroll_loot");
LootTweaker.getTable("minecraft:chests/village_blacksmith").getPool("tombstone:chest_treasure").removeEntry("tombstone:magic_scroll_loot");
LootTweaker.getTable("minecraft:gameplay/fishing/junk").getPool("tombstone:lost_treasure").removeEntry("tombstone:magic_scroll_loot");

recipes.remove(<tombstone:fishing_rod_of_misadventure>);
JEI.hide(<tombstone:fishing_rod_of_misadventure>);
LootTweaker.getTable("minecraft:gameplay/fishing/junk").getPool("tombstone:lost_treasure").removeEntry("tombstone:fishing_rod_of_misadventure_loot");
```

I get the message that Minecraft cannot find the Pool on the Loot Table. Can you help me to determine what the Pool names are to disable them?

![image](https://github.com/Corail31/tombstone_lite/assets/51968609/c7363a35-c572-45ff-ae54-e0cfa6d19299)

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes, along with LootTweaker (needed to adjust Loot Tables)

### Occurence

occurs all the time

### Other relevant mods

- CraftTweaker2-1.12-4.1.20.698
- LootTweaker-0.3.3+MC1.12.2

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by KnightCa** [comment]
The LootTweaker devs say this is a issue on Tombstone's side. I can't fix it by editing the Loot Tables myself.

**Comment by KnightCa** [comment]
Reading the description, I found the fix (thanks for all of your amazing work team)

Loot Tables (related to this mod) can be edited in your savegame folder (in "tombstone/loottables). It just needs reload the save (or use the command /reload) after modifications.

For 1.12.2, Theses lootTables are lost treasures (for unlucky fishing in 'openwater'), chest treasures (for structure chests), and undead loots (including undead boss).

**Comment by KnightCa** [comment]
I spoke to soon. 

After editing the savegame/tombstone/loottables to remove all references to the three items, they reverted back to the default settings (losing the changes) as soon as the world starts up.

How can we keep the changes we make to these tables?

**Comment by Corail31** [comment]
You found the right solution KnightCA.
The loottables are loaded from the json in your save folder (in "tombstone/loottables"), the change is relatively new (since the last version in 1.12.2).
The json loottables are reset if :
- you update to a new version of Tombstone that requires the reset (done once)
- the json is not loadable (incorrect json, you can test the validity on https://jsonlint.com, you can also copy/paste the pretty display of the json on this website in your file to simplify the edit)

Each time it creates a .bak file with the old file.
For Jared, the loottables exist but only one tick later in a callback.
NB: i'll make a test soon to ensure the edit is working properly in 1.12.2.

Edit: It seems the file resets anyway in 1.12.2 (unlike in upper mc versions), i'll need to revert this, you can use the previous version if you need to edit the loottables with CraftTweaker.

**Comment by KnightCa** [comment]
Thank you so much Corail31 for the revert in the next version of 1.12.2. Will we be using loottables in the world folder in the next version (with changes being saved, instead of lost) or CraftTweaker instead?

I'm attaching the Loot Tables from the world save folder (edited to remove Voodoo Poppet, Magic Scroll, Fishing Rod of Misadventure) for others who may need them later.

- [tombstone-pool-chest_treasure.json](https://github.com/Corail31/tombstone_lite/files/15285143/tombstone-pool-chest_treasure.json)
- [tombstone-pool-lost_treasure.json](https://github.com/Corail31/tombstone_lite/files/15285144/tombstone-pool-lost_treasure.json)
- [tombstone-pool-undead_boss.json](https://github.com/Corail31/tombstone_lite/files/15285145/tombstone-pool-undead_boss.json)
- [tombstone-pool-undead_mob.json](https://github.com/Corail31/tombstone_lite/files/15285146/tombstone-pool-undead_mob.json)

**Comment by Corail31** [comment]
I will revert to the old way, 1.12.2 is too old ^^ Why you can simply use the previous version.

**Comment by KnightCa** [comment]
There are many mods that still only have a 1.12.2 release that are great for our modpack. I do really like the new features you are adding into Tombstone. You are very much appreciated.

**Comment by Corail31** [comment]
@KnightCa I re-added the editable loottables in 4.7.0 for 1.12.2 ;)

**Comment by KnightCa** [comment]
Thanks so much ;)
