### ISSUE TITLE
Issues with Running Corail tombstone on MC server

### ISSUE THREAD

**Issue by gcgol** [Corail31/tombstone_lite#219]
### Minecraft Version

1.20.1

### Forge Version

1.250.3.177967

### Corail Tombstone Version

1.20.1 

### What happened?

When running Corail tombstone on MC server With ATM9 server is crashing 

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

ATM9

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
If you don't have logs, your issue is simply closed.
