### ISSUE TITLE
Compatible with Enigmatic Legacy mod

### ISSUE THREAD

**Issue by DrSigma4164** [Corail31/tombstone_lite#22]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Corail Tombstone Version

6.4.7

### What happened?

Hi! I had a question. Is it possible, if so how to do it, to add blacklist items that should not be equipped automatically? That is, there is a mod called Enigmatic Legacy. In this mod there is an item that must be worn in the curio slot, but then it can not be removed in survival, but it can not be worn, which I did, but after semester and raising the grave, he automatically put on the curio slot. I found the line "allow_curio_auto_equip" in the config file, and I can exclude that NO item was worn there, but it is inconvenient and sometimes there is no place in the inventory. So is it possible to somehow add an item to the blacklist of items that should not be worn automatically?

### Gametype

Singleplayer, Dedicated Server

### Happen with only Corail Tombstone

No

### Other relevant mods

Enigmatic Legacy

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, can you give me the registry name of this item ? If the slot is equipped, it means it's allowed in code.
Can you provide more details why this item can't be equipped in survival but you have one in your inventory ?

**Comment by DrSigma4164** [comment]
Hi!
Name: <item:enigmaticlegacy:cursed_ring>
Tags: <tag:items:curios:ring>
Slot: ring
Details: This item can be worn. If you put it on in survival, you will not be able to take it off. The essence of this subject: when you wear a "curse" hangs on you, that is, you get debuffs, but at the same time you get some features.
That is, when I put it on myself, it should stay put on, but when I don't put it on, it shouldn't move into the ring slot itself, although other rings, amulets or something else can be put on automatically, but it would be good if it kept where the item was put on. because I don't keep it.
And one more thing, how to do so every year on the hotbar or in the inventory were in the same places as at death, and if there is another object, during the removal of the grave things from the grave replaced the things that lie there and sent the old to the inventory if there is a place or thrown away if it is not.

**Comment by Corail31** [comment]
It seems this mod has others cursed items.
The trouble is more related to my wish to prevent Curio to be a laggy thing when re-equipping the dropped loots, i already avoid any stackable item.
On one side, Curio accepts items without capabilities by only being in a tag (so, a list of items).
Then, there's the curio capability for item that can be present or not, so i would need to check for each item in loot (with effectively a method "canRightClickEquip" but even the name doesn't fit).
In the past, i only accepted items having a capability (but some bag items didn't have the capability or 'toolbelt'), so now i rely on IDynamicStackHandler.isItemValid(i, stack).
I don't think i should handle the use case of theses "cursed items", they could have the enchantment "curse of binding", and they would be more compatible by this way.
I'm any way open to suggestions others than a user defined list of items to check.
Edit: wanting items to get to the same slot is a dumb logic, you can have multiple graves with stacked items and you can wear new items in the between of your last death. There're client configs to set your preference about how to re-equip. Items are restored in an order that should be in the right slots but won't replace any slot already equipped.

**Comment by Corail31** [comment]
solved in 6.6.1
Edit: as precision about the compat, the cursed ring/amulet are never auto-equipped and the amulet depends on how player configured their client config "deny_grave_on_death" (/tbgui): if the grave is allowed, the amulet will be found in the grave; if not, the amulet will handle its code.
