### ISSUE TITLE
The grave doesn't recognize which armor you had before die

### ISSUE THREAD

**Issue by Sheppard22** [Corail31/tombstone_lite#22]
Well.. thats it. When you have an armor equiped and you die, when you recover your things IF you had other armors in the inventory the grave can't recognize which ones you had equipped and will mix everything.

**Comment by Corail31** [comment]
Yes, it' how it works, it equips any empty slots that you have with the items gathered from the graves (to have a fast equip, but no to restore exactly the slots)

**Comment by Sheppard22** [comment]
its just you've got your best armor equipped and then if you die you end up with another armor

**Comment by Corail31** [comment]
included in the coming release 2.4.0
