### ISSUE TITLE
No grave spawning

### ISSUE THREAD

**Issue by wiblu** [Corail31/tombstone_lite#22]
I'm playing the modpack Towncraft on a server and have run into this issue twice now where my death grave doesn't spawn.
The conditions for both times i was flying/falling with the glider from Techguns and jetpack from Wearables mod while being shot down by Techguns mobs i have been killed while wearing both many times just not high in the air.
First time i was in the caverns from Caverns II second time was in the nether both ive had many deaths.
After i respawn the message 'Tombstone Disappears' shows like when you collect your items and i don't receive the key
Any help on this would be appreciated 
Cheers, Wiblu

**Comment by Corail31** [comment]
Hi Wiblu,
i need the log on pastebin.

**Comment by ProsperCraft** [comment]
What server?

**Comment by wiblu** [comment]
hope this is the right log had to split it
https://pastebin.com/bs2BVxEB
https://pastebin.com/Re423Axs
@ProsperCraft playing on a private server

**Comment by Corail31** [comment]
[tombstone] Found status: OUTDATED Target: 3.1.1
You're on a old version of tombstone, i would recommand you to use the last version (as for example, you haven't yet received the dataFixer for the namespace of the tileEntities in V2.10.2)
You can modify your towncraft with a more recent version of my mod and you won't have this bug anymore (and you might discover the new content with the knowledge of death)

**Comment by wiblu** [comment]
Ah ok will do thank you,thought i had the latest version guess i should have checked that first,

**Comment by Corail31** [comment]
All is fine to report issue :)
