### ISSUE TITLE
Mobs able to kill in ghost mode

### ISSUE THREAD

**Issue by blacksinger69** [Corail31/tombstone_lite#220]
### Minecraft Version

1.20.4, 1.20.1

### Forge Version

47.2.21

### Corail Tombstone Version

8.6.5

### What happened?

I'm playing the modpack atm9 no frills and died to a vindicator, tried to teleport to the death waypoint using the mod journey map and the vindicator kept killing me in ghost mode.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Vindicator (whatever it's) is probably not following how they can target an entity and should also follow forge events about damages (so, other mod bug).  I can't do nothing on my side for such a (broken) mod.
