### ISSUE TITLE
Client Crash - 1.20.1 - Rendering Issue

### ISSUE THREAD

**Issue by HalestormXV** [Corail31/tombstone_lite#222]
### Minecraft Version

1.20.1

### Forge Version

47.2.30

### Corail Tombstone Version

8.6.5

### What happened?

Seems to get a client crash. Log is detailed.

https://mclo.gs/TbiKbjO

Looks particularly related to Invisible Mobs from either Vampirism and Apotheosis but something goes haywire and caused the crash with Corail rendering and perhaps related to Oculus. It seems to occur randomly.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Other relevant mods

Oculus, Apotheosis, Vampirism

### Log Link

https://mclo.gs/TbiKbjO

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You have to start by reducing your mod list if you want help.
