### ISSUE TITLE
issue with losing items on death, its real bad.

### ISSUE THREAD

**Issue by Salutatorian** [Corail31/tombstone_lite#224]
### Minecraft Version

1.20.1

### Forge Version

no idea

### Corail Tombstone Version

atm9 version59 so probably the latest

### What happened?

how do u freaking turn off that chance to lose items, I was going insane till I accidentally hit the mob masher death on instance without escape. went to my grave lost a sophisticated backpack that was full of stuff to get. i already set the settings to 0 - 100 chance: 0 and I'm still losing items.....

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
What is really bad is to not locate your problem when you see it's not happening with only my mod and why the issue is closed.

**Comment by Salutatorian** [comment]
im asking for help on how to remove it and u cant help...

**Comment by Salutatorian** [comment]
you made the mod right???? whats wrong with helping people fix it so I could help others online too.

**Comment by Corail31** [comment]
Your assumptions are just incorrect, people don't lose items with my mod (and you can't make this happening with only my mod). Even the config that you mentioned wouldn't allow to remove a non stackable item (and even less with an inventory).
If you lose your backpack, it means it was simply not in the drops.
If you don't have time to locate the problem with your modpack (as asked in the issue template, by reducing your modpack to a few mods), why should i do it.

```
Other relevant mods
if this issue is not happening with only Corail Tombstone, provides the minimal list of mods (max 5) to make the issue happening.
```

**Comment by Salutatorian** [comment]
i wasnt even losing a backpack lol. i was even losing a pickaxe...

**Comment by Corail31** [comment]
Ok, you don't understand what i'm saying about "invalid issue".
