### ISSUE TITLE
colored marble blocks and variants cannot be mined, and many are too hard

### ISSUE THREAD

**Issue by kiteserpent** [Corail31/tombstone_lite#225]
### Minecraft Version

1.20.4

### Forge Version

49.1.0

### Corail Tombstone Version

8.6.3

### What happened?

Red, green and blue marble blocks vanish when mined with a normal or Silk Touch diamond pickax. Black and white marble blocks are collected normally with both.

Red, green and blue marble slabs and stairs have the same problem PLUS take noticeably longer to break. Black and white behave normally.

Did not test other marble shapes.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Good catch, they're not added to the mineable tags.

**Comment by Corail31** [comment]
@kiteserpent Hi, i noticed while porting to 1.21 that the json loottables for colored marbles were also missing. They will be added in the next release.
