### ISSUE TITLE
dying upon respawning

### ISSUE THREAD

**Issue by Vibin-crafter** [Corail31/tombstone_lite#227]
### Minecraft Version

1.19.2

### Forge Version

43.3.0

### Corail Tombstone Version

1.19.2-8.2.17

### What happened?

found this out upon testing explosions on myself, found out later explosions weren't actually the issue, i do get a grave key, a gravestone does appear, i can even teleport back too it and i do get points or knowledges of death i believe on the first initial death- but afterwards i have no idea, i don't believe by itself the mod is causing this, it has too be something else conflicting with it but i'm not sure what, i do not crash nor does anything game breaking happen, i simply die, respond- but it says i need to respond again, and it says i die again after i hit respond, despite me being in a ghostly shape too- so then i hit respond, and my character's in this weird limbo of life in death, perfectly alive and healthy, but is sideways glitching and red tint all over it, showing that it's died or in a dying animation- i thought it was certain armor i wrote that triggered it, apparently not, i thought it was some curios item but that was also a no as well.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

curios, apothic curios, apotheosis, enigmatic leagcy, vampirism.

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
For sure, dying on respawn is not from my mod. You have to locate which mod is problematic.

**Comment by Vibin-crafter** [comment]
i just found out which mod it is i believe-!! unfortunately it seems like it only happen's with corail tombstone however! i had the simple gravestone mod not too long ago and it was not troublesome at all, now that i added this into the mix the problem has surfaced, and the problem that causes it i believe is enigmatic leagcy.

also btw this is my first ever time writing a issue on a github mod dev page so if i seem new too this i am sorry =w=

**Comment by Corail31** [comment]
It doesn't change that my mod handles drops on death, and is not related to death on respawn. You can probably have this happening without my mod.
