### ISSUE TITLE
Duplication with mules's chest and familiar stone

### ISSUE THREAD

**Issue by XeroXII** [Corail31/tombstone_lite#228]
### Minecraft Version

1.20.1

### Forge Version

47.3.1

### Corail Tombstone Version

tombstone-1.20.1-8.6.5

### What happened?

Tame a mule and put a chest on it, once killed, the stuff in the chest is dropped with saddle and once you revive the mule the stuff that was previously in the chest chest before it died is still there causing a duplication of the stuff inside the chest and the saddle.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You're right, unlike the Familiar Receptacle, the Familiar Stone doesn't remove the chest.
