### ISSUE TITLE
Controlled undead crash game upon taking damage

### ISSUE THREAD

**Issue by Atenge** [Corail31/tombstone_lite#229]
### Minecraft Version

1.20.1

### Forge Version

47.3.5

### Corail Tombstone Version

1.20.1-8.6.5 and 1.20.1 - 8.6.6

### What happened?

Using the ankh to control an undead (I did it with -4 alignment) will successfully make the undead your ally however as soon as the controlled mob takes damage the game will crash instantly. I discovered this initially when playing the ATM9 modpack however it also happens when using only corail tombstone versions 1.20.1-8.6.5 and 1.20.1-8.6.6

Note: I asked someone else to test this issue and they have had the same result (they are a little more familiar with code than I am and suspect that the issue is with casting an int to a float value)
hope this helps

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Log Link

https://pastebin.com/1QnE8Bb2

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Atenge** [comment]
https://pastebin.com/C3dvUfSK

Crash log for version 1.20.1-8.6.6

**Comment by Corail31** [comment]
You're right, it happens if you have an alignement -3 and below/+3 and higher (bad method description, since version 8.6.0).
https://github.com/AllTheMods/ATM-9/issues/1687
