### ISSUE TITLE
Xp Handling and "LevelUp!" mod

### ISSUE THREAD

**Issue by Sheppard22** [Corail31/tombstone_lite#23]
Hi. So, let me explain: This mod is about spending levels you have. I mean, you can spend your xp. If you die, with this mod you get back the levels you spended in this mod. LevelUp! has an option to lose the progression you have in the mod, or to keep it. Either way it's bad to get back the xp, of course.
Oh and i checked without tombstone and yes it works fine without it

Btw, i play with 100% xp loss, so it doesn't bothers me! Just telling you 👍

**Comment by Corail31** [comment]
Hi Sheppard22,
Xp is a config option, so it's to the user to choose what fit to his wish & mod pack. (and on server, you just follow the server config options)

**Comment by Corail31** [comment]
I discussed with Beeto, i'll disable the xp handling when 'Levels Up' is present in release 2.4.0
