### ISSUE TITLE
[Feature Request] Config Option to Enable Grave Key/Ender Pearl Recipe for Teleporting to Grave

### ISSUE THREAD

**Issue by p1ut0nium-git** [Corail31/tombstone_lite#23]
### Minecraft Version

1.16.5

### Forge Version

36.2.4

### Corail Tombstone Version

6.5.5

### What happened?

I'd really like my players to be able to use ender pearls + grave key to teleport to their graves (not the grave soul mechanic). Maybe an added config option to enable/disable this?

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I'm not sure if you're trolling about disabling decorative graves or if you don't know this recipe exists by default, but the issue form asks not to submit suggestions here.
Most features in Tombstone can be disabled in the config and it will automatically disable recipes or their visibility in the creative inventory. If you mean to disable to enchant with decorative graves, it's how the mod is built on.
You can change the rarity of soul to appear if it's the trouble in the config, you can set the "chance_enchanted_grave_key" config to -1, it will disable the Jailer perk.
If you're looking for a grave mod that doesn't use decorative graves, you probably want another grave mod.
Edit: i didn't see your other message so, i wasn't sure of the meaning of your issue; now, i know that you don't succeed to enchant grave's keys with the crafting table and you got an answer about it on the other issue.
