### ISSUE TITLE
More scroll drops from modded mods

### ISSUE THREAD

**Issue by Jeremias-zip** [Corail31/tombstone_lite#230]
### Minecraft Version

1.20.1

### Forge Version

47.3.0

### Corail Tombstone Version

8.6.7

### What happened?

Just like the #188 issue if you break the "Dungeon Door" from Valhelsia Structures, you get some scrolls, and you can place it again, so you can just repeat that over and over again to have a lot of them.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Valhelsia Structures

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Fixed in 8.6.8 for 1.20.1 (others versions will be released when they will get more changes)
