### ISSUE TITLE
Game Crash Ticking Entity (erroneous mixin related to alchemist perk and potion)

### ISSUE THREAD

**Issue by nevernever1** [Corail31/tombstone_lite#232]
### Forge Version

51.0.33

### Corail Tombstone Version

1.21-9.0.1

### What happened?

Game crashes at random times. Happens every 15 to 30 minutes of play. Error code -1. 

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Log Link

https://pastebin.com/tamdwHW3

**Comment by Corail31** [comment]
Hi Nevernever1,
Thanks you for your report and for drawing my attention to this code which requires improvements (related to potions and alchemist perk) as it's different from 1.20.1 ;)

Edit: I changed it in dev to a more satisfactory mixin, it will be published soon.
