### ISSUE TITLE
Error happening : Trying to add tag of type 10 to list of 1

### ISSUE THREAD

**Issue by 1kili2** [Corail31/tombstone_lite#234]
### Minecraft Version

1.19.2

### Forge Version

43.3.13

### Corail Tombstone Version

8.2.18

### What happened?

When I die the game has stopped generating a grave and key for me but it also doesn't drop my items and there's an error thrown in the server console, this didnt used to happen and for the other players its no issue they get a grave like normal but for me my items get completely deleted

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Log Link

https://pastebin.com/5TD4q6ss

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You didn't follow the issue template to test without others mods, i don't debug modpacks.
It's not reproductible in a sane environment. Your player datas are incorrect ("Trying to add tag of type 10 to list of 1").
Note that as it's not first time that i see this kind of report so, i will return a new list of the right type if it happens in the next release, this will solve your issue (i just need to finish to backport things to older versions so, in a few days...).

If you want a provisory solution, and the server owner wants to help you, he can:
- use the command /tbrecovery save_all_players (when you are online obviously)
- edit your last save in the folder "world folder"/tombstone/saved_players/"your uuid"
- remove the tag "tb_grave_locations:[]" in "ForgeData/PlayerPersisted" and save the file
- use the command /tbrecovery load_player "player name" "save name"
- optionally, tell me what was the content in this removed tag

**Comment by 1kili2** [comment]
Thank you for the provisory solutions, will be trying them out tomorrow to see if they work!

I also apologize for not following full procedure, I knew it would be a long shot and I initially tried looking for a discord or something to get some community feedback but there are no links to any kind of community on the curseforge page so I figured I'd shoot my shot here in hopes it was something you had seen before, also this is no excuse but I figured since I had no clue what was causing it and it didn't happen to any of the other players testing with just corail in a singleplayer world wasn't gonna give any issues.

Lastly I am hosting the server for my friends so I should be able to tell you what was the content of the removed tag, but since I'm incredibly incompetent in understanding minecraft crash and error reports I wouldn't even know what the tag is it's referring to so I don't know....

PS: If you know of a subreddit or another community that does enjoy debugging modpacks a reference would be great and maybe I could come back with some more specific details or learn that the cause was something completely separate, either way I would like to apologize again and thank you for the help!

**Comment by Corail31** [comment]
Don't be sorry, even if i tag your issue as invalid (because the modpack makes the issue not located), your report log was enough to look for a solution. I just don't know the origin even if it's not the first time that i see this error (also in mojang report).
Keep me informed about your test with tbrecovery as you're the server owner ;)

**Comment by Corail31** [comment]
@1kili2 You can test directly the new version ;)

**Comment by 1kili2** [comment]
Hadn't gotten around to trying anything yet as today was a busy day but just tested it, still happened before update, then updated just corail tombstone to the new version, tested it and i got a grave and a key, no errors in console or anything either

"[08:50:24] [Server thread/INFO] [minecraft/MinecraftServer]: 1kili2 fell out of the world
[08:50:24] [Server thread/INFO] [minecraft/MinecraftServer]: [1kili2: Killed 1kili2]
[08:50:24] [Server thread/INFO] [tombstone/]: The player 1kili2 has successfully been saved"
