### ISSUE TITLE
`Ankh of Pray` Naming

### ISSUE THREAD

**Issue by xavier630** [Corail31/tombstone_lite#235]
### Minecraft Version

1.20.1

### Forge Version

N/A

### Corail Tombstone Version

N/A

### What happened?

Hey Corail, I hope all is well.

I just wanted to raise a minor flag that `Ankh of Pray` doesn't quite make sense to me as a name. I feel that it would be more right in English to call it an `Ankh of Prayer` or `Ankh of Praying`.

Cheers,
Xavier

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, in general, the right translation for the meaning is the french one ("Ânkh de Prière").
I guess it should be "Ankh of Prayer" in english (but it's not my main language).
It will be changed in a future release.
