### ISSUE TITLE
Items get disorganized in the inventory every time you die.

### ISSUE THREAD

**Issue by Emperor339** [Corail31/tombstone_lite#238]
### Minecraft Version

1.20.1

### Forge Version

47.3.0

### Hybrid Server

I don't use

### Corail Tombstone Version

Corail Tombstone 8.6.7 for 1.20.1

### What happened?

Items get disorganized in the inventory every time you die.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

Yes

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, can you explain exactly what you mean by this ?
If you expect to have the items exactly at the same place that when you die, you probably forget that you can have multiple graves and recover them in different order (what would be the items to place at the exact place in this case ?).
There is anyway a logic in how they're restored on your player, they're equipped if possible, and in the order of how they dropped, then you have client configs to define some details in /tbgui (equip_elytra_in_priority, equip_curio_slot_magic_book, priorize_tool_on_hotbar, auto_equip_rule).

**Comment by Emperor339** [comment]
I will send photos for a better explanation

**Comment by Emperor339** [comment]
My inventory:
![1](https://github.com/user-attachments/assets/953a5e26-827c-4e23-90a9-0f2bfe5101d1)

I use /kill to kill myself
[2](https://github.com/user-attachments/assets/aa5efb7b-c20f-4007-bfeb-be7f25f397fb)

I open my grave
[3](https://github.com/user-attachments/assets/e23e762c-7ffb-41ea-9734-42cca9fb1215)

The items in the first slots of my hotbar stay in place, but they fill the two empty spaces I had, and the flowers get grouped together. Additionally, the other items in the upper part of my inventory do not retain their previous location or order at all. And my torch is no longer in my other hand.
![4](https://github.com/user-attachments/assets/c859253a-ce69-47f0-857f-a9ce6b4688a4)

Edit Corail31: Sorry to edit your message but, it's to be able to see the 2 images on one screen.

**Comment by Corail31** [comment]
Supposing that you have read my previous answer, what is the problem ? and how it should be different ? (saying that an empty space is filled is not a valid reason, items are stacked).
Is the problem related to have at least an empty slot in the hotbar to interact ?
Except this reason, i find the new inventory better arranged than before (the only reason that the offhand item is not kept is because it's not a shield (useable in offhand).
If it's to have a config to keep track of the offhand item even if it's not a shield, i can also do it.
But, if it's to have a potatoe in the middle of your inventory, i can't help you.
![screen](https://github.com/user-attachments/assets/93049b9a-13c0-4cf2-8b61-fb4da736beca)

**Comment by Emperor339** [comment]
Apologies, I didn’t explain myself very well, and I realize now that my message might not have come across as very polite. I apologize for that too. There are just two things I’d like to know if they can be configured:

1) That items remain in their original location.
2) (As you mentioned) That the off-hand item stays in its slot, even if it's a torch.

My inventory arranged my way.

Edit Corail31: in reverse order, no need additional screenshots.

**Comment by Corail31** [comment]
@Emperor339 
> That items remain in their original location.

So, you didn't even read the first answer.

> If you expect to have the items exactly at the same place that when you die, you probably forget that you can have multiple graves and recover them in different order (**what would be the items to place at the exact place in this case ?**).

> Supposing that you have read my previous answer

> But, if it's to have a potatoe in the middle of your inventory, i can't help you.

The case of the offhand can be changed as answered in my second message.

And i suppose you want a config to define the fill order (because another player could ask the actual order).

Sorry to clarify things, but i prefer to keep the discussion on the suggested solutions and not "noyer le poisson").

**Comment by Emperor339** [comment]
> If it's to have a config to keep track of the offhand item even if it's not a shield, i can also do it.

Yes, I would like to have a config to keep track of the offhand item even if it's not a shield. Pls

> Sorry to clarify things, but i prefer to keep the discussion on the suggested solutions and not "noyer le poisson").

I understand, thank you.

> But, if it's to have a potatoe in the middle of your inventory, i can't help you.

I'm just sad because I can't keep my potato in the middle of my inventory every time I retrieve my grave... :(

**Comment by Corail31** [comment]
@Emperor339 The changes have been implemented in dev.
- The offhand request is now the default behavior.
There is a client config 'equip_shield_in_ priority', disabled by default (similar to the config for elytra).
If you have others similar itemstacks in your inventory, they will be stacked to your offhand.
- There is a client config 'reverse_inventory_sorting', disabled by default, allowing to fill the last slots first.
This doesn't change how the hotbar is filled.

As precisions, theses 2 client configs are accessible in the Tombstone config screen in menu 'equipment' (by using the command /tbgui config or by assigning a keybind in minecraft config).
You can contact me on CurseForge if you want a "test" version.

**Comment by Emperor339** [comment]
(You can delete it if you want, it's just a question)


I don't see the "equip_shield_in_ priority". I suppose you mean that you'll implement it in an "alpha" or "beta" test version that you'll upload or send to me.
![1](https://github.com/user-attachments/assets/dd2ebe49-014d-4d35-8bf0-77ccea098b7e)

**Comment by Emperor339** [comment]
(You can delete it if you want, it's just a question)

I don't see the "equip_shield_in_ priority". I suppose you mean that you'll implement it in an "alpha" or "beta" test version that you'll upload or send to me.

**Comment by Corail31** [comment]
I provide a jar in general in private message ;)
I'll wait your opinion about the changes before preparing a new release (with others changes that i still need to backport from 1.21.1).

**Comment by Corail31** [comment]
It's published (8.7.2 for 1.20.1).

**Comment by Emperor339** [comment]
Good morning, I apologize for my absence, I was busy with exams. I tested the mod, and everything was working perfectly. However, when I died with an item in my off-hand, my armor didn’t equip automatically. This only happens if I have any type of item in my off-hand, whether it’s a torch, shield, or block. To clarify, if I don’t have anything in my off-hand, my armor equips normally. (This happens regardless of whether I have the "Equip Shield In Priority" setting set to Yes or No). This happens both in the version you sent me and in the latest version you released, "8.7.2".

Note: Thank you so much for addressing this request in your latest update, it's an excellent mod. It means a lot that you respond so quickly.

**Comment by GokuSayan01** [comment]
> Good morning, I apologize for my absence, I was busy with exams. I tested the mod, and everything was working perfectly. However, when I died with an item in my off-hand, my armor didn’t equip automatically. This only happens if I have any type of item in my off-hand, whether it’s a torch, shield, or block. To clarify, if I don’t have anything in my off-hand, my armor equips normally. (This happens regardless of whether I have the "Equip Shield In Priority" setting set to Yes or No). This happens both in the version you sent me and in the latest version you released, "8.7.2".
> 
> Note: Thank you so much for addressing this request in your latest update, it's an excellent mod. It means a lot that you respond so quickly.

I don't know how it's fixed, but the bug that armor isn't automatically equipped when you have a shield still exists.

**Comment by Corail31** [comment]
@Emperor339 Sorry, i only notice your message now (it's always better to contact me on CurseForge), and i confirm that there is a problem. I probably didn't saw it due to a soulbound armor :p
You can stay on 8.7.1 until i publish a new version (i thought that your only message on CurseForge was a confirmation that you tested it).

**Comment by Corail31** [comment]
Edit: fixed in 8.7.3
