### ISSUE TITLE
Problem with Tablet

### ISSUE THREAD

**Issue by IzWush** [Corail31/tombstone_lite#24]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2855

### Corail Tombstone Version

1.12.2-4.4.7

### What happened?

 Good morning ! I am trying to use the "Tablet Of Home", but when I right click or when I stay right click nothing happens even though I have a spawn point ... Would you have a solution? Thank you !

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I just test it to work, so there's something missing in your report (by sleeping in a bed, teleporting to nether and then using the scroll).
Edit : do you use Mohist or Sponge or anything that could be relevant ?
Be sure to check the tooltip of the scroll as in general, you have some additional informations (and it could be simply that your tablet isn't enchanted with a Soul).

**Comment by Corail31** [comment]
@IzWush if you open an issue, it means you're going to participate to that issue.
