### ISSUE TITLE
Feature request: Cancel Ghostly Shape if player breaks blocks, or X seconds after picking up their items

### ISSUE THREAD

**Issue by CplPibald** [Corail31/tombstone_lite#24]
I notice ghostly shape cancels if the player attacks a mob, but if the player doesn't attack, they can gather their death pile and then run out the timer with no mob interaction.  Players are using this to fully loot mob dungeons without bothering to kill the mobs.  They set a bed just outside the dungeon.  Then they intentionally get killed, and go back to collect their pile, loot all the chests, and break all the valuable blocks before the timer runs out.

I don't want to set the timer too short because it might legitimately take a long time to get back from your bed to your death location, but I'd like to see the effect end shortly after they pick up the pile so they can't just ignore the mobs while they pillage.

I'd like to see the following events also force ghostly shape to cancel.

1) Player breaks a block
2) 10-15 seconds (configurable?) after picking up their tombstone.  Just long enough to get away if you don't want to die to the same enemy again, but not so long you can do anything else.

Thank you.

**Comment by Corail31** [comment]
Hi CplPibald,
Indeed, there's the config option that can be put to a lower value.
I could also remove the effect when clicking the grave.
But, for the breaking, it was to avoid adding such a check in several events (right click and so on), as these tests slow down minecraft.

**Comment by CplPibald** [comment]
I see your point about block breaking.  I don't know if distance is a good proxy for time needed to get back because 200 blocks over extreme hills is very different than 200 blocks over plains.

For the block issue maybe just add a mining fatigue effect like an elder guardian gives so that until ghostly shape wears off you can't effectively break blocks.

For the time issue, I think it's easy to make it so that when you pick up your grave, if you have ghostly shape then the timer is reset down to 10s.

**Comment by Corail31** [comment]
nice idea the effect :+1: (for the time 5 sec should be enough)

**Comment by Corail31** [comment]
included in 2.5.0
