### ISSUE TITLE
Crash on load due to loottable id being null

### ISSUE THREAD

**Issue by Zelioth** [Corail31/tombstone_lite#242]
### Minecraft Version

1.21.1

### Framework Type

NeoForge

### Framework Version

21.1.54

### Hybrid Server

N/A

### Corail Tombstone Version

9.0.1

### What happened?

Client crashes on single player world load and reports CT as the crash 

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

Friends United 2.1 

### Log Link

https://gist.github.com/Zelioth/f62f6fcab010d4f43762b8c9ad8c8cfe

### Valid Launcher

- [X] Yes

**Comment by Zelioth** [comment]
[crash-2024-09-16_22.34.17-server.txt](https://github.com/user-attachments/files/17022577/crash-2024-09-16_22.34.17-server.txt)

**Comment by Corail31** [comment]
@Zelioth you checked in the issue form that is reproductible with only my mod but you provide a log containing others mods.
Note that the mod has been tested on dedicated server.

**Comment by Corail31** [comment]
@Zelioth Even if i could avoid it by checking loottables having a null lootTableId, this is a bug in another mod (lootTableId is not nullable). I recommand you to locate the mod making this happening and open an issue in that mod.

**Comment by Corail31** [comment]
@Zelioth 9.0.2 prevents the null loottable id to crash my code.
