### ISSUE TITLE
Tombstone loading Extra textures into minecraft:\textures\atlas\blocks.png

### ISSUE THREAD

**Issue by I2pRandom** [Corail31/tombstone_lite#243]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.3.6

### Corail Tombstone Version

8.7.3

### What happened?

Identified CorailTombstone is loading extra effect textures from other mods, via assets\minecraft\atlases\blocks.json
```java
{
    "sources": [
        {
            "type": "directory",
            "source": "particle",
            "prefix": "particle/"
        },
        {
            "type": "directory",
            "source": "mob_effect",
            "prefix": "mob_effect/"
        }
    ]
}
```
![image](https://github.com/user-attachments/assets/b43e175f-4f63-4242-8013-12ca4d230a90)
Identified via AtlasViewer 

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Other relevant mods

https://modrinth.com/mod/create-steam-n-rails

### Log Link

https://gist.github.com/I2pRandom/5cd45cf49065ef1c8aa5c46fcb1ac67a

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@I2pRandom Nice catch, this seems to be a leftover from the initial port, it will be replaced by single entries in the next release.
