### ISSUE TITLE
`Accessories` Compat

### ISSUE THREAD

**Issue by thecreare** [Corail31/tombstone_lite#244]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.3.0

### Corail Tombstone Version

8.7.4

### What happened?

When dying with equipped accessories from the [accessories mod](https://github.com/wisp-forest/accessories) the accessories do not enter the tombstone and instead float around similar to how you die in vanilla

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

https://github.com/wisp-forest/accessories

### Valid Launcher

- [x] Yes

**Comment by Corail31** [comment]
If accessories are not in the tombstone , it's a bug in the other mod (their unequiped items just need to be in the drop event, it's simple).
Consider to open an issue in that mod. Also, note that 'Accessories' seems to have an incompatibility with 'Player Revive'.

**Comment by Corail31** [comment]
https://github.com/wisp-forest/accessories/issues/78

**Comment by Corail31** [comment]
https://github.com/wisp-forest/accessories/issues/136
