### ISSUE TITLE
Incompatibility with the Sync Re-Ported mod

### ISSUE THREAD

**Issue by DrSigma4164** [Corail31/tombstone_lite#245]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.3.1

### Corail Tombstone Version

8.7.4

### What happened?

There is a Sync Re-Ported mod for version 1.20.1, it is ported to fabric, but using the Sinytra Connector mod it can be run on forge. It allows you to create clones and move control between them. Each of them has its own inventory. When one of the clones dies, if you were in it, you are "sent" back to the original shell, while the death screen is not shown, and it is as if we did not die, but a grave with the clone's items is created.
The essence of the problem is that when the clone you controlled dies and control is returned to the main body, a grave is created, but the key to it is not given when returning, you can manually take items from the grave, but at the next death of the main body , you are given two keys, from the grave of the clone and the original.
My suggestion for compatibility is this: when you die while controlling the clone, the key should give 2-3 seconds after, since there is still an animation going on.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Other relevant mods

Sync Re-Ported

### Log Link

https://gist.github.com/DrSigma4164/7be59aa7d62cda37e6dd9cd50a1b1bdf

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I remember IChun's mod, and have already tested it in the past.
From your explanation, it's not possible to get 2 keys after: the first one was probably present but not visible in inventory, or the respawn event is not fired (preventing to restore the key in inventory).

As additional infos: You don't need a key to open a grave. The key is stored in the player when the drops are handled and restored later in the respawn event. If a grave is not present, the key will vanish after some seconds/minutes (depending if you're near the grave or not, and if the key is 'selected' in hand or not, and in the same dimension).

Edit : i think the right reason is the second (the respawn event not being fired). I suppose that you can ask to the other modder if i'm right and if he can call this respawn event. (obviously, it's a fabric mod but to be compatible, it's needed to call this event, with 'reflection', as it's not only about grave's keys, it's about any soulbound items).

I only found the mod on Modrinth for 1.20.1 and it's marked as 'not maintained' (with few downloads), so i don't think i can do something as i have no way to know when it's a dying clone or the original (and using the 'clone' event would bring more troubles).
