### ISSUE TITLE
Wrong title

### ISSUE THREAD

**Issue by kezmodius** [Corail31/tombstone_lite#246]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.3.0

### Hybrid Server

Dedicated Forge Server

### Corail Tombstone Version

1.20.1-8.7.4

### What happened?

keepInventory is on. I died. An item was removed on death. A sophisticated backpack (gold level) totally full. I expected to keep my  items. My other players have also been complaining about the same thing.
I tested it in SP with only Corail Tombstone, Curios and Sophisticated backpacks and I couldn't reproduce.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Other relevant mods

Sophisticated Backpacks, Curios and Player Respawn are all I can think of

### Log Link

https://gist.github.com/kezmodius/6fd306f8579be7106c8ae0f32b5d3a01

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Don't say stupid things. I check if keep inventory is on and any player knows this.
If you are not able to check the real reason (Ketting or another Hybrid Server), don't spend your time to open reports.
Note that even if you have keep inventory, and if the backpack can be equiped, it's perhaps just equiped in a Curio Slot...
Additionally, the command /tbrecovery is not just there "pour faire joli".
