### ISSUE TITLE
Items duplicated by reviving a Familiar (by using command?)

### ISSUE THREAD

**Issue by AntonioKeyxer** [Corail31/tombstone_lite#247]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.3.0

### Corail Tombstone Version

8.7.4

### What happened?

When you give a familiar mob, like a Zombie, an item such as a sword, and then kill the zombie, it will drop the sword. However, if you revive the zombie, it will come back holding the same sword that it dropped earlier. This allows you to kill the zombie again and make it drop another sword, repeating the process. This issue isn't limited to swords — it happens with any item. In short, you can duplicate items infinitely.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I tested it to work properly with a zombie (the sword won't be dropped unlike your explanation).
Supposing that you use a Receptacle of Familiar to revive it (commands are not considered as gameplay).
