### ISSUE TITLE
Particles are allocating more memory over time

### ISSUE THREAD

**Issue by Wizqok** [Corail31/tombstone_lite#248]
### Minecraft Version

1.21.1

### Framework Type

NeoForge

### Framework Version

21.1.55, 21.1.66

### Corail Tombstone Version

tombstone-neoforge-1.21.1-9.0.3

### What happened?

Hi, i think i found a problem with your mod here, seems that standing near couple of graves leading to a memory leak through particle effects (i'm not an expert, just assuming) however noticed that on our server after seeing fps drop from 120 to 20, after narrowd down with a heapdump, i tested it without any other mods. And by just standing in render distance to the grave bloating the gamerenderer and raises allocation rate and memory allocation.
Leaving the area dont fix it, the memory allocation still growing, only changing dimension kills the loop.
Hope i could help with these infos.
BR

![2024-10-07_14 31 18](https://github.com/user-attachments/assets/5544a42e-5800-4508-8d64-9d30305efb4a)

![{C6831D50-1CBB-4FE4-8DC5-D63A767B00E4}](https://github.com/user-attachments/assets/42a87a39-cb80-47be-9409-074845eb2e7a)

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

Yes

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
My particles are loaded only on client side (and render is not on server side). Closed.
Lastest version is also 9.1.0, so if you noticed a difference of tps on your 'server' between 9.0.2 and 9.0.3, it's probably the version that you need (personally, when i test, the fps is always at max). Then, about memory leaks, no comment because your screen doesn't mean anything about my particles (0%).
~~Edit: now, you're blocked as a troll for spamming my mod page with fake informations as you seem unable to understand my answer here.~~

**Comment by Corail31** [comment]
@Wizqok Sorry for having doubt about your report (but i don't like spam on my mod page and i think i badly read the mean of your message about 'server').

I made a serie of tests:
- in 1.20.1 and below: the allocated memory doesn't change over time with multiple graves with soul
- in 1.21.1 (forge & neoforge): having graves don't change memory allocated, but having souls over multiple graves will change it relatively fast

Actually, i have no clue about the reason (as the code is nearly similar to 1.20.1) but i will find the reason soon.
Edit: multiple creation of 'ParticleRenderType' was the problem and is solved in dev, a new release is expected for tomorrow as i don't like this kind of bug.
![test_soul](https://github.com/user-attachments/assets/0c8a570e-5527-404c-9878-b13517961a9f)
