### ISSUE TITLE
Undead Merchant crashing server

### ISSUE THREAD

**Issue by ghost** [Corail31/tombstone_lite#25]
### Minecraft Version

1.16.5

### Forge Version

36.2.6

### Corail Tombstone Version

6.5.3

### What happened?

Undead Merchant (ovh.corail.tombstone.entity.AbstractMerchant) causing server to crash when trying to spawn (I think?).

### Log Link

https://pastebin.com/4tgreBHi

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

No

### Other relevant mods

AMT6 Modpack (Version 1.8.7)

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Next time, make sure to update your version, and read the changelog, more over if you're on a modpack already informed on this and already having updated it.
