### ISSUE TITLE
[1.12] Knowledge of death keybinding is not saved

### ISSUE THREAD

**Issue by CplPibald** [Corail31/tombstone_lite#25]
tombstone-3.2.1-1.12
on Forge 14.23.5.2768

1. Go to Options->Controls and change the keybind for "Knowledge of Death" from default (NONE) to a key (eg: K)
2. Quit and restart Minecraft
3. Go to Controls menu again and view keybinding

Expected: Key is bound to 'K'
Actual: Key is bound to 'NONE'

**Comment by Corail31** [comment]
Hi CplPibald, and thanks for the interest to my mod.
So, i made tests and you're right, and it's already fixed for the next release :)
NB : the key will also be in a custom category
