### ISSUE TITLE
Exception ticking world 

### ISSUE THREAD

**Issue by cowardlyDog** [Corail31/tombstone_lite#25]
Version: tombstone-2.4.0-1.12

[Crash report](https://pastebin.com/PzJxWzFS)

**Comment by Corail31** [comment]
disabled the feature for now in the config, to be able to check what's wrong

**Comment by cowardlyDog** [comment]
Thanks. I doubt this has anything to do with it but just In case it helps.. it happened when I was on JEI searching for something and I pressed the down/up arrow then it immediately crashed

**Comment by Corail31** [comment]
no, it's my fault, i removed a null check.
