### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by iLLHunter** [Corail31/tombstone_lite#250]
### Minecraft Version

1.12.2

### Framework Type

Forge

### Framework Version

14.23.5.2855

### Corail Tombstone Version

tombstone-1.12.2-4.6.8.jar

### What happened?

not sure how I died, I was afk but when I came back I was dead. I respawned and returned to site of death... no grave. I had a bunch of expensive hard to make items, armor, a backpack full of tools and loot, but no grave to save any of it

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
When you die, you receive a 'Tombstone' message (that you didn't even provide here).
You have the command tbrecovery to recover your inventory.
Your informations are invalid (occurs all the time, you don't even know what happen because you were absent).
1.12.2 version exists since ages, it's nearly impossible to not have a player grave (except if a mod is doing something wrong bypassing the drop event like setHealth 0). Lastest version is also 4.7.0

**Comment by iLLHunter** [comment]
I can see "closing tickets" is more important to you than "providing help" or "resolving issues".
When I came to your issues page and saw 0 open I thought "here's a person who thinks their code is effing perfect. this might be interesting" 

You closed this as 'invalid' without providing any troubleshooting, which is what we come here for.

Thank you for that tbrecovery command, i was able to restore items, but this is a valid report.
 
It does happen 'all the time' according to your selection in ticket submission. I have only died twice, the other time I had barely any gear and I made a conclusion 'the grave must have spawned somewhere underneath me' so I did not care much since nothing was lost and that incident was not worthy of investigation. 

The only other time I died was this incident so that is 'all the time' 

I don't know what happened to cause my death, but I was around after death, then re-spawned and returned to the site of death only to not find any grave there either. 

I am looking for troubleshooting help. Please provide things I can check or look for to figure out why the mod fails to create grave

**Comment by Corail31** [comment]
The first thing that i said you is you get a message from Tombstone when you die, explaining you if you got a grave or not.
If you don't get this message, it means that one of your mods is breaking the death handling.
Then , the **issue template** asks you **to test without any other mod, or to locate the mod bringing a problem**.
Next time, you will read the issue template correctly, for sure, graves are working, why i don't spend time on this if you don't bring the correct informations.
It's not a dropbox to put issues by using tons of mods and then requesting help.

Your report, wow: you don't pay by words used in your report, you know!

> not sure how I died, I was afk but when I came back I was dead. I respawned and returned to site of death... no grave. I had a bunch of expensive hard to make items, armor, a backpack full of tools and loot, but no grave to save any of it

You were not trying to explain your problem, you were saying more likely the list of lost items (even if a command exists to restore them). You didn't mention if you get a grave's key or not, or test a third time to be sure of your explanation (now that you remember that it happened before).
