### ISSUE TITLE
Potion of giant strength is horribly op

### ISSUE THREAD

**Issue by schindlershadow** [Corail31/tombstone_lite#251]
### Minecraft Version

1.21.1

### Framework Type

NeoForge

### Framework Version

21.1.42

### Corail Tombstone Version

9.1.1

### What happened?

Potion of giant strength is horribly op with no config or datapack option to disable. +50 attack damage is way too much, even +5 would be too much. all for the cost of a red mushroom and some grave dust

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hello,
I have no special opinion about this, but i can let the issue opened to let others players give their opinions.
So to provide more informations:

- this potion only exists in 1.21 and is an effect level 5 (10 damages by level)
- your size doesn't allow you to move everywhere
- you can combine the "Little World" potion to benefit of the 2 effects with a normal size
- Minecraft DamageBoost effect is 3 damages by level (potion of Strong Strength is level 2)
- the ingredient could be different if it's so easy to find for you

**Comment by schindlershadow** [comment]
at least a config to disable it would be appreciated. a datapack option to change the recipe would be nice. 
you cannot run a pvp server when all it takes is 2 easy to find ingredients to one shot everyone with your fists

**Comment by Corail31** [comment]
Yes, i already think about some adjustments (10 damages/level looks too high, but i think i initially made it a single level effect so, 10 damages, that i changed later and forgot to change the damage bonus) and some configs for each potion (without featureFlag) is a good point. But, i'll also wait some suggestions.
Personally, i didn't think to pvp when i did this, i thought to the advancement and i also enjoyed going between blocks of 1 block height :p

Edit:
I already made some changes (and they can still change):

- configs to enable each potion
- reduces the damage bonus to 3 damages / level (so, 15)

Some ideas:

- use 'Strong Strength Potion' as ingredient for 'Giant Strength' and 'Strong Swiftness Potion' for 'Little World'
- config to allow to combine 'Giant Strength' and 'Little World' (but could look strange if one potion removes the other from my tests when i did this code)

**Comment by Corail31** [comment]
@schindlershadow If you can confirm me that you're fine with theses 2 changes and don't need anything else because the new release is soon.

**Comment by schindlershadow** [comment]
yes these changes sound good but I would also like a config to completely disable them just in case

**Comment by Corail31** [comment]
@schindlershadow The configs allow to disable them (they're enabled by default), more precisely, it disables the recipe to create them (and can be changed while in game and have been tested).
