### ISSUE TITLE
Book of Disenchantment does not remove enchantment

### ISSUE THREAD

**Issue by schindlershadow** [Corail31/tombstone_lite#252]
### Minecraft Version

1.21.1

### Framework Type

NeoForge

### Framework Version

21.1.62

### Corail Tombstone Version

9.1.1

### What happened?

using the Book of Disenchantment gives you the enchanted book but does not remove enchantment from the item, duping the enchantment 

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

Yes

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@schindlershadow Thanks for the report ;) Don't hesitate if you find others bugs.
