### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by funnycubeguy** [Corail31/tombstone_lite#253]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

atm9

### Corail Tombstone Version

tombstone-1.20.1-8.7.1.jar

### What happened?

Please please please get rid of the halloween event by default, or at the very least please let the server config file force disable this event. Big servers it's so bad, every single player complains about it then the entire chat for days is "run /tbgui this corail junk mod has a halloween even", it's super annoying and ruins the server.

thanks

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Other relevant mods

atm9 modpack

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
There is a config to disable the Ghost. Perks are also disableable. Your opinion is yours but i don't like trolls.
Additionally, ghost doesn't spawn as long as you pray on graves during Halloween (as long as the ankh is in cooldown more precisely) which is the gameplay way to avoid it.
FYI: in Belgium and France, there is the "fête des morts" during Halloween where everyone pays homage to the graves of loved ones.
