### ISSUE TITLE
Crash on resetting grave guardian spawn position [Canary]

### ISSUE THREAD

**Issue by AnyankaT** [Corail31/tombstone_lite#254]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

47.2.23

### Corail Tombstone Version

tombstone-1.20.1-8.8.1.jar

### What happened?

After upgrading the server and modpack with this version of tombstone, one particular player logging on to the server immediately caused the server to crash. It's location based, not player based, and it has something to do with the two Grave Guardians near his base. He doesn't even know how he got two Guardians, but yesterday with 8.8.0 there was no crash.

Downgrading to 8.0.0 in modpack and server stopped the crash.

One of the crashlogs is attached.

I can't test with only Tombstone - I can't reproduce the situation, since it's only at his location this happened.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Log Link

https://gist.github.com/AnyankaT/73065a434fb490f66b09be9a35e4201a

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's related to 'Canary' mod. The Grave Guardian checks its spawn position based on ticking blockentities to find a decorative grave.
The best that i could do is to try/catch to prevent the problem with theses "SleepingBlockEntity".

**Comment by AnyankaT** [comment]
So do you suggest - at least for now - that I remove Canary?

**Comment by Corail31** [comment]
You have 2 choices:

- stay on a previous version (8.8.0)
- remove 'Canary' just the time to load the world to allow the Grave Guardians to reset their pos (the code is done once as long as the chunks are loaded).

The good news is 'Canary' is not on 1.21.1 so, i could do a 1.20.1 release soon ;)

**Comment by AnyankaT** [comment]
Thanks for your help! Guess I'll leave it on the older version for now until I can manage another mod pack update.

**Comment by Corail31** [comment]
Thanks for your report too, i prefer to be informed of unexpected incompatibilities ;)

**Comment by AnyankaT** [comment]
I just realized… I'm going to have to find ALL the grave guardians on the server to update... 

I think this might be the final straw on Canary.

**Comment by Corail31** [comment]
You know sometimes in minecraft modding : not everything is black or white ;) An incompatibility is just an incompatibility and can be solved most of the time.
I won't blame the other mod: it's doing performance improvements and in my case, i use a list of ticking blocks to avoid to 'search' for decorative graves.
My next release 1.20.1 is probably tomorrow.

**Comment by Corail31** [comment]
@AnyankaT ~~Can you try to make this problem happening with only Canary ? because i can't make this happening in singleplayer.~~
Edit : Ah, i succeed to crash the game, i guess that your **canary 'properties'** in config folder are set with the option for **'mixin.world.block_entity_ticking' that you can disable**.

**Comment by AnyankaT** [comment]
Thanks, I will. For the time being I've had to roll my modpack back a version - there were other issues as well apparently - and I can work on it in the coming days.
