### ISSUE TITLE
Players cannot respawn after death due to Sleep tigh mod

### ISSUE THREAD

**Issue by Astral-SqZ** [Corail31/tombstone_lite#255]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

forge-47.3.11

### Corail Tombstone Version

tombstone-1.20.1-8.8.2

### What happened?

Players cannot respawn after death if using [sleep tight](https://www.curseforge.com/minecraft/mc-mods/sleep-tight) mod and config `sleep_tight-common.toml/only_respawn_in_home_bed = true` together (when a bed state is 'home bed' already). 

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

sleep_tight-1.20-1.1.19, moonlight-1.20-2.12.6-forge

### Log Link

https://github.com/user-attachments/files/17507487/debug.log

### Valid Launcher

- [x] Yes

**Comment by Corail31** [comment]
Hello, sleep tight has a bug of capability. My mod doesn't change anything on respawn. It's only a bug on this mod.
The bug can probably happen with only this mod.
