### ISSUE TITLE
Bag of Seeds

### ISSUE THREAD

**Issue by KingSkel** [Corail31/tombstone_lite#257]
### Minecraft Version

1.21.1

### Framework Type

NeoForge

### Framework Version

What Framework?

### Corail Tombstone Version

9.1.2

### What happened?

30 minutes into a new save I used a bag of seeds and received awakened draconium seeds from mystical agradditions which are too OP this early, and also don't exist because I don't have that mod installed.
I know I can disable the bag, but I'd rather not if I can avoid it.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Other relevant mods

mystical agradditions

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You should consider that i don't make a mod for specific modpack.
The Bag of Seeds has a chance of 2% to drop on undeads and only if you kill it yourself.
If you use mod allowing to create 'farm' using a player context, it's your problem and illogic (why not playing directly in creative mode at this stage).
As i mentioned multiple times, there is a 'tombstone:seeds' tag to define the seeds in the bag (can be changed with a datapack or a tweak mod) and the loot chance can be edited in loottables too (in config folder in recent versions).
Also, note that you can only receive items being present in your modlist, even if you say that you don't have the mod installed.
I will probably use the item rarity in the future (knowing it has been reworked in 1.21.2).
