### ISSUE TITLE
Grave Guardian Holiday Overlap

### ISSUE THREAD

**Issue by BingusDepartment** [Corail31/tombstone_lite#258]
### Minecraft Version

1.16.5

### Framework Type

Forge

### Framework Version

36.2.42

### Corail Tombstone Version

6.9.2

### What happened?

Hi, minor graphical bug I think; but I noticed yesterday (October 29th, first day I got back into Minecraft since last year and updated many mods including Corail Tombstone) that the Grave Guardians had both their Halloween and Christmas decorations on at the same time. I don't recall if I had ever seen the holiday skins overlap like this before when playing with previous Corail versions around this same time of year. Today (Oct 30th) they are still the same.
![bin Screenshot 2024 10 30 - 17 20 44 10](https://github.com/user-attachments/assets/38b43332-5dd0-42e9-ac42-cc546cb3f1a7)

Possibly too many details but I just want to note some other things I noticed *weren't* happening:
-The GUI only says it's Halloween for seasonal events
-The graves (set to default appearance) are Halloween as well
-The guardian trades are the candy-related Halloween ones, no Christmas present quests or anything

So everything is Halloween except the Guardians have their Christmas hats on. It also happens with newly spawned Grave Guardians as well as ones that have been around since previous Corail versions in our server. (This happens in singleplayer too.)

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone on Forge (required)

No

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Strange, i'll check this as it's probably only happening in 1.16.5.

**Comment by Corail31** [comment]
There was a little bug in the code to render the armor helmet in 1.16.5 (as it's more a "transmogrification", the real armor of the Grave Guardian doesn't change), it will be published soon.

**Comment by Corail31** [comment]
@BingusDepartment resolved in 6.9.3 for 1.16.5
