### ISSUE TITLE
[Minor] Disenchantment Book unexpected behavior.

### ISSUE THREAD

**Issue by alxcool** [Corail31/tombstone_lite#26]
[latest.log](https://github.com/Corail31/tombstone_lite/files/2483782/latest.log)

Hi! I really like your work! Thk for Tombstone! Lately I've tried to complete all the achivement, then by learning some more about it, I can not do without it! So here the thing, I've found something not working.

Forge 2705
Botania+r1.10-356
Baubles-1.12-1.5.2
tombstone-3.2.2-1.12

I just finish Running a test, with theses 3 mods alone to be sure.

What happen and how to reproduce.
A) Enchant a Mana sword from Botania
B) Set up a grave with soul then try to use a disenchantment book.
C) [...] Nothing special in-game except an unexpected behavior
c) Inside latest.log we could read ... [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

Note : Instead of removing enchantments from the items, the item's data is kept unchanged and the tombstone book, is replaced by an enchantment book who only contain the first, or just one of the enchantments.

After reproducing this, I've tried to unenchant a vanilla diamond sword. I had the same result. Is it possible that the only probleme here is my forge's version? I use 2705, mostly because I'm actually playing with thaumcraft, and that last one is not compatible with newer versions...

So I'l take time to say hi, I really enjoy your work! Note, I will try an another test, with tombstone alone, then update this comment only if this test have a different result.

**Comment by alxcool** [comment]
This is weird! I've just run a test, only with tombstone and with a forge version of 2768 and I've got the same result... as ingame... Let see if it make a difference about : 
[latest.log](https://github.com/Corail31/tombstone_lite/files/2483870/latest.log)

**Comment by Corail31** [comment]
Don't worry about forge version, tombstone always uses the 2611 ;)
I'll make tests to keep you update on this :)

**Comment by alxcool** [comment]
I remember this item was working fine, about 2 month ago... din't used it since today... I will try to find which version make it work... might be 3-5 previous ones

**Comment by Corail31** [comment]
It's ok Alxcool, and i'll just make some tests later before publishing the release (don't search the version so)

**Comment by alxcool** [comment]
Disenchantment is Functional : 
- tombstone-3.1.0-1.12	7 sept
- tombstone-3.1.1-1.12	15 sept
- tombstone-3.1.2-1.12	21 sept

Not functionnal :
- tombstone-3.2.0-1.12	2 octo
 ...
Well ok... It took me time, sorry

**Comment by Corail31** [comment]
contact me on curse ;)
