### ISSUE TITLE
Removes "->" in enchantment description translation

### ISSUE THREAD

**Issue by VaporeonScripts** [Corail31/tombstone_lite#260]
### Minecraft Version

1.21.1

### Framework Type

NeoForge

### Framework Version

latest

### Hybrid Server

no

### Corail Tombstone Version

latest

### What happened?

its useless and annoying, if this cant be done, please provide the enchant format (like: 'enchantment.tombston.enchantname.desc' )

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone on Forge/NeoForge (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

no

### Log Link

no

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I don't know what you mean but if it's related to a mod called "enchantment description", you should consider to open an issue on their github. Also, all tombstone enchantments have a description in that format.
Next time that you don't provide a correct description of your issue, it will be closed with no message.

**Comment by VaporeonScripts** [comment]
not related to that mod,as the mod is not present, i mean this
![image](https://github.com/user-attachments/assets/4705f796-50cd-4aa4-9c78-509cb970fcfb)

**Comment by VaporeonScripts** [comment]
sorry for not describing correctly the issue

**Comment by VaporeonScripts** [comment]
hopefully, managed to temp fix it by kubejs :grin: 
![image](https://github.com/user-attachments/assets/0677a9ee-07f2-4085-810c-299c01018d34)

**Comment by Corail31** [comment]
Ho but your title is not enougly correct ! You mean "->" !
Yes, i could be change the translations for next release even if the "arrow" was added to make a difference with enchantment title but the gray color could be enough.
![description](https://github.com/user-attachments/assets/7486b6c3-d6dd-4ca5-b45a-844c5f826f4d)

**Comment by VaporeonScripts** [comment]
alright,tyy
