### ISSUE TITLE
Grave placement when dying in water with config "grave_in_water" disabled

### ISSUE THREAD

**Issue by Teboran** [Corail31/tombstone_lite#261]
### Minecraft Version

1.21.1

### Framework Type

NeoForge

### Framework Version

21.1.72

### Corail Tombstone Version

1.21.1-9.1.2

### What happened?

Client config set to not allow graves to spawn in water.

Expected to spawn near death but out of the water. Grave spawns at world spawn instead. Testing with just Tombstone the grave was close tp spawn but far from my death point.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone on Forge/NeoForge (required)

Yes

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Teboran** [comment]
Tested again with 9.1.7 version and the same thing happens.
![2024-11-15_14 34 58](https://github.com/user-attachments/assets/fbf50ae1-6e3b-4a07-ad3e-e5d2ed4bc8db)
![2024-11-15_14 35 27](https://github.com/user-attachments/assets/5168bf10-c017-454f-be4b-37abe9d02b2b)

**Comment by Corail31** [comment]
Except if you created a world in creative mode, flew to a location where no grave is possible and have no bed location, you won't have a grave at the starting overworld position. So, you checked "occurs all the time", i made a test and it wasn't the case.

**Comment by Teboran** [comment]
I didn't create the world in creative mode. even using a bed the grave spawned about 150 blocks to the southwest instead of the shoreline 10 blocks the the south.

**Comment by Corail31** [comment]
Ok, but it doesn't happen when i test myself and latest is 9.1.7. The only thing that i noticed is if the "grave_in_water" is disabled in config, it won't consider the water as a possible ground for graves, but it doesn't change that a grave won't be created at overworld sharedpos.

**Comment by Teboran** [comment]
On my server my base is over 5000 blocks away from spawn with a bed, but my grave is at world spawn if set to not allow graves in water. I've had to also help people get their graves with water allowed because the grave ends up in another cave underwater.

**Comment by Teboran** [comment]
The deleted pics showed me dead in the ocean with kelp (I was just off the shore) and then the grave by a river to the southwest.

**Comment by Corail31** [comment]
@Teboran I finally found something not working as expected. I recommand you anyway to enable the option "grave_in_water" that you disabled.

**Comment by Teboran** [comment]
I will re-enable it for now. The problem with it being set to allow is people end up with their graves in unconnected caves and sometimes the cave is waterlogged. starts a deathloop easily while they find their pick and in the dark.

**Comment by Corail31** [comment]
Can you test with 9.1.1 ? because there was a minor change in 9.1.2 and i'm still checking it.

**Comment by Teboran** [comment]
will check it

**Comment by Corail31** [comment]
@Teboran Don't, it wasn't problematic by checking. I'll make more tests tomorrow.

**Comment by Teboran** [comment]
Grave spawns by my bed even after moving and resetting my spawn. Consistently.

**Comment by Corail31** [comment]
@Teboran Ok, i located the problem (since 9.1.0), it will be published tomorrow.
Note that i recommand you to re-enable the config "grave_in_water" (which is the default), as the grave will be created at your death position (and not in an underground cave).

**Comment by Teboran** [comment]
Thank you for your time.
