### ISSUE TITLE
Invalid [Blood Magic]

### ISSUE THREAD

**Issue by vinnyg0621** [Corail31/tombstone_lite#264]
### Minecraft Version

1.20.1

### Framework Type

Forge

### Framework Version

?

### Corail Tombstone Version

8.8.4

### What happened?

when I lost to a zombie brute, I died and the client crashed.
i can't play my survival world anymore, someone please help **immediately**!!!!
using modpack all the mods 9

crash report: https://mclo.gs/VLcs4iN

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge/NeoForge (required)

No

### Occurence

occurs all the time

### Other relevant mods

modpack: all the mods 9

### Log Link

https://mclo.gs/gPw0o8T

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
As far as i know, ATM 9 didn't crash before.
The report mentions Embedium, so why do you open an issue in my mod ?
If it can help, try to remove ModdernFix (as there is the mixin "bugfix.entity_pose_stack" before your crash with embeddium).
Also note that ModdernFix can disable some functionalities in their config.
https://github.com/AllTheMods/ATM-9/issues/2157
https://github.com/FiniteReality/embeddium/issues/423

**Comment by vinnyg0621** [comment]
it's spelled embeddium not embedium.
 and it's modernfix not moddernfix, too.

**Comment by Corail31** [comment]
Et je parle français donc, voilà, il faut faire avec mes fautes d'anglais ^^
Vous devriez en profiter pour tester si le problème venait bien de ModernFix (vu que le nom du mixin semblait coïncider avec l'erreur) plutôt que de chipoter sur les mots employés (surtout pour quelqu'un qui souhaitait de l'aide rapidement).

**Comment by DatBoiOmonie** [comment]
> Et je parle français donc, voilà, il faut faire avec mes fautes d'anglais ^^ Vous devriez en profiter pour tester si le problème venait bien de ModernFix (vu que le nom du mixin semblait coïncider avec l'erreur) plutôt que de chipoter sur les mots employés (surtout pour quelqu'un qui souhaitait de l'aide rapidement).

lmao sorry you have to deal with weirdos like that, we others appreciate you. don't mind this oddball. i'm having a similar crash i will try to remove modernfix to see if it fixes anything.

**Comment by Corail31** [comment]
@DatBoiOmonie Sorry to not have seen your message sooner, it's related to BloodMagic as explained by Embeddium modder ;) 
https://github.com/WayofTime/BloodMagic/issues/2063
