### ISSUE TITLE
Lost Tablet never awakens.

### ISSUE THREAD

**Issue by xtended2l** [Corail31/tombstone_lite#265]
### Minecraft Version

1.21.1

### Framework Type

NeoForge

### Framework Version

21.1.83

### Corail Tombstone Version

1.21.1-9.1.10

### What happened?

Lost Tablet, captured using enchanted fishing rod of misadventure, never awakens.

I captured two of these, and they just keep shaking when you hold them in hand. In previous versions of modpack it should awaken in a couple of minutes. I was waiting for hours, carrying them around, etc.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge/NeoForge (required)

No

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It has already been fixed in 9.1.10 (and tested).

**Comment by xtended2l** [comment]
Sorry, had busy week.

**Comment by Corail31** [comment]
@xtended2l no prob, it's fine to let an issue about this ;)
