### ISSUE TITLE
Giant Strength potion is uncraftable

### ISSUE THREAD

**Issue by SirKingSebas** [Corail31/tombstone_lite#266]
### Minecraft Version

1.21.1

### Framework Type

NeoForge

### Framework Version

1.27

### Corail Tombstone Version

9.1.10

### What happened?

trying to brew a giant strength potion does not work, im not sure how to do it at this point

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone on Forge/NeoForge (required)

No

### Occurence

occurs all the time

### Other relevant mods

iron's spells?

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@SirKingSebas Did you try with a "spectral potion" (water potion with a grave dust) with a red_mushroom ?

**Comment by SirKingSebas** [comment]
> @SirKingSebas Did you try with a "spectral potion" (water potion with a grave dust) with a red_mushroom ?

i did, i tried a variety of ways, even tossing things inside

**Comment by SirKingSebas** [comment]
@Corail31 i also tested everything in single player, it just doesnt work at all

**Comment by Corail31** [comment]
I tested it to work properly, make sure to locate the mod creating this issue.
If you're using a modpack, make sure to check that the config "allow_giant_strength" (category Potions) is set to true in "tombstone-server.toml".

![potion_of_giant_strength](https://github.com/user-attachments/assets/05849209-3fe3-427d-be72-18666675e5a7)

**Comment by SirKingSebas** [comment]
oooooh it works in a brewing stand :D

**Comment by Corail31** [comment]
What do you use to brew your potions instead of the brewing stand ?
