### ISSUE TITLE
Enchanted Keys

### ISSUE THREAD

**Issue by Mobuid** [Corail31/tombstone_lite#267]
### Minecraft Version

1.21.1, 1.20.1

### Framework Type

Forge

### Framework Version

Forge - 47.3.12

### Corail Tombstone Version

Tombstone-1.20.1-8.8.6.jar

### What happened?

Im currently creating a modpack to start a server with my classmates and friends, i wanna know is there a way to disable permanent enchanted keys? From research i heard its from the ended halloween event, but i cant figure out how to disable and i dont know where else to ask, apolgoies if people have asked this before. But i want to know how to configure it, because i love the knowledge of death system but i do not want to begin with those levels

Thank you so much for taking your time to read this

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone on Forge/NeoForge (required)

No

### Occurence

occurs all the time

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You didn't search a lot on my github for your answer. https://github.com/Corail31/tombstone_lite/issues/259

**Comment by Mobuid** [comment]
Apologies, i literally dont know how github works and am completely new, sorry it was so simple, thats my fault

**Comment by Mobuid** [comment]
I just want to make sure, i want to be able to craft it, i just dont wanna automatically spawn with 5 levels in jailer, so just disable jailer? I still want to be able to level it, i just want to disable the innate 5 levels in it

**Comment by Corail31** [comment]
There is no option for "le beurre et l'argent du beurre".
