### ISSUE TITLE
Allow halloween to be year round - toggle in config 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Corail31/tombstone_lite#27]

**Comment by P3rf3ctXZer0** [comment]
You could also make it so players can pick. So you can say in config - only activate one.

**Comment by Corail31** [comment]
In fact, Halloween provides some behaviors that shouldn't be allowed all the time :)
or i was more the theme from graves ?

**Comment by P3rf3ctXZer0** [comment]
yeah like customs and stuff but honestly I just like having full control over a mods behavior.

**Comment by P3rf3ctXZer0** [comment]
Impatient XD <-

**Comment by P3rf3ctXZer0** [comment]
Thank you for humoring me 🗡

**Comment by Corail31** [comment]
@P3rf3ctXZer0 It's based on the date on your computer any way :p (in singleplay) and start in 4 days :)
