### ISSUE TITLE
[Suggestion] Add in default values to config

### ISSUE THREAD

**Issue by DWX12** [Corail31/tombstone_lite#28]
Something that should be a standard practice in mod development is to have default values present in the configs. This helps when changing and testing different values. Otherwise the only other method of getting the default values is to delete the config and let it regenerate.

I hope you'll take this into consideration.

Again, great mod and I thank you for all of your hard work, effort, and time spent working on this and all of your other projects.

**Comment by Corail31** [comment]
It's the normal forge config with annotation, and the only way to have the default is to delete the file to regenerate it, or to reset to default in the config in game.
I'm not sure to understand your suggestion, but i'm ok for any change if you can explain me the trouble :)
NB : is it related to the lang file and the config text in it ?

**Comment by Corail31** [comment]
@DWX12 is it ok ?
