### ISSUE TITLE
Compatibility with TechGuns

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/tombstone_lite#28]
Could you please add compatibility for the Tech Guns inventory slot? Right now they drop on the ground.

It holds food, and ammo.

https://minecraft.curseforge.com/projects/techguns

![itemsdrop](https://user-images.githubusercontent.com/4427684/38012606-54d7abb0-321f-11e8-95f0-a0dcbf18f390.png)

**Comment by Corail31** [comment]
You need to activate the option in the config to auto-equip techguns. (it's not the default option)

**Comment by Corail31** [comment]
The support for techguns is working, i just tested it. So, you probably have a mod that is interfering.

**Comment by Corail31** [comment]
https://youtu.be/uRQuy6hNwGo

**Comment by ProsperCraft** [comment]
I suspect Spongeforge then, will have to test.

**Comment by Corail31** [comment]
I made custom tests on a sponge server, and this bug prevents grave to catch the ammo items from techguns, even in the lowest priority of the playerDrop event.
So, i made a provisory fix for this "forgeSponge" bug by using a "delayed method" that will aspirate all theses items in the grave a little later (only if sponge & techguns are presents).
It'll be included in release 2.8.4
NB : but there's a bug in sponge any way...
