### ISSUE TITLE
Add blacklist for item lost.

### ISSUE THREAD

**Issue by Dominance** [Corail31/tombstone_lite#29]
Some items like the Botania relics cannot be replaced. love the feature just need to make sure its not game breaking to use it in a pack 👍

**Comment by Corail31** [comment]
Hi Dominance,
don't worry, the config option to allow some lost items when you die is only applied to items that are stackable and with no compound tags.
did you get a trouble with this feature ?

**Comment by Corail31** [comment]
If you find an example of item removed that you think it shouldn't, i'll add this blacklist. (as you need the same to fill this blacklist)
NB : don't hesitate to contact me on forgeCurse about this
