### ISSUE TITLE
Compability with Relicks and other

### ISSUE THREAD

**Issue by DrSigma4164** [Corail31/tombstone_lite#29]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Corail Tombstone Version

6.5.5

### What happened?

Along with your mod, I also use the Relics mod. So the problem is that these items don't have an "exact" place where I could put them in Curio slots, ie they have a curio slot as shown in screenshot 1, ie I can put them in any free slot that I do. Your mod allows you to wear all such accessories in Curio when choosing a cemetery, but such accessories, where their specific location is not specified, are not worn. Is it possible to make them dress in any free slot after everyone else that has a specific slot like Ring Bracelet Belt has dressed?
The name of the item I noticed: "relics: blazing_flask"
Relic mod version: 0.2.11.1
In mod files, these items are grouped into a curio tag (in screenshot 2)
And in 3 screenshots one more such subject is shown.

![image](https://user-images.githubusercontent.com/93322905/142754309-6b94dcea-f8e5-4589-b1d6-7ba3b1bfcb3b.png)
![image](https://user-images.githubusercontent.com/93322905/142754294-aa3a5733-56bc-4f75-a4fd-cc3088bceb64.png)
![image](https://user-images.githubusercontent.com/93322905/142754313-8944e3a2-5081-42be-9699-6dd8dc524d62.png)

### Gametype

Singleplayer, Dedicated Server

### Happen with only Corail Tombstone

No

### Other relevant mods

Relics, etc(look describtion)...

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
There would be a lot to say about Curios, but i will make it short: if it's to equip them the last, the compat will be added.
Edit: neat presentation btw (i'll probably handle #22 on the same time)
After looking at it, it's only the 1.16.5 compat that still relies on the items having a curio capability (unlike the compat in 1.17.1), and will be changed to be similar.

**Comment by Corail31** [comment]
@DoctorSigma solved in 6.6.1 (also your previous issue about Enigmatic Legacy)
