### ISSUE TITLE
Wrong Version [2.8.6]

### ISSUE THREAD

**Issue by BloomCake** [Corail31/tombstone_lite#3]
Hey,

our server crashes every time with the following report: https://pastebin.com/NtnN4Peg
Any ideas? Is this issue fixed with the latest version 2.8.7? 
Currently I am using version 2.8.6

**Comment by Corail31** [comment]
Hi BloodCake,
It's completely normal, the 2.8.6 isn't in download as wrong version, just use any version of the 2.8 scope except 2.8.6

**Comment by BloomCake** [comment]
Okay, thanks
