### ISSUE TITLE
Inability to open curios after unlocking a grave

### ISSUE THREAD

**Issue by Letoric** [Corail31/tombstone_lite#3]
Version 6.2, does not occur on version 6.0.2

Steps to repro:
die
unlock grave
attempt to open curios

Error in logs:
[18:32:35] [Render thread/WARN] [minecraft/ScreenManager]: Failed to create screen for menu type: curios:curios_container
[18:32:42] [Render thread/WARN] [minecraft/ScreenManager]: Failed to create screen for menu type: curios:curios_container
[18:32:47] [Render thread/WARN] [minecraft/ScreenManager]: Failed to create screen for menu type: curios:curios_container

Mod list:
absentbydesign-1.16.4-1.2.0.jar
AdditionalEnchantedMiner-1.16.4-16.1.3.jar
ae2extras-1.1-1.16.4.jar
aiotbotania-1.16.4-1.5.0.jar
allthemodium-1.1.19-1.16.4-35.1.4.jar
alltheores-0.1.13-1.16.3-34.1.0.jar
allthetweaks-1.1.7-1.16.3-34.1.10.jar
angelring-1.16.3-1.3.3.jar
Apotheosis-1.16.3-4.4.1.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
appliedenergistics2-8.2.0-alpha.2.jar
archers_paradox-1.16.3-1.0.0.jar
architectury-1.1.55-forge.jar
ars_nouveau-1.16.4-1.9.3.jar
astralsorcery-1.16.4-1.13.7.jar
atmadditions-1.16.2-1.0.0.jar
AttributeFix-1.16.4-9.0.2.jar
AutoRegLib-1.6-47.jar
BadMobs-1.16.4-8.0.2.jar
bagofyurting-1.16.4-1.1.0.2.jar
balancedenchanting-1.0.jar
BetterAdvancements-1.16.4-0.1.0.103.jar
BetterMineshafts-Forge-1.16.3-1.1.jar
biggerreactors-1.16.4-0.3.0-beta.jar
BloodMagic-1.16.3-3.0.2-7.jar
Bookshelf-1.16.4-9.3.18.jar
Botania-1.16.4-410.jar
botanicalmachinery-1.16.4-0.3.1.jar
BotanyPots-1.16.4-6.0.8.jar
buildinggadgets-1.16.4-3.7.3.jar
bwncr-1.16.4-3.9.16.jar
camera-1.16.4-1.0.7.jar
cc-tweaked-1.16.4-1.94.0.jar
chonk-1.16.3-0.1.4.jar
citadel-1.5.3.jar
cleancut-mc1.16-2.2-forge.jar
ClientTweaks_1.16.3-5.2.0.jar
cloth-config-forge-4.1.1.jar
Clumps-6.0.0.13.jar
cofh_core-1.16.3-1.0.4.jar
collective-1.16.4-1.53.jar
comforts-forge-1.16.4-4.0.0.3.jar
compact-machines-4.0.0-alpha.3.jar
Compressium-1.16.4-1.1.36.jar
confdespawntimer_1.16.4-1.3.jar
constructionwand-1.16.2-1.7.jar
Controlling-7.0.0.11.jar
CookingForBlockheads_1.16.3-9.2.2.jar
CosmeticArmorReworked-1.16.4-v1.jar
CraftingTweaks_1.16.3-12.2.0.jar
crashutilities-3.8.1.jar
create-mc1.16.3_v0.3a.jar
Cucumber-1.16.4-4.1.5.jar
culinaryconstruct-forge-1.16.3-4.0.0.1.jar
curios-forge-1.16.4-4.0.3.0.jar
Cyclic-1.16.4-0.10.1.jar
dankstorage-3.13.jar
DarkUtilities-1.16.4-7.0.3.jar
deathbackup_1.16.4-1.1.jar
DefaultOptions_1.16.3-12.2.0.jar
demagnetize-forge-1.16.2-1.2.2.jar
DimStorage-1.16.4-4.3.0.jar
Ding-1.16.3-1.2.0.jar
DungeonCrawl-1.16.3-2.2.2.jar
Dynmap-3.1-beta5-forge-1.16.3.jar
dynviewdist-1.7.jar
elevatorid-1.16.4-1.7.8.jar
emojiful-1.16.3-2.1.1.jar
enchantingcmds_1.16.4-1.3.jar
EnchantmentDescriptions-1.16.4-6.0.2.jar
enderchests-1.16-1.7.5.jar
endertanks-1.16-1.9.3.jar
engineersdecor-1.16.4-1.1.5.jar
engineerstools-1.16.4-1.1.2.jar
ensorcellation-1.16.3-1.0.3.jar
entangled-1.2.9-mc1.16.4.jar
envirocore-1.16.4-3.0.5.2.jar
enviroenergy-1.16.4-3.0.4.1.jar
enviromats-1.16.4-2.0.5.0.jar
envirotech-1.16.4-3.0.5.1.jar
extradisks-1.16.4-1.3.4.jar
ExtraStorage-1.16.4-1.2.1.jar
extremeSoundMuffler-3.2_Forge-1.16.4.jar
FarmingForBlockheads_1.16.3-7.2.1.jar
FastFurnace-1.16.3-4.3.0.jar
FastLeafDecay-v25.jar
FastWorkbench-1.16.3-4.4.1.jar
flatbedrock-1.16.4-1.1.6.jar
FluxNetworks-1.16.4-6.1.5.10.jar
forbidden_arcanus-1.16.4-1.0.0.jar
forge-1.16.4-geckolib-3.0.0.jar
ftb-backups-2.1.1.6.jar
ftb-chunks-1604.2.2.54.jar
ftb-gui-library-1604.1.1.26.jar
ftb-ranks-1604.1.1.9.jar
ftb-teams-1604.1.0.13.jar
ftb-ultimine-1603.1.1.13.jar
ftbessentials-1603.1.0.11.jar
globalxp-1.16.3-v1.4.15.jar
iceandfire-2.1.4-1.16.4.jar
ImmersiveEngineering-1.16.4-4.1.2-129.jar
ImmersivePetroleum-1.16.4-3.1.0-2.jar
industrial-foregoing-1.16.4-3.2.6-c3ea663.jar
invtweaks-1.16.4-1.0.1.jar
ironchest-1.16.4-11.2.10.jar
ironfurnaces-1.16.4-2.5.4.jar
IronJetpacks-1.16.4-4.1.3.jar
item-filters-1604.2.2.19.jar
JAOPCA-1.16.4-3.4.0.1.jar
jei-1.16.4-7.6.0.62.jar
jeiintegration_1.16.4-6.1.1.11.jar
jumbofurnace-1.16.4-2.2.0.1.jar
JustEnoughResources-1.16.4-0.12.0.103.jar
KleeSlabs_1.16.3-9.2.0.jar
kubejs-1604.3.2.121-forge.jar
kubejs-blood-magic-1604.1.0.2.jar
kubejs-immersive-engineering-1604.1.0.9.jar
kubejs-mekanism-1604.1.1.5.jar
kubejs-thermal-1604.1.0.5.jar
kubejs-ui-1604.1.0.12.jar
LibX-1.16.3-1.0.1.jar
light-overlay-5.5.4.jar
LightingWand-1.16.4-1.7.2.jar
Lollipop-1.16.4-3.2.3.jar
mahoutsukai-1.16.4-v1.26.8.jar
managear-1.16.3-2.2.3.jar
Mantle-1.16.4-1.6.43.jar
mcjtylib-1.16-5.0.15.jar
mcw-bridges-1.0.4-mc1.16.4.jar
mcw-doors-1.0.1fix-mc1.16.4.jar
mcw-trapdors-1.0.0-mc1.16.4.jar
mcw-windows-1.0.2-mc1.16.4.jar
mcws-roofs-2.0.0-mc1.16.4.jar
Mekanism-1.16.4-10.0.18.445.jar
MekanismAdditions-1.16.4-10.0.18.445.jar
MekanismGenerators-1.16.4-10.0.18.445.jar
MekanismTools-1.16.4-10.0.18.445.jar
metalbarrels-3.3a.jar
mininggadgets-1.7.1.jar
mining_dimension-1.16.4-1.0.2.jar
modnametooltip_1.16.2-1.15.0.jar
modular-routers-1.16.3-7.2.0-39.jar
morered-1.16.4-2.0.1.2.jar
MouseTweaks-2.13-mc1.16.2.jar
MysticalAgradditions-1.16.4-4.1.2.jar
MysticalAgriculture-1.16.4-4.1.3.jar
MysticalCustomization-1.16.4-2.1.1.jar
MythicBotany-1.16.3-1.2.0.jar
NaturesAura-33.2.jar
NaturesCompass-1.16.4-1.8.6.jar
NetherPortalFix_1.16.3-7.2.1.jar
nomowanderer_MC1.16.4_1.0.jar
observerlib-1.16.4-1.4.4.jar
omgourd-1.16.3-1.0.0.jar
PackMenu-1.16.3-2.3.0.jar
pamhc2foodcore-1.16.3-1.0.0.jar
Patchouli-1.16.4-48.jar
pedestals-0.8l.jar
phosphophyllite-1.16.4-0.3.2-beta.jar
PickleTweaks-1.16.4-5.1.4.jar
Placebo-1.16.3-4.3.3.jar
platforms-1.16-1.7.8.jar
pneumaticcraft-repressurized-1.16.4-2.8.1-96.jar
polymorph-forge-1.16.4-0.20.jar
portality-1.16.4-3.2.0.jar
potiondescriptions-1.16.3-1.3.4.jar
potionsmaster-0.1.31-1.16.4-35.1.13.jar
Powah-1.16.4-2.3.6.jar
Psi 1.16-88.jar
Quark-r2.4-280.jar
randompatches-1.16.4-1.22.1.11.jar
rangedpumps-0.8.2.jar
ReAuth-1.16-Forge-3.9.3.jar
refinedstorage-1.9.9.jar
refinedstorageaddons-0.7.2.jar
reliquary-1.16.3-1.3.4.1061.jar
repurposed_structures-1.16.4-2.3.3.jar
resourcefulbees-1.16.3-0.5.5b.jar
restrictions-1.16-3.0.3.jar
rftoolsbase-1.16-2.0.9.jar
rftoolsbuilder-1.16-3.0.13.jar
rftoolscontrol-1.16-4.0.6.jar
rftoolspower-1.16-3.0.8.jar
rftoolsstorage-1.16-2.0.8.jar
rftoolsutility-1.16-3.0.19.jar
rhino-1.7.13.9.jar
rsgauges-1.16.4-1.2.6-b2.jar
Runelic-1.16.4-6.0.2.jar
ScalableCatsForce-2.13.3-build-6-with-library.jar
scuba-gear-1.16.4-1.0.1.jar
shetiphiancore-1.16-3.8.4.jar
shutupexperimentalsettings-1.0.1.jar
SilentGear-1.16.3-2.4.5+191.jar
SilentLib-1.16.3-4.9.0+63.jar
simplemagnets-1.0.8-mc1.16.4.jar
simplylight-1.16.4-1.1.1.jar
SolarFluxReborn-1.16.3-16.2.3.jar
solcarrot-1.16.3-1.9.8.jar
spatialharvesters_forge_1.16.4-0.9.10.jar
StorageDrawers-1.16.3-8.2.1.jar
tanknull-2.2a-1.16.4.jar
tgcropesmod-1.16.2-1.1.0.jar
theoneprobe-1.16-3.0.6.jar
thermal-1.16.3-1.0.5.jar
thermal_cultivation-1.16.3-1.0.5.jar
thermal_expansion-1.16.3-1.0.5.jar
thermal_innovation-1.16.3-1.0.3.jar
thermal_locomotion-1.16.3-1.0.3.jar
titanium-1.16.4-3.2.3.jar
TMechworks-1.16.3+-2.2.2.jar
Toast-Control-1.16.3-4.3.0.jar
tombstone-6.0.2.jar
ToolBelt-1.16.3-1.15.2.jar
torchmaster-2.3.5-alpha.jar
TrampleStopper-2.4.8+mc-1.16.4.jar
trashcans-1.0.5-mc1.16.4.jar
TrashSlot_1.16.3-12.2.1.jar
TravelAnchors-2.1.jar
useful_backpacks-1.16.4-1.11.6.86.jar
useful_railroads-1.16.4-1.4.6.34.jar
u_team_core-1.16.4-3.1.17.191.jar
valkyrielib-1.16.4-3.0.5.2.jar
WaterStrainer-1.16.3-10.0.0.jar
Waystones_1.16.3-7.3.1.jar
Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar
woot-1.16.4-1.0.2.2.jar
WorldEdit-CUI-FE3-1.16.4-3.0.8.jar
worldedit-forge-mc1.16.3-7.2.1-dist.jar
XaerosWorldMap_1.11.4_Forge_1.16.4.jar
Xaeros_Minimap_20.29.1_Forge_1.16.4.jar
xnet-1.16-3.0.11.jar
XNetGases-1.16.4-2.1.1.jar
xptome-1.16.2-v1.1.6.jar

**Comment by Letoric** [comment]
Issue seems to be intermittent, reproduction may be difficult, which means the comment about not occurring in 6.0.2 may be off. Sorry. I know we all love intermittent issues :P

**Comment by Corail31** [comment]
You can disable fully the compat for curios in config/compatibility -> allow_curio_auto_equip.
It's already partially disabled, but still accept toolbelt.
