### ISSUE TITLE
Question: How to trigger the poppet Prevention of Darkness

### ISSUE THREAD

**Issue by JonesiBlitz** [Corail31/tombstone_lite#3]
Hello Trying to figure out how to trigger the death for prevention of darkness to get the achievement. 

Falling into the void was my first guess, but I am getting: 
```
The Power of the Graves prevented you from getting lost outside of the world
```

so not sure is there a config something that needs changed?

**Comment by Corail31** [comment]
Hi, i prefer to keep the section specifically for issues as i already answer a lot on CurseForge, some informations are provided in game in compendium, others are to discover by yourself.
It's not related  to void... but to wither, end dragon breath, damage related to tombstone (beyongTheGrave) and can proc with some modded damages and is an advancement to discover. There will never be poppet protection against void damages.
If you're trying to achieve the advancement death master, just keep the protection until it happens, don't die intentionally to achieve it ;)
NB: the message that you display is related to a config preventing player to die outside world and has no relation.
