### ISSUE TITLE
Channels rejected their server side version number

### ISSUE THREAD

**Issue by Koiske** [Corail31/tombstone_lite#30]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Corail Tombstone Version

6.6.1

### What happened?

Me and my friends have been having issues with joining our server since the mod updated. Client side we keep getting an mismatch mod error. We reinstalled all the mods and ran the server again. Going deeper into the modpack's client logs there's one error that shows up in relation to the mod:

`[Netty Client IO #5/ERROR]: Channels [tombstone:tombstone_channel] rejected their server side version number`

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Krunnie make sure that you connect to the server with the same version, and if it's not the trouble, please provide the debug log when you tested with only Tombstone.
