### ISSUE TITLE
[config?] Disable ghosts

### ISSUE THREAD

**Issue by DemonfangArun** [Corail31/tombstone_lite#31]
Is there a way to disable the ghosts that come from lightning bolts? I scoured the config but couldn't find anything.

**Comment by Corail31** [comment]
he seriously, did you read the topic opened on the subject about halloween, have you read the changelog ?
-> no

**Comment by DemonfangArun** [comment]
Yes, I did read the changelog, and I saw that post, but neither gave any information on disabling the ghosts outright. There's also no need to be hostile.

**Comment by Corail31** [comment]
so you read the change log : 
- client config to disable the special effects of halloween

**Comment by DemonfangArun** [comment]
Oh, it's way back there in the changelog, from well before I started using it. My apologies. All I saw mention of was some particle stuff in some of the issue tickets relating to Halloween and didn't think much of it.

We're all human ¯\_(ツ)_/¯

**Comment by Corail31** [comment]
The ideal way is to use 3.2.6 to be able to pray on graves, so the ghost won't haunt you for 6 hours real time (but played time), and you'll receive a buf on the same time.
=> it was done to learn to players how to pray on graves as it's one of the ways to increase the knowledge of death.

**Comment by DemonfangArun** [comment]
I can understand this, and have no problem with this myself (I'm a bit into the spiritual stuff irl), but not all players would be willing to do this. I'm making a modpack that's meant to appeal to a wide range of players, and not everyone is willing to pray on the graves to avoid lightning and ghosts (which have really good detail btw). As for why I chose this tombstone mod out of many others: aesthetics, the mob spawning on graves, and the ghost effect on death, among other features.

**Comment by Corail31** [comment]
I'm atheist, so i don't trust in any god or anything else, that's why i added the ankh that is more a symbol of life. But there're only actually only 3 ways to improve the knowledge of death skills (free a soul from a receptacle, the pray, and the exorcism on zombie villager)

**Comment by Corail31** [comment]
@DemonfangArun about the option to spawn mobs around after recovering the grave is really new, so any wish about this feature will be added directly in the coming release.
