### ISSUE TITLE
Unable to start server with toombstone mod.

### ISSUE THREAD

**Issue by jsanzmig** [Corail31/tombstone_lite#32]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Corail Tombstone Version

6.6.2

### What happened?

When trying to start the server from aternos, it crashes because of "requires mixin subsystem version 0.8.4 but 0.8.2 was found". The server starts normally when removing the toombstone mod. 

### Log Link

https://pastebin.com/n8nERZPd

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi Jsanzmig,
It's a little my fault to have lower the minimal version of forge to load this version.
You need forge 36.2.5+ as it requires mixin 0.8.4 and forge provides it (it's also better to remove any mod that would bring mixin as it's no more needed).
Edit: more precisely, Forge was using 0.8.2 in previous versions (8098).

**Comment by jsanzmig** [comment]
Hello,
Aternos gives me the option to either have Forge 36.2.0 or 36.2.19, what version should I chose?
Also, this is a list of the mods that I have, tho it seems only toombstone is causing the crash.
![Screenshot](https://user-images.githubusercontent.com/95410002/144399865-be3fd56f-454c-4a66-af5b-e8b2903e2978.PNG)

Thank you!

**Comment by Corail31** [comment]
In general, it's recommanded to be on latest version of forge to benefit from their changes (as long it's not a version subject to breaking changes like 1.18 will probably be).

**Comment by jsanzmig** [comment]
It worked, thank you very much!
