### ISSUE TITLE
The effect Purification seems to be able to cause a negative damage modifier.

### ISSUE THREAD

**Issue by ChristophGra** [Corail31/tombstone_lite#32]
I had the problem that after eating a few lollipops I couldn't attack anything anymore. After checking the player nbt data in the save, it turned out to be -12 damage modifier. As I didn't find any other possible cause for it, I am posting the report here.

Attached a video of how the error looks like ingame. The modpack is gregblock. The occasional damaged mobs are from wooden spikes.
[Here is the video](https://www.youtube.com/watch?v=Jo7UQm261UI)

**Comment by Corail31** [comment]
Hm, the lollipop only provides a random "not bad" potion effect from the mod list of the pack, it would be good to know what was the effect.
NB : if you have trouble with your nbt, you can use /tbrecovery if needed (except if you have others solutions like this one in the pack)

**Comment by ChristophGra** [comment]
Sadly I seem to have overwritten the backups. And for further info: It also persisted through not having any active buffs/debuffs.  Which log do you mean?

**Comment by Corail31** [comment]
In fact, you can use the command to save your player, and then open the file in your save folder /tombstone/saved_players/ and remove the wrong modifier, and the reload your save (there's probably some soft that allow to edit players, as normally the command shouldn't be used in this way)
The logs when starting your game(log folder).

**Comment by ChristophGra** [comment]
[2018-10-28-1.log](https://github.com/Corail31/tombstone_lite/files/2531410/2018-10-28-1.log)
This log is from when I had the problem going on.

And I already edited the nbt data today.

**Comment by ChristophGra** [comment]
Oh, in case you need the debug log too. Game startup shouldnt influence anything so any debug-log should be as good as any other.
[debug-5.log](https://github.com/Corail31/tombstone_lite/files/2531464/debug-5.log)

**Comment by Corail31** [comment]
the debug.log would be better, sorry :)

**Comment by Corail31** [comment]
Based on your informations, i found the reason : the effect "purification" doesn't remove correctly the bad effects, and this prevents to remove the modifier.
So, ideally on the time that i'll publish a fix, add this effect to the blacklist as explained above, and disable the item in the config (Category Allowed Items).
