### ISSUE TITLE
Suggestion: Featuers that would fit your mod and are easy to do i think.

### ISSUE THREAD

**Issue by SirAron111** [Corail31/tombstone_lite#33]
First of all I really like your mod and the way it handles player death inventory which is the main part I added it to my Modpack.

And since you added in these Halloween ghosts I was thinking. (Dear good I hope they stop spawning when Halloween is over.) But only partially that is. I really like the random scare factor just not every night. Did you think about making It so that random ghosts/ghouls or whatever appear on special events called haunted nights? Like every full moon or so not every night even after Halloween. Since having this ghost appear every night is just getting boring and not scary anymore. Having it appear every some 8 - 10 other night would make it a refreshing scare every time (since players can’t sleep in my pack).

Also the fog on graves (same as the ghost has) is sadly really ugly and way to speed up in animation to look spooky. Could you make a better fog? This way you could have graves (decorative ones) spawn randomly for spookiness covering the area in a low ground level fog that is slowly and menacing animated without it lagging to death. Not the super speedy fart clouds that they are atm.

This is just a suggestion! .I really like the mod the ghost scared the shit out of me the first time XD.

**Comment by Corail31** [comment]
Seriously, the smoke of graves is ugly ? play skyrim and not minecraft in this case.
The fog is done to be not laguy with few particles and have an enough good result.
The Ghost won't appear any more after Halloween, and was just a small contribution to this holiday event.

**Comment by SirAron111** [comment]
Yes this fog looks nice how do I get it? All I get is this fog here that looks like particle overkill.
https://i.imgur.com/jdHvuGW.png
https://imgur.com/jdHvuGW
