### ISSUE TITLE
How to turn on the nice fog you showed in the picture??

### ISSUE THREAD

**Issue by SirAron111** [Corail31/tombstone_lite#34]
all i get when i turn fog on for your mod is this.
https://imgur.com/jdHvuGW
https://i.imgur.com/jdHvuGW.png
How do i get the nice fog you showed me in the picture? that's exactly what i meant. are there 2 kinds of fog?

**Comment by Corail31** [comment]
You'll have to search by yourself the reason, as it works properly without "interference" of others mods/shaders/vbo button in game..., the transparency seems to be removed in your actual setup, and the issue support is disabled for november.
