### ISSUE TITLE
Book of Recycling

### ISSUE THREAD

**Issue by VeloVS** [Corail31/tombstone_lite#36]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Corail Tombstone Version

6.6.3

### What happened?

I can't seem to recycle anything using the book, no recipes found it says. I'm playing in All the magic: Spellbound modpack.

### Gametype

Dedicated Server

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@VeloVS You were right, it doesn't work well with damageable items.
