### ISSUE TITLE
Fishing rod doesn't work.

### ISSUE THREAD

**Issue by cjser** [Corail31/tombstone_lite#36]
When I try to use the charged fishing rod it doesn't  cast the bouy. It doesn't  work

**Comment by Corail31** [comment]
![rod](https://user-images.githubusercontent.com/17954109/48681423-a927fe80-eba2-11e8-8ac4-941bee47d5ee.png)
not sure what you mean, be sure to be on a recent version, in the other case, you'll have to find the reason.
