### ISSUE TITLE
Cant combine enderpearls with keys in inventory on survival mode

### ISSUE THREAD

**Issue by neonyxiaa** [Corail31/tombstone_lite#37]
### Minecraft Version

1.18

### Forge Version

39.0.22

### Corail Tombstone Version

7.3.4

### What happened?

you can only combine ender pearls with keys in creative mode for some reason it doesnt work on survival

### Gametype

Singleplayer, Dedicated Server

### Happen with only Corail Tombstone

No

### Other relevant mods

i dont think its because of other mods

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Whaleguy5533 Thanks you for reporting this issue.
