### ISSUE TITLE
[Suggestion] Make some kind of payment/tribute mechanism to recover items

### ISSUE THREAD

**Issue by CritFlaw** [Corail31/tombstone_lite#38]
I would love to not make death painful as vanilla, but not quite as inconsequential as with a grave mod. Could you maybe add a customize-able item/items cost to unlock a given grave? I think this would really help balance it a bit.

**Comment by Corail31** [comment]
@CritFlaw I think i could add a config option to require to upgrade for the key with a crafting recipe to be able to access the grave (and a message when clicking the grave with no upgrade to explain what is missing)

**Comment by CritFlaw** [comment]
Appreciate the reply. I've since switched to vanilla death chest. I love your mod, but they've added all the features I wanted in a grave mod, including game-stage integration.
