### ISSUE TITLE
When I die, sometimes my bookmarks in the JEI disappear.

### ISSUE THREAD

**Issue by DrSigma4164** [Corail31/tombstone_lite#38]
### Minecraft Version

1.16.5

### Forge Version

36.2.21

### Corail Tombstone Version

6.6.3

### What happened?

When I die, sometimes my bookmarks in the JEI disappear, it happens after I pick up the grave with a key.

### Log Link

https://gist.github.com/260b998a49e3b2e0bd5b3e36ea1982f0.git

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone

No

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Bookmarks are a JEI thing, so it's better to report to that mod.
