### ISSUE TITLE
Massive mod pack crashes with tombstone.

### ISSUE THREAD

**Issue by jacobmix** [Corail31/tombstone_lite#4]
I have a massive modpack me, and my friends play.
Pretty much just DireWolf20, and AllTheMods3 plus some more. Hasn't crashed on us yet tho.
Before we tried adding Corail Tombstone. Here's the crash log on Google Drive:
https://drive.google.com/open?id=1fEd6YUlFbxjQE3oiCkVJ9G-OBQoGHujR
It crashes as soon as it's finishing up mods. If any more info is needed just say.

**Comment by Corail31** [comment]
My mod is probably not related to this bug.
