### ISSUE TITLE
Class-cast crash with my mod.

### ISSUE THREAD

**Issue by FINDERFEED** [Corail31/tombstone_lite#4]
### Forge Version

1.17.1 - 37.0.13

### Corail Tombstone Version

7.0.1

### What happened?

Hello! Your mod is having an issue with my SolarCraft mod, my capability somehow is being class-cast to your capability in your "EventHandler" class and this causes a crash. (It happened right when i entered the world)

### Log Link

https://pastebin.com/PHFP59sw

### Gametype

Singleplayer

### Tested with only Corail Tombstone

- [ ] Yes

### Relevant others mods

https://www.curseforge.com/minecraft/mc-mods/solar-forge

**Comment by Corail31** [comment]
Hi, and thanks for testing the form :)
This is more related to the implementation of your capability, i suppose you can find help on the forge forum.
NB: it's about returning empty in getCapability when it's not yours.
