### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by Dunkmania101** [Corail31/tombstone_lite#4]
Hello! I tried launching a server with version 1.16-6.2.1 and got a crash, logged below. It said there was no such method on line 159 in EventHandler. I tried checking it in IntelliJ out of curiosity but it didn't complain about anything. The Forge version in that project was the same as the server, 1.16.4-35.1.13. It seems fine in singleplayer, so maybe there's something else going on here.

Crash Report:

[log](https://gist.github.com/Dunkmania101/57d061ff1eaaae8fc31339c9f43a5a2a)

**Comment by Terpo** [comment]
I can confirm this issue. The server started but when a player joins it crashes for me.
The stack trace is the same as above. Btw... the link behind address is wrong.^^

**Comment by Dunkmania101** [comment]
I guess I worded that wrong. The crash was on joining for me, too. Fixed the link, markdown is fun!

**Comment by Corail31** [comment]
Hi, can you just test with the new release as what i fixed is not what you reported ?

**Comment by Terpo** [comment]
Tested and works

**Comment by Dunkmania101** [comment]
Works for me too, thanks!
