### ISSUE TITLE
Server Bug : Cannot Open Tombs With Keys [client method called on server]

### ISSUE THREAD

**Issue by ivardensphere** [Corail31/tombstone_lite#4]
Hello!

Version: tombstone-1.2.2-1.11.2
Forge Version: forge-1.11.2-13.20.0.2284-universal
Error: Not able to open any grave with key in hand.
Log File: https://gist.github.com/ivardensphere/3c5dd827afa7d1ec515db7e14cf6860b

I am not able to open a tomb after death even with a key. This is for a 1.11.2 server. If you need more info please let me know.

Ivarden

**Comment by Corail31** [comment]
Can you try with forge 2281 plz to see if it changes something :)

**Comment by ivardensphere** [comment]
Good morning Corail,

Yes to both :).
Baubles-1.11-1.4.3
InventoryTweaks-1.62+beta.86
MouseTweaks-2.8-mc1.11.2

She is a big pack.

My Discord is combichrist#6042

Ivarden

**Comment by Corail31** [comment]
bug is localized with the help of ivardensphere, will be fixed in 1.2.3
