### ISSUE TITLE
Aether Legacy compat is not working

### ISSUE THREAD

**Issue by DemonfangArun** [Corail31/tombstone_lite#40]
Forge: 2800
Tombstone: 3.3.0

I got a report yesterday about not being able to get tombstone stuff back. Today while investigating another unrelated issue I ran into a cascade of bugs. This video will tell all:
https://www.dropbox.com/s/ep73fm1lmmpb4f4/TombstoneBug.mkv

Here is the log file mentioned in the video: 
[latest.log](https://github.com/Corail31/tombstone_lite/files/2849777/latest.log)

**Comment by Corail31** [comment]
Honestly, i have no time to waste on this video, my mod is working, and your setup is broken.

**Comment by DemonfangArun** [comment]
Well that's a terrible way to handle a bug report. Bugs can and do lie dormant, I'm using a recent version of java 8, and you completely missed that I stated a forge version. I don't use any mod called nucleus, and have never heard of it.

If I could describe the issue without a video, I would, but I can't. Seeing how you've handled the situation though, I don't care, ad I'm just removing your mod and moving on like I do all developers that act like you do.

**Comment by Corail31** [comment]
I just said that the bug is not in my mod, if you want to remove my mod, you can too... this won't change your trouble. There's no dormant bug, because there's nothing complex in it...

**Comment by DemonfangArun** [comment]
I will credit that the video was a tad on the long side, I don't really record much stuff so I don't have a video editor installed to make nice pretty videos like the big youtubers (something I plan to fix). I will await the mentioned update.

To make it simple, it triggered a weird death state that exists in minecraft when transitioning to creative mode where all sorts of craziness happens.

**Comment by Corail31** [comment]
@DemonfangArun it's already published

**Comment by DemonfangArun** [comment]
And I just woke up -drinks more coffee-
