### ISSUE TITLE
Dedicated server crash after upgrading to 6.7.0

### ISSUE THREAD

**Issue by ChargedByte** [Corail31/tombstone_lite#40]
### Minecraft Version

1.16.5

### Forge Version

36.2.23

### Corail Tombstone Version

6.7.0

### What happened?

After upgrading the dedicated server to use version _6.7.0_ the server crashes at startup.

I also tested with Corail Tombstone being the only installed mod and the same error still occurred.

This was resolved by downgrading back to _6.6.3_

### Log Link

https://gist.github.com/ChargedByte/69c49a64b879e0537b38e2450e9b9f99

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone

Yes

### Other relevant mods

No

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@ChargedByte Thanks you for the fast report, fixed in 6.7.1.
