### ISSUE TITLE
Returning to grave with Zombie pigman crashes the game.

### ISSUE THREAD

**Issue by SirAron111** [Corail31/tombstone_lite#42]
When I return to my grave and the zombie pigman that killed me are still there it crashes the game her is he report. https://pastebin.com/XwEvaAjP can this be fixed or is my world now unplayable forever as it always crashes when loading up the world.

**Comment by SirAron111** [comment]
Ok I found the problem. It is tombstone mod but it’s the ghostly shape that causes the problem. Turning it to ghostly shape time 0 (so turning it off basically) let me go to them and get the grave. I tested it with no other mods installed as well for some reasoned the pigmans group agro seems to be a problem with the ghostly shape. (This is game breaking and needs to be fixed I don’t want to remove the mod from my Modpack since its features are awesome and needed for some things like quests and progression).

In case you want to test it for mod compatibility the bug is existent in my current version and many versions below that (tested it down to 5.1) of my Modpack “Dimension Zero” bug also happens when it’s just the tombstones installed.

**Comment by Corail31** [comment]
First this is not the first mod to add an effect removing the target of mob.
Secondary, you should test it without others mods as this doesn't mean that tombstone is really the cause of what happen in the forge events.

**Comment by SirAron111** [comment]
Greetings Corail32

Thx I will try it out if I have the time. But on that note I wanted to ask wouldn’t it be easier to instead of making mobs ignore you (being ghostly invisible) just making the player ghostly undamagable be enough or at least with a setting. Since the effect will end the moment someone attacks a mob or breaks a block it wouldn’t be op invulnerability and a lot more compatible with other Mods that add some kind of extra targeting system that just spams the console otherwise telling you mob X couldn’t find target Y would also make it less abuse able in survival when waiting out invasions just chilling around in ghost shape (at least in my pack).

Well I am not a modder at all so I am probably totally wrong anyway XD. That’s also why I am so confused that its only with zombie pig man as far as I could find.
Also having to revert down from the newest forge version is nearly impossible since in my modpack many other mods need the newer version. (Will try it out with only your mod thought to see if that fixes it there.)

Thx for the fast replay.

**Comment by SirAron111** [comment]
yep it does work with the 2768 but going higher gives me this crash hope that helps

https://pastebin.com/wdV4naHA

**Comment by Corail31** [comment]
sure, i know the fix for it, don't worry and thanks for the test of forge version, as i was sure it was related to forge 2777 ;)

**Comment by SirAron111** [comment]
Np finding bugs and helping mod makers helps me make my modpack work error free. (I only discovered it in the first place because I decided to readjust damage values for pigman by chance)

**Comment by Corail31** [comment]
May you check that all is working with the fix in this link as you feel used to reproduce the bug ?
[link](https://cdn.discordapp.com/attachments/352073584853647370/546069246170628116/tombstone-3.3.2-1.12.jar)

**Comment by SirAron111** [comment]
Still happens with the new version you linked me.
Here with my modpack and many mods: https://pastebin.com/QSd7LyUD
Here without any other mods only newest forge and tombstones https://pastebin.com/wnYxeewV

**Comment by Corail31** [comment]
@SirAron111 [new try](https://cdn.discordapp.com/attachments/352073584853647370/546286897748639754/tombstone-3.3.2-1.12.jar)

**Comment by SirAron111** [comment]
This one works no more crashes with pig man (also tested some normal zombies and some modded mobs).

Hope no more bugs like this occur XD once its uploaded to curse I will have to immediately update my Modpack since I have a feature that makes invasions and one of the harder ones has a lot of pig man (I don’t want anyone crashing because of this).

That was some fast bug fixing work GJ what even caused the problem?

**Comment by Corosauce** [comment]
I guess this is the source problem? Found this PR from the forge 2777 changelog: https://github.com/MinecraftForge/MinecraftForge/pull/5217

If it's an ongoing issue in latest forge I'm considering looking into it further to improve the situation for modders so they don't trigger this issue again in their own mods.

How did you fix it on your end? Don't see any recent commits as of writing this.

**Comment by Corail31** [comment]
@Corosauce by providing a dummyEntity that returns true to isSameTeam() and already dead, so it's removed the next tick.
