### ISSUE TITLE
NoSuchMethodError GraveGuardianArmorLayer.getArmorModelHook

### ISSUE THREAD

**Issue by alyssacodes** [Corail31/tombstone_lite#43]
### Minecraft Version

1.18

### Forge Version

39.0.63

### Corail Tombstone Version

tombstone-7.3.7-1.18.jar

### What happened?

I'm not sure what exactly happened. I had one decorative tomb placed against a cave wall and was at my base fishing when my game crashed with the error linked below.  I was not able to reconnect to the server until i disabled the mod on server and client. I can only assume from the error it was trying to spawn a grave guardian. I tried the mod in a solo creative world and placed several graves and mob spawners near them to see if I could get one to spawn but no such luck. If I knew how to force a grave guardian to spawn I would test this further.

This is where the entity was trying to render per the crash report
![image](https://user-images.githubusercontent.com/15969708/151776434-78d819f8-9ba1-462b-8257-eca3c7b1c6ec.png)

### Log Link

https://pastebin.com/5LwZDBB5

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone

No

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Grave guardians are summonable with command if a test is needed (but you need to prefix the param of the command /summon with 'tombstone' modid).
Can you test with only Corail Tombstone (singleplayer might be enough) ? (without optifine ;) all versions 1.18.1 of optifine are for forge 39.0.0)
NB: make sure you don't have multiple versions of Tombstone in your mod folder because 7.3.6- was incompatible with newer forge 39.0.57+ (relative to the armor layer).
Edit: optifine is probably related ([6581](https://github.com/sp614x/optifine/issues/6581))

**Comment by alyssacodes** [comment]
I will test this today with only Tombstone. This is the only version of Tombstone I have - installed with CurseForge.

**Comment by alyssacodes** [comment]
Confirmed the problem is OptiFine. 

1. Confirmed the crash can be reproduced. - Summoned a Grave Guardian in a creative world with all mods toggled off in CurseForge except Tombstone. This did not include Optifine because it is not a CurseForge mod. Results in a crash.
2. Created a new custom profile in CurseForge.
3. Installed Tombstone and successfully summoned a Grave Guardian - no crash.
4. Added back in all of my other mods (except OptiFine) and was able to load back in and see the Grave Guardian without crashing.

**Comment by Corail31** [comment]
Thanks for the tests, i suppose you can stay on forge 39.0.56, forge will probably make a RB at a moment.
NB: next version will be built with a forge version below 39.0.57 and should solve this.

**Comment by alyssacodes** [comment]
I am confused, I am not on 39.0.56. I am on 39.0.63

**Comment by Corail31** [comment]
Optifine is often sticked to one forge version as it uses lots of hooks that can be easily incompatible with Forge.
"all versions 1.18.1 of optifine are currently for forge 39.0.0" so, by using a forge version over, it's normal to get such issues, and why i recommanded you to stay on a compatible forge version.
