### ISSUE TITLE
Bigger Text

### ISSUE THREAD

**Issue by Fortist** [Corail31/tombstone_lite#43]
After getting rid of that ugly overlay, there is one more fix I need.
Bigger Text
It is way too small and you have to be right up next to it to clearly see any details
![2019-02-18_09 07 54](https://user-images.githubusercontent.com/5784537/52956385-0d528e00-335d-11e9-951e-7687375f5548.png)

**Comment by Corail31** [comment]
First, this is not the way to correctly make an issue (and the typo is yours, not the default used by tombstone, so the size is related to this)
