### ISSUE TITLE
Add back the config to hold right click the key to teleport to the grave

### ISSUE THREAD

**Issue by CindyLouWho03** [Corail31/tombstone_lite#44]

**Comment by Corail31** [comment]
Hi CindyLouWho03,
There's no really a config option to allow to "hold right click to teleport with the grave's key".
In fact, there's a config option "chanceEnchantedGraveKey" that gives you a % chance to have an enchanted key on respawn after your death. (if you're on a server, it's defined by the server indeed)
The other way to enchant this key (allowing to use the teleportion) is to craft it with an ender pearl, or by right clicking a "decorative grave" haunted by a soul (that is the way used by Tombstone to enchant items, the souls spawn randomly based on the config options too)
