### ISSUE TITLE
[1.16.5] New version incompatible with Pehkui

### ISSUE THREAD

**Issue by Timeken** [Corail31/tombstone_lite#45]
### Minecraft Version

1.16.5

### Forge Version

forge-36.2.20

### Corail Tombstone Version

tombstone-6.7.3-1.16.5

### What happened?

Newest version is incompatible with the mod Pehkui-3.1.0, it crashes on startup. The older version tombstone-6.7.2-1.16.5 works fine with it.

### Log Link

https://gist.github.com/Timeken/a4d36cdd29f04f44685602ec04148cac

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

No

### Other relevant mods

tombstone, Pehkui

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Thanks you for informing me about this incompatibility, but you need to report to the other mod; i don't know "pehkui", but this can't be solved on my side.
To my opinion, the way used to change the reach in pehkui is really not ideal (their injection fails).
Forge also has a PR(7808) about the 'reach' that will perhaps happens in 1.16.5 too (avoiding the need of a mixin).
