### ISSUE TITLE
Bug: Without key and other user can shift right click grave to open my grave when i die and when they do so my key disappears

### ISSUE THREAD

**Issue by CindyLouWho03** [Corail31/tombstone_lite#45]

**Comment by Corail31** [comment]
Hi again CindyLou,
The config options of the server that you play on allows others players to open your grave (sometimes, the grave is defined to be directly opened, or after a time elapsed)
There's also an option for pvp, that if allowed, make players killing others players able to open their graves. I think you should really contact the server, you're playing on to get more infos on how they use Tombstones (as there're more than 100 options in the config)

**Comment by CindyLouWho03** [comment]
Well it’s my server

**Comment by Corail31** [comment]
so the config file on your server needs to be edited :)
