### ISSUE TITLE
Sophisticated Backpacks are not removed from Curios Slot on death.

### ISSUE THREAD

**Issue by FryoKnight** [Corail31/tombstone_lite#46]
### Minecraft Version

1.18

### Forge Version

39.0.76

### Corail Tombstone Version

7.4.1

### What happened?

When this mod and the mod [Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks) are used together, Backpacks are not removed from the [Curios](https://www.curseforge.com/minecraft/mc-mods/curios) Back Slot, remaining in the slot after death, even though other Curios from other mods are removed.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

No

### Other relevant mods

Curios API - 5.0.6.1, Sophisticated Backpacks -3.15.9.533

### Valid Launcher

- [X] Yes

**Comment by FryoKnight** [comment]
I will also be crossposting this in SB's issue tracker.

**Comment by Corail31** [comment]
@FryoKnight Hi, to give you some basic indications, the 'unequipping' part has no relation with Corail Tombstone; the fact that the backpack is kept on death might be normal if it's enchanted with a 'soulbound'. Ideally, make sure to test with only the 3 mods. You also have a client config 'auto_equip_rule' (accessible via the command /tbgui) that defines 'when to reequip'.
NB: i won't be able to make the tests myself for the moment.

**Comment by FryoKnight** [comment]
@Corail31 So, after cross-posting the issue in the other mod's issue tracker, it seems to be a common issue with [Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks), as other "Gravestone" mod also seem to be having the same issue, and not something just isolated to your mod.

Thank you for taking the time to respond to this post though, and hopefully the developer of the Backpacks mod will find a fix for this issue (though it is just a minor one).

**Comment by Corail31** [comment]
I wasn't able to get the behavior where the backpack is kept on death.
Make sure to update your curio version to latest (5.0.6.2), and to test with only those 3 mods, ideally with default configs.

**Comment by Corail31** [comment]
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/429
