### ISSUE TITLE
Tombstone not Appearing

### ISSUE THREAD

**Issue by ritzbitz69** [Corail31/tombstone_lite#46]
I put the mod in my mod pack server since it wasn't included in the first place, I can access the config and change things but the physical tombstone doesnt appear when I die.

**Comment by Corail31** [comment]
It's probably due to another mod : Tombstone logs when a mod is canceling the death event.
This is done in a way allowing others mods to do what they want before.
You should show me the list of your mods, and indeed you can try to localize yourself the mod doing this.

**Comment by Corail31** [comment]
@ritzbitz69 any news ?
