### ISSUE TITLE
Illager+ compatibility Crash

### ISSUE THREAD

**Issue by Vascar** [Corail31/tombstone_lite#47]
### Minecraft Version

1.16.5

### Forge Version

forge-1.16.5-36.2.29

### Corail Tombstone Version

tombstone-6.7.3-1.16.5

### What happened?

When the Frostmancer is fighting it causes a crash in a single player world. I have tested it with only the two mods active and only Illager+ active and it only occurs with both mods active. It seems to happen with the large ice attack(the one that sits on the ground). I am posting this on Illager+'s Issues page as well. It seem to be linked to the Voodoo Poppets as in the log it says something about "onProjectileImpact".

### Log Link

https://gist.github.com/Vascar/adc7ad2969dcd13d942fd60d5a7ef993

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

No

### Other relevant mods

illagers_plus-1.16.4v1.7.2

### Valid Launcher

- [X] Yes

**Comment by Vascar** [comment]
disabling poppets stops the crash

**Comment by Corail31** [comment]
Make sure to open this issue on the other mod, it's strange to use the snowball entityType for their EntityIceBall.

**Comment by Corail31** [comment]
@Vascar Thanks for bringing up this incompatibility, here is some additional infos:
This change corresponds to the addition of the Smoke Ball (6.7.0) and my wish to avoid instanceOf (being slower) when possible. It will crash with the ice ball from that mod (not related to voodoo poppet).
While it's relatively unexpected to have an entityType used by multiple entity classes, it's still possible.
So, i'll make a change about this in the next release, you can use a version older than 6.7.0 if needed.
