### ISSUE TITLE
Allow people to get grave contents even when land is claimed.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Corail31/tombstone_lite#47]
Can you make graves immune to land claim restrictions?

**Comment by Corail31** [comment]
Can you be more precise ?
There's an option enables by default in Tombstone to bypass restrictions of others mods.
And there's a config option in Tombstone that restricts where graves are allowed to appear (defined by the server).

**Comment by P3rf3ctXZer0** [comment]
Oh sweet I will try it then.

**Comment by P3rf3ctXZer0** [comment]
Okay so let me specify - in ftbutilities there is an option that allows users to prevent block interaction on land claimed areas - this seems to affect tombstones

**Comment by Corail31** [comment]
sneaking^^

**Comment by P3rf3ctXZer0** [comment]
Okay I will try that.
