### ISSUE TITLE
Ankh cooldown changes depending on which dimension you are in

### ISSUE THREAD

**Issue by CplPibald** [Corail31/tombstone_lite#48]
Use ankh to pray over grave.  Observe cooldown is 6 hours.
Go to a world whose tick timer is ahead.  Note you can pray again immediately.
Go back to original world.  Now the cooldown is unreasonably long.  In this case, over a week.

![pray](https://user-images.githubusercontent.com/902089/54049877-a6bdd480-4192-11e9-8705-d9bf0375d8f1.png)

**Comment by Corail31** [comment]
Hi CplPibald,
thanks for this report, i'll make a fix tomorrow :)

**Comment by Corail31** [comment]
@CplPibald could you precise what is this dimension with a total world time different from overworld?

**Comment by CplPibald** [comment]
The dimension in question is custom, added to the server using [Just Enough Dimensions](https://minecraft.curseforge.com/projects/just-enough-dimensions).  I just realized that this bug can't happen in vanilla because the End, Nether, and Overworld share one WorldInfo object.  JED (and possibly other dimension-management mods) maintains separate WorldInfo per dimension.

**Comment by Corail31** [comment]
May you check if this is working as expected ? [Link](https://cdn.discordapp.com/attachments/352073584853647370/553860814717845544/tombstone-3.3.3-1.12.jar)

**Comment by CplPibald** [comment]
That version appears to be working.  The cooldown displayed in the tooltip is synchronized across all of the dimensions on the server, even after praying.  Thanks!  You didn't have to fix this cross-mod issue, and we appreciate that you did.

**Comment by Corail31** [comment]
Nice, Masa also said he's going to make an option in JED to keep this totalWorldTime.

**Comment by CplPibald** [comment]
I hate to bring this issue back up again, but we are still seeing the same cooldown issue in version 3.3.3 with tablets.  The Ankh is fixed, but a player just showed me a tablet of recall with a cooldown of over 200 hours.

**Comment by Corail31** [comment]
Sure, but unlike the ankh, others item cooldowns are removed on reloading the game as they're intended to be relatively short and not stored ;)
I think it's only the display of the item that show a wrong time (the ankh cooldown works differently with a capability)

**Comment by Corail31** [comment]
@CplPibald May you check this for the compat ? [Link](https://cdn.discordapp.com/attachments/429050628044488705/555753089609629748/tombstone-3.3.3-1.12.jar)
It's only required on the server if you already want to use the compat before my next release.

**Comment by CplPibald** [comment]
Using that patch on the server fixes the long cooldown problem.  The cooldown on tablets is about one minute now regardless of source or destination dimension.

The only strangeness right now is that the cooldown is being displayed in ticks and not seconds.  It's counting down from `Cooldown: 00:1200` to `Cooldown: 00:00`
