### ISSUE TITLE
Time out/Crash on death Corail's Tombstone triggers it often.

### ISSUE THREAD

**Issue by qqbone** [Corail31/tombstone_lite#48]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Corail Tombstone Version

6.7.3-1.16.5

### What happened?

Often when using Corail Tombstone, a timeout and eventually crash happens on death for my mc server and on restart tombstones/player doesn't have a key after death causing a wipe from the inventory. Here is a log link. It's a very heavily modded pack so a numerous amount of conflicts can occur. However, this only happens while Corail's Tombstone is installed and never when removed.

### Log Link

https://pastebin.com/nRjh6MRg

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone

No

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
The error message seems to target 'sereneseasons', so it would be best to report the problem to them.
Also, don't forget that you have a command /tbrecovery for such a crash if needed and checks in your common config if 'backup_on_death' is enabled (category "recovery").

**Comment by qqbone** [comment]
thank you, also with your recent update when this re-occured your tombstone remained fantastic fixes
