### ISSUE TITLE
Can´t teleport to grave

### ISSUE THREAD

**Issue by SparkiTV** [Corail31/tombstone_lite#49]
### Minecraft Version

1.16.5

### Forge Version

36.2.29

### Corail Tombstone Version

6.7.4

### What happened?

When i use the Key with teleport function it dont let me teleport to my grave. 
Animation is fine, but nothing happend after it

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

No

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You're intended to follow the template: actually, your issue means it's not happening with tombstone and you don't provide a log or the incompatible mods. Feel free to edit your current post.
