### ISSUE TITLE
[1.12.2] Circular model dependency

### ISSUE THREAD

**Issue by Gamertech** [Corail31/tombstone_lite#49]
Corail Tombstone: 3.3.2
Forge: 14.23.5.2808
Log: https://pastebin.com/EmgSWiF3

Loading the pack on singleplayer or server generates the above error in the debug. The rod's hidden in the pack, so can't say if there's any actual effect in world, but the error occurs in 100% of pack loads.

tombstone:item/fishing_rod_of_misadventure_cast is calling tombstone:models/item/fishing_rod_of_misadventure which in turn calls tombstone:item/fishing_rod_of_misadventure_cast again.

Also, if it's possible to add config options to disable and unregister items such as the fishing rod, tablets, scrolls etc, that would be a great help in optimising packs and freeing up ItemID's.

Thanks for the reliable grave mod :)

**Comment by Corail31** [comment]
Actually, i never got this log, so i'll test with a recent version of forge, as it's exactly how the vanilla model of fishing rod is done.

**Comment by Gamertech** [comment]
https://pastebin.com/Btse4yrB

**Comment by Corail31** [comment]
```
[03:12:40] [Client thread/ERROR] [FML]: Could not load override model quark:item/override_res/bow_pulling_2 for model minecraft:models/item/bow
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: circular model dependencies, stack: [quark:item/override_res/bow_pulling_2]
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:108) ~[ModelLoaderRegistry.class:?]
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModelOrLogError(ModelLoaderRegistry.java:211) [ModelLoaderRegistry.class:?]
    at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.getDependencies(ModelLoader.java:364) 
```
If i see this log, it's exactly the same for quark : the error is not related to Tombstone or Quark, but something in your pack.

**Comment by Gamertech** [comment]
Never mind. I disabled FoamFix in the Twitch app, but it didn't actually disable the mod. Re-toggling it a couple of times actually did the job and removed it. The errors no longer show in debug. One day they'll fix the app...

Have to go through and figure what setting is causing it.
