### ISSUE TITLE
Special Dimension Behaviors

### ISSUE THREAD

**Issue by Corail31** [Corail31/tombstone_lite#5]
Only request here for any dimension where Tombstone should behave differently. (no grave, or whatever)
NB : By default, graves never appear in liquid, so if a dimensionType is only made of liquid, it needs to be referenced here.
Tombstone already integrates theses special dimensionTypes :
- "Aqua Cavern" from the mod Cavern (v2.8.4)

**Comment by Saphrym** [comment]
The mod Dimensional Doors causes a person who dies to go to a different dimension. So Tombstone does not work with it. Could you add that mod to this feature?

**Comment by Corail31** [comment]
It's not really a trouble, you can enchant the key (allowing teleportation even if you're in another dimension), with a crafting recipe, or with a soul on a grave. (there's also a config option to allow to have directly an enchanted key when you die)
And the other solution is to find an eternal fabric (related to dim doors)
I'm not sure to understand how i can help more on this ? how could i behave it differently when you die in theses dim doors dimensions ? :)

**Comment by Saphrym** [comment]
I didn't notice the option for enchanted keys on death. That would fix it. Thanks!

**Comment by Boymann** [comment]
Hey, I want to add to this issue. We encountered a simliar thing. The problem is that when you fall from a Dimensional Doors dimension, you fall into the void and a grave spawns in the void, but you get teleported to Limbo. Even if you craft an Enchanted Key, you get teleported to your grave, and fall to limbo again.

**Comment by Corail31** [comment]
Actually, there's a compat for Dimensional Doors to desactivates Ghostly Shape in Limbo Dimension, isn' it enough to make it work correctly ? if there's a grave, it's more related because there're drops on the ground, but i'll look with Runemoro and your coming details about this :)

**Comment by Robijnvogel** [comment]
@Boymann perhaps we (team Dimensional Development, the developers of Dimdoors) should actually make it so that you teleport to Limbo as soon as you hit the void below y=0 instead of actually allowing you to die in the void. 🤔

**Comment by Corail31** [comment]
@Boymann what about the compat with dim doors ? Do the recent versions require more changes to make it fine ?

**Comment by Boymann** [comment]
I have not updated my modpack yet because of certain issues, and I have not got to testing yet either. I will let you as soon as I get to it though.
