### ISSUE TITLE
incompatibility with Corpse

### ISSUE THREAD

**Issue by TsplayerT** [Corail31/tombstone_lite#5]
In a simple way, the title describes what happened 🤷‍♂️

[latest.log](https://github.com/henkelmax/corpse/files/5750153/latest.log)

**Versions**
- Minecraft version: 1.16.4
- Forge version: 35.1.13
- Corpse Mod version: 1.16.4-1.0.4
- Corail Tombstone version: 1.16-6.2.0

**Comment by Corail31** [comment]
As you imagine, this mod is incompatible because it's a grave mod.
