### ISSUE TITLE
Message needs updating for the advancement.

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/tombstone_lite#50]
Goshen just gained the achievement Knowledge raises the soul!
You chose your first knowledge of death (see the keybind in "Misc")

This is actually not in Misc but in Corail Tombstone

**Comment by Corail31** [comment]
Hi Goshen, it looks to be a detail in the lang files that can be updated by users, but will be added in my next update :)
https://github.com/Corail31/tombstone_lite/blob/master/src/main/resources/assets/tombstone/lang/en_US.lang#L381
