### ISSUE TITLE
Crafting recipe missing or failling 

### ISSUE THREAD

**Issue by Oscaramelo** [Corail31/tombstone_lite#50]
### Minecraft Version

1.18

### Forge Version

39.0.88

### Corail Tombstone Version

7.4.1

### What happened?

When I craft a voodoo doll, I can't craft its upgrades.

I don´t know why but it just don´t let me craft any upgrade. 
![BugCorailTombstone](https://user-images.githubusercontent.com/99420544/157313515-8b9e3e67-7397-489f-ab5e-1bd62d0da4e3.PNG)

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Crafting recipes have been replaced since 1.17 by combinations directly in the inventory.
You just need to hover your item 'Voodoo Poppet' to see the tooltip, or uses JEI to see theses 'combination' recipes.
It's almostly similar the actions you do with an item 'bundle'.
