### ISSUE TITLE
[1.13.2] null in CapabilityDispatcher

### ISSUE THREAD

**Issue by Gbergz** [Corail31/tombstone_lite#51]
Minecraft Version: 1.13.2
Forge Version: forge-25.0.107
Tombstone Version: 3.4.0
Crash-report: [https://pastebin.com/bKai8fKZ](https://pastebin.com/bKai8fKZ)

**_What's Happening_**:
Creating a world, generating as normal but when it's on the stage "Joining World" the client shuts down, (Crashed)!

**Comment by Corail31** [comment]
i'll look further as it has been tested to work...

**Comment by Corail31** [comment]
@Gbergz can you start first to update your java version...

**Comment by Gbergz** [comment]
Might be another mod making it crash.
I don’t really know 🤷‍♀️

tors 4 apr. 2019 kl. 17:27 Corail31 <notifications@github.com>:

**Comment by gegy1000** [comment]
While Tombstone is in the call stack, it is not necessarily a tombstone issue. Some mod is returning null from `getCapability` when they should be returning `LazyOptional.empty()`

**Comment by Corail31** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/5645
