### ISSUE TITLE
Tomb raiding not working

### ISSUE THREAD

**Issue by DylanEhv** [Corail31/tombstone_lite#51]
### Minecraft Version

1.18

### Forge Version

40.0.54

### Corail Tombstone Version

7.4.3

### What happened?

When i try to kill my friend and loot his tomb stone after a minute it will says "You plunder the grave, better not hang around here" but the tomb is still there, and i also don't have the loot when i get the message.

this is what i have for config

#Whether to unlock access to a grave if the player has been killed by another player [false/true|default:true]
	pvp_unlock_grave = true
	#Whether to handle player death [false/true|default:true]
	handle_player_death = true

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by DylanEhv** [comment]
When does it get fixed?

**Comment by Corail31** [comment]
I don't forget you, probably tomorrow ;)

**Comment by DylanEhv** [comment]
haha sorry i didn't mean to push you, thank you very much
