### ISSUE TITLE
No items back from grave

### ISSUE THREAD

**Issue by Icedragonzzz** [Corail31/tombstone_lite#52]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Corail Tombstone Version

4.5.3

### What happened?

No one is receiving items when they die, The key does nothing 

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
No time for trolls, if you don't have time to localize the trouble in your modpack, i don't have time to help you.
