### ISSUE TITLE
ItemSeekerRod broken

### ISSUE THREAD

**Issue by snydej** [Corail31/tombstone_lite#53]
### Minecraft Version

1.16.5

### Forge Version

36.2.28

### Corail Tombstone Version

6.7.3

### What happened?

In func_77663_a, rather than using the x and z coordinates of the player to look up the chunk with the bell in it, it uses the x coordinate in both places. Only by placing a bell at a particular spot in the world and going back to the village was I able to get "target_found" set to true.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, you're right and i already fixed it in 6.7.5. It's mentioned in the changelog: fixes Seeker Rod (stuck finding the bell).
Just update your 1.16.5 version ;)
