### ISSUE TITLE
[1.12.2] Suggestion - Config option to toggle holiday tombstone models

### ISSUE THREAD

**Issue by DWX12** [Corail31/tombstone_lite#53]
Similar request/suggestion for year round Halloween/other holidays, but at the very least an option to have toggle-able recipes for holiday tombstones since you feel that holiday events should only happen around their time.

I would really like that option and others making modpacks may want to go for a specific holiday theme without having to play that modpack in that month or timeframe in order to activate it.

Thanks for all the time, hard work, and effort that has gone into creating this mod. It is well appreciated.

**Comment by Corail31** [comment]
Hi DWX12, i'm ok to add this option, and thanks for the comment :)
I just need to know if it's for the whole content of the Halloween (as explained in the compendium in 1.13.2) or [here](https://github.com/Corail31/tombstone_lite/blob/master/src/main_1.13/resources/assets/tombstone/lang/en_us.json#L465-L466) 
or just a part of it ? (the ghost can be boring for players who don't pray on the graves)

**Comment by DWX12** [comment]
Actually, if it's not too much trouble, an option for both would be nice. One for recipes for decorative graves and another for the whole holiday event (Halloween in this case). It's not only for packs, but good for testing purposes too.

Thanks for responding.

**Comment by Corail31** [comment]
So, i could add :

- a server config option to force every client grave to be rendered with the Halloween theme
- a client config option to see all graves in Halloween theme
- a server config option to enable Halloween outside the event but, i think some perks could be useless when the event is enabled, so i prefer to be sure to understand what is the main thing that you want from it. (if it's just to have no need of perk level for voodoo poppet for example)

**Comment by DWX12** [comment]
Most Halloween/holiday events from mods are decorative such as vanilla Minecraft for example (pumpkin headed zombies and skeletons or the present boxes) and others add items and mechanics that you can only get during a certain time period like special candy and equipment from the Inventory Pets mod.

If it's not too much trouble, all three options you listed would be good. If someone wants to see the decorative graves on their end while on a server or in a modpack (which they look awesome by the way) without affecting anyone else or if someone is making a modpack or holiday themed pack, but just cares about the decorations, then that's a nice option to have too. And of course, if anyone wants to test out everything that the holiday events do, theme a server or modpack around it, or just have it for their own personal use.

Atleast just an option to enable and disable the full event outside of the specified time and the decorative options would be nice to have if they aren't too much trouble to implement.

Sort of off topic, but a particle effect I've seen Better Animals + do is snowflakes falling around reindeer (possibly only in cold biomes), which I thought would be cool for you to do something similar for the graves instead of the fog for around Christmas time. Maybe even a Christmas Carol theme of the three spirits that visit Scrooge (Past, Present, and Future). Just some ideas.

**Comment by Corail31** [comment]
Back on this, may you contact me on curse or discord to test the current changes and see if all is ok ?
NB : about others seasonal events, nothing is planned for now.

**Comment by Corail31** [comment]
@DWX12 feel free to contact me for feedbacks about this change ;)

**Comment by DWX12** [comment]
Thank you so very much for not only considering my idea, but implementing it. I'll test out the changes when I am able to.

Again, thank you for such an awesome mod.
