### ISSUE TITLE
Halloween advancements should be hidden unless it's Halloween

### ISSUE THREAD

**Issue by DWX12** [Corail31/tombstone_lite#55]
I took a look at the advancements and saw that "Not so bad" and "Expert tasting" show up, but don't have any actual way to get them if it isn't Halloween time.

Recommend hiding both of those achievement until the player obtains a lollipop. Also maybe have them show up if it's Halloween or that option is enabled in the config for the Halloween event.

**Comment by Corail31** [comment]
@DWX12 By looking further, no advancement was hidden, so i changed it for the next release to hide the first advancements (except the one asking to choose the grave model), i also moved the advancement related to the book of disenchantment upper in the tree.
