### ISSUE TITLE
1.16.5 Compatibility issue with Dragon Survival mod

### ISSUE THREAD

**Issue by SumaniPardia** [Corail31/tombstone_lite#56]
### Minecraft Version

1.16.5

### Forge Version

36.2.35

### Corail Tombstone Version

6.7.6

### What happened?

Dragon Survival mod adds for extra slots for dragon characters to hold a sword, axe, pickaxe, and shovel so they can use them automatically.  If they die with tools in those slots, the gravestone will hold them UNLESS their inventory was full when they died, in which case the tools are deleted.  This is with Dragon Survival version DragonSurvival_DragonEditor-1.16.5-0.10.6.jar.jar, and I have reported it to them as well.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone

No

### Other relevant mods

Dragon Survival

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, the other mod doesn't have an issue section, or visible source.
The grave would take the items whatever if the inventory is full or not. They don't seem to use Curio for extra slots.
Edit: i suppose it's more related to when you recover the items on the player and how the inventory is filled with their implementation (as the item should fall on ground if your inventory is full).
Except if the other modder provides infos about this, the issue will be closed.

**Comment by Corail31** [comment]
@SumaniPardia I made a compatibility to auto-equip their custom claw slots that would solve the trouble for the next release ;)
