### ISSUE TITLE
[Bug] Grave's Key advancement shows up even if player has no key or grave

### ISSUE THREAD

**Issue by DWX12** [Corail31/tombstone_lite#56]
If a player dies without any items, no grave spawns nor key spawns, which works as intended; however, they will still get the advancement "Grave's Key". In most circumstances this wouldn't happen, but it doesn't make sense to get the advancement without getting a key. The first time getting the key should trigger the advancement rather than the first time a player dies.

Another minor bug is that the advancement name is called [INFO : Grave's Key] instead of just Grave's Key. Maybe because of the space between info and : ?

**Comment by Corail31** [comment]
This advancement "info" was just a way to get informed players of the importance of the key (asked by Yamza for atm remix) so, the name is normal.
I will change the advancement to just fire when you have a key ;)

**Comment by DWX12** [comment]
Ah, alright. From my perspective it just looked out of place or like a syntax error rather than a something I needed to take a look at. But hey, if it gets other players to take a look at it and it works, then it does its job.

Awesome job so far, keep it up.

**Comment by Corail31** [comment]
It's just the time to improve the compendium. After, there will be some clickable information in the chat leading to the explaination in the compendium.
