### ISSUE TITLE
[Suggestion] Add in an item to open up the gui and compendium

### ISSUE THREAD

**Issue by DWX12** [Corail31/tombstone_lite#57]
Just a suggestion to add in an item or book that opens up the gui and compendium so that players don't have to take up another key binding if they don't have to.

**Comment by Corail31** [comment]
Hm, why don't ask this on others mods to do the same ? so you'll safe your keybinds.
My answer is indeed "no" on this : there's a way to open this gui when you receive a new point to spend, and there's no default key on this keybind, to let you do what you want. An item to open a gui is really a bad idea. And you have the command /tbgui to open it.

**Comment by DWX12** [comment]
I thought of it more as a standard information book type of thing. Honestly, I didn't know about the command, but then again, I don't use commands all that much except for things I have to like changing the weather, game modes, time of day, etc.

This was only a suggestion. I can see it your way too. But I guess a book, block, or some other item to me, makes the mod feel more immersive than typing a command. Even something like an angel statue or something could serve the same purpose as a way to open up the gui. Just more aesthetics from my point of view.

And yes, I would ask similar things of other mods. Keybinds get taken up rather quickly, especially in large packs like Sky Factory 4 for example. But if you feel that this isn't something your mod needs then we can leave it at that.

Thanks again.

**Comment by Corail31** [comment]
Modpacks don't specially like when the grave mod is adding item/block id in 1.12.2.
I got requests for this to reduce the ids in the past (even if lots of past issues are no more visible since i removed the source code), and if i would add a book to open this gui, the next request would be to make the gui having a book background, that's really not the intention.
