### ISSUE TITLE
Crash at entering world

### ISSUE THREAD

**Issue by agentwolf88** [Corail31/tombstone_lite#57]
### Minecraft Version

1.18.2

### Forge Version

40.1.25

### Corail Tombstone Version

7.4.6

### What happened?

Crash at entering world

### Log Link

https://pastebin.com/L3BF9m3c

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

No

### Other relevant mods

Agricraft, Minecolonies

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's not the first time that i saw this when attaching capabilities where the delegate in entityType is null but it's anormal to my opinion. The entity is probably created early or not registered.
I changed my code on the compat with Minecolonies with log.
