### ISSUE TITLE
Claw slots from Dragon Survival are auto-equip when not yet a dragon

### ISSUE THREAD

**Issue by butterflygirl30** [Corail31/tombstone_lite#59]
### Minecraft Version

1.16.5

### Forge Version

36.2.35

### Corail Tombstone Version

6.7.7-1.16.5

### What happened?

I die, and tools and weapons disappear from my inventory.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone

No

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You bypassed what is asked in the form. You need to test to produce this issue with only Corail Tombstone or to find the mod responsible for this issue. You also didn't mention if you got a grave or any detail that could help.
NB: feel free to edit.

**Comment by butterflygirl30** [comment]
oh ok ill do this sorry didnt know still new to this process

**Comment by Corail31** [comment]
If you use the mod Dragon Survival, the items may be in their custom inventory (claw slots).
You can define in your client config (/tbgui and the button config -> auto_equip_rule) if you want to "auto-equip" your items on respawn or when recovering items from a grave (and it can help to locate your trouble).

**Comment by butterflygirl30** [comment]
I  am using that mod. and wasnt a dragon when it was happening i will disable that setting tho thank u

**Comment by butterflygirl30** [comment]
i dont see a / command /tbgui

**Comment by butterflygirl30** [comment]
oh, i misread your post sorry

**Comment by butterflygirl30** [comment]
sorry to bother again. the auto equip rule is set to always, but we are still getting items taken. and i checked it's not in the dragons inventory(i became just to test this)

**Comment by Corail31** [comment]
In 1.16.5, the command "/tbgui" doesn't appear with autocompletion (only in 1.19) but you can enter it manually.
I suppose the compat Dragon Survival requires an additional compat when you're not yet a dragon.
NB: you can simply use the version 6.7.6 that doesn't contain the compat.
Edit: i made the test, they're not lost. They're in the claw slots but as you're not yet a dragon, you can't access them.

**Comment by butterflygirl30** [comment]
sorry for late reply i fell asleep changing config didnt fix it
	#Defines when to automatically equip your items [NEVER/GRAVE_RECOVERY/DEATH_RESPAWN/ALWAYS|default:ALWAYS]
	#Allowed Values: NEVER, GRAVE_RECOVERY, DEATH_RESPAWN, ALWAYS
	auto_equip_rule = "NEVER"

**Comment by Corail31** [comment]
@butterflygirl30 Can you just try 6.7.8 ? ;)
