### ISSUE TITLE
[Request] Make the Gravestone mod have the fog effects of your mod

### ISSUE THREAD

**Issue by Xorbah** [Corail31/tombstone_lite#59]
Title. I like to use both of your mods, could you possibly extend the fog effects to also take effect with Nightkosh's Gravestone mod?

Curseforge link here - 

https://minecraft.curseforge.com/projects/gravestone-mod-graves?gameCategorySlug=mc-mods&projectID=62929

**Comment by Corail31** [comment]
I don't think i have a real wise way to do it from my mod, so you'll have to wait the other issue that you opened on this mod.

**Comment by Xorbah** [comment]
Okay, thank you.
