### ISSUE TITLE
In R.A.D not working

### ISSUE THREAD

**Issue by moduS0421** [Corail31/tombstone_lite#6]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2854

### Corail Tombstone Version

4.4.3

### What happened?

I'm unable to use corail tombstone when erebus is on the server, is there any way to make the tombstone over erebus? I looked up all the configs but couldn't find anything on erebus to disable it's tombstone? (The mod is working itself but no tombstone from corial tombstone is ever made, only erebus's tombstone is made and I hate it compared to yours!)

### Gametype

Dedicated Server

### Tested with only Corail Tombstone

- [ ] Yes

### Relevant others mods

Erebus

**Comment by Corail31** [comment]
Update your version to latest, there's a mention to compat with Erebus.
The objective in theses compatibilities with others 'grave mods' is to be just before them, and allows players to define in their client config in game if they want a 'tombstone grave' or not (and if not to let the 'others grave mods' behind handling their code).
For this, i need to add an optional dependency on theses mods for the priority of events (why it doesn't work with your version).
It's the best i can do to not just make them incompatible (as it would logically be).
