### ISSUE TITLE
[1.10.2] Griefprevention Question/issue

### ISSUE THREAD

**Issue by YOYOK9** [Corail31/tombstone_lite#6]
Not sure if this is a bug or if I'm just forgetting something but my players have noticed that their graves do not spawn when they are killed within a Gp claim. Any ideas what might need to be added? or is this a gp issue?

**Comment by Corail31** [comment]
You should ask about it to modders of grief prevention mod, because if you're in a non building area, it won't allow to put the grave... ^^ Perhaps, this mod allows a list of allowed blocks and the name of grave is "tombstone:tombstone" ;)
Keep me informed :)

**Comment by YOYOK9** [comment]
Heres the link where I posted the question
https://forums.spongepowered.org/t/griefprevention-official-thread-1-8-9-1-10-2-1-11/1123/1262?u=yoyok9

**Comment by Corail31** [comment]
Nice, i'll wait for their answer, before choosing a way to make it work :)

**Comment by YOYOK9** [comment]
Not sure if this is a newish issue but:

Someone on my server told me that they were killed by another player outside of a claim and no tomb spawned. Ran some tests and if a player is killed by another player no tombs spawn (tested in overworld and nether) but if they are killed by the world (mob/nature) it spawns one... Did have pvp time mod installed but it doesn't effect the nether.

**Comment by Corail31** [comment]
As i understand it, grief prevention probably cancel the event with drops when killed by player. (i could change the priority of my event as a test and let you try it as a fix)
Does the drops lies on the ground or they are kept in inventory after death? (because i saw a config option in grief prevention to keep inventory after death)

**Comment by YOYOK9** [comment]
The problem is that when the player dies all their stuff is voided on death. doesn't drop on the ground. It is almost like the grave spawns, takes the items, the despawns

**Comment by Corail31** [comment]
they don't have errors log?

**Comment by YOYOK9** [comment]
nope. not that I am aware of.

**Comment by Corail31** [comment]
Could i ask you to test if "Corail Tombstone 1.2.5" as the same issue ?
It's to be sure the issue doesn't come from my last patch that was about pvp.

**Comment by Corail31** [comment]
I tested pvp mode on server without trouble (the incompatibility should come from GriefPrevention)
