### ISSUE TITLE
[1.16.4] (Curios mod compatibility) inventory sorted

### ISSUE THREAD

**Issue by Ruchian** [Corail31/tombstone_lite#6]
If you open your grave with the key, it won't put stuff you had equipped back into your Curios inventory.
Also, Curios inventory works perfectly fine on 1.16.4, so Issue 3 is unrelated. The thing is, I suspect that because it cannot put these items back, it causes your inventory to be simply sorted instead of putting stuff back where they were in the inventory.

I encountered this issue in AllTheMods 6: 1.3.7 modpack, which has:
Forge 35.1.13
Curios: 4.0.3.0
Corail Tombstone: 6.2.0
Minecraft: 1.16.4

**Comment by Corail31** [comment]
I can't ensure Curios to work correctly in 1.16.4, the compat has a code for reequip but the modder made changes in its mod, and not sure it still works. I got no answer from illu so it will stay like this, it's its code after all.

**Comment by Ruchian** [comment]
Inventory is still sorted, but backpacks for example do get put back into slots. Any open slot in the hotbar is taken by a random item.

Sorry about before, I was playing on ATM6 modpack which has that specific version, despite it being newer than when you released 6.2.2. I assumed it was newest.

**Comment by Ruchian** [comment]
Thanks at least, for your comment. I think the modpack makers of AllThemods6 will include your update in their next release. My bad for not checking the version changelog before. ;;
