### ISSUE TITLE
IllegalAccessError : entityLivingToAttack

### ISSUE THREAD

**Issue by Dayyer1** [Corail31/tombstone_lite#6]
Whenever I shoot a mob with a Tinker's Construct Arrow, the game crashes.
I'm not sure if tombstone or TC is causing this error.

[crash-2018-05-15_23.59.20-server.txt](https://github.com/Corail31/tombstone_lite/files/2007592/crash-2018-05-15_23.59.20-server.txt)

**Comment by Corail31** [comment]
It was a missing AT in this version, i'm going to publish a new release (but i'll look if i should add others features of 1.12 that aren't yet added like the code to avoid anti griefing mods)

**Comment by Corail31** [comment]
Fixed in this release : [Release 2.9.4 for 1.10.2](https://minecraft.curseforge.com/projects/corail-tombstone/files/2562507)
