### ISSUE TITLE
[Cross Mod Bug] Backpack from Improved Backpacks returned as Blank Scroll

### ISSUE THREAD

**Issue by Dragnier** [Corail31/tombstone_lite#60]
I had a basic backpack from [Improved Backpacks](https://www.curseforge.com/minecraft/mc-mods/improvedbackpacks) and died. When I retrieved my grave, I got a Blank Scroll from your mod instead of the backpack and lost quite a bit of stuff.

**Comment by Corail31** [comment]
Thanks for your visit, lol
