### ISSUE TITLE
tombstone-8.0.2-1.19 combine in inventory dosn't work

### ISSUE THREAD

**Issue by Bazilisko** [Corail31/tombstone_lite#61]
### Minecraft Version

1.19

### Forge Version

41.0.37

### Corail Tombstone Version

8.0.2

### What happened?

At the moment I try to combine in the inventory, it seems that crafting is not available. test with various mods installed or just tombstone.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Please read the compendium in game for more information before posting issues (/tbgui compendium combination).
NB: i admit it's not instinctive, i'll look for 1.19.1 to re-add some crafting recipes ;)
