### ISSUE TITLE
Grave dust are no longer stacking

### ISSUE THREAD

**Issue by LemADEC** [Corail31/tombstone_lite#61]
As of 3.5.0-1.12, Grave dusts are no longer stacking in your inventory.
When stacking in the world, you can pick them up as stacked, but if you split the stack in your inventory, you can't stack them anymore.
Previous version 3.4.1-1.12 doesn't have the issue.

Seen while updating https://minecraft.curseforge.com/projects/spacearchitect/files/2712729 .

**Comment by Corail31** [comment]
Hi LemADEC,
Thanks for your report, it's due to a little oversight after merging the crafting ingredients into one item :)
I'll change it in the next release. (the recommanded version is still 3.4.1)

**Comment by Dragnier** [comment]
If it really bugs you, you can use StackUp in the meantime. It lets you modify stacksize for any item or groups of items based on lots of options. Wiki and everything. Same author as FoamFix and Charset.
