### ISSUE TITLE
[suggestion] Crow or Raven familiars/pets

### ISSUE THREAD

**Issue by DWX12** [Corail31/tombstone_lite#62]
Reading the latest change log and you spoke of familiars, which made me think of images of black birds perched on graves and thought that would be a cool addition to this mod. One such image is that of Edgar Allan Poe's The Raven with the raven being perched and looking unto things.

The AI of the raven could be similar to that of the Minecraft parrot and would perch on the owner unless a grave is nearby. Could be used to help lead a player to their grave, attack mobs, scavenge for items (iron and gold nuggets, enchanted items, potions, etc.) since they like picking up shiny items, and possibly various other perks, which would be unlocked in the perk tree. Maybe an easter egg where it would say "never more".

I think it's a cool idea and just like the image of a black bird perched on top of a grave.

Thanks again.

**Comment by Corail31** [comment]
Hi DWX12,
Your idea is a good idea, that fits well with tombstone, but any way, it should be done in a separate extension, and would require the time to make the crow model in tabula and the texture.
So, i'm going to tag it for 1.14+ extension for now, unless i'm motivated to create the model and start a small extension with this content (but it's rare when i'm motivated to do artistic things, i focus more on improving the existing features)
Feel free to detail more this feature :)
