### ISSUE TITLE
I can't use the right click on scrolls, tablets or enchanted key

### ISSUE THREAD

**Issue by Jotechno** [Corail31/tombstone_lite#62]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Corail Tombstone Version

4.5.5

### What happened?

Hello! I have the corail tombstone mod and I'm trying to use the tablets, the scrolls and the enchanted key by holding right click, but when I release it nothing happens, is anything wrong?

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
There can only be 2 reasons:
- you discover the mod and have not enchanted the item with a Grave Soul
- you release the mouse button instead of waiting the required time (which can be reduced with the Perk Concentration)

**Comment by Jotechno** [comment]
I have like 20 enchanted items and I've been holding the mouse for like 5 orr7 seconds
![image](https://user-images.githubusercontent.com/103002715/176796930-cf9ad6ad-756e-49e2-81d5-0561cf3cffc6.png)
![image](https://user-images.githubusercontent.com/103002715/176796998-b23dc7af-e429-47b2-98ff-f28bad7198a7.png)

**Comment by Corail31** [comment]
@Jotechno and you also checked that you tested with only Tombstone so you got an answer adapted to your information.
Edit: i just saw your answer on CurseForge that you had succeeded :) I'll probably remove 1 second in future versions (it looks long to me too)
