### ISSUE TITLE
Crash when exploring "Attempted to load class net/minecraft/client/renderer/LightTexture for invalid dist DEDICATED_SERVER"

### ISSUE THREAD

**Issue by Gbergz** [Corail31/tombstone_lite#63]
### Minecraft Version

1.19

### Forge Version

41.0.62

### Corail Tombstone Version

8.0.2

### What happened?

Server crashed suddenly while running around "Ticking entity".

### Log Link

https://gist.github.com/Gbergz/687c1b8783eee5af07272b0406a6579b

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone

No, but it might happen didn't have time to test though.

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Gbergz Hi and thanks for reporting this issue.
It looks like i used a wrong method by porting the mod to 1.19.
As 1.19.1 should be soon, i'll wait before updating the mod, but you can disable Shadow Step enchantment to solve this problem ;)
