### ISSUE TITLE
The ankh dosnt work anymore

### ISSUE THREAD

**Issue by cjser** [Corail31/tombstone_lite#63]
Since last update the ankh dosnt work anymore. I try to use it in both hands near the tomb and still do nothing.

**Comment by Corail31** [comment]
I need precision, can you confirm it's on 1.12.2. (as 1.13 is ok)

**Comment by cjser** [comment]
Yes, is 1.12.2. I need a receptacle now?

**Comment by cjser** [comment]
I will try with the version tomorrow.

**Comment by Corail31** [comment]
@cjser no, you don't need a receptacle, it's more a mistake when i've done this change in 3.5.1-1.12 :
"the ankh can only be used in right hand, and prevent to pray with a receptacle in offhand if the condition doesn't fit"
I'll probably publish a new release tomorrow ;)
