### ISSUE TITLE
Game crash after upgrading Forge to 41.0.91

### ISSUE THREAD

**Issue by jellybean13** [Corail31/tombstone_lite#64]
### Minecraft Version

1.19

### Forge Version

41.0.91

### Corail Tombstone Version

8.0.2

### What happened?

All mods in mod lists are working on Forge 41.0.63. However, Corail Tombstone, Configured and Catalogue stop working after upgrading Forge to 41.0.91.

Relevant commits in MinecraftForge (suspicious): https://github.com/MinecraftForge/MinecraftForge/commit/4d074f0a1ef1d774786b4f1e1e3e827a9bf576e0

### Log Link

https://pastebin.com/eZDsSbxm

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone

No

### Valid Launcher

- [X] Yes

**Comment by papillo12** [comment]
yes, forge made many changes in 41.0.64 and many mods have to be updated, have to wait for corail to update.

**Comment by Corail31** [comment]
The real question is why are you updating to the latest forge knowing these breaking changes and 1.19.1 is coming.
I'll have a look tomorrow to make an update.
