### ISSUE TITLE
Support for spigot/bukkit or Forge

### ISSUE THREAD

**Issue by alexchandel** [Corail31/tombstone_lite#65]
The project page doesn't state any requirements.  Does this support spigot/bukkit?  What version of Forge does it require?

**Comment by Corail31** [comment]
Tombstone is build for forge 2611+. It works on Sponge correctly (although i haven't tested it recently).
Then, to know if it's compatible with bukkit/spigot, and not being myself a player, i have no idea (the question being more if forge works with them).
