### ISSUE TITLE
1.18.2 getting stuck on ''loading terrain'' screen

### ISSUE THREAD

**Issue by AzyWinter** [Corail31/tombstone_lite#65]
### Minecraft Version

1.18.2

### Forge Version

Forge - 40.1.60

### Corail Tombstone Version

tombstone-7.4.9-1.18.2.jar

### What happened?

issue for minecraft 1.18.2 (not listed in the dropdown menu)

when teleporting to another dimension using the enchanted key, the game gets stuck on the ''loading terrain'' screen, untill you either alt+f4 or get killed by something at the place you teleported to

Example: death occurs in nether -> respawn in overworld -> use of enchanted key -> stuck on loading screen 

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
If you bypass the template, don't imagine a better end.

**Comment by AzyWinter** [comment]
> If you bypass the template, don't imagine a better end.

so you dont offer support for 1.18.2 anymore?

**Comment by AzyWinter** [comment]
> If you bypass the template, don't imagine a better end.

please would you still be able to look into it

**Comment by Corail31** [comment]
Hi, i'm not against to bring some minimal support to 1.18.2 even it the version is in its "final version".
But if i read your issue, it's about teleportation that is a code from Mojang, nothing else.
So, i had in mind that your report is probably wrong and your tests are done with others mods affecting this teleportation?

**Comment by AzyWinter** [comment]
> Hi, i'm not against to bring some minimal support to 1.18.2 even it the version is in its "final version". But if i read your issue, it's about teleportation that is a code from Mojang, nothing else. So, i had in mind that your report is probably wrong and your tests are done with others mods affecting this teleportation?

i have tested with other mods, and with corailtombstones alone
tested in a dedicated server and single player world
i've also tried using a diffrent mod that adds crossdimensional teleportation commands but those do work fine
whereas the teleportation provided by the enchanted key gives you an infinite loading terrain screen in multiplayer 

-only cross dimension teleportation doesnt function correctly, teleportation within one dimension works fine

-in singleplayer the loading terrain screen isnt infinite but the world refuses to render

**Comment by Corail31** [comment]
@AzyWinter Sorry for the doubt on the validity of your report, but i finally located the problem (a bad param when calling the respawn packet), so thanks you ;) It was only present in 1.18.2

**Comment by AzyWinter** [comment]
> @AzyWinter Sorry for the doubt on the validity of your report, but i finally located the problem (a bad param when calling the respawn packet), so thanks you ;) It was only present in 1.18.2

heyyy im glad to be of help ^-^
