### ISSUE TITLE
Graves are moving on their own

### ISSUE THREAD

**Issue by katubug** [Corail31/tombstone_lite#66]
One of my players has made a bunch of the craftable tombstones in order to make a graveyard. But often times when she comes back to the area, they've rotated or shifted over one block. I'm not sure what could be causing it.

Here's our version of the mod: tombstone-3.5.3-1.12
And forge: forge-1.12.2-14.23.5.2838-universal
And our full modlist with versions is at the bottom of this post: http://enthusiasticraft.cf/modpack-update-1-5-1/

**Comment by Corail31** [comment]
Hi Katubug,
You're probably right as it reminds me an old issue, i'll have a look tomorrow. [Link](https://github.com/Corail31/tombstone_lite/issues/16)

**Comment by Corail31** [comment]
It's fixed in dev, so in the next release, it will be fine, thanks for reporting this issue in here :)

**Comment by katubug** [comment]
Glad to hear it, thank you! And it's no problem, happy to help :D

**Comment by Corail31** [comment]
@katubug it's ready in 3.5.4.

**Comment by katubug** [comment]
Great, I'll be updating asap! Thank you very much!
