### ISSUE TITLE
Particles don't display with shaders (Oculus ~Iris)

### ISSUE THREAD

**Issue by Tekyo23** [Corail31/tombstone_lite#67]
### Minecraft Version

1.18.2

### Forge Version

1.18.2-forge-40.1.54

### Corail Tombstone Version

7.4.9

### What happened?

Hello!
Well, I've been playing with the Corail Tombstone for a while and I've seen that when I have the shaders activated, the soul of the graves is not visible. I don't know if it is on purpose, but with hope it is not, I'm reporting it. 

I use the shaders "Complementary Shaders v4.5.1" and "Sildurs Vibrant Shaders High v1.32" but I've tried with the "Chocapics", the "Seus" and the "BSL" and none of them show the soul.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (this test is required)

Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, i understand your issue, but it's about shaders for "Optifine".
Theses shaders are done by "some other people" than the Optifine modder (sp614x) and can be easily incompatible.
Additionally, it's not easy to test optifine in workspace as far as i know.
So, except if i get some render hints how to to be certain to render the Grave Soul with theses custom shaders, i couldn't help you easily.
NB: some shader names were already problematic in 1.12.2 (Sildur & chocapics for sure)

**Comment by Tekyo23** [comment]
Hmm, I understand, I thought it was probably because it is hard to make a render compatible with shaders but I wanted to be sure.
I hope one day you'll find the way to make it possible. Thanks for your work developing this mod! <3
Have a nice day.

**Comment by Corail31** [comment]
@Tekyo23 Can you make this happening in 1.19? (as i prefer to make changes in future 1.19 releases that you could then test unlike 1.18.2 which gets fewer releases due to final version and could be fixed later)
I should perhaps specify that I gave up recovering my mc account so I rely on players in general for tests outside workspace (and this is what gives me problems to debug optifine)

**Comment by Corail31** [comment]
@Tekyo23 If i don't get enough infos, i wouldn't be able to make adequate changes. If the test on 1.19 is not possible, which particles of Tombstone are you able to see with theses shaders on 1.18.2 ? Are you certain to use "OptiFine HD U H7" ?

**Comment by Tekyo23** [comment]
I cannot play in 1.19, idk but my minecraft crashes. 
In 1.18.2 I don't see any particles except the grave's key's one (the rainbow ones). And I'm not using Optifine, I'm using Rubidium

**Comment by Corail31** [comment]
So, try to update your version of Occulus or report to them (there are already reports about invisible things).

**Comment by Corail31** [comment]
I reopened the issue as i was able to test it in 1.19.2 with Rubidium & Oculus (and BSL).
As soon as an optifine shaderpack is active (by using the modified vanilla video setting), no transparent particle using the tombstone shader will display.
Hint: it's possible to see the grave at distance if the client config is set to display a box (and not particles) but the grave souls won't be visible at all, nor the casting animation.
Edit: Actually, the latest update for 1.18.2/1.19.2 displays the particles except smoke. The next release will fix the smoke (tested with BSL & Sildur Vibrant) except with Complementary Shader (on the same time, it already doesn't work in 1.16.5) ;)
