### ISSUE TITLE
Shulker attacks cause infinite floating if under Purification effect

### ISSUE THREAD

**Issue by VallenFrostweaver** [Corail31/tombstone_lite#67]
Upon being hit by a shulker projectile while under the Purification effect the levitation effect persists after it is supposed to expire and gets stuck at 0:00. I am forced to drink milk to remove the Purification effect and then enter an effect command to renew and cancel the old levitation effect.
Forge: 14.23.5.2836
Corail Tombstone: 3.5.3-1.12
Minecraft 1.12.2
EDIT: The same happens with the wither effect.

**Comment by Corail31** [comment]
Hi VallenFrostweaver,
The attack is not related and just reloading the game is enough too, i made a fix in dev for it :)

**Comment by Corail31** [comment]
It's fixed in 3.5.4, thanks for reporting the issue :)

**Comment by VallenFrostweaver** [comment]
No problem. Thanks for making a cool mod.
