### ISSUE TITLE
Server randomly crashing

### ISSUE THREAD

**Issue by misterplus** [Corail31/tombstone_lite#68]
Here's the crash report:
https://pastebin.com/X4N7ggWe

It seems like a advancement issue, I have triumph installed, not sure if it's the reason.

**Comment by Corail31** [comment]
@misterplus Did you remove the tombstone advancement? because there's no error in tombstone at this line...

**Comment by misterplus** [comment]
I use the mod "simple dimensions" to create a custom dimension, and when players die in it, this crash happened.    I'm not trying to removing the advancements.

**Comment by misterplus** [comment]
Ahhhhhh, I think i found the problem, the mod "better advancement" edited the way advancement shows, when I remove it, the crash no longer happens, I think it's because the way tombstone handles the advancement is not compatible with better advancement, but other mods works fine, I suggest you looking into that.

**Comment by Corail31** [comment]
First thanks for the localization of the trouble :)
Can you try this blind fix ? (as it's based on trigger so, it shouldn't be anymore in conflict with this mod)
[Link](https://cdn.discordapp.com/attachments/429050628044488705/592500017554653184/tombstone-3.5.5-1.12.jar)

**Comment by misterplus** [comment]
Great! There seems to be no more errors, if any crashes happens again, I'll let you know! Thanks for the help!
