### ISSUE TITLE
Error in the console "The death event of the player

### ISSUE THREAD

**Issue by ghost** [Corail31/tombstone_lite#69]
### Minecraft Version

1.18.2

### Forge Version

1.18.2 - 40.1.68

### Corail Tombstone Version

tombstone-7.4.10-1.18.2

### What happened?

Hi, I've been playing with the mod "Corail Tomstone" and "Vampirism" and every time I die being a vampire I get this error in the console "The death event of the player TextComponent{text='Player', siblings=[], Style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft: default}} was cancelled by another mod".

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (this test is required)

No

### Other relevant mods

Vampirism

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi Tychaia, it's a minor translation bug ;)
Additionally, don't try to put more than one issue: i already answered on curseForge that Vampirism is incompatible with PlayerRevive on server in 1.18.2 and why i edited your issue.
**from CurseForge**: _The 2 mods that you mention look to have already incompatibilities between them on server ([Vampirism issue 1105](https://github.com/TeamLapen/Vampirism/issues/1105))
Tombstone almostly waits for the drop events to make a grave after these mod behaviors, nothing else.
You can also use the command /tbrecovery if you lost something._
