### ISSUE TITLE
[Suggestion] Client config to disable or reduce shadow step particles

### ISSUE THREAD

**Issue by CplPibald** [Corail31/tombstone_lite#7]
The Shadow Step enchant is a really cool idea, but when wearing shadow step boots, the particles are opaque enough that it's difficult to see blocks below you, especially in the dark, and _especially_ when wearing other particle-generating items.

![](https://i.imgur.com/XeytV7a.png)

This image is Shadow Step boots with the Astral Sorcery Mantle of the Stars.  Even in full daylight it's hard to make out the block I'm standing on.  Looking down also causes a noticeable frame rate drop on a lower-end graphics card.  Changing the particle settings in Optifine to "minimal" has no effect.

Any chance we can have a setting that allows clients to turn off the boot particle effect?  It would be much appreciated!

**Comment by Corail31** [comment]
there is already a client config option for this :)

**Comment by CplPibald** [comment]
Oh, man, I swear I had searched the config, but I missed that setting.  Sorry for the spurious issue.  You clearly already anticipated and addressed my suggestion.  Thanks!

**Comment by Corail31** [comment]
Don't hesitate to ask any way when you don't find, i'm here for this ;)
