### ISSUE TITLE
[1.16.4] Question &/or bug? 

### ISSUE THREAD

**Issue by YOYOK9** [Corail31/tombstone_lite#7]
Not sure if this is a bug or just a confused config. I have noticed in my custom pack/server that when a player dies 2 tombstones spawn. A normal looking one (no outline) and an outlined one. Both spawn more or less beside one another only thing it the outlined one is empty where the normal looking one has the items in it.  The key will only disappear when the outlined grave is picked up. 
![](https://puu.sh/H3vGU/314fd48d41.png)

If this is just a config thing which config do I need to change? 
If it's a bug here is all the related stuffs:
MC: 1.16.4
Forge: 35.1.28
Corail: 1.16-6.2.3

**Comment by Corail31** [comment]
The best i can say you for now is that it should be related to another mod, you should first test with Tombstone alone and then testing your modpack by splitting in half and testing :)

**Comment by YOYOK9** [comment]
In the morning I will do the process of splitting the pack. 
Mod List: https://pastebin.com/69JZe9nC
F3 of heighted grave: https://puu.sh/H3EHq/620165a1c2.png
F3 of normal grave: https://puu.sh/H3EHU/4b70f41bf5.png

Note: the highlighted one on lights up when the key is in my hand. Both disappears when crouched on. But only the highlighted one takes the key away.

**Comment by Corail31** [comment]
So you have your answer, you combine another grave mod.

**Comment by YOYOK9** [comment]
Ah yeah I see it now, Not sure how simple tomb got in there. Thanks for the hand
