### ISSUE TITLE
problem about knowledge of death

### ISSUE THREAD

**Issue by TBFenix45** [Corail31/tombstone_lite#7]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Corail Tombstone Version

tombstone-1.16-6.4.7

### What happened?

My problem is basically that when my character dies, all levels of knowledge of death are reset. going from having for example 5 levels to 0 every time I die. is there any way to fix it?

### Gametype

Dedicated Server

### Tested with only Corail Tombstone

- [ ] Yes

**Comment by Corail31** [comment]
If you want some helps, you need to fill the relevant informations, and theses informations include to test the mod with only Corail Tombstone or to find the related mods that make your trouble happening.
Without theses informations, don't open issues as you won't get any answer as any mod can break your setup.
Edit: if you're using a modified Forge (like Mohist), it may be related. Does it happen in singleplayer ? May you check in the common config (on the server) if "knowledge_loss" is set to 0 ?
