### ISSUE TITLE
Graves eat all keys instead of only the associated one

### ISSUE THREAD

**Issue by groverfield** [Corail31/tombstone_lite#7]
As the title says, which is a problem since graves appear to be indestructible.  So say, a player dies, and gets a grave key, and dies on their way back to the grave, and now they have two keys instead of the old key being inside of the new grave or only one key disappearing.  You access the new grave on the way to the old one, and you lose both of the grave keys.

**Comment by Corail31** [comment]
For now, just change the decay time in your config (the file in config folder, not the gui in game)
to allow to loot your grave after x minutes without key. I'm going to make test.

**Comment by Corail31** [comment]
It's confirmed, and i'll patch this for tomorrow.

**Comment by Corail31** [comment]
fixed in 1.3.6 (thanks for the report :+1: )
