### ISSUE TITLE
[1.14.3] Explosions blow up the player and a grave is not formed.

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/tombstone_lite#70]
When a player walks over a mine and blows up the player is disintegrated and a grave does not form, the key is given a tombstone key as if a grave was created but it is not.  When a player holds the key and teleports to where the grave is, it is not there.

If you have a grave in the world and put three mines around it and blow up the mines, the grave is not destroyed, so I suspect it is in the way the player is killed not the grave itself.

**Comment by ProsperCraft** [comment]
This was reported to security craft, they don't have a github but a google form, this was supposed to be a crosspost for your information.

**Comment by bl4ckscor3** [comment]
1. SecurityCraft has a GitHub repository: https://github.com/Geforce132/SecurityCraft
2. This is not an issue caused by SecurityCraft. On a client with only Corail Tombstone installed, I killed myself with vanilla TNT and the grave did not appear, just like described by ProsperCraft above.

**Comment by Corail31** [comment]
Hi Goshen,
I can reproduce it, and as far as i understand it in debug : 
- the first step of the explosion happens and forge gives us an event to remove our blocks if present from that explosion (but no grave yet) - during this step, the player dies creating a grave.
- the second step of the explosion happens : it takes the list of positions known to be explodable... where the grave is now, and blow it with no forge event to prevent it.
So for now, i suppose i could trick the thing, but it's not reproductible in 1.12.2... you know what i mean.

**Comment by Corail31** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/5914
