### ISSUE TITLE
the key disappears

### ISSUE THREAD

**Issue by srdelri** [Corail31/tombstone_lite#70]
### Minecraft Version

1.16.5

### Forge Version

32.2.34

### Corail Tombstone Version

6.7.8

### What happened?

I have a magma server for 1.16.5 with several mods, the problem is that when I die the tomb is generated but I don't receive the key, this only happens on the server, because if I open the map in my minecraft the key works perfectly.  I have been doing tests and I have tried the command [/give @a tombstone:graves_key] and I receive the key but it instantly disappears from the inventory, and in the server console there is no record that anything has been deleted.  Can somebody help me?

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (this test is required)

No

### Other relevant mods

Player revive

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@srdelri If you want my help, you have to test with a forge server with player revive, or a magma server without player revive in way to localize your trouble.
FYI The key can't be received with /give because it needs the data for the location of the grave.

**Comment by srdelri** [comment]
I'll try it but with the /give command it doesn't work

**Comment by Corail31** [comment]
I made tests: Player Revive (latest 1.16.5) works properly on server with Tombstone and the key is present.
Player Revive is incompatible with Mohist & Magma.
I won't test Magma (as it has to behave like forge...) but there seems also a report about Tombstone:
[link](https://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/issues/29)
So, according to it, i would suppose there's no grave and you only see the place of your minimap mod (showing your death location, and not a grave). So, it's up to you to test if Magma works with only Tombstone. In general, Tombstone provides a message to a player that dies. If not, it means that Magma doesn't fire the drop event (or related to keep inventory).

**Comment by zackfall** [comment]
I know this is a closed issue and a little old, but I'm having the same problem now with mohist, could it be that tombstone, I'm having the same problem, I die and but I don't get the key and the grave doesn't appear
![chat](https://i.imgur.com/sLNK66n.jpg)
![items](https://i.imgur.com/TKYpFhr.jpg)
In the in-game config I have turn off the deny grave on death and I have also player revive, and I'm playing in the 1.19.4 is there some incompatibility with that version? And I also tried without player revive but is still happening.

It is something with the version or with mohist?
