### ISSUE TITLE
[1.12.2] bauble equpiping issues II, electric boogaloo. Soulbound shifting causes bauble unequiping and false equiping 

### ISSUE THREAD

**Issue by Shibva** [Corail31/tombstone_lite#71]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Corail Tombstone Version

tombstone-4.5.6-1.12.2

### What happened?

This is a continuation of issue #60, while the overall issue regarding that has been resolved, it appears the issue regarding baubles unequipping themselves by baubles that can go into any slot is occurring ONLY if they have a soulbound enchantment on them

to best demonstrate this issue, ill provide visuals on the issue occurring

Here is me with various trinkets; keep note of the lemon, a bauble that can go into any slot and enchanted with Tombstone's Soulbound enchantment.
![image](https://user-images.githubusercontent.com/38770780/181123342-8a4d5d3d-e39e-440a-b627-19a925e58579.png)

Here is me after killing myself (via /kill). Notice that the lemon had moved; keep in mind this action.
![image](https://user-images.githubusercontent.com/38770780/181123558-c13c8891-344c-401d-8a0d-f5e942418981.png)

Finally, here I am after recovering my equipment from the grave generated
![image](https://user-images.githubusercontent.com/38770780/181123665-cc6f0393-ccd2-4458-aa69-689f4c2fcfb4.png)
As you can see, because of the soulbond item moving into a different slot, the pink item couldn't re-equip in that place given that it can only go into this slot and instead goes back into my inventory slots (and will drop as an item if it was full)

In my perspective, a solution to this would have soulbound items equipped in the baubles inventory slots to remember where they were last equipped and then return into that slot. this would be the best action and having it remember such if its only in these slots would be negligible to performance overall

==================

and while I'm on this, id also likes to point out that regardless of the bauble being enchanted with soulbound or not that baubles will be put into their slots if the slot is open and you have it in your inventory. Not that this is a big issue but something id likes to point out if for some reason this is a problem.

Feel free to reach out if you need any more info, and thanks again for looking into this and my last issue (#60 ) ^w^

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (this test is required)

No

### Other relevant mods

same as report #60

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Shibva I'll adapt it but i can't say when since 1.12.2 receives less updates.

**Comment by Shibva** [comment]
👍

**Comment by Corail31** [comment]
Let me know if it works properly, i was not able to test with a "trinket type".

**Comment by Shibva** [comment]
@Corail31 Hey uh, im aware you have moved on from this version of the game but I noticed 2 issues, one not necessary and one that appears to be a missed error

1. auto-equip doesn't seem to like requiring stuff that was in the offhand slot (minor)
2.  **Command Permissions are messed up; allowing for a non-cheat enabled word and people without special permissions to use admin commands** (Major). Im guessing one of the final changes made might have unintentionally screwed up the command permissions needed
