### ISSUE TITLE
Config typo on backing up of players.

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/tombstone_lite#71]
#Options related to the command recovery and auto-save of players
[recovery]
	#Enables to backup automatically players [false/true|default:true]
	recovery_player_enable = true
	#Time in minutes between players' backups [10..1000|default:40]
	#Range: 10 ~ 1000
	**siege_chance = 40**

**Comment by Corail31** [comment]
I have patience Goshen but not so much... you have a version updated for you... so why you open an issue and without the required information (so the version....)
