### ISSUE TITLE
Knowledge of Death perks lost on Death.

### ISSUE THREAD

**Issue by Elesvan20** [Corail31/tombstone_lite#72]
### Minecraft Version

1.16.5

### Forge Version

36.2.35

### Corail Tombstone Version

tombstone-6.7.8-1.16.5

### What happened?

I created a modpack, to play in a private server with friends, but looking in detail, when a player dies, the Knowledge of Death experience (upper bar on Knowledge of Death UI) goes back to zero (0) and also, all the perks are set to 0.

A few of the mods causing this behaviour are:

Chisel-MC1.16.5-2.0.1-alpha.4
CTM-MC1.16.1-1.1.2.6

CreativeCore_v2.2.1_mc1.16.5
PlayerRevive_v2.0.0-pre04_mc1.16.5

iceandfire-2.1.9-1.16.5
citadel-1.8.1-1.16.5

And a actually more, but maybe these will work to debbug and see what could be wrong.

By itself, Corail Tombstone works fine, but I have found that issue when mixed with these other mods mentioned above.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (this test is required)

No

### Other relevant mods

CreativeCore_v2.2.1_mc1.16.5 PlayerRevive_v2.0.0-pre04_mc1.16.5  iceandfire-2.1.9-1.16.5 citadel-1.8.1-1.16.5

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Please, edit your issue to locate your problem or it will be closed (one of your mod is problematic, not 5).

**Comment by Elesvan20** [comment]
So, here is the scenario. We gathered a modpack, and tried to debug/locate which mod could be the one that is breaking the Knowledge of Death experience and Perks. 
But, seems like, it is some kind of combination that causes the issue and without debbuging tools, we cannot determine the location of the issue.
If possible, please download the **[ModPack](https://drive.google.com/file/d/1Clczof5yBGl8zQzDQ11TqGHcykC64EXj/view?usp=sharing)** on a launcher using forge and you should be able to jump into a SinglePlayer world and test it (I was using the _/tbknowledge player give exp_ command and then _/kill_ several times).

Let me know if I can help with anything else.
Regards.

**Comment by Corail31** [comment]
So, let me inform you that i'm not here to debug modpacks. You check singleplayer, with player revive(?), you add some additional mods above like Chisels & CTM, and ice&fire seems strange in workspace (some versions have duplicate methods...)
Edit: my best guess is it will be related to the clone event but it's not something to look in my mod. You don't need to look into code, but to reduce your mod list to locate your 'culprit' mod, and it's not something that i'll do for you.
Also, don't use Mohist or Magma when testing: they bring their own problems by not sticking to forge code.

**Comment by Elesvan20** [comment]
Like I said, the modpack is currently used on a server which allowed us to test Player Revive (and confirmed it is not an issue). I am aware you are not here to debug modpacks, but please dont ask me to do so since I am not the one with the tools or source code to do it. I have done as much as possible to track this issue swaping mods and checking the behaviour but the issue is still there.

I did not ask you to debug the whole modpack, the modpack is just evidence for you to see that, there is an issue with the Knowledge of Death and their Perks when combined with other mods (which I am sure people would like to do so). Please do not close this ticket as I think its very beneficial for the mod to have this scenario clear and "fixed" if possible (at least determine what is causing it and have some documentation for the people out there using it).
