### ISSUE TITLE
Tombstone loses soulbound equipment

### ISSUE THREAD

**Issue by kreezxil** [Corail31/tombstone_lite#72]
When the tombstone is configured to lose stuff when a player dies, if the player has a soulbound item it can and will lose the soulbound item.

The tombstone needs to not allow soulbound items to disappear.

MC: 1.12.2
FORGE: 14.23.5.2838
MOD VERSION: 3.5.5-1.12

**Comment by Corail31** [comment]
Are you sure of what you say ? because i would like a concrete example... only item non stackable can be lost...

**Comment by kreezxil** [comment]
exactly, soul bound armor and weapons, those aren't stackable and I had two
players back to back who had them lost. They didn't use your soul bound
enchantment either, could that be an issue?

**Comment by Corail31** [comment]
An issue with no relation with Tombstone : if a mod is doing something wrong in the clone event (often when they want to copy their capability a little fast...)
But probably, it can't happen if you used the tombstone soulbound.
Anything related to soulbound of another mod is always something related to this mod, as theses items are no more in the drops handled by the grave.

**Comment by kreezxil** [comment]
you're telling me that If I configured the tombstone to forget stuff on the
player, that your tombstone will not forget soul bound items from any other
mod?

attached is my config for reference

**Comment by Corail31** [comment]
I said you it's not a bug in tombstone but in the mod that provides the soulbound (but more related the X mod doing something in the clone event)
