### ISSUE TITLE
Fishing not getting a tablet

### ISSUE THREAD

**Issue by poboy975** [Corail31/tombstone_lite#73]
So like the title says, I've been fishing for about 2 hours now. I've even change the drop chance to 100 in the config, and I've still not gotten a tablet. Is this a bug or do I have the config incorrect? Or is there another setting somewhere.

**Comment by Corail31** [comment]
In 1.14.3, they can't drop actually from the fishing, more related to Forge where the modded loot tables don't appear in the the forge event, but i have an alternative for it that i should add in Tombstone (i added something similar in Flying Things one day ago)

**Comment by poboy975** [comment]
Ah, gotcha. So there isn't any way to get a tablet currently, other than creative mode?

**Comment by Corail31** [comment]
I don't think so, except if you have a way to add this item "tombstone:lost_tablet" in a loot table.
But i'll make an update soon for it ;)
