### ISSUE TITLE
Combine in inventory 1.18.2

### ISSUE THREAD

**Issue by Tekyo23** [Corail31/tombstone_lite#73]
### Minecraft Version

1.18.2

### Forge Version

1.18.2-forge-40.1.54

### Corail Tombstone Version

7.4.9

### What happened?

Well. I've been trying to make some scrolls but I can't find the way to make them. In CourseForge and YouTube appears that you can do a "Scroll of knowledge" using a "Strange scroll" and a "Glowstone Dust" in a Crafting Table, but if I try to do it I can't. 
I checked the recipe with JEI and it says "Combine in Inventory" but I can't find how to do it. I've tried to use a grave with a soul, I've tried an anvil, I've tried the crafting menu of the inventory, I've checked the "/tbgui" command, but I can't find anything. I don't know if it's something that I haven't seen or what. 
I'm sorry for bothering with such a simple thing.
Have a nice day,
Tekyo

PD: I clicked "yes" on the "Tested without any Forge "alternatives"" but I haven't (just that I couldn't send the report without checking it)

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (this test is required)

No

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
https://github.com/Corail31/tombstone_lite/issues/76
