### ISSUE TITLE
Incompatible with Apotheosis

### ISSUE THREAD

**Issue by Xetaxheb** [Corail31/tombstone_lite#74]
Why tho?

Encountered an unexpected exception java.lang.RuntimeException: Corail Tombstone Exception : this version of Apotheosis is incompatible (death chest) at ovh.corail.tombstone.ModTombstone.onServerStarting(ModTombstone.java:104) at net.minecraftforge.eventbus.ASMEventHandler_56_ModTombstone_onServerStarting_FMLServerStartingEvent.invoke(.dynamic) at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:76) at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:585) at java.lang.Thread.run(Thread.java:745)

**Comment by Xetaxheb** [comment]
Apotheosis has a config to turn it off, but you throw this error anyway.

Nothing really stops you overriding its event even if it's on.

**Comment by Xetaxheb** [comment]
Additionally, regardless of whether you have some beef with shadows of fire, this kind of "another mod exists so i'm going to refuse to run at all" is completely unacceptable.

**Comment by Corail31** [comment]
You're probably wrong there's no apotheosis on 1.14.3 except a mod of 25 ko looking to it.
You can check the Apotheosis closed issues to have a better explanation about this.
