### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by NillerMedDild** [Corail31/tombstone_lite#75]
`tombstone-3.7.2-1.14.4` crashes servers on startup with the below crash report:
https://gist.github.com/NillerMedDild/246625f10ebb3c61ff6930cb33ae55df

Using `Forge-1.14.4-28.0.21`

Let me know if you need additional info :)

**Comment by Corail31** [comment]
this is not the real error... this only means that the holder of my custom registry can't be applied because you crash before...

**Comment by ProsperCraft** [comment]
Don't run modded minecraft with 1 gig of ram.

JVM Flags: 2 total; -Xmx1G -Xms1G

Try 5 minimum, better 6.

This is a dedicated server? remove clientside mods I have not got them all to get their sidedness set up yet.

BetterAdvancements-1.14.4-0.1.0.87.jar Better Advancements {betteradvancements@0.1.0.87 CONSTRUCT}
EnchantmentDescriptions-1.14.4-1.3.3.jar EnchantmentDescriptions {enchdesc@1.3.3 CONSTRUCT}
EquipmentTooltips-1.14.4-1.3.1+9.jar Equipment Tooltips {equipmenttooltips@1.3.1+9 CONSTRUCT}
overloadedarmorbar-3.0.0.jar Example Mod {overloadedarmorbar@3.0.0 CONSTRUCT}
ToastControl-1.14.4-2.1.1.jar Toast Control {toastcontrol@2.1.1 CONSTRUCT}

to start with..

I have not tested FPS reducer not sure if it runs clean on a dedicated server.

If you remove tombstone you will see the real errors which will say something about not being able to run on a dedicated server.

**Comment by NillerMedDild** [comment]
My bad, thanks guys :)
