### ISSUE TITLE
The grave doesn't appear in multiplayer

### ISSUE THREAD

**Issue by Ciswi** [Corail31/tombstone_lite#75]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Corail Tombstone Version

7.4.10

### What happened?

We are trying to play minecraft with this mod and when we die our appearence changes to the ghost with invunerabily boost, but where is supposed to be our grave there is nothing either the key in our inventory, just our stuff like when you die normaly.
The corail tombstone menu works perfectly, and there is no log error in console when someone dies.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (this test is required)

No

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Thanks for wasting my time with incorrect info.
