### ISSUE TITLE
Suggestion: An Undead Boss mob fitting this mods theme

### ISSUE THREAD

**Issue by SirAron111** [Corail31/tombstone_lite#76]
I like this Mod it handles the player death nicely and it also even revives Tamed Pets.

On top of that you add a skill system and some many ways to stay alive (some even save you from kill commands lol) and spell scrolls and whatnot all this integrates nicely into modded minecraft.

All you are missing is something to use all the Surviving and reviving for in your own Mod so I thought you should add a boss mob.

You could make some kind of Ritual where you need to have a special altar surrounded by a number of Graves (decorative graves) that have souls floating on them. And offer something to it.

And the Summoned Boss could be themed around a lich or grim reaper that is mad that you always revive XD or something like that… In the first phase he won’t fight on his own and instead summon some normal undead mobs to fight for him like zombies or skeletons. Next stage he could summon giant Zombies or something funny. And if you survive his waves without leaving the area you can fight him. He could use some normal attacks but be floating around or something more fancy (lich style boss could use fireballs or something like that) (grim reaper could teleport behind you and slash with sickle or dash at you).

I think something like this would fit nicely into the Mod as a kind of end goal after you made lots of death prevention stuff and got some buffs and so on. The boss could Drop some fancy death/revival themed Stuff.

Sry I have no better description about it. 

If you are against adding mobs in general or just don’t like the Boss idea I can understand it as well. The Mod works great as it is. I just thought this would fit in as a some kind of end goal.

**Comment by Corail31** [comment]
Hi SirAron, this is not my priority right now to add any entity (and in any case, they would be added in an extension and not in the mod), the next steps will be more focus on the grave models.
But i tag it to extension, as this extension should happen one day ;)
