### ISSUE TITLE
Tablets are not enchanted with souls 

### ISSUE THREAD

**Issue by GnomTocha** [Corail31/tombstone_lite#76]
### Minecraft Version

1.18.2

### Forge Version

40.1.54

### Corail Tombstone Version

tombstone-7.4.10-1.18.2

### What happened?

Maybe I don’t understand something, the craft of enchanted tablets does not work.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (this test is required)

Yes

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
I don't check videos but you just need to put the ingredient on the strange tablet with the right click in the inventory (corresponding to how fill a bundle).
The strange tablet tooltip (by hovering the item) contains informations. The compendium in 1.19 and JEI provides more infos.
This change is since 1.17.1

**Comment by GnomTocha** [comment]
OK.  Thanks.  I just don’t speak English freely, so combining items in the inventory can be understood what needs to be combined in the crafting slot, or as it was before with the left and right hand on the grave.  unusual mechanics.  sorry for the ping.

**Comment by Corail31** [comment]
Sometimes, it's better to use unusual mechanics than continuying to be with mods using the crafting table as a furnace (and preventing the player context).

**Comment by GnomTocha** [comment]
I agree with this.  this is already 2 similar mod that I saw.

**Comment by Corail31** [comment]
@GnomTocha I'm still looking for a solution to be easier to understand: there's a Toast that provides informations when combining incorrectly (ex when you try to put an ender pearl on an already enchanted key) and initially, i wanted to test the commit of Dieseben about the custom tooltips with pictures ;)
