### ISSUE TITLE
symbols in the commands

### ISSUE THREAD

**Issue by JeeGGy** [Corail31/tombstone_lite#77]
### Minecraft Version

1.18.2

### Forge Version

1.18.2

### Corail Tombstone Version

1.18.2

### What happened?

hello ive been trying to use this mod in minecraft forge 1.18.2 and when i enter minecraft it says this
 and idk how to fix it also when i download a mod it dosent appear wioth the java symbol even tho i have the latest ver of java and. pls help me fix this i really want ot play with this mod
as you can see right there its just symbol i also noticed that the version says 1.16.5 but when i downloaded from the mods website it said 1.18.2.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (this test is required)

No

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Please, you're running the 1.16.5 version (6.7.9). Is there a need to answer you ?
