### ISSUE TITLE
[1.14.4] Player kicked when using ankh on a tombstone

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/tombstone_lite#77]
https://gist.github.com/ProsperCraft/7ded4545f9b13076479000548f10259c

tombstone-3.7.2-1.14.4

**Comment by Corail31** [comment]
i just tested on server and singleplayer, in vanilla launcher & in workspace with all my mods, and it never failed. (forge 29 as you)

**Comment by Corail31** [comment]
I finally succeed to reproduce it : it requires the effect bad omen on you when you pray, and it makes you disconnect ;)
