### ISSUE TITLE
PVP No grave appeared as there were no items to store

### ISSUE THREAD

**Issue by AlbertoGarciaMiguelez** [Corail31/tombstone_lite#78]
### Minecraft Version

1.16.5

### Forge Version

1.16.5

### Corail Tombstone Version

6.7.9

### What happened?

When a player kills another the tomb does not appear in these cases:
if the player has armor.
if the player has any item in the inventory bar.
Grave appears when killed and has no armor or any item in the inventory bar.
If you have items in your inventory it does appear but if some previous condition is given.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (this test is required)

No

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] No

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It seems you didn't precise any other mod to make this happening ? no error logs ?
Your "forge version" is incorrect. ~~You don't mention any message provided by tombstone (there's always a message, or a log if canceled => but this would mean that you have multiple mods in this case...)~~
Also, you didn't agree to not using Magma or Mohist... didn't you read to report bugs to them ?
Please edit your issue, or it will be closed. To have a player grave, you just need "loots" (osef if they wear armors or not, i was not able to make this happening, so feel free to explain the steps).
Edit: Oh, i just realized that your title is the message that you receive: there's no drop.
