### ISSUE TITLE
1.14.4 Server crash

### ISSUE THREAD

**Issue by KitaenSilva** [Corail31/tombstone_lite#78]
Game runs fine for a while, then abruptly crashes - client is unaffected, just loses connection.

Near as I can tell, there's something going on with Corail Tombstone when the game tries to begin a village raid event.

I have not had a moment to thoroughly confirm whether this is explicitly a Corail Tombstone issue, as I am reporting this immediately following the crash, but the crash report seems pretty vehement in pointing this way and I feel like i'm not _too_ terrible at parsing reports.

https://pastebin.com/X32aYb36

**Comment by Corail31** [comment]
Hi KitaenSilva, this custom villageSiege can be disabled in config option (as i'm on some changes, the fix will be a little delayed)
NB : for details, it's the constructor of the super of the event being private.
