### ISSUE TITLE
[Feedback] 12 minutes of Fear III upon praying isn't really ok. 

### ISSUE THREAD

**Issue by VeloxAzo** [Corail31/tombstone_lite#79]
As per usual, I used my ankh upon logging in for those sweet points. But instead of getting a buff like I normally do, I was inflicted with a debuff that prevents me from moving on my own?

https://i.imgur.com/LR7PKWc.png
https://i.imgur.com/stf8gre.png

This effect will occasionally send me walking in random directions but I otherwise cannot move at all. Thus I can not even walk to my storage area to grab some cleanse.

**Comment by VeloxAzo** [comment]
On further investigation, fear may be an effect from the mod Lycanites.

**Comment by Corail31** [comment]
So, this pray only provides benefict effect, and it's the mod to set correctly if they're neutral, benefict, or bad...

**Comment by Corail31** [comment]
@VeloxAzo : the 3.7.5 version ensures to not use the neutral effects if it was related to 1.14.4 ;)

**Comment by VeloxAzo** [comment]
Thank you. It was indeed 1.14.4
