### ISSUE TITLE
Crash when you die (no tomb, no key)

### ISSUE THREAD

**Issue by agustinscaz** [Corail31/tombstone_lite#79]
### Minecraft Version

1.19.1

### Forge Version

41.1.0

### Corail Tombstone Version

8.0.4

### What happened?

Once a player dies, server throws an internal error and kick off the player from the game.

Maybe it's not Corails Tombstone error, but any help would be appreciated, here you got the logs:

Thanks in advance!

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (this test is required)

No

### Log Link

https://pastebin.com/wvYXaUSM

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hello, 8.0.4 is for 1.19 and is not supported, you have to update to 1.19.1.
Just try to locate which mod is doing a strange thing to persistent datas because it would lead to others issues.
Is there a reason for players to stay on 1.19 when 1.19.1 is released ?
