### ISSUE TITLE
Crash when using 1.16-6.2.4

### ISSUE THREAD

**Issue by Morningate** [Corail31/tombstone_lite#8]
Game crashes when opening inventories for chests and useful backpacks. Crash reports attached.
[crash-2021-01-15_18.54.10-client.txt](https://github.com/Corail31/tombstone_lite/files/5823727/crash-2021-01-15_18.54.10-client.txt)
[crash-2021-01-15_18.58.05-client.txt](https://github.com/Corail31/tombstone_lite/files/5823726/crash-2021-01-15_18.58.05-client.txt)

**Comment by Corail31** [comment]
Hi Morningate, and thanks for your report : your version is 6.2.4 (so i changed your title), and it seems to be a wrong import capitalise/capitalize. A new release is coming.
