### ISSUE TITLE
Server crash on latest version

### ISSUE THREAD

**Issue by Gbergz** [Corail31/tombstone_lite#8]
Hello, i'm trying to launch my server but it crashes on startup.

Crashlog here:
[Pastebin](https://pastebin.com/jwih4kfG)

**Comment by Corail31** [comment]
Hi Gbergz,
Don't use grave mod from EuhDawnson, or make a choice between it and tombstone.
As his code is not visible, i can't bring more support to it. (i mainly keep compatibility with nightkosh grave and disable euhdawnson)
