### ISSUE TITLE
I dont get a grave and a key on my minecraft sv 1.18.2

### ISSUE THREAD

**Issue by EZLuis** [Corail31/tombstone_lite#80]
### Minecraft Version

1.18.2

### Forge Version

40.1.69

### Corail Tombstone Version

7.4.11

### What happened?

I have and issue, when i die on my server i dont get the grave and key, i do get it on a normal world but when i try it to apply it on servers always have this error, and its the only problem i got, all the rest of the mod works correctly on the server.

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (this test is required)

Yes

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@EZLuis hi, provides the debug log (or the issue will be closed as i tested Player Revive and Tombstone on 1.18.2 server recently).

**Comment by YeraX7** [comment]
Minecraft Version
1.18.2

Corail Tombstone Version
7.4.11

What happened?
I have and issue, when i die on my server i dont get the grave and key, i do get it on a normal world but when i try it to apply it on servers always have this error, and its the only problem i got, all the rest of the mod works correctly on the server.

Gametype
online host

Happen by testing with only Corail Tombstone (this test is required)
Yes

Log Link
No response

Other relevant mods
No 

Tested without any Forge "alternatives" (Magma, Mohist, and so on)
 Magma Server

Valid Launcher
 Yes

**Comment by YeraX7** [comment]
Minecraft Version
1.18.2

Corail Tombstone Version
7.4.11

What happened?
I have and issue, when i die on my server i dont get the grave and key, i do get it on a normal world but when i try it to apply it on servers always have this error, and its the only problem i got, all the rest of the mod works correctly on the server.

Gametype
online host

Happen by testing with only Corail Tombstone (this test is required)
Yes

Log Link
No response

Other relevant mods
No 

Tested without any Forge "alternatives" (Magma, Mohist, and so on)
 Magma Server

Valid Launcher
 Yes

This line appears on the console:
[main/WARN] [mixin/]: Error loading class: de/maxhenkel/corpse/events/DeathEvents (java.lang.ClassNotFoundException: de.maxhenkel.corpse.events.DeathEvents)

**Comment by Corail31** [comment]
I can understand that you want to use a "Magma" Server. But theses issues ask to report bugs happening only with Magma to their issues: [Magma Issue](https://git.magmafoundation.org/magmafoundation/Magma/-/issues)
Corail Tombstone is a "Forge mod" meaning that "hybrid server" still have to be compatible with Forge first of all...
There're lots of chance that they use keep inventory by world.
NB: also, no need to create new github account to post issues (like if you never reported a bug), you just force me to apply the moderation for new accounts that doesn't help others players wanting to post real issues.
