### ISSUE TITLE
Draconic Evolution Chaos Island Explosion Destroys Graves

### ISSUE THREAD

**Issue by nightstick24** [Corail31/tombstone_lite#80]
Hey there, I'm playing Project Ozone 3 and was flying around breaking Chance Cubes, one happened to spawn a Chaos Island Explosion from Draconic Evolution and I died. I went back but there was just a crater with no grave.

I had the key and it was highlighting an air block like there was a grave there, but there was no grave, using the restoreinventory, showlastgrave, or teleportgrave all failed with a "The grave has not been found" error.

**Comment by Corail31** [comment]
draconic evolution chooses to destroy blocks without respect for others mods so i can't do anything to this...

**Comment by Corail31** [comment]
https://github.com/brandon3055/Draconic-Evolution/issues/1335

**Comment by Corail31** [comment]
Thanks for your issue but this is really to the other mod to fix its code. (and there's no alternative against a block deleted)
I close this issue and the tag "invalid" is only to say it's not in my mod.

**Comment by Corail31** [comment]
As clarification of this bug, and after a discussion with Brandon, players have all the time to recover their graves and leave this place before the Chaos Vortex, so if graves are broken it's more an expected behavior of this carelessness.
