### ISSUE TITLE
[1.14.4] Crash when creating new worlds

### ISSUE THREAD

**Issue by darkphan** [Corail31/tombstone_lite#81]
Tombstone Version: tombstone-3.7.5-1.14.4
Forge: 28.0.45
Minecraft: 1.14.4

When creating a new world the crashes. The following is output to the log: https://pste.me/#/Lc4Q7
And the crash log is as follows: https://pste.me/#/mAZbh

I am currently using the following mods: https://pste.me/#/MT2jp

**Comment by Corail31** [comment]
Hi Darkphan, forge 45 makes lots of mods bugued but loading and crashing others (with unrelevant messages), you can find an explanation here :
https://github.com/Corail31/corail-pillar/issues/24
NB : you can test that tombstone works properly if not all your mods are present.

**Comment by darkphan** [comment]
Thanks. It seems that it is the update to Apotheosis and/or Placebo that is causing this.

**Comment by Corail31** [comment]
I prefer to target no one because this forge version is quiet ennoying for everyone.
But the error message above would say that the packet handler hasn't been initiated before the playerlogin packet... ^^ so not relevant as this packethandler is init before world load.

**Comment by Corail31** [comment]
To my opinion, it's actually a forge bug, as it decides to load the game even if some events are skipped.

**Comment by Corail31** [comment]
The version 4.0.0 should solve your trouble (SimpleChannel init in static) but this is just a protection against the mods not updated to forge 45, hoping this forge version to be forgotten into limbo soon ^^

**Comment by Corail31** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/6148
