### ISSUE TITLE
Cannot combine items in the inventory

### ISSUE THREAD

**Issue by Elesvan20** [Corail31/tombstone_lite#81]
### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Corail Tombstone Version

7.4.9

### What happened?

When putting the items on the inventory to craft, recipe do not work. I have tried crafting table and others, but they should be combined on the inventory crafting. No other mods included besides Optifine.
Notes:

- Tested without Optifine
- Tested in both SinglePlayer and dedicated server
- Tested in both No Premium Launcher, aswell as in the Premium Launcher.

![2022-08-15_01 41 18](https://user-images.githubusercontent.com/44454933/184595786-4c2dfd52-8db2-47cb-b1bb-eff82af4cd0f.png)
![2022-08-15_01 41 26](https://user-images.githubusercontent.com/44454933/184595789-e2b7bf44-1c3c-462f-9ba0-79d455858edb.png)
![2022-08-15_01 41 27](https://user-images.githubusercontent.com/44454933/184595796-a1667b08-8d4e-4e72-9105-acf8e4bafa10.png)
![2022-08-15_01 41 36](https://user-images.githubusercontent.com/44454933/184595806-451f9dab-2f69-42e7-956f-aee2c737ed39.png)
![2022-08-15_01 41 44](https://user-images.githubusercontent.com/44454933/184595811-1f7fdbe1-6f7b-48b9-a5d8-58f54072b4e6.png)

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Other relevant mods

Perhaps Optifine included in the TLauncher option.

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
https://github.com/Corail31/tombstone_lite/issues/76
