### ISSUE TITLE
Player death not picked up to create grave

### ISSUE THREAD

**Issue by Streamcyper** [Corail31/tombstone_lite#82]
Hi, so I'm assuming this will be a rare edge case as I have not seen anything like it on the server before. 

Playing on SevTech Ages 3.1.1
With Corail Tombstone  - tombstone-3.3.2-1.12.2

I fell into lave and ended up dying, then going back fell down and died again.
Death 1 at x167, z-28, y10 
Death 2 at x169, z-25, y10

However the grave for the second death was never created, using any of the commands gave no result and looking at the logs I only see this
```
[20:13:53] [Server thread/INFO]: StreamCyper tried to swim in lava
[20:13:53] [Server thread/INFO]: The last known grave of StreamCyper is at location [x:166, y:20, z:-31]: in the dimension 0
[20:14:05] [Server thread/INFO]: StreamCyper joining dimension 0
[20:16:37] [Server thread/WARN]: Keeping entity minecraft:pig that already exists with UUID 15fe46d3-09e0-4ea5-8860-25cfd9430c73
[20:17:56] [Server thread/INFO]: StreamCyper tried to swim in lava
[20:18:11] [Server thread/INFO]: StreamCyper joining dimension 0
[20:19:18] [Aromabackup-Backup/INFO]: [AromaBackup]: Starting Backup. The server may lag for a bit!
```

Might also add that I my armor disappeared but that might be connected to me wearing an other set of armor when I picked up the grave.

**Comment by Corail31** [comment]
It's normal it fills the same grave if one is around.

**Comment by Streamcyper** [comment]
Ah that makes sense, just can't seem to remember that being the case before, or not met the conditions.... Tho strange that the logs said nothing and that I lost two full sets of armor, but that might be because of something else even tho I don't know what that would be.

**Comment by Corail31** [comment]
if you lost armors it's not a normal

**Comment by Streamcyper** [comment]
I opened the grave with the key, and due to overfilled inventory a bunch of stuff ended up on the ground. I was wearing an other set of armor at the time so the armor couldn't automatically fill my armor slot. When I then finished opening my backpack to put stuff away I was missing both the two sets of armor as well as a charm of gluttony. Might be other things as well but I did not notice them.

I do not believe it to be items glitching thought the floor or something like that as the armors were Tinker Armors, the don't de-spawn or get broken and I was wearing something that was magnetic so everything stuck to me and I could not find them even after looking around.

Log for the session it occurred 
[2019-09-01-3.log](https://github.com/Corail31/tombstone_lite/files/3564065/2019-09-01-3.log)
[debug.log](https://github.com/Corail31/tombstone_lite/files/3564066/debug.log)

**Comment by Corail31** [comment]
Btw, you have a rollback of player with the command /TBRecovery that is intended for this kind of trouble. (but needs an /op for it on server)
NB : you precise that you had a magnetic items, i hope it doesn't work while you're dead ;)

**Comment by Streamcyper** [comment]
I tried using the /TBRestoreInventory but that did not help. And reason I precise that it was magnetic is that should dispel most concerns about the item falling to the ground and not being able to see/find it. And it has never been a problem before, so not quite sure what happened.

**Comment by Corail31** [comment]
/TBRecovery is not the same, it's a rollback of player.

**Comment by Streamcyper** [comment]
If I were to do that several hours after the death would that cause problems?

**Comment by Corail31** [comment]
no if the config option is enabled for backup, the command will work (tbRestoreInventory is more only an activation of grave at distance, and only consider if you have a grave's key or if the server hasn't been restarted it can remember the grave too without key)

**Comment by Streamcyper** [comment]
Ah thank you very much for the help, sadly it looks like I'm unable to restore the armor I lost due to it being to long ago, but I will be sure to keep the feature in mind if/when run into issues at a later time. Thank you very much for the help!

**Comment by Corail31** [comment]
Now about your logs, you got a crash than you didn't mention?

**Comment by Streamcyper** [comment]
Ah yes, that's due to a Blue Screen on the machine that was running it, it us unrelated to minecraft as it happens even when it's not running anything. Just haven't had time to do a clean re-install of windows.

**Comment by Corail31** [comment]
The logs show a fatal error with ThirstyBottles and item used, but i don't like to target mods, and as you say your install was not cleaned, so i can't help you more on this uncommon circonstance of this :)

**Comment by Streamcyper** [comment]
It's already plenty, the main issue was that it seemed as if the second grave was never created. That however has been cleared up, and the losing of the armor seems more like it's a series of things happening that caused it. If anything like it happens again on a clean version I will open a new issue regarding that.
