### ISSUE TITLE
Keep dying after respawn (PlayerRevive)

### ISSUE THREAD

**Issue by FabsAcr** [Corail31/tombstone_lite#82]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Corail Tombstone Version

6.7.8

### What happened?

When i die on multiplayer server and click respawn my player keeps dying.
it shows me a message in the server console that says ""The death event of the player  (....) was canceled by another mod"
The thing is that i have installed corail tobstone mod 6.7.8 and Player revive 2.0.0

Here´s the picture attached:

![3](https://user-images.githubusercontent.com/111235854/184781379-e96fb2ae-0974-48eb-8095-21aef57aa74c.PNG)

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Player revive 2.0.0

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Hi, the message about the death event being canceled is a normal log. It means that a mod chose to handle the player death.
Corail Tombstone & Player Revive are working on server (tested recently on 1.16.5 & 1.18.2)
Player Revive has incompatibilities with Vampirism (except 1.19), Mohist & Magma.
It's not something that can be solved on my side.
