### ISSUE TITLE
PVP unlocks graves

### ISSUE THREAD

**Issue by d-rick** [Corail31/tombstone_lite#83]
### Minecraft Version

1.18.2

### Forge Version

40.1.74

### Corail Tombstone Version

7.4.11

### What happened?

Hola, dos jugadores en mi servidor lucharon y al uno matar al otro en la tumba pudo ser quitada por otro jugador que no era dueño de la tumba sin llave ni nada.

[2022-09-01-1.log](https://github.com/Corail31/tombstone_lite/files/9480103/2022-09-01-1.log)

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
From the template to fill an issue : "The language used to fill the information is english, but can be in french as long as you're really french native (no google translation)."
Any way, your problem is related to the config "pvp_unlock_grave" set to true by default.
