### ISSUE TITLE
Issue: My knowledge of death is getting reset 

### ISSUE THREAD

**Issue by Elsker99** [Corail31/tombstone_lite#83]
I've done quite a few advancements with Tombstone and i've even used the points to get things (like more disenchantment from a gravestone) but after some time playing and I get another perk lets say, I go to use the point and my previously bought point is gone and I'm back to level 1. 

Not sure why this is happening and i don't really know what to do.

**Comment by Corail31** [comment]
Hi Elsker, the only way to lose your knowledge of death is you use a mod that breaks the capabilities on death or on teleportation.
Tombstone provides a command to set directly your knowledge points to what you want (/tbknowledge add|set|remove).
But you should localize what is making the knowledge to be reset as you'll get others surprises in others mods if it's.

**Comment by Corail31** [comment]
I think i know what is your real trouble :)
Tombstone uses a custom damage called "BeyondTheGrave", that is used actually by lost tablets & familiar receptacles. By moment, theses items drain your life to regen themself.
If you die from this special damage, you lose 10 knowledge points as it's explained in the Compendium section of the gui in game.
There's also a config option (disabled by default) allowing to set the lost of knowledge when you die from any damage (so perhaps the server uses this config option)
I'm adding a config option to allow players to disable this kind of damages if they don't want in my next release ;)
NB : confirm me it's what you got.

**Comment by Corail31** [comment]
Finally, i succeed to reproduce it, when crossing the End Portal to come back to Overworld after the kill of the End Dragon.
Not sure, if it's a forge fault (as it's a least the third time they fix the clone/death events since 1.13, so i suppose it's now how they expect us to use it...^^), the cap is not present in the clone => revive()
