### ISSUE TITLE
Client crash in 1.14.4 (forge 93 requires tombstone 4.1.1)

### ISSUE THREAD

**Issue by Wissi** [Corail31/tombstone_lite#84]
Awesome work, great mod.

We are having a bit of an issue with clients crashing in SP (no server involved).
World creates, loads fine. But after you start to move around it just crashes.
Full crash log [here](https://gist.github.com/Wissi/6def3953a2c697d1de28eeabcad7f863).
Using:
forge-28.0.93
tombstone-4.1.0-1.14.4.jar

Just reporting, hope it's something new in Forge.
Thanks.

**Comment by Corail31** [comment]
Hi Wissi, i already published today the version for forge 93.
As i had already saw the change done by LexManos ;)

**Comment by Wissi** [comment]
As always ahead of the issues.

Even before we ask, there's a fix  XD.

Thanks.
