### ISSUE TITLE
Crash on main menu with latest update

### ISSUE THREAD

**Issue by Flame1211** [Corail31/tombstone_lite#84]
### Minecraft Version

1.19.2

### Forge Version

43.1.3

### Corail Tombstone Version

8.1.3

### What happened?

get to the main menu and met by a crashlog from not enough crashes

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

werewolves shows up in the log, but was working fine before this update

### Log Link

https://pastebin.com/NtaG7Rx5

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
It's an error from Werewolf (Vampirism modder) but related to forge (and a mod didn't work properly), try to locate the problem and provides the **debug log**.
The problem is probably that the **latest version of Corail Tombstone requires Forge 43.1.8**.

**Comment by Corail31** [comment]
https://github.com/TeamLapen/Werewolves/issues/96
https://github.com/TeamLapen/Werewolves/issues/93
https://github.com/MinecraftForge/MinecraftForge/issues/8342
