### ISSUE TITLE
Bug with Astral Sorcery Resplendent Prism (infinite enchantment level)

### ISSUE THREAD

**Issue by Quipex** [Corail31/tombstone_lite#85]
Hello, 

I have both Corail Tombstone v3.5.6 and Astral Sorcery v1.10.20
There is an item in astral sorcery called [Resplendent Prism](https://minecraftguides.net/AS/constellation/resplendent%20prism). It can have +N to all existing enchantments.

While wearing it and stripping enchantments from items, an enchanting book has actual enchantment level+N from this prism. This way, you can infinitely increase the enchantment level. Works in both multiplayer and singleplayer. 

To recreate, take a prism from creative menu until you get the required enchantment (every time it gets random enchantments) [image of prism](https://imgur.com/a/DRyF5kn).

**Comment by Corail31** [comment]
Hi Quipax, thanks for your report, 
i never tried Astral Sorcery (even if i saw nice screen of their perk gui :) ), so it's the good occasion to make a test of this and make a compat if needed for this prism :)

**Comment by Corail31** [comment]
I'll wait to have an answer from the modder of Astral Sorcery before making a compat, as even if the code is visible, the mod doesn't use api so i can't really trust to use anything from theses classes (except injection of the cap & nbt stuff) and if i read well their code, there's a hardcoded blacklist.

**Comment by Quipex** [comment]
Sorry, I haven't yet contacted the author of AS regarding this. Do you mind doing that? Im afraid that im far from understanding minecraft modding (PRing to forge and stuff), therefore, I may incorrectly convey information to him :/

**Comment by Corail31** [comment]
Don't worry, i sent him a message some days ago, it's more to inform you why i didn't yet make the compat :)

**Comment by Corail31** [comment]
It should be handled by Astral Sorcery, as i need to keep the helper (as others mods use asm at this place).
If nothing changes in Astral Sorcery, open an issue in the mod, but not in tombstone.
