### ISSUE TITLE
Corail Tombstone 3.5.8 for 1.12.2  Downloading for 1.14.4 instead of 1.12.2

### ISSUE THREAD

**Issue by raziel23x** [Corail31/tombstone_lite#87]
for some reason this update is showing up in forge version 1.14.4 mods when you update and needs to be relabeled correctly unless its suppose to be for 1.14.4 but if the case it does not function at all

**Comment by Corail31** [comment]
thanks raziel, it was only the category from curseForge but it's really for 1.12.2
