### ISSUE TITLE
"First Death" achievement bug - Advancement Plaques Mod

### ISSUE THREAD

**Issue by Palito2222** [Corail31/tombstone_lite#87]
### Minecraft Version

1.18.2

### Forge Version

1.18.2-40.1.80

### Corail Tombstone Version

7.5.2

### What happened?

Every time I die I get the "First Death" achievement in a loop, is it possible to fix this?

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

Advancement Plaques Mod

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Palito2222 Hi, there's no advancement "First Death" in Corail Tombstone, there's one called "First Grave".
Can you confirm the name of the advancement ?

**Comment by Palito2222** [comment]
Yes yes, sorry, im from Spain and my mate spell bad the name HAHAH.

The correct name is "First Grave"

**Comment by Corail31** [comment]
@Palito2222 I was not able to make this happening. Tested with latest 1.18.2 forge version on server in workspace with only "advancement plaques" & "iceberg" mods. After the first /kill command with an item in inventory, the only advancements appearing after the "first grave" are related to "chain death".
