### ISSUE TITLE
recent tomb locked/recent key doesn't interact with tomb

### ISSUE THREAD

**Issue by MG4K** [Corail31/tombstone_lite#88]
![2022-09-30_04 49 59](https://user-images.githubusercontent.com/41134488/193254638-3b9dc3da-ab1f-415a-9f6d-35d1aa2dbb3b.png)
![2022-09-30_04 49 28](https://user-images.githubusercontent.com/41134488/193254640-fd7c3a88-9b08-4bfc-a33b-e6ee1ed20e44.png)
![2022-09-30_04 49 13](https://user-images.githubusercontent.com/41134488/193254642-33dac34d-a4aa-4253-99b1-0de9c303b4c5.png)
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Corail Tombstone Version

4.5.7

### What happened?

I don't know if it's a problem or not.
testing things in a flat world I have died in various ways (about 8 times) and it was not until the 9th time that I realized that my tombs said "locked", despite having the most recent key I could not open my own grave, I'm glad I didn't try it in my survival. [Minecraft version 1.12.2][Corail Tombstone 4.5.7]
[and no configuration has been modified]

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You checked you use a valid launcher, so that your uuid never changes (same if you're in a workspace). To be precise, you don't need a key to open a grave. If you change the decayTime to 0, the graves will be opened.

**Comment by MG4K** [comment]
> You checked you use a valid launcher, so that your uuid never changes (same if you're in a workspace). To be precise, you don't need a key to open a grave. If you change the decayTime to 0, the graves will be opened.

![2022-09-30_16 37 24](https://user-images.githubusercontent.com/41134488/193365689-dbf3937d-2a8b-4335-b1db-87b0a90b81f8.png)
![2022-09-30_16 35 31](https://user-images.githubusercontent.com/41134488/193365691-95464b46-5122-44a8-811e-2800b54d4c5e.png)
![2022-09-30_16 35 44](https://user-images.githubusercontent.com/41134488/193365692-2af32668-3c04-43a9-8509-ca1ed95edc71.png)

That didn't solve one of the problems!
I still can't get the tomb back but now it's unlocked and no I'm not using the key or holding SHIFT

**Comment by Corail31** [comment]
From your provided informations, it works by using Corail Tombstone alone, up to you to localize the mod making an incompatibility: it's what is asked in the issue template. Until that's done, there's nothing else i can tell you.
If it's a "chunk claim mod" or something like "GriefPrevention", sneaking over a grave allows to activate it.
NB: Normally, i will release a new version for 1.12.2 soon, so if you localize the problem, the compat may be added to that version.

**Comment by Corail31** [comment]
@MG4K May you confirm that it was a problem with a "chunk claim mod" ?
