### ISSUE TITLE
Water logged graves

### ISSUE THREAD

**Issue by RogueYin** [Corail31/tombstone_lite#88]
So I've had an issue with the graves, both the pre-generated (which is excessively spawned) and my own crafted ones where they're covered in water and its impossible to pick them back up, can't break them with any tool. I crafted one grave and it appeared when I placed it as a different one and immediately waterlogged itself, using most recent version. Any idea on a fix or whats causing it?

**Comment by RogueYin** [comment]
![2019-09-18_02 05 48](https://user-images.githubusercontent.com/50600508/65095692-263a2500-d9ba-11e9-836d-f3a4b7006f00.png)
![2019-09-17_03 38 39](https://user-images.githubusercontent.com/50600508/65095683-220e0780-d9ba-11e9-8e7b-bcdaf4d83040.png)

**Comment by Corail31** [comment]
Please, don't just bring me what you get but bring real infos, version and so on .... don't forget that forge has the habbit to not test their patches...

**Comment by Corail31** [comment]
@RogueYin don't open issues if you don't follow them...
