### ISSUE TITLE
Suggestion:  Ghost visitation frequency control?

### ISSUE THREAD

**Issue by fuzzyweapon** [Corail31/tombstone_lite#89]
The womanly ghost that visits our server seems to be stalking players to annoyance rather than delight.  I didn't see any mention of her in the config.  Is there any way we can get a setting to tweak the chance of her showing up?  I'd love to make it rare enough to really spook new players into thinking they saw something but aren't sure.

Thanks for this awesome mod btw!  All our players love it.

**Comment by Corail31** [comment]
It's already set to be rare (normally it wouldn't happen more than once almostly by night), it's slightly related to the Ankh, and affecting players not praying on graves during the [Festival of the Dead](https://en.wikipedia.org/wiki/Festival_of_the_Dead).
There're informations in the section "Compendium" of the tombstone gui about Halloween.
If you set a short cooldown on the Ankh, it makes the Ghost more present.
NB : there's a client config option to prevent the ghost to ennoy them.

**Comment by fuzzyweapon** [comment]
It's actually happening a lot, so maybe there's a bug?  I'm getting them every few minutes.

**Comment by fuzzyweapon** [comment]
Yeah I didn't see any config option, but I'll look again.  My vim options have super hard to read blue for the comments, so I might have missed it bc of that.

**Comment by fuzzyweapon** [comment]
Also I don't have Halloween events turned on persistently.  Should this be happening outside of halloween events being turned on persistently?

**Comment by fuzzyweapon** [comment]
This constant ghost appearance was happening on default ankh settings of every 3 hrs.

**Comment by Corail31** [comment]
So, when i say by night, it's in game, so every 10 minutes (this doesn't mean it's to be exactly this)
You don't need vim as Tombstone provides the client configs directly in game.
The persistant is only to set halloween outside the events.
You only need to pray with the Ankh (so by discovering the mod), or to disable it by disabling the halloween effects.
![image](https://user-images.githubusercontent.com/17954109/65573440-2cf10b00-df6b-11e9-9716-2c5a311d2f91.png)

**Comment by fuzzyweapon** [comment]
Thank you so much for the detail!  I'm going to go ahead and close this, but do some follow up investigation (as I could have sworn our config said that we had persistent halloween turned off).  If behavior isn't what you've described, I'll enter in a new ticket for a bug. :)

**Comment by Corail31** [comment]
Persistent halloween is only to activate the halloween event when it's not the period of halloween.
The ghost is more part of the tutorial as it only remembers you that you "can" pray, for the ones that didn't discover the mod during the year...^^
