### ISSUE TITLE
XP loss on death not working as expected

### ISSUE THREAD

**Issue by mipod** [Corail31/tombstone_lite#9]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2855

### Corail Tombstone Version

4.4.6

### What happened?

The setting for xp loss on death is not working as expected. 

General behavior, loss of all xp.

Options I have tried:

1.  Set it to -1 => loss of all xp
2.  Set it to 0 => no loss of xp
3.  Set it to any % ( tried 15, 25, 40) => loss of all xp

### Gametype

Dedicated Server

### Tested with only Corail Tombstone

- [ ] Yes

### Relevant mods

enderIO, astralsorcery, applied energetics, tinker construct

**Comment by Corail31** [comment]
Edit: i did the test and the xp is not working as expected, thanks for bringing this issue but next time, please consider to 'test with only the mod' and check the checkbox.
It affects 4.4.6 for 1.12.2, 6.5.0 for 1.16.5 & all 1.17.1 versions. (due to a floor())

**Comment by Corail31** [comment]
@mipod you can test 4.4.7 ;)

**Comment by mipod** [comment]
I can confirm as well that it's fixed with 4.4.7!
Thank you for the support and fast fix, you guys are amazing!
