### ISSUE TITLE
Config to disable blocks

### ISSUE THREAD

**Issue by justinrusso** [Corail31/tombstone_lite#9]
Hello Corail,

This might be an odd request, but I'm looking for a way to disable just about every block the mod adds.

As a quick TLDR: I am a dev of SevTech: Ages and we are currently facing a very shrinking amount of Block IDs. We are looking for a better mod to handle gravestones and were quite happy with yours and would like to add it, but we cannot afford to give up 9 block IDs.

We would like to be able to use just the 1 grave for a players death and that is all. If there is a way you can support this request by adding a config option to disable them, it would be greatly appreciated.

Thanks!

**Comment by Corail31** [comment]
Hi Justinrusso,
when you say "We would like to be able to use just the 1 grave for a players death and that is all"
does it means without the decorative graves ?

**Comment by justinrusso** [comment]
Do you happen to have discord? I'd love to chat!

We are trying to just reduce the number of block IDs this will add. So the goal would be to have it so we can disable any other block. I assume we'd just stick with the simple gravestone, but maybe give the option so we can pick either of the three?
