### ISSUE TITLE
XP Dupe

### ISSUE THREAD

**Issue by Daihok41** [Corail31/tombstone_lite#9]
It seems everytime i die i get like 50 lvls of XP automatically. Seems Like it just giving back Excessive amounts of xp. Im in the 1.12.2 version

**Comment by Corail31** [comment]
have you mods that can alter xp? have you tried with only my mod?

**Comment by Corail31** [comment]
@Daihok41 : i'm waiting for your answer, or your report'll be deleted soon. (i'm not fan of fake report)
