### ISSUE TITLE
[Suggestion] Configurable tablets cooldowns

### ISSUE THREAD

**Issue by BrangGit** [Corail31/tombstone_lite#9]
### Version
1.16.4

### Suggestion
Add a line in config file which allows different cooldowns settings for tablets of home. (Maybe other tablets ? Assistance / Recall ?)

### Why ?
It would allow modpackers to increase the cooldowns in order to force the players to plan their journey with the cooldown in mind and would prevent them to over-use the item. Il would be like hearth stones in world of warcraft.

**Comment by Corail31** [comment]
does the change in the latest release is not corresponding to your suggestion ?

**Comment by BrangGit** [comment]
You're right, actually I wasn't using the latest release. ^^' My bad ! Closing this now.
