### ISSUE TITLE
Unexpected behavior with certain mods that prevent death

### ISSUE THREAD

**Issue by QuantumToasted** [Corail31/tombstone_lite#90]
Hello! I am a huge fan of the things this mod provides. 
However, it seems to behave strangely with another mod, [Hardcore Revival](https://www.curseforge.com/minecraft/mc-mods/hardcore-revival).

The expected behavior I would think would be that when a player is incapacitated, reviving them will simply make it act as if they never died. They would keep their inventory and carry on their way.

However, with Tombstone installed, if a player is incapacitated and revived, they still retain their inventory but gain the Ghost effect (can't remember the full name, it's the effect given when you respawn with the gravestone key). It's strange that this is the only Tombstone effect applied. They don't lose their inventory or place a grave, OR get a gravestone key, but they gain the Ghost effect.

I am not sure if this is something you could fix on your end or if I would need to contact the writer of *that* mod, but I thought I would bring it to your attention! In case it matters, I am running a 1.14.4 Forge server with the latest version of Tombstone ~~(3.5.8)~~ (4.1.3, apologies - I should try reading).

**Comment by QuantumToasted** [comment]
I have updated my original message, I am using version 4.1.3, not 3.5.8. Sorry about that! As for a testing version, we can get in touch on Curse, though I am not sure how to do that since I have not used Curse in awhile. You can contact me via Email or on Discord as well if either of those are options for you.

**Comment by Corail31** [comment]
@QuantumToasted contact me on curseForge plz.

**Comment by Corail31** [comment]
After the tests of QuantumToasted, it's evident that the other mod needs to fix its code. (my doubt was only related to the receivedCanceled and doesn't seem to help this mod to have the proper behavior)
NB : some other mods are able to revive without bugs.
