### ISSUE TITLE
No log no chocolate

### ISSUE THREAD

**Issue by Kavik1996** [Corail31/tombstone_lite#90]
### Minecraft Version

1.16.5

### Forge Version

 36.2.39

### Corail Tombstone Version

6.8.0

### What happened?

Crash on the startup of the game

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
You didn't add the log of your crash ?

**Comment by Corail31** [comment]
Fake issues from newly created accounts are not welcome.
