### ISSUE TITLE
Question: Possible to give users non-enchanted Gravestone Key on respawn?

### ISSUE THREAD

**Issue by QuantumToasted** [Corail31/tombstone_lite#91]
Hello, I was wondering - is it possible to give players a regular Gravestone Key on respawn instead of an enchanted one? Something I thought was a cool idea presented by this mod was for dead players to need to make a "mad dash" back to their grave before the Ghost effect wore off, making it much harder to return. With the current setup, users can die and then instantly teleport back to where they died, and I am trying to discourage or disable it so that dying has a __little__ more consequence.

If this is already an option and I did not notice it, my apologies.

**Comment by Corail31** [comment]
Actually, all the grave's keys are enchanted on respawn because it's the Halloween period (there's a section for the changes related to Halloween in the tombstone gui/compendium)
There're configs to set the time of Ghostly Shape, and you can set "chanceEnchantedGraveKey" to disabled the enchanted keys.

**Comment by QuantumToasted** [comment]
Ah, It's just a temporary effect? I might keep it enabled then if it's only meant to be active during the Halloween period. Does this "period" actually coincide with the real holiday? IE, does it just encompass "around the whole month of October"? (Can I expect it to end after October?) Or is it something else? Just want to make sure I understand. Thank you for your quick responses :)

**Comment by Corail31** [comment]
All of this is already said in the recent messages on curseForge, until 3nov.
