### ISSUE TITLE
Minecraft crashes on the start [OptiForge]

### ISSUE THREAD

**Issue by Kavik1996** [Corail31/tombstone_lite#91]
### Minecraft Version

1.16.5

### Forge Version

 36.2.39

### Corail Tombstone Version

6.8.1 6.8.2 6.8.3

### What happened?

Crash on the startup of the game. I've found the conflict mod, it is OptiForge-MC1.16.5-0.5.7.jar, when I'd disabled it the game started correctly.

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

OptiForge-MC1.16.5-0.5.7

### Log Link

no log, the game crashed on the red screen stage

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
The intention of the mod that you mention is to bring compatibilities between Forge & Optifine (as in general, Optifine is for a specific forge version).
The latest is for forgeForge-1.16.5-36.1.51 & OptiFine HD U G8, it would be better to stick to theses versions if you want to use them. Without the log in your log folder, i can't help you obviously ;)
https://github.com/ZekerZhayard/OptiForge/issues/103

Edit: you'll still need forge 36.2.0 to run recent versions of Corail Tombstone. Maybe with the log, i could see something else.
You can also try with only optifine optiforge & forge to see if it works, and if it's only by adding Corail Tombstone that the incompatibility occurs.

**Comment by Kavik1996** [comment]
Thank you for the answer!
