### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by UnlimitedTurtlez** [Corail31/tombstone_lite#93]
this mod doesnt work in my custom modpack my players are getting keys with empty graves and loosing all their stuff
sometimes when a player dies the grave mod deletes the players inventory and all thats in it is player meat (from cannibalism), we have tried to find out why this is happening and cant

**Comment by Corail31** [comment]
I don't know if it's the first time you submit an issue on a github, but if the mod has reached over 5M downloads, there's chance it works and you're wrong.
It's also used on some server packs where it works propertly, is it your own modpack?
I really advice you to edit your issue to provide enough details to help, in the other case, your issue will be closed.

**Comment by UnlimitedTurtlez** [comment]
and you sure do sound like a creator with 5 mil downloads, could you be a little nicer? thanks, and as a matter of fact i am new to this

**Comment by Corail31** [comment]
What you think "not kind" is only related to not be my main language, and by reading your initial message with the title "broken" and only with a content saying "your mod is broken" is not a message of someone asking really for help but more a sentence done in the way "i just blame your mod".

**Comment by Corail31** [comment]
So, after this, if you want help, you will need to provide me a log of the server when a player die, your version of forge and tombstone, because it's a minimum of informations to help you.
As precision, your graves are empty but they're some meats from another mod called "cannibalism" in it. Is this meat is initially in the player inventory before the death, or is it a behavior on death ?

**Comment by UnlimitedTurtlez** [comment]
I already found the issue and reported to that mod maker
 i apologize for being blunt as im autistic and will try better in the future
 i meant no wrong by saying "broken" sorry, the issue was the cannibalism mod when a player dropped player flesh it sometimes took priority over the players actual inventory causing it to delete leaving them with a grave with their meat in it

**Comment by UnlimitedTurtlez** [comment]
i just noticed the edit i just removed the cannibalism mod, what logs you need?
im still learning the server ropes

**Comment by Corail31** [comment]
Is your trouble is fixed since the Cannibalism mod is removed ? (as i don't need the logs if your trouble is localized)

**Comment by UnlimitedTurtlez** [comment]
yes its all good
its def the meat

**Comment by UnlimitedTurtlez** [comment]
I would like to get it back if itll work tho

**Comment by Corail31** [comment]
But, if i try tombstone with only Cannibalism, the grave contains properly the drops.
In your explaination, you mention that the "player inventory" was deleted : are you sure this inventory to be lost, or the players were just surprised to get some graves with only meat in.
And is this inventory is also lost if you try with Cannibalism without Tombstone ? There seems to be something in the Cannibalism code about a possession if the killer is a player.

**Comment by UnlimitedTurtlez** [comment]
i killed a player and we ran tests, its the meat or at least appears that way 
but with out it it works

**Comment by UnlimitedTurtlez** [comment]
and yes player inv was gone without graves

**Comment by Corail31** [comment]
Ah neat, so i think the issue can be closed, and will be solved on their side :)
