### ISSUE TITLE
Decorative tombstone not breaking

### ISSUE THREAD

**Issue by DoctorMage** [Corail31/tombstone_lite#93]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Corail Tombstone Version

tombstone-4.5.9-1.12.2.jar

### What happened?

Mining a decorative tombstone does not break the tombstone but stilll drops a tombstone

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Log Link

https://gist.github.com/DoctorMage/08a12f0713420bedb5af36be042800c4

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@DoctorMage Thanks for reporting the issue. As a provisory solution, you can use 4.5.7 or you can make decorative graves "unbreakable" with the config "unbreakableDecorativeGrave" (in the category "Decorative Graves").

**Comment by Corail31** [comment]
About magic books, they're used in offhand with the update to be similar to upper versions (mainly because it's not possible to disenchant a bow in offhand).
https://github.com/SamaraIsnt/Roguelike-Adventures-and-Dungeons/issues/374

**Comment by DoctorMage** [comment]
Alright will do also managed to figure out book changes thx

**Comment by Corail31** [comment]
@DoctorMage about the books, the translations were not yet changed (it's now done in 4.5.10) and there's a message if they try to enchant with the mainhand.
