### ISSUE TITLE
Mule crashing server when it falls into void

### ISSUE THREAD

**Issue by Yertled** [Corail31/tombstone_lite#95]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Corail Tombstone Version

tombstone-7.5.4-1.18.2.jar

### What happened?

When players on my Forge / Bukkit hybrid server prays near a Tombstone, it spawns a Mule.
And since I host a skyblock server (All the Mods 7 - To the Sky), the mule can fall into the void.
When the mule falls into the void, it crashes the server.

I see you don't like getting these reports from Magma servers, but is there anything I can possible disable in Tombstone mod in config to stop mules from spawning maybe?

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

All The Mods 7 - To the Sky modpack version 1.1.0

### Log Link

https://pastebin.com/CWDFZizp

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
@Yertled Hi, when praying near a decorative grave, it rarely spawns a tamed animal (except if you have an abnormal level of knowledge of death and it wouldn't be a mule on each prayer in any case).
About Magma: it's not that i don't like magma: i just think magma has to behave like forge to stay compatible with forge mods.
I need some additional infos:
- Did you try with Forge (without Magma) ?
- Did you try to reduce your mod list to precise your issue ?
- The log that you provide would mean that you are disconnected before the death of the mule ?

NB: if you think the "mule" is the only animal doing this, you can add it to the config "unhandled_tameable_entities".
Edit: I made a server test (forge) with a disconnected player holding a familiar receptacle while the tamed creature was killed: after reconnecting, the familiar receptacle contained the tamed creature. So, i suppose it's related to magma or your other mods.

**Comment by Corail31** [comment]
@Yertled As you don't update your issue, it's now closed.
