### ISSUE TITLE
How to post an issue | Comment poster un problème

### ISSUE THREAD

**Issue by Corail31** [Corail31/tombstone_lite#96]
Before submitting a new issue, it will be wise first to consult the existing problems to check if the solution is not there.
You can write your text in French or in English, but do not post in French unless you speak it (no google translate).
Then, it is important to always provide the version of Tombstone, the version of Forge and any other mod that may be involved in your explanation.
Knowing that I am not in your head to understand what you are testing, it is important to provide any information that could help me put myself in your place and understand your problem, not being myself especially a player.
In general, you will also need to provide the server log when it is related to crashes or strange interactions with the graves. (with pastebin)
![sticker-arabesque0029](https://user-images.githubusercontent.com/17954109/66265410-3bb2aa00-e816-11e9-8fb4-0d7311d3fec5.png)
Avant de soumettre un nouveau problème, il sera tout d'abord judicieux de consulter les problèmes existants pour vérifier si la solution ne s'y trouve pas.
Vous pouvez rédiger votre texte en français ou en anglais, mais ne postez en français que si vous le parlez courrament (pas de google translate).
Ensuite, il est important de toujours fournir la version de Tombstone, la version de Forge et de tout autre mod qui pourrait être impliqué à votre explication.
Sachant que je ne suis pas dans votre tête pour comprendre ce que vous êtes en train de tester, il est important de fournir toute information qui pourrait m'aider à me mettre à votre place et comprendre votre problème, n'étant moi-même pas spécialement un joueur.
En général, vous devrez aussi fournir le log du serveur quand c'est lié à des crashs ou des interactions étranges avec les tombes. (avec pastebin)

**Comment by DygDyg** [comment]
ru_RU.lang:
[https://drive.google.com/file/d/1vB8fwflBFq-Yai0jc9YKtdLrK5trhV4A/view?usp=sharing](url)

Hello, decided to make Russian localization for your fashion. In Russian forums on minecraft this mode is propagated as a fashion with a single function - graves after death, and it will be difficult for a user who does not know English to understand this fashion and its additional capabilities. I also think about making a Russian-language description for fashion. Your mod is so much more than they say about it!

**Comment by Corail31** [comment]
@DygDyg the language has been added to 1.12, and requires more translation if you want to achieve it.
[LINK](https://github.com/Corail31/tombstone_lite/blob/master/src/main/resources/assets/tombstone/lang/ru_ru.lang)
