### ISSUE TITLE
Missing title translation for halloween advancement

### ISSUE THREAD

**Issue by Shibva** [Corail31/tombstone_lite#96]
### Minecraft Version

1.18.2

### Forge Version

boo

### Corail Tombstone Version

spooky update 2022

### What happened?

the details are vauge on purpose, this is most likey a forgotten thing to define in the lang file (or a typo)

![image](https://user-images.githubusercontent.com/38770780/196867154-4bfa7ff1-8aaf-42fc-b847-240b0802b5cd.png)

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Advancements are generated recently with datagen (the missing title is a side effect of this change and the only one missing).
Thanks for the report ;)
