### ISSUE TITLE
Crafting Recipe for VoodooPoppet checks slots 0 - 9 instead of 0 - 8 causing indexoutofbounds

### ISSUE THREAD

**Issue by Tfarcenim** [Corail31/tombstone_lite#97]
More information here https://github.com/Tfarcenim/crafting-station/issues/28#issuecomment-547604526

**Comment by Corail31** [comment]
Thanks IItemStack, sure it's on my side and since the start of this version 1.14.4.

**Comment by Corail31** [comment]
As precision of this bug, vanilla fallback the getter of a wrong slot to an empty stack, so it makes sense why it breaks only with Crafting Station mod (that didn't have this fallback).
