### ISSUE TITLE
holloween content bug

### ISSUE THREAD

**Issue by deadlywolf301** [Corail31/tombstone_lite#97]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Corail Tombstone Version

6.8.4

### What happened?

so i think it has to do with the holloween content specifficaly the lolli pops and sophistacated backpacks trying to stack them in it, i have the auto pick up upgrade and any time the lollis drop as loot the game freezes as the backpack tries to pick them up and stack them witch causes a crash and ive allready contacted the guys for sophistacated backpacks with the crash log and they say and i agree theres something wrong with the lolli pops cause everything was fine till they started to drop from mobs so heres the crash report https://pastebin.com/eh7KtN58
Im trying to start a youtube channel and right now its on hold cause this bug makes the game un playable

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Other relevant mods

sophisticated backpacks latest version

### Log Link

https://pastebin.com/eh7KtN58

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by deadlywolf301** [comment]
forgot to mention that enchant levels go higher and i have looting seven on my sword

**Comment by Corail31** [comment]
It's requested to try only with Corail Tombstone and the mod you think there's an incompatibility.
There's a null pointer in sophisticatedbackpacks so, open an issue on their mod whatever you think and them.
If their mod stuck, reverts to a previous version of their mod or try another backpack mod, there're a lot (as lollipops have no trouble to be saved and stacked in graves).
NB: The issue is mainly closed because you try with lots of mods not taking care to follow the issue template. Feel free to test with only the 2 related mods and edit your issue and the log.

**Comment by deadlywolf301** [comment]
i already went to the owner of sophistacated backpacks and they said its not thier mod so you need to look at it again i have a video of this happening in game every thing was fine with my pack till your mods holloween content showed up looks like ill have to try a different grave stone mod didnt realise the author was a dick

**Comment by deadlywolf301** [comment]
if you watch my video on youtube called Dragons: Why? Ep5 and start at 17 mins in youll see exactly the problem cause i had collected three yellow ones and one pink then the next pink lolli appeared froze game then crashed procedes to do so like two or three more times in video and i have like 8+ hours in this pack and everything was fine till your lolli's started to show up

**Comment by deadlywolf301** [comment]
and to top it off ive got some guy on sophistacated backpacks discord thats just recreated the same issue and can confirm its your mods lolli pops that are the issue

**Comment by deadlywolf301** [comment]
speciffacly its the lolli's changing color thats doing it, if you keep watching after it crashes i load back in and open the backpack at 21:09 minutes and find that all the lolli's in the backpack have changed color

**Comment by deadlywolf301** [comment]
doctor mage on discord had this to show and i quote: yeah just recreated it solo with corail tombstone (ftb libary but that was for looting 100 sword)
[crash-2022-10-22_11.00.29-server.txt](https://github.com/Corail31/tombstone_lite/files/9844074/crash-2022-10-22_11.00.29-server.txt)
[debug.log](https://github.com/Corail31/tombstone_lite/files/9844075/debug.log)
[latest.log](https://github.com/Corail31/tombstone_lite/files/9844076/latest.log)
