### ISSUE TITLE
A Weird Crash (and lost my items :( )

### ISSUE THREAD

**Issue by KenyMylankca** [Corail31/tombstone_lite#98]
this crash happens randomly, while me and my friend playing in my local world.
[crash-2019-10-29_23.21.32-server.txt](https://github.com/Corail31/tombstone_lite/files/3785647/crash-2019-10-29_23.21.32-server.txt)
on 1.12.2, forge 2847, tombstone 3.6.1

**Comment by KenyMylankca** [comment]
and the mob name is Djinn (maybe the issue related to it;)

**Comment by Corail31** [comment]
Looks to be related to the alignment added in this packet, you can stay on the recommanded for now (3.6.0) until i post a new version (probably soon).

**Comment by KenyMylankca** [comment]
so is it fixed in 3.6.2?

**Comment by Corail31** [comment]
sure :)
