### ISSUE TITLE
Chance get an enchanted key always 100%

### ISSUE THREAD

**Issue by rosemberg-12** [Corail31/tombstone_lite#99]
### Minecraft Version

1.19.2

### Forge Version

43.1.43

### Corail Tombstone Version

8.1.8

### What happened?

Always the chance to get an enchanted key is up to 100% , it doesn't matter the number, always is up to 100 and increasing

#Miscellaneous options
[general]
	#The duration of the Ghostly Shape effect in seconds [0..MAX|default:120]
	#Range: > 0
	ghostly_shape_duration = 30
	#The chance that a player receives an already enchanted Grave's Key on death [-1..100|default:0|disabled:-1]
	#Range: -1 ~ 100
	chance_enchanted_grave_key = 2

this configuration gives 102 percent of chance
![Example](https://user-images.githubusercontent.com/8755580/197602664-35962a6f-c36f-4bfe-b98c-b37397855db8.jpeg)

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [ ] Yes

### Valid Launcher

- [x] Yes

**Comment by itsTort** [comment]
Came to report this issue myself.  

I am on Forge 1.18.2 version. The default chance in the Knowledge of Death screen is 100%, and every death without selecting any points into Jailer will result in an Enchanted Key.

**Comment by Corail31** [comment]
During Halloween, the grave keys are always enchanted (command /tbgui compendium halloween).
The % over 100 is only a display indirectly related to the halloween bonus but it's 100%. It's the config chanceEnchantedGraveKey + level * 20 (and the level is capped depending on the value of this config)
